### PR TITLE
do not multiple SNMP title strings; enable link-time-optimizations; locks optimizations

### LINKED ISSUE #1929: NaN when using titleoids
Hi,

I found that when I used titleoids in the snmp module, I got NaN rather than port names.  The cause of the problem seems to be attempting to multiple a Strings returned from netsnmp.   I'm not sure the intent of the original code, however this modification fixes the issue with titleoids not working for me.

Giles

---  old-snmp.node.js	2017-03-11 09:21:07.347129394 +0000
+++ snmp.node.js	2017-03-11 11:45:01.903283373 +0000
@@ -272,7 +272,7 @@
                         if(__DEBUG === true)
                             netdata.debug(service.module.name + ': ' + service.name + ': found ' + service.module.name + ' value of OIDs ' + varbinds[i].oid + " = " + varbinds[i].value);
 
-                        if(varbinds[i].type === net_snmp.ObjectType.OctetString)
+                        if(varbinds[i].type === net_snmp.ObjectType.OctetString && service.snmp_oids_index[varbinds[i].oid].type !== 'title')
                             value = parseFloat(varbinds[i].value) * 1000;
                         else
                             value = varbinds[i].value;

### PR DESCRIPTION
**Pull request by ktsaou**
fixes #1929

### CODE REVIEW

**Comment by ktsaou** [comment]
@alonbl I need you help on this.
I tried to enable `-flto` on the compiler. I used `AX_CHECK_COMPILE_FLAG` which worked fine, except for one case where it returned `yes` but the compiler could not produce executables together with `pthreads` (travis with `clang` on ubuntu was failing, although `clang` on macos worked).

I decided to use `AC_RUN_IFELSE` to build a sample program that exits with zero to detect that really the compiler can produce executables. I added the file `m4/ax_c_lto.m4` that does this.

This is the code in `configure.ac`:

```
# Link-Time-Optimization

if test "${enable_lto}" != "no"; then
    opt="-flto"
    AX_CHECK_COMPILE_FLAG(${opt}, [have_lto=yes], [have_lto=no])
fi
if test "${have_lto}" = "yes"; then
    oCFLAGS="${CFLAGS}"
    CFLAGS="${CFLAGS} -flto ${OPTIONAL_MATH_CLFAGS} ${OPTIONAL_NFACCT_CLFAGS} ${OPTIONAL_ZLIB_CLFAGS} ${OPTIONAL_UUID_CLFAGS} ${OPTIONAL_LIBCAP_CFLAGS} ${OPTIONAL_IPMIMONITORING_CFLAGS}"
    AC_C_LTO
    CFLAGS="${oCFLAGS}"
    test "${ac_cv_c_lto}" = "no" && have_lto="no"
fi
test "${enable_lto}" = "yes" -a "${have_lto}" != "yes" && \
    AC_MSG_ERROR([LTO is required but is not available.])
AC_MSG_CHECKING([if LTO should be enabled])
if test "${enable_lto}" != "no" -a "${have_lto}" = "yes"; then
    enable_lto="yes"
    CFLAGS="${CFLAGS} -flto"
else
    enable_lto="no"
fi
AC_MSG_RESULT([${enable_lto}])
```

So, I copy `CFLAGS` to `oCFLAGS`, I add to `CFLAGS` all the options detected so far and I call `AC_C_LTO` to compile the confidence test program. This works.

I have to following problem: when cross compiling, `AC_RUN_IFELSE` has a third argument that is executed. When cross-compiling and `enable_lto="detect"` I want this to be `no`, but when `enable_lto="yes"` I think it should be `yes`. Otherwise, there is no way to enable `-flto` on cross compiling.

Any ideas?

**Comment by ktsaou** [comment]
A way could be to do this:

```
    cross_compile_lto="${enable_lto}"
    test "${cross_compile_lto}" && cross_compile_lto="no"
    AC_C_LTO
```

and in `AC_C_LTO` use `cross_compile_lto` as its third parameter (used when cross-compiling).

**Comment by ktsaou** [comment]
I did it. So it should work when cross-compiling.
If you have any comments, please let me know.

**Comment by alonbl** [comment]
Hi,
I believe we discussed that multiple times.
The optimization flags should be added by downstream unless critical.
I do not believe this is critical, hence can be added you your installation wrapper script.
Running output programs during configure is discouraged especially because of cross compiling.
Detecting cross compile can be done by $cross_compiling, but be warned this is not something you need to mess up with.

**Comment by ktsaou** [comment]
> I do not believe this is critical, hence can be added you your installation wrapper script.

yes, that is what I am trying to do... but it has to pass through autoconf somehow...

**Comment by alonbl** [comment]
On 12 March 2017 at 01:48, Costa Tsaousis <notifications@github.com> wrote:
>
> I do not believe this is critical, hence can be added you your installation wrapper script.
>
> yes, that is what I am trying to do... but it has to pass through autoconf somehow...
>

./configure CFLAGS="xxx" ?

**Comment by ktsaou** [comment]
> ./configure CFLAGS="xxx" ?

yes, but then the installer would need to detect if `-flto` is possible or not. I thought this is what `autoconf` is about. I mean, if it can be done by autoconf, is there a reason not be done with it? The way it is now, we have a very nice `--enable-lto` that actually can check if that is possible or not...

**Comment by alonbl** [comment]
On 12 March 2017 at 02:23, Costa Tsaousis <notifications@github.com> wrote:
>
> ./configure CFLAGS="xxx" ?
>
> yes, but then the installer would need to detect if -flto is possible or not. I thought this is what autoconf is about. I mean, if it can be done by autoconf, is there a reason not be done with it? The way it is now, we have a very nice --enable-lto that actually can check if that is possible or not...
>

As you do not intend to support (I hope) cross compiler for the
installer, just do a simple test if that so important. I do not
understand why people will use this installer if you provide decent
packages for rpm based, debian based etc... but for those who wish to
use this installer they can either remove this problematic
optimization or you can try and run somekind of test program.

**Comment by ktsaou** [comment]
ok, thanks. 
I guess the reason is that after a year, netdata is still missing from all major distros - they are just too slow... this is probably why docker thrives...

**Comment by alonbl** [comment]
Per my view Docker thrives because developer do not know how to cope with
standard, backward compatibility and dependency management to be able to
leverage single managed system of reusable components.
Netdata is yet one more example of a very difficult to maintain and manage
component which does not comply with best practices in term of how
installation is, security model (privilege escalation) and HFS compliant.
We fixed what we could but we are still behind from being able to install
it into a downstream distribution.

**Comment by ktsaou** [comment]
nice! :)

You know... in all things there must be some balance. If the standards or the best practices are inefficient, the problem is probably not the users or the developers, but the standards. After all, the O/S is here to serve us - not the other way around... Of course there must be rules, of course the apps must follow them. But the standards have to be adapted too... Otherwise, the world does not move forward... And when the world does not move forward, a parallel universe (e.g. docker) takes the lead...

:)

**Pull request merged**
