### PR TITLE
Beanstalk module + optimization (SimpleService, Charts)

### LINKED ISSUE #2820: Beanstalk monitoring
I was looking for a beanstalk monitor to use with netdata but couldn't find one and spoke to you guys on twitter and you weren't aware of one so I've put one together. It's rough and is all configured from within the chart.py file at the moment but it works. It creates a dimension with tubename_stat and then assigns the value to that.

Happy for someone to tear it apart or adapt it!
[beanstalk.chart.txt](https://github.com/firehol/netdata/files/1346426/beanstalk.chart.txt)

### PR DESCRIPTION
**Pull request by l2isbad**
~~WIP~~
~~not really tested~~
~~only tube stats for now~~

fixes #2831 
fixes #2820 

> Ideally this should be configurable per module job. For example, user A knows that its tubes are permanent, so no cleanup. But user B knows that its app creates tubes for some time and then it closes them. So, a job configuration like:
> 
> cleanup: 0 to disable or false, or N seconds

[global variable](https://github.com/l2isbad/netdata/blob/beanstalk_module/plugins.d/python.d.plugin#L40-L45) `chart_cleanup` option added. Can be specified per module/job.

### CODE REVIEW

**Comment by l2isbad** [comment]
Ok, it works.

@edwade3 @ecowed
Please test it.

**Comment by edwade3** [comment]
> Please test it.

Excuse my ignorance, but how do I test it?! I've got the latest version from the installer but not sure how to install this PR?

**Comment by l2isbad** [comment]
```
mkdir test
cd test
got clone https://github.com/l2isbad/netdata --branch beanstalk_module
cd netdata
sudo ./netdata-installer.sh --install /opt
```

**Comment by edwade3** [comment]
Perfect! It's running and I can see the charts! I'll monitor it over the next few days as the tubes get some use and keep you posted but so far it looks amazing!! Thank you sooo much for doing it! 

Do you 2 guys do this as a job or is it a hobby thing?

**Comment by ktsaou** [comment]
@l2isbad you rock! (as always)

**Comment by edwade3** [comment]
Been playing around with it, and created some alarms (my first alarms, ever!) and it's brilliant! Absolutely fantastic work!

**Comment by l2isbad** [comment]
@edwade3 
i suggest to look into [dashboard_info.js](https://github.com/firehol/netdata/blob/master/web/dashboard_info.js) code, you can help to make the module much better (dashboard icon, chart descriptions, gauges, etc. - like mysql, web_log, ...)😄

[dashboard icons](https://github.com/firehol/netdata/blob/master/web/dashboard_info.js#L9-L321)
[descriptions](https://github.com/firehol/netdata/blob/master/web/dashboard_info.js#L1552-L1588) (chrony as excample)

**Comment by ktsaou** [comment]
Icon names can be searched here: http://fontawesome.io/icons/

**Comment by l2isbad** [comment]
Ok, if there is no more suggestions i think it's ready to merge 😄

**Comment by edwade3** [comment]
I have nothing to add - it's all set up on our servers and alerting me as it should so one very happy customers!

**Comment by l2isbad** [comment]
not ready

**Comment by ktsaou** [comment]
@edwade3 please post here screenshots of all the charts. I need the global charts and the charts of one tube.

**Comment by l2isbad** [comment]
I believe it's ready now. Creating/deleting/recreating charts in runtime works.

**Comment by ktsaou** [comment]
@l2isbad is it possible to pass to netdata the module that generates each chart?

Check this: https://github.com/firehol/netdata/wiki/External-Plugins#chart

(just append: `'python.d.plugin' 'module_name'` to all `CHART` lines)

**Comment by ktsaou** [comment]
They are visualized here:

screenshot from 2017-11-05 15-09-39

**Comment by l2isbad** [comment]
What about modules like `apache`, which change the name of their module? (`apache` -> `lighttpd`).
Should we pass real or modified module name?

**Comment by ktsaou** [comment]
> What about modules like apache, which changes the name of their module? (apache -> lighttpd).
> Should we pass real or modified module name?

hm.... I think not. The idea is to provide information people will use to find the configuration file to edit. So, if the config is `apache` I think we should provide that name.

**Comment by l2isbad** [comment]
Done.
I noticed that for some reason netdata shows incorrect chart name for `cpuidle`, `cpufreq` modules.
screenshot_20171105_225126

**Comment by ktsaou** [comment]
> I noticed that for some reason netdata shows incorrect chart name for cpuidle, cpufreq modules.

hm... it is the context. These charts have wrong `context`. It has to be fixed at the plugin.

**Comment by ktsaou** [comment]
merge?

**Comment by l2isbad** [comment]
ye

**Comment by ktsaou** [comment]
merged! @l2isbad you are the best!

**Comment by ktsaou** [comment]
infographic beanstalkd logo:

image

**Comment by l2isbad** [comment]
@edwade3 don't forget to switch back to the main repo

**Comment by edwade3** [comment]
Thanks! You guys are brilliant! Thank you so much for making such an amazing programme and such a fantastic monitor for beanstalkd!

Did you still need me to go through the dashboard_info.js file and post the screenshots? If so, I can do this tomorrow for you!

**Comment by ktsaou** [comment]
> Did you still need me to go through the dashboard_info.js file and post the screenshots? If so, I can do this tomorrow for you!

yes please. The idea is to add some additional information on the dashboard, so that people using netdata with beanstalkd will be able to get familiar with the work we have done.

Also, please post your alarms here. I would be nice to add default alarms too.

**Comment by edwade3** [comment]
Not a problem at all. I'll go through it tomorrow and send it all over and a couple of alarms too! Cheers guys!

**Comment by ecowed** [comment]
netdata_beanstalkd_alarms
netdata_beanstalk_server_stats
netdata_default_tube_stats

3 screenshots - one of the server stats section, one of the default tube section, and one of the 2 alarms I have setup so far. I'll have a look through the dashboard_info.js file now

**Comment by ecowed** [comment]
Ok I've gone through the dashboard_info.js file and added info to every chart to explain roughly what it means, as well as adding an icon and some info to the main beanstalk title - do you want me to send it through as a pull request?

**Comment by ktsaou** [comment]
thanks!

> Ok I've gone through the dashboard_info.js file and added info to every chart to explain roughly what it means, as well as adding an icon and some info to the main beanstalk title - do you want me to send it through as a pull request?

yes please. Also include the first alarm, that seems pretty generic and good to have by default. You could provide the second alarm commented, so that other folks will find it ready to be uncommented and used.

@l2isbad I see the charts are named `beanstalkd.xxxx`. Should they be `beanstalkd_local.xxxx`? I mean a netdata could monitor multiple beanstalkd. Right?

**Comment by l2isbad** [comment]
> @l2isbad I see the charts are named beanstalkd.xxxx. Should they be beanstalkd_local.xxxx? I mean a netdata could monitor multiple beanstalkd. Right?

It can. Beanstalk config is not multijob by default. 
For single jobs name == module_name
https://github.com/firehol/netdata/blob/master/python.d/python_modules/bases/FrameworkServices/SimpleService.py#L75-L79

**Comment by l2isbad** [comment]
@ecowed 
1. Keep in mind you have to change version https://github.com/firehol/netdata/blob/master/web/index.html#L3010 to make the changes appear in the browser.
2. 2nd alaram descriptions is wrong (beanstalk.current_tubes -> the number of buried jobs in all queues)

**Pull request merged**
