### PR TITLE
python plugin monotonic fix

### LINKED ISSUE #4152: python clocks don't work under FreeBSD
From https://github.com/firehol/netdata/pull/3776#issuecomment-416839935

Commit 20bbce31336b860af48a918046b7defd31be5ee8 seems to break Python plugins on FreeBSD; at least on this system:
```
$ uname -mrs 
FreeBSD 10.4-RELEASE-p10 amd64
$ python --version
Python 2.7.15
```

After updating to the latest git version, python plugins no longer returned data (neither when running from netdata, nor when running directly in debug mode) (this isn't 100% true - once in a while (several minutes) a record is returned). I narrowed the problem down to the mentioned commit, reverting it makes the plugins run fine again.

Researching a bit more revealed that FreeBSD is using different constants for CLOCK_MONOTONIC (from /usr/include/time.h): 
```
#define CLOCK_VIRTUAL   1
//...
#define CLOCK_MONOTONIC 4
```

So the Python code is now using CLOCK_VIRTUAL, which is defined as "for time that increments only when the CPU is running in user mode on behalf of the calling process". The old value 4 was actually good on FreeBSD, because it referenced CLOCK_MONOTONIC.

### PR DESCRIPTION
**Pull request by l2isbad**
Add https://github.com/atdt/monotonic library for monotonic calculation. 

fixes #4152

### CODE REVIEW

**Comment by paulfantom** [comment]
I am generally against vendoring other libraries, but since in netdata it works then ok. However we need to figure out better way of doing this, copying files from other projects isn't a good way of doing this. Maybe we should consider git submodules, as that's exactly what they were introduced for.

**Comment by amichelic** [comment]
Works great - thanks.

**Comment by ktsaou** [comment]
@Ferroin could you please check SPDX? Do we need to add such a header on third party files?

> I am generally against vendoring other libraries, but since in netdata it works then ok. However we need to figure out better way of doing this, copying files from other projects isn't a good way of doing this. Maybe we should consider git submodules, as that's exactly what they were introduced for.

I agree. But it needs some research.

**Comment by ktsaou** [comment]
@l2isbad I see all the other third party files have SPDX header.  So please add it to this one too, to merge it.

**Comment by l2isbad** [comment]
yes

**Pull request merged**
