### PR TITLE
Fix invalid 'seconds behind the master' value for mysql slave

### PR DESCRIPTION
**Pull request by alibo**
This PR fixes an invalid `seconds behind the master` value when the actual value is 0 but it shows -1.

### CODE REVIEW

**Comment by l2isbad** [comment]
Well, 'Seconds_Behind_Master' can be an empty string.
How about

```python
return value if value is not '' else -1
```

**Comment by alibo** [comment]
@l2isbad good point 👍 fixed ;)

**Comment by ktsaou** [comment]
thanks!

**Comment by l2isbad** [comment]
@alibo i found that `Seconds_Behind_Master` can be `None`

**Comment by alibo** [comment]
@l2isbad I don't really know what `None` means. maybe it's related to this change?

> In MySQL 5.7, this field is NULL (undefined or unknown) if the slave SQL thread is not running, or if the SQL thread has consumed all of the relay log and the slave I/O thread is not running. (In older versions of MySQL, this field was NULL if the slave SQL thread or the slave I/O thread was not running or was not connected to the master.) If the I/O thread is running but the relay log is exhausted, Seconds_Behind_Master is set to 0.
> > https://dev.mysql.com/doc/refman/5.7/en/show-slave-status.html

So, if it was `None` the status should be `-1` or `0`? What do you think?

**Comment by l2isbad** [comment]
To be honest i don't know but let's do this - If it's not numeric value we will return -1 i think. Are you willing to make a PR?

**Comment by alibo** [comment]
@l2isbad 
Unfortunately, I'm not python developer. Does this work with both Python 2 and 3?

```python
try:
   return int(value)
except ValueError:
   return -1
```

If it's wrong, I think it's better to be handled by someone who is expert in Python like you :D :)

**Comment by l2isbad** [comment]
> Does this work with both Python 2 and 3?

👍

**Pull request merged**
