### PR TITLE
fix charts types + six sensors issues

### LINKED ISSUE #681: python.d.plugin mysql wrong chart
image

I guess it should be `incremental`.

@paulfantom

### PR DESCRIPTION
**Pull request by paulfantom**
fix #681

### CODE REVIEW

**Comment by ktsaou** [comment]
merge?

**Comment by paulfantom** [comment]
Yup.

**Comment by ktsaou** [comment]
it does not work.
python.d ERROR: squid_local wrong dimension id: client_http_kbytes_out
python.d ERROR: squid_local wrong dimension id: client_http_hit_kbytes_out
python.d ERROR: squid_local wrong dimension id: client_http_requests
python.d ERROR: squid_local wrong dimension id: client_http_hits
python.d ERROR: squid_local wrong dimension id: client_http_errors
python.d ERROR: squid_local wrong dimension id: server_all_kbytes_in
python.d ERROR: squid_local wrong dimension id: server_all_kbytes_out
python.d ERROR: squid_local wrong dimension id: server_all_requests
python.d ERROR: squid_local wrong dimension id: server_all_errors
python.d ERROR: squid_local wrong dimension id: client_http_kbytes_in
python.d ERROR: squid_local wrong dimension id: client_http_kbytes_out
python.d ERROR: squid_local wrong dimension id: client_http_hit_kbytes_out
python.d ERROR: squid_local wrong dimension id: client_http_requests
python.d ERROR: squid_local wrong dimension id: client_http_hits
python.d ERROR: squid_local wrong dimension id: client_http_errors
python.d ERROR: squid_local wrong dimension id: server_all_kbytes_in
python.d ERROR: squid_local wrong dimension id: server_all_kbytes_out
python.d ERROR: squid_local wrong dimension id: server_all_requests
python.d ERROR: squid_local wrong dimension id: server_all_errors
python.d ERROR: squid_local wrong dimension id: client_http_kbytes_in
python.d ERROR: squid_local wrong dimension id: client_http_kbytes_out
python.d ERROR: squid_local wrong dimension id: client_http_hit_kbytes_out
python.d ERROR: squid_local wrong dimension id: client_http_requests

**Comment by ktsaou** [comment]
it does this forever...

**Comment by ktsaou** [comment]
Also:

```
 # ./plugins.d/python.d.plugin mysql
 INFO: Using python v2
python.d INFO: reading configuration file: /etc/netdata/python.d.conf
python.d INFO: MODULES_DIR='/data/src/netdata-ktsaou.git/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['mysql']
python.d INFO: using MySQLdb
python.d ERROR: mysql/socket2_root: is misbehaving. Reason:sequence item 2: expected string, OperationalError found
python.d ERROR: mysql/tcp_root: is misbehaving. Reason:sequence item 2: expected string, OperationalError found
python.d ERROR: mysql/socket2: is misbehaving. Reason:sequence item 2: expected string, OperationalError found
python.d ERROR: mysql/mycnf: is misbehaving. Reason:sequence item 2: expected string, OperationalError found
python.d ERROR: mysql/tcp: is misbehaving. Reason:sequence item 2: expected string, OperationalError found
python.d ERROR: mysql/local: is misbehaving. Reason: invalid literal for int() with base 10: 'absolute'
python.d ERROR: mysql/local: is misbehaving. Reason: invalid literal for int() with base 10: 'absolute'
python.d FATAL: no more jobs
DISABLE
```

**Pull request merged**
