### PR TITLE
create /var/cache/netdata and /var/lib/netdata if they are missing

### PR DESCRIPTION
**Pull request by ktsaou**

### CODE REVIEW

**Comment by candrews** [comment]
Ugh, for some reason, I thought all users could create directories in `/var/vache` - sorry about that.

So the systemd unit should be changed to create the directory just like how the openrc one does. I'll create a PR (or if you want to make the change, you could be beat me to it :-) ).

**Comment by ktsaou** [comment]
> So the systemd unit should be changed to create the directory just like how the openrc one does. I'll create a PR (or if you want to make the change, you could be beat me to it :-) ).

Is there a policy that installation packages should not install `/var/cache/app`? I don't get it. Why is this needed?

**Comment by candrews** [comment]
It's Gentoo policy (and I bet other distros too, but I haven't checked). Here's the message:
` * QA Notice: This ebuild installs into paths that should be created at runtime.
 * To fix, simply do not install into these directories. Instead, your package
 * should create dirs on the fly at runtime as needed via init scripts/etc...
 *
 * var/cache/netdata`

Imho, this policy makes sense - /var/cache is used to cache stuff so it should be able to be deleted and rebuilt at any time.

**Comment by thinrope** [comment]
Well, I have been thinking about the /var/cache issue (also Gentoo user), and I think the right move is to get the data stored in a different location. Here is a good citation from [Wikipedia/FHS:](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard#Directory_structure)

>  /var/cache: Application cache data. Such data are locally generated as a result of time-consuming I/O or calculation. The application must be able to regenerate or restore the data. The cached files can be deleted without loss of data.
>
Since netdata can NOT recreate the data (it is gathering data from ephemeral sources), a better option will be to store it under /var/lib/netdata/data for example. If ever we need to store cache (e.g. connect to another host, query some data, aggregate several hosts), it can go into /var/cache. 

So I'd treat that as a design issue.

BTW, I just looked at the Gentoo MSG again:

>  * QA Notice: This ebuild installs into paths that should be created at runtime.
 *  To fix, simply do not install into these directories.  Instead, your package
 *  should create dirs on the fly at runtime as needed via init scripts/etc...
 * 
 *   var/cache
 *   var/cache/netdata
 *   var/cache/netdata/.keep
>

Here is the relevant code: https://github.com/firehol/netdata/blob/v1.4.0/src/Makefile.am#L23

On a side note, I am not sure I understand the reason behind not creating an empty /var/cache/${APP} if it is going to be used. This is the only sane way to create it with proper permissions, without running as root later. May be it is only an issue due to using .keep files (as opposed to empty directory?

**Comment by ktsaou** [comment]
Well, `/var/cache/netdata` is storing the runtime database, only when netdata exits. `/var/lib/netdata/db` will store the database, once we have longer history.

I needed a place to save temporary files on exit, so I chose `/var/cache/netdata`.

**Comment by thinrope** [comment]
I see... 

Well, that is a bit specific to netdata, that is why I wasn't sure. If we are to stick to the definition, /var/cache should be re-creatable from /var/lib (and it is not right now). So, I'd say move everything to /car/lib now rather than later.

**Comment by ktsaou** [comment]
ok, I'll do this change during the development of the longer history. This will require a new file format for the cache too, so files in `/var/cache/netdata` will have to be ignored.

For the moment this PR creates this directory, if it can (i.e. netdata is started as root).

**Pull request merged**
