### PR TITLE
Icecast module

### PR DESCRIPTION
**Pull request by l2isbad**
closes https://github.com/firehol/netdata/issues/3486
@tommybuck

### CODE REVIEW

**Comment by ktsaou** [comment]
oops! a merge broke this.
Could you please update it?

**Comment by l2isbad** [comment]
done

**Comment by ktsaou** [comment]
merged! you rock!

**Comment by tommybuck** [comment]
How do i get this to show up on my dashboard? I have edited the icecast config file with my url. But it still doesn't show?

**Comment by l2isbad** [comment]
```bash
# become user netdata
sudo su -s /bin/bash netdata

# execute the plugin in debug mode, for a specific module.
# example for the python plugin, mysql module:
/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace icecast
```

**Comment by ktsaou** [comment]
This plugin is also missing from docs / wiki / infographic.

**Comment by ktsaou** [comment]
icecast logo for the infographic: 
image

**Comment by ktsaou** [comment]
cropped: 
logo-icecast

**Comment by ktsaou** [comment]
added it to infographic and the wiki menu.
Please add it at https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata

**Comment by alsyundawy** [comment]
icecast not show in dastboard

**Comment by l2isbad** [comment]
`python.d.plugin` has [debug mode](https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata#configuring-plugins)

**Pull request merged**
