### PR TITLE
Add ZFS TRIM statistics and additional dimensions for disk charts to FreeBSD Plugin

### PR DESCRIPTION
**Pull request by vlvkobal**
Implements #2625

### CODE REVIEW

**Comment by ktsaou** [comment]
nice!
merge now?

**Comment by vlvkobal** [comment]
Yes, its ready.

**Comment by ktsaou** [comment]
merged it.
Thank you!

**Comment by Fyr42** [comment]
Hi,

I found this plugin during a google search so I visited it. Sorry to unearth it.

sysctl OID have changed for ZFS TRIM. It's a per zpool tree. And had a separate hierarchy for auto trim tree, from manual trim and a third one called "simple"


auto trim cames from zpool set autotrim=on pool, else values stay at zero.
manual trim cames from the command : zpool trim pool. 

Error file example : 

/var/log/netdata/error.log:2023-07-11 13:26:02: netdata ERROR : P[freebsd] : FREEBSD: sysctl(kstat.zfs.misc.zio_trim.bytes...) failed: No such file or directory (errno 2, No such file or directory)

Collector file example : 

/var/log/netdata/collector.log:2023-07-11 13:26:02: netdata ERROR : P[freebsd] : DISABLED: zfs.trim_bytes chart
/var/log/netdata/collector.log:2023-07-11 13:26:02: netdata ERROR : P[freebsd] : DISABLED: zfs.trim_success chart
/var/log/netdata/collector.log:2023-07-11 13:26:02: netdata ERROR : P[freebsd] : DISABLED: kstat.zfs.misc.zio_trim module


sysctl example of a pool named zroot : 

kstat.zfs.zroot.misc.iostats.simple_trim_bytes_failed: 0
kstat.zfs.zroot.misc.iostats.simple_trim_extents_failed: 0
kstat.zfs.zroot.misc.iostats.simple_trim_bytes_skipped: 0
kstat.zfs.zroot.misc.iostats.simple_trim_extents_skipped: 0
kstat.zfs.zroot.misc.iostats.simple_trim_bytes_written: 0
kstat.zfs.zroot.misc.iostats.simple_trim_extents_written: 0

kstat.zfs.zroot.misc.iostats.autotrim_bytes_failed: 0
kstat.zfs.zroot.misc.iostats.autotrim_extents_failed: 0
kstat.zfs.zroot.misc.iostats.autotrim_bytes_skipped: 37863424
kstat.zfs.zroot.misc.iostats.autotrim_extents_skipped: 4363
kstat.zfs.zroot.misc.iostats.autotrim_bytes_written: 645558272
kstat.zfs.zroot.misc.iostats.autotrim_extents_written: 3288

kstat.zfs.zroot.misc.iostats.trim_bytes_failed: 0
kstat.zfs.zroot.misc.iostats.trim_extents_failed: 0
kstat.zfs.zroot.misc.iostats.trim_bytes_skipped: 10627166208
kstat.zfs.zroot.misc.iostats.trim_extents_skipped: 1079092
kstat.zfs.zroot.misc.iostats.trim_bytes_written: 2057801666560
kstat.zfs.zroot.misc.iostats.trim_extents_written: 1076390


The per pool statistic gives no trivial patch to write.

Of course manual trim only gives a chart during its run. Perhaps only auto trim is meaningful to chart in case of autotrim is set to "on" on the pool.

Kind Regards

**Pull request merged**
