### PR TITLE
Simplify mysql.chart.py

### PR DESCRIPTION
**Pull request by paulfantom**
I have rewritten `mysql.chart.py` to use the same schema as in other modules. 
Also implemented features discussed in #632.

Tested and ready to be merged.

Using `SimpleService` class simplifies writing new python modules thus I plan to rewrite most of bash counterparts to python by the next weekend.

### CODE REVIEW

**Comment by ktsaou** [comment]
nice!

**Comment by ktsaou** [comment]
oops! I merged it but I guess your intention was only for mysql.
Is it ok?

**Comment by paulfantom** [comment]
Yes it is ok. Now I can start writing more modules. Do you want me to start from rewriting bash ones or write ones that are requested in issues (like HAProxy)?

**Comment by ktsaou** [comment]
Your choice.

If you rewrite all the bash ones to python, we could disable by default charts.d and enable python.d.
Of course, we will have to work on the installation of python dependencies for that to happen. I think the `python-modules-installer.sh` will help in this area, although `pip` is problematic for local installations for a few systems (system-wide installations work though).

**Comment by paulfantom** [comment]
So I will start from rewriting bash modules.

**Comment by paulfantom** [comment]
@ktsaou I will have many questions about bash modules. First one:
What does `airsearches.chart.sh` do? I know it gets some information with `wget` and some html parsing regex. However there is no default url and I cannot find information about this module in wiki.

**Comment by ktsaou** [comment]
ignore it. It is something I needed at work that is specific to one particular custom application. No need to port it.

**Comment by ktsaou** [comment]
Also `cpu_apps`, `crsproxy`, `load_average`, `mem_apps` can be ignored.

**Comment by ktsaou** [comment]
`cpu_apps` and `mem_apps` are now handled by `apps.plugin`.
`load_average` has been embedded in netdata
`crsproxy` is another custom monitoring I needed at work.

**Comment by paulfantom** [comment]
Ok. Next question.
First of all I have never used `squid`.
Is it possible to get squid statistics just by http request to `cache_object://$host:$port/counters` and `http://$host:$port/squid-internal-mgr/counters`?

**Comment by paulfantom** [comment]
Could you provide me some sample of raw data from `cache_object://$host:$port/counters`? I want to write parser, but I cannot find any examples. And `eval` in `squid.chart.py` doesn't help.

**Comment by ktsaou** [comment]
Here it is:

```
# telnet localhost 3128
Trying ::1...
Connected to localhost.
Escape character is '^]'.
GET cache_object://localhost:3128/counters HTTP/1.0

HTTP/1.1 200 OK
Server: squid/3.5.17
Mime-Version: 1.0
Date: Sun, 03 Jul 2016 23:00:51 GMT
Content-Type: text/plain;charset=utf-8
Expires: Sun, 03 Jul 2016 23:00:51 GMT
Last-Modified: Sun, 03 Jul 2016 23:00:51 GMT
X-Cache: MISS from boxe
X-Cache-Lookup: MISS from boxe:3128
Connection: close

sample_time = 1467586839.878462 (Sun, 03 Jul 2016 23:00:39 GMT)
client_http.requests = 2327685
client_http.hits = 120
client_http.errors = 93
client_http.kbytes_in = 412098
client_http.kbytes_out = 4342416
client_http.hit_kbytes_out = 94
server.all.requests = 1191996
server.all.errors = 0
server.all.kbytes_in = 2509165
server.all.kbytes_out = 291153
server.http.requests = 1189615
server.http.errors = 0
server.http.kbytes_in = 1214862
server.http.kbytes_out = 274832
server.ftp.requests = 0
server.ftp.errors = 0
server.ftp.kbytes_in = 0
server.ftp.kbytes_out = 0
server.other.requests = 2381
server.other.errors = 0
server.other.kbytes_in = 1294303
server.other.kbytes_out = 16321
icp.pkts_sent = 0
icp.pkts_recv = 0
icp.queries_sent = 0
icp.replies_sent = 0
icp.queries_recv = 0
icp.replies_recv = 0
icp.query_timeouts = 0
icp.replies_queued = 0
icp.kbytes_sent = 0
icp.kbytes_recv = 0
icp.q_kbytes_sent = 0
icp.r_kbytes_sent = 0
icp.q_kbytes_recv = 0
icp.r_kbytes_recv = 0
icp.times_used = 0
cd.times_used = 0
cd.msgs_sent = 0
cd.msgs_recv = 0
cd.memory = 0
cd.local_memory = 432
cd.kbytes_sent = 0
cd.kbytes_recv = 0
unlink.requests = 147
page_faults = 5
select_loops = 31937146
cpu_time = 3801.626285
wall_time = 11.708813
swap.outs = 379
swap.ins = 50
swap.files_cleaned = 14
aborted_requests = 188
Connection closed by foreign host.
```

**Comment by paulfantom** [comment]
Since someone at squid thought it is a good idea to implement their own standard (schema `cache_object://`), I cannot use high-level `urllib` library and I am forced to use low-level sockets. As a result I wrote something that cannot be quickly tested without squid. So maybe you can test this snippet below? It should output raw data from squid server.
```py
#!/usr/bin/env python
import socket
SCHEMA = "cache_object"
HOST = "localhost"
PORT = 3128
OTHER = "counters"

request = "GET " + SCHEMA + "://" + HOST + ":" + str(PORT) + "/" + OTHER + " HTTP/1.0\r\n\r\n"
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.settimeout(3)
sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
sock.connect((HOST, PORT))
sock.send(request)
data = ""
header = sock.recv(1024)
while True:
    buf = sock.recv(1024)
    if not buf:
        break
    else:
        data += buf
sock.shutdown(1)
sock.close()
if "200 OK" in header:
    print(data)
else:
    print("SOMETHING WENT WRONG")
    print(data)
```

If above works, I have working version of `squid.chart.py`.

**Comment by ktsaou** [comment]
```
# python squid.py
Traceback (most recent call last):
  File "squid.py", line 13, in <module>
    sock.send(request)
TypeError: 'str' does not support the buffer interface
```

**Comment by paulfantom** [comment]
Ah python3 quirks.
change line 13 `sock.send(request)` to `sock.send(encode(request))`

**Comment by ktsaou** [comment]
```
 # python squid.py
Traceback (most recent call last):
  File "squid.py", line 13, in <module>
    sock.send(encode(request))
NameError: name 'encode' is not defined
```

**Comment by paulfantom** [comment]
Too many mistakes from my side. Sorry. Here is python3 version:
```py
#!/usr/bin/env python3
import socket
SCHEMA = "cache_object"
HOST = "localhost"
PORT = 8080
OTHER = "squid-internal-mgr/counters"

request = "GET " + SCHEMA + "://" + HOST + ":" + str(PORT) + "/" + OTHER + " HTTP/1.0\r\n\r\n"
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.settimeout(3)
sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
sock.connect((HOST, PORT))
sock.send(request.encode())
data = b""
header = sock.recv(1024)
while True:
    buf = sock.recv(1024)
    if not buf:
        break
    else:
        data += buf
sock.shutdown(1)
sock.close()
if b"200 OK" in header:
    print(data)
else:
    print("SOMETHING WENT WRONG")
    print(data)
```

**Comment by ktsaou** [comment]
```
# python3 squid3.py
SOMETHING WENT WRONG
b'gn by Free CSS Templates\n http://www.freecsstemplates.org\n Released for free under a Creative Commons Attribution 2.5 License\n*/\n\n/* Page basics */\n* {\n\tfont-family: verdana, sans-serif;\n}\n\nhtml body {\n\tmargin: 0;\n\tpadding: 0;\n\tbackground: #efefef;\n\tfont-size: 12px;\n\tcolor: #1e1e1e;\n}\n\n/* Page displayed title area */\n#titles {\n\tmargin-left: 15px;\n\tpadding: 10px;\n\tpadding-left: 100px;\n\tbackground: url(\'/squid-internal-static/icons/SN.png\') no-repeat left;\n}\n\n/* initial title */\n#titles h1 {\n\tcolor: #000000;\n}\n#titles h2 {\n\tcolor: #000000;\n}\n\n/* special event: FTP success page titles */\n#titles ftpsuccess {\n\tbackground-color:#00ff00;\n\twidth:100%;\n}\n\n/* Page displayed body content area */\n#content {\n\tpadding: 10px;\n\tbackground: #ffffff;\n}\n\n/* General text */\np {\n}\n\n/* error brief description */\n#error p {\n}\n\n/* some data which may have caused the problem */\n#data {\n}\n\n/* the error message received from the system or other software */\n#sysmsg {\n}\n\npre {\n    font-family:sans-serif;\n}\n\n/* special event: FTP / Gopher directory listing */\n#dirmsg {\n    font-family: courier;\n    color: black;\n    font-size: 10pt;\n}\n#dirlisting {\n    margin-left: 2%;\n    margin-right: 2%;\n}\n#dirlisting tr.entry td.icon,td.filename,td.size,td.date {\n    border-bottom: groove;\n}\n#dirlisting td.size {\n    width: 50px;\n    text-align: right;\n    padding-right: 5px;\n}\n\n/* horizontal lines */\nhr {\n\tmargin: 0;\n}\n\n/* page displayed footer area */\n#footer {\n\tfont-size: 9px;\n\tpadding-left: 10px;\n}\n\n\nbody\n:lang(fa) { direction: rtl; font-size: 100%; font-family: Tahoma, Roya, sans-serif; float: right; }\n:lang(he) { direction: rtl; }\n --></style>\n</head><body id=ERR_INVALID_URL>\n<div id="titles">\n<h1>ERROR</h1>\n<h2>The requested URL could not be retrieved</h2>\n</div>\n<hr>\n\n<div id="content">\n<p>The following error was encountered while trying to retrieve the URL: <a href="cache_object://localhost.home.tsaousis.gr/squid-internal-mgr/counters">cache_object://localhost.home.tsaousis.gr/squid-internal-mgr/counters</a></p>\n\n<blockquote id="error">\n<p><b>Invalid URL</b></p>\n</blockquote>\n\n<p>Some aspect of the requested URL is incorrect.</p>\n\n<p>Some possible problems are:</p>\n<ul>\n<li><p>Missing or incorrect access protocol (should be <q>http://</q> or similar)</p></li>\n<li><p>Missing hostname</p></li>\n<li><p>Illegal double-escape in the URL-Path</p></li>\n<li><p>Illegal character in hostname; underscores are not allowed.</p></li>\n</ul>\n\n<p>Your cache administrator is <a href="mailto:root?subject=CacheErrorInfo%20-%20ERR_INVALID_URL&amp;body=CacheHost%3A%20box%0D%0AErrPage%3A%20ERR_INVALID_URL%0D%0AErr%3A%20%5Bnone%5D%0D%0ATimeStamp%3A%20Mon,%2004%20Jul%202016%2011%3A59%3A32%20GMT%0D%0A%0D%0AClientIP%3A%20127.0.0.1%0D%0A%0D%0AHTTP%20Request%3A%0D%0AGET%20%2Fsquid-internal-mgr%2Fcounters%20HTTP%2F1.0%0A%0D%0A%0D%0A">root</a>.</p>\n<br>\n</div>\n\n<hr>\n<div id="footer">\n<p>Generated Mon, 04 Jul 2016 11:59:32 GMT by box (squid/3.5.19)</p>\n<!-- ERR_INVALID_URL -->\n</div>\n</body></html>\n'
```

**Comment by ktsaou** [comment]
invalid url:

```py
# cat squid3.py
#!/usr/bin/env python3
import socket
SCHEMA = "cache_object"
HOST = "localhost"
PORT = 3128
OTHER = "counters"

request = "GET " + SCHEMA + "://" + HOST + ":" + str(PORT) + "/" + OTHER + " HTTP/1.0\r\n\r\n"
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.settimeout(3)
sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
sock.connect((HOST, PORT))
sock.send(request.encode())
data = b""
header = sock.recv(1024)
while True:
    buf = sock.recv(1024)
    if not buf:
        break
    else:
        data += buf
sock.shutdown(1)
sock.close()
if b"200 OK" in header:
    print(data)
else:
    print("SOMETHING WENT WRONG")
    print(data)
```

response:

```txt
# python3 squid3.py
b'sample_time = 1467633576.700443 (Mon, 04 Jul 2016 11:59:36 GMT)\nclient_http.requests = 565721\nclient_http.hits = 20283\nclient_http.errors = 1359\nclient_http.kbytes_in = 151877\nclient_http.kbytes_out = 7664281\nclient_http.hit_kbytes_out = 355680\nserver.all.requests = 187058\nserver.all.errors = 0\nserver.all.kbytes_in = 6955160\nserver.all.kbytes_out = 100147\nserver.http.requests = 187030\nserver.http.errors = 0\nserver.http.kbytes_in = 6875846\nserver.http.kbytes_out = 100124\nserver.ftp.requests = 0\nserver.ftp.errors = 0\nserver.ftp.kbytes_in = 0\nserver.ftp.kbytes_out = 0\nserver.other.requests = 28\nserver.other.errors = 0\nserver.other.kbytes_in = 79314\nserver.other.kbytes_out = 23\nicp.pkts_sent = 0\nicp.pkts_recv = 0\nicp.queries_sent = 0\nicp.replies_sent = 0\nicp.queries_recv = 0\nicp.replies_recv = 0\nicp.query_timeouts = 0\nicp.replies_queued = 0\nicp.kbytes_sent = 0\nicp.kbytes_recv = 0\nicp.q_kbytes_sent = 0\nicp.r_kbytes_sent = 0\nicp.q_kbytes_recv = 0\nicp.r_kbytes_recv = 0\nicp.times_used = 0\ncd.times_used = 0\ncd.msgs_sent = 0\ncd.msgs_recv = 0\ncd.memory = 0\ncd.local_memory = 1081\ncd.kbytes_sent = 0\ncd.kbytes_recv = 0\nunlink.requests = 44874\npage_faults = 108819\nselect_loops = 20983303\ncpu_time = 2065.703000\nwall_time = 59.932437\nswap.outs = 30528\nswap.ins = 19063\nswap.files_cleaned = 0\naborted_requests = 5305\n'
```

**Comment by ktsaou** [comment]
The url `/squid-internal-mgr/counters` is for older versions of squid.

**Comment by paulfantom** [comment]
Thanks.

**Comment by ktsaou** [comment]
> The url /squid-internal-mgr/counters is for older versions of squid.

and it does not need anything else. Just this without any prefix or suffix.

**Comment by paulfantom** [comment]
So I don't need to use full address in GET?

**Comment by ktsaou** [comment]
In the second case URL, no you don't. Just connect and send `GET /squid-internal-mgr/counters HTTP/1.0`.

This of course should be tried only in autodetection and only if the first URL has failed.

**Comment by paulfantom** [comment]
You mean I need to use full address with `cache_object` but not when accessing it with `http`? If this is the case, then I know.

**Comment by ktsaou** [comment]
I am not sure I understand what you mean.

Check again my response here: https://github.com/firehol/netdata/pull/639#issuecomment-230154597

There are 2 different URLs to be tried.
Anyway, do it and I have both version of squid, so I'll let you know if something does not work.

**Comment by paulfantom** [comment]
That's exactly what I meant.

I will try to finish it today along with `hddtemp.chart.py`.

**Pull request merged**
