### PR TITLE
[cleanup crusade] move profiling to tests directory

### PR DESCRIPTION
**Pull request by paulfantom**
Profiling is nothing else than performance testing and tests should be in `tests` directory.

### CODE REVIEW

**Comment by ktsaou** [comment]
hm... `/profile/` has quick-and-dirty code to profile various aspects of netdata. They are not tests.

**Comment by paulfantom** [comment]
Can you shine some more light on what it does? Files are named `benchmark*` so I assumed it is performance testing.

**Comment by ktsaou** [comment]
Exactly, so these files test the performance of some aspect of netdata, by providing binaries that can be analyzed with `gprof`.

`gprof` enabled binaries save a log when they exit, which can then by examined with `gprof` to provide a function call graph, function call frequencies and timings, etc.

So, these are special binaries, for analyzing the performance of things. Unfortunately, I don't think they can be automated somehow. The final product of the analysis is a human readable report.

**Comment by paulfantom** [comment]
Sooo... those **are** performance **tests** :)

**Comment by paulfantom** [comment]
That doesn't matter. This PR isn't about CI system, it is about repo structure cleanup.

**Comment by ktsaou** [comment]
ok, merge?

**Comment by paulfantom** [comment]
yup! :shipit:

**Pull request merged**
