### PR TITLE
various timing improvements; new idlejitter plugin; fixed color palette management

### PR DESCRIPTION
**Pull request by ktsaou**
1. added checks to make sure the database is always current. Since netdata trusts its plugins or its slaves to provide timing information, issues in these systems may lead to charts having wrong datetime. To fix this issues netdata detected charts running in future time, but did not do anything about charts running in the past. This PR fixes that. netdata now allows up to 10 iterations (10 seconds by default) past charts. When charts are detected to be more than that time behind, netdata will fix them (gap on the dashboard).

   Charts from slaves are checked once every minute (controlled by `initial clock resync iterations` - yes, I used the same setting for 2 functions: a) the slaves will send BEGIN lines with dt = 0 for that many iterations when start streaming and b) the master will ignore the `dt` at BEGIN lines every that many iterations). I thought it was overkill to add another setting...

2. The above PR identified an issue in apps.plugin which was somehow loosing some time. The issue was not noticable on all systems. It is **now fixed**.

3. Improved idlejitter plugin. Now the plugin is a lot more capable to detect CPU jitter. VMs vs bare-matel is now clearly visible.

4. Fixed an issue in charts color palette management. Somehow, custom colors were not allowing the default palette to be appended, resulting in single-color charts.

---
This change is [Reviewable](https://reviewable.io/reviews/firehol/netdata/2114)

### CODE REVIEW

**Comment by ktsaou** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/firehol/netdata/2114)*

**Comment by ktsaou** [comment]
@l2isbad what do you think about "Reviewable"? It seems nice, but possibly too much for netdata. What do you think?

**Comment by l2isbad** [comment]
Literally the same 😄

**Comment by ktsaou** [comment]
yeah, I am disconnecting it...

**Pull request merged**
