### PR TITLE
fail2ban_plugin: can read config files from "conf_dir" now

### PR DESCRIPTION
**Pull request by l2isbad**
https://github.com/firehol/netdata/issues/1808
Not ready. Should be tested.

i will say when it's ready @ktsaou

### CODE REVIEW

**Comment by iredmail** [comment]
Confirmed, it works.

**Comment by l2isbad** [comment]
@iredmail 
Can you test it one more time?
some changes were made 😄

**Comment by iredmail** [comment]
Confirmed, the new optimization code works fine too. :)
Thank you for helping. @l2isbad

**Comment by l2isbad** [comment]
ready @ktsaou

**Comment by ktsaou** [comment]
nice! merged!

**Comment by iredmail** [comment]
Hi @l2isbad,

Why don't we read fail2ban jails from command output `fail2ban-client status`? Isn't it easier?

**Comment by l2isbad** [comment]
@iredmail 
Non root user can't execute ` fail2ban-client status`.

**Pull request merged**
