### PR TITLE
detect if running inside a container to avoid using setcap for apps.plugin

### LINKED ISSUE #1331: setcap in netdata-install.sh, problem with docker image
The command setcap on [line 714](https://github.com/firehol/netdata/blob/master/netdata-installer.sh#L714) might be incorrect in some measure. It works, but the apps.plugin is not executable when in effect. I currently worked around by running the chown/chmod commands, which should be only done if the setcap command fails (it doesn't).

I am not familiar with it in terms of:

1. I already use SYS_PTRACE as --cap-add with netdata docker as recommended,
2. apps.plugin seems to work with chown/chmod without any additional caps

Which leaves me with the question why setcap is used if chmod/chown is a reliable way to perform the same, and if setcap is used, 1) are we missing some --cap-adds on the container, or 2) is the actual setcap missing some caps to make apps.plugin executable ("Operation not permitted" when running by hand, or when run from within netdata was not exactly what was needed here).

Please advise.

### PR DESCRIPTION
**Pull request by ktsaou**
netdata-installer normally uses `setcap` to set capabilities on `apps.plugin`.

However, when running in containers, `setcap` completes reporting it has set the required capabilities, but `apps.plugin` fails to start.

To work-around this issue, `netdata-installer` can now detect if it is running inside a container and setuid to root `apps.plugin`.

This is only used if container detection works.

fixes #1331

### CODE REVIEW

**Comment by ktsaou** [comment]
@breed808 note this.
Is it proper to do something similar in the spec file?

**Comment by breed808** [comment]
I'm not sure if it is the 'proper' thing to do in a spec file, but I believe it is technically possible. @alonbl would likely know more about this than I.
The scriptlets in a spec file are passed to `bash`/`sh` for execution, so the function could be theoretically copied into `%post` scriptlet.

I can build a test package for this, but I'm not familiar enough with docker to test it.

**Comment by ktsaou** [comment]
The simplest check is this:

```
setcap ... apps.plugin || setuid ...
apps.plugin -v || setuid ...
```

So, if `setcap` succeeds but `apps.plugin` cannot be run, then fallback to setuid...

**Comment by alonbl** [comment]
I believe we have talked about this many times... this plugin should be run as separate process started separately with privileged context. it should not be a child of netdata and perform privilege escalation. if you have done so, you should could have executed it as a separate workload (container) with its own settings.

**Comment by ktsaou** [comment]
Happy New Year @alonbl !

Yes we have. You are right that it will solve this issue. However, it will complicate netdata a lot.

Have a look at this: https://github.com/firehol/netdata/issues/474#issuecomment-223142222 - if every plugin requiring special permissions ends up in its own process tree, complexity will increase exponentially. It will be impossible to coordinate them.

Maybe it would be better to split netdata in 3 parts:

1. a supervisor running as root
2. the database and web server
3. plugins

This way, the supervisor could have the right permissions to start and stop plugins as required.

I don't know. All methods have pros and cons...

**Comment by alonbl** [comment]
Hi,
We should follow least privileged mode for each of these processes, not even root.
It should not be that difficult to have s separate service/container per "plugin", anyway it is linear not exponential...
All you need is a simple rpc using usock or similar to communicate with these plugin that are executed as dependencies.
Alon

**Comment by ktsaou** [comment]
> It should not be that difficult to have s separate service/container per "plugin", anyway it is linear not exponential...

Well... it is not difficult. The question is: is it right?

I mean, if there were 10 plugins, would it be right to have 10 independent daemons running for just one job? And how could the unprivileged netdata start an independent daemon/plugin to monitor another container that just started, or stop an independent daemon/plugin because a container stopped?

You see... it will make the problem a lot more difficult. We need a solution that will be able to monitor a dynamically changing setup (like docker swarm, kubernetes, etc) easily, without a mess of configuration and integration.

So, I am still not convinced separate daemons will do the trick...

**Pull request merged**
