### PR TITLE
Add FreeBSD support to apps.plugin

### PR DESCRIPTION
**Pull request by vlvkobal**
@ktsaou is it OK for `apps.plugin` to consume 50% of one CPU core when 100-120 thousand files are opened in a system? I don't have any idea how to make `read_pid_file_descriptors()` be less resource consuming without changing the original logic of `apps.plugin`.

### CODE REVIEW

**Comment by ktsaou** [comment]
wow!

The way it works in Linux it is supposed to cache everything, so it evaluates a files only the first time it sees it and while it is open.

ok. give me a day to review it in detail.

**Comment by vlvkobal** [comment]
@ktsaou FYI. Stats for apps.plugin CPU (one core) usage:

| files opened | CPU core usage |
| --- | --- |
| 212 | 0.0% - 0.75% |
| 3655 | 1.5% - 2.3% |
| 38547 | 14% - 17% |
| 115100 | 30% - 65% |
| 115100 | later 48% - 52% |

**Comment by ktsaou** [comment]
I did the following test:

test program to create 100k files:

```c
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>

#define FILES 100000

int main() {
	int i;

	int fds[FILES];
	char filename[FILENAME_MAX + 1];
	for(i = 0; i < FILES ;i++) {
		snprintf(filename, FILENAME_MAX, "/tmp/netdata.test.%d", i);
		int fd = open(filename, O_CREAT);
		if(fd == -1)
			fprintf(stderr, "Cannot open filename '%s'\n", filename);
	}

	fprintf(stderr, "waiting...\n");
	while(1) sleep(1);
	exit(1);
}
```

This is what happened:

image

So, in Linux, apps.plugin climbed from 15 ms/second (1,5% of a single core) to 80ms/second (8% of a single core).

Can you give them same on freebsd?

**Comment by ktsaou** [comment]
What is also interesting, is that after increasing files to 100k and stopping the test program, the increased arrays inside apps.plugin made it use twice the CPU. At the gap below, I restarted apps.plugin:

image

**Comment by ktsaou** [comment]
Another test at 200000 files (2 test programs running):

image

So, it is pretty linear: 8% every 100k files.

In linux, I don't we can do anything to solve this. As you can see most of the time is system time. So, it is probably `opendir()` and `readlink()` that do this.

**Comment by ktsaou** [comment]
What can consume more CPU is a condition where 100k files are constantly changing, let's say at about 5k files removed/added per second. Is that your case?

**Comment by ktsaou** [comment]
I did another test, that is constantly changing 10k files, with up to 100k open at once:

```c

/*
 *
 * compile with:
 * # gcc -Wall -Wextra -O2 -o test test.c
 *
 */

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <string.h>

#define FILES 200000
#define CHANGES 10000
#define LOOPS 120

int myrandom(int max) {

	long long i = 0, rmax = 0;

	while(rmax < max) {
		i += rand();
		rmax += RAND_MAX;
	}

	return (int)(i * max / rmax);
}

char *filenames[FILES];
int fds[FILES];

void close_file(int i) {
	close(fds[i]);
	fds[i] = -1;

	unlink(filenames[i]);

	free(filenames[i]);
	filenames[i] = NULL;
}

void open_file(int i) {
	char filename[FILENAME_MAX + 1];
	snprintf(filename, FILENAME_MAX, "/tmp/netdata.test.%d.%d", i, myrandom(FILES));

	filenames[i] = strdup(filename);
	fds[i] = open(filenames[i], O_RDWR|O_CREAT);
	if(fds[i] == -1) {
		fprintf(stderr, "Cannot open filename '%s'\n", filename);
		free(filenames[i]);
		filenames[i] = NULL;
	}
}

void do_file(int i) {
	if(filenames[i])
		close_file(i);
	
	else
		open_file(i);
}

void cleanup(void) {
	int i;

	for(i = 0; i < FILES ;i++) {
		if(filenames[i])
			close_file(i);
	}
}

int main() {
	int i, loop = LOOPS;

	for(i = 0; i < FILES ;i++) {
		filenames[i] = NULL;
		fds[i] = -1;
	}

	while(loop--) {
		for(i = 0; i < CHANGES; i++) {
			do_file(myrandom(FILES));
		}
		sleep(1);
	}

	cleanup();

	exit(1);
}
```

image

**Comment by ktsaou** [comment]
I also verified the cpu utilization at the apps.plugin chart, is also reported by `top`. So, yes 10% for 100k files with 10k files changing every second.

**Comment by ktsaou** [comment]
The legend is a bit misleading: `files` is the number of all files apps.plugin has processed. This includes `/proc` files needed to read the process tree.

However, it also includes the open files examined: https://github.com/firehol/netdata/blob/155d0e6fbdf23b5858485e5908d91f0c529e2a77/src/apps_plugin.c#L1464

On linux there is a little hack that speeds it up and when too many files are changing. It is described here: https://github.com/firehol/netdata/blob/155d0e6fbdf23b5858485e5908d91f0c529e2a77/src/apps_plugin.c#L1473

So, in linux, files get an `fd`. This `fd` can be found as a symbolic link in `/proc/PID/fd/`. What apps.plugin does, is that if the `fd` number hasn't changed, it does not re-read the symbolic link to find what exactly it is. This little optimization accounts for much of its performance when a lot of files are constantly changing.

I suggest to change the `files` to `calls` (which would count the `sysctl` calls under freebsd, or the `/proc/PID/xxx` file reads under linux)  and add another dimension for `files`, which will count the number of new open files processed. So, under both linux and freebsd, we will get the same view.

Do you want me to do this change and rebase your PR?

**Comment by ktsaou** [comment]
I implemented this little change about the files counter and did another test.

I remove file descriptor caching at apps.plugin, so that it processes all files on every iteration.

Guess what... I got close to your figures:

image

So, with just 6.500 files, I had 45ms/second (4.5% of a single core), with 100.000 files I had 600ms/second (60%).

As I understand it, you are not saving any processing on the files. You are processing them all on every iteration (`snprint()`, etc), while you should not re-process files that remain.

This is the change I made to apps.plugin for this test:

```c
static inline int read_pid_file_descriptors(struct pid_stat *p) {
    if(unlikely(!p->fds_dirname)) {
        char dirname[FILENAME_MAX+1];
        snprintfz(dirname, FILENAME_MAX, "%s/proc/%d/fd", netdata_configured_host_prefix, p->pid);
        p->fds_dirname = strdupz(dirname);
    }

    DIR *fds = opendir(p->fds_dirname);
    if(unlikely(!fds)) return 0;

    struct dirent *de;
    char fdname[FILENAME_MAX + 1];
    char linkname[FILENAME_MAX + 1];

    // we make all pid fds negative, so that
    // we can detect unused file descriptors
    // at the end, to free them
    make_all_pid_fds_negative(p);

    while((de = readdir(fds))) {
        // we need only files with numeric names

        if(unlikely(de->d_name[0] < '0' || de->d_name[0] > '9'))
            continue;

        // get its number
        int fdid = (int) str2l(de->d_name);
        if(unlikely(fdid < 0)) continue;

        // check if the fds array is small
        if(unlikely(fdid >= p->fds_size)) {
            // it is small, extend it

            if(unlikely(debug))
                fprintf(stderr
                        , "apps.plugin: extending fd memory slots for %s from %d to %d\n"
                        , p->comm
                        , p->fds_size
                        , fdid + MAX_SPARE_FDS
                );

            p->fds = reallocz(p->fds, (fdid + MAX_SPARE_FDS) * sizeof(int));

            // and initialize it
            zero_pid_fds(p, p->fds_size, (fdid + MAX_SPARE_FDS) - p->fds_size);
            p->fds_size = fdid + MAX_SPARE_FDS;
        }

        //if(unlikely(p->fds[fdid] == 0)) {
            // we don't know this fd, get it

            sprintf(fdname, "%s/proc/%d/fd/%s", netdata_configured_host_prefix, p->pid, de->d_name);
            ssize_t l = readlink(fdname, linkname, FILENAME_MAX);
            if(unlikely(l == -1)) {
                if(debug || (p->target && p->target->debug)) {
                    if(debug || (p->target && p->target->debug))
                        error("Cannot read link %s", fdname);
                }
                continue;
            }
            else
                linkname[l] = '\0';

            file_counter++;

            // if another process already has this, we will get
            // the same id
            int new = file_descriptor_find_or_add(linkname);
            if(p->fds[fdid] < 0) p->fds[fdid] = -p->fds[fdid];
            if(p->fds[fdid])
                file_descriptor_not_used(p->fds[fdid]);

            p->fds[fdid] = new;
        //}

            // else make it positive again, we need it
            // of course, the actual file may have changed, but we don't care so much
            // FIXME: we could compare the inode as returned by readdir dirent structure
            // UPDATE: no we cannot use inodes - under /proc inodes don't change when the link is changed

        //else
        //    p->fds[fdid] = -p->fds[fdid];
    }

    closedir(fds);
    cleanup_negative_pid_fds(p);

    return 1;
}
```

**Comment by ktsaou** [comment]
merged the change with the calls/files counter. You will need to rebase.

**Comment by vlvkobal** [comment]
I've found the problem. `sysctl()` calls eat a huge amount of cpu time when they read file descriptors data. `procstat_getfiles()` is a sysctl wrapper. I can't find other methods of getting the needed information. Kernel is hiding file descriptors structures which are inside processes data so I can't get them without defining structures explicitly.

@ktsaou I think you can merge the PR. I've disabled file charts for FreeBSD by default. I might try to find a better solution later.

**Comment by ktsaou** [comment]
@vlvkobal I did another breaking change, to help this PR:

## system init pid

Please set this: https://github.com/firehol/netdata/blob/10b7678a790e70c46cf309487a9850bbce62264f/src/apps_plugin.c#L13-L15

## order of processing PIDs

In Linux, PIDs are processed one by one. To avoid discrepancies in the collected data, apps.plugin builds a sort list of all PIDs and tries to process children before parents.

In FreeBSD I understand you don't need this, since all PIDs are read instantly.

So, please set `ALL_PIDS_ARE_READ_INSTANTLY` to 1: https://github.com/firehol/netdata/blob/10b7678a790e70c46cf309487a9850bbce62264f/src/apps_plugin.c#L17-L22

## rate calculation

To lower the number of `#ifdef` in the program, I defined 2 macros that take care of rates calculations: https://github.com/firehol/netdata/blob/10b7678a790e70c46cf309487a9850bbce62264f/src/apps_plugin.c#L829-L844

## loops to find the pid in `procbase`

I saw in your code that to collect data for a PID from `procbase` you make a lot of loops through it to find it.

I added to all functions a `void *`. This is generated at `collect_data_for_all_processes()`, passed at `collect_data_for_pid()` and propagated to all data collection functions. So, please pass `&procbase[i]` there to avoid all these loops.

Keep in mind that using this feature and `ALL_PIDS_ARE_READ_INSTANTLY = 0` are mutually exclusive. You will need to refactor `collect_data_for_all_processes()` to pass this pointer properly at this point: https://github.com/firehol/netdata/blob/10b7678a790e70c46cf309487a9850bbce62264f/src/apps_plugin.c#L1882

**Comment by vlvkobal** [comment]
@ktsaou I've rebased the commits and removed the loops.
You can merge the PR.

**Comment by ktsaou** [comment]
merged! nice work!

**Comment by ktsaou** [comment]
looks nice! http://freebsd.my-netdata.io/#menu_apps_submenu_cpu;

**Pull request merged**
