### PR TITLE
Bind to 127.0.0.1 by default

### PR DESCRIPTION
**Pull request by FedericoCeratto**
Also add a security warning.
Related to #164

### CODE REVIEW

**Comment by ktsaou** [comment]
On IPv6 systems, this will make netdata inaccessible.

In my tests, binding to `::1` allows accessing netdata as either `127.0.0.1` and `::1`, but binding to `127.0.0.1` does not allow accessing netdata as `::1`.

Can you test it?

**Comment by FedericoCeratto** [comment]
That's expected. I think few people access localhost using an IPv6 address and fewer have IPv6-only local networking. Those who do can edit the conffile to use ::1.
On a side note, when listening on both 127.0.0.1 and ::1, netstat -nlpt shows only "tcp6       0      0 ::1:19999 ..." and this seems to be confusing to some users

**Comment by Kubuxu** [comment]
I think we should listen both on local IPv6 and IPv4.

User confusion about IPv6 shouldn't be a factor in this case. IPv6 adoption will be increasing there is no reason to limit it.

**Comment by Night1** [comment]
I agree with v6,  by default IPv6 should also have  priority over v4. but that is handled on the OSI model.

**Comment by FedericoCeratto** [comment]
@Kubuxu we are talking about the loopback interface. This is independent from how other network interfaces are configured: IPv4-only, IPv6-only or dual stack mode.
Anyhow @ktsaou if you think it's important to listen on IPv6 addrs as well on localhost I'll update the PR - the important bit here is no listening on every interface by default :)

**Comment by ktsaou** [comment]
Well, I am only concerned if certain systems resolve by default `localhost` to `::1`. If there is such case at scale (a main distro), people will start being frustrated and will complain. I totally understand the need though.

**Comment by szymonszydelko** [comment]
Hi,
not sure if you consider it 'a main distro', but at least arch linux when using systemd-networkd resolves localhost to `::1`.
```
$ ping localhost
PING localhost(localhost.localdomain (::1)) 56 data bytes
64 bytes from localhost.localdomain (::1): icmp_seq=1 ttl=64 time=0.028 ms
64 bytes from localhost.localdomain (::1): icmp_seq=2 ttl=64 time=0.038 ms
```
Yes, even ssh tunnels created eg using eg. `ssh user@host -fNL 8080:localhost:8080` seem to travel via ipv6 stack.

So I'd like to propose listening on `::1`  by default (it should also allow access via `127.0.0.1).

**Comment by paulfantom** [comment]
Shouldn't we use `localhost` instead of specific IP and leave resolving to the system? Can someone pinpoint me benefits of using IP versus domain name considering netdata (I'm just curious)?

**Comment by ktsaou** [comment]
> Shouldn't we use localhost instead of specific IP and leave resolving to the system? Can someone show me benefits of using IP versus domain name considering netdata (I'm just curious)?

this is related to #458

**Comment by ktsaou** [comment]
> this is related to #458

and I think could be the ideal solution. `127.0.0.1` and `::1` may fail under certain conditions. So probably, using `localhost` is probably the only universal solution.

**Comment by FedericoCeratto** [comment]
Updated to use ::1. Not on all systems this would allow IPv4 connectivity as well - however most user will use "localhost" and resolve to IPv6.
Using "localhost" in configuration files leads to daemon failing to start or behaving erratically if they cannot resolve (which might happen due to misconfiguration, /etc files being written non-atomically, failing stub resolvers...)

**Comment by ktsaou** [comment]
You are right. However `::1` fails on all raspberry Pis. There is no ipv6 at all there.
I don't like it.

I still think `localhost` is the best solution. If the user's machine is failing to resolve `localhost`, netdata will probably be the least problem he/she is having...

**Comment by ktsaou** [comment]
With the PR #723 I have added the capability to listen to multiple IP:PORTs, which can be given as hostnames too. Netdata now opens a different socket for IPv4 and IPv6, based probably on hostname resolution.

Also, netdata will fail to start only when no socket has been opened. If at least one socket has been opened it will continue.

The names of the config options have changed (the old are also accepted though):

- `port` is now `default port`
- `bind socket to IP` is now `bind to` and accepts a space or coma separated list of IPs, hostnames, probably with a different port each.

So, I suggest to change this to either:

- `bind to = localhost` (this will bind to all IPs - ipv4 and ipv6 - localhost resolves to).

or 

- `bind to = 127.0.0.1 [::1]` (the brackets are there to make sure this is the IP - it can also be `[::1]:19999` - like the web browsers accept it - but I suggest to ommit the port from `bind to` for backwards compatibility with existing config files).

**Comment by FedericoCeratto** [comment]
Updated, you might want to squash the commits ;)

**Comment by ktsaou** [comment]
> Updated, you might want to squash the commits ;)

Thanks! I don't know how to do this.

**Comment by FedericoCeratto** [comment]
I thinks this should do the trick https://help.github.com/articles/about-pull-request-merge-squashing/

**Comment by ktsaou** [comment]
done thanks!

**Pull request merged**
