### PR TITLE
FreeBSD plugin: add system interrupts chart

### PR DESCRIPTION
**Pull request by vlvkobal**

### CODE REVIEW

**Comment by ktsaou** [comment]
Nice! You rock!

**Comment by ktsaou** [comment]
@vlvkobal I have made a few changes to the freebsd VM:

1. it now listens to [http://freebsd.my-netdata.io/](http://freebsd.my-netdata.io/), [https://freebsd.my-netdata.io/](https://freebsd.my-netdata.io/) and [http://http://178.62.98.199/](http://http://178.62.98.199/). No port required. HTTPS is implemented by cloudflare.com.
2. an nginx is running at port 80, which forwards all requests to a netdata listening on localhost:19999.
3. it should be auto-updating netdata daily (`/etc/daily.local/netdata` - we need to verify this, I am a noob at freebsd).
4. The source of netdata is at `~freebsd/netdata.git` and it is installed at `/opt/netdata`.

**Comment by ktsaou** [comment]
Oh, I forgot. I see a few issues:

1. `free` swap memory is a negative number. It should not I think. It causes a few alarms in netdata.
2. disk I/O is always zero (I did quite some work there, and it did not show anything but zero).

**Comment by vlvkobal** [comment]
> 3. it should be auto-updating netdata daily (/etc/daily.local/netdata - we need to verify this, I am a noob at freebsd).

`periodic`does not set `/usr/local/bin` in the `PATH` environment. As a result `bash` couldn't be found by script. I added the path. It should work now.

**Comment by ktsaou** [comment]
thanks!

**Pull request merged**
