### PR TITLE
python.d: add 'hidden' option to charts

### LINKED ISSUE #4023: Hidden charts in python plugin
Hello.

In [External plugins](https://github.com/firehol/netdata/wiki/External-Plugins) i found this:

> options
> 
> <SKIPPED> ... and hidden to perform all operations on a chart, but do not offer it on dashboards (the chart will be send to backends). 
> CHART options have been added in netdata v1.7 and the hidden option was added in 1.10.

I'm trying to declare it like this:

```python
CHARTS = {
    'process_children': {
        'options': ['processes childrens', 'Child processes', 'childrens', 'applications', 'monit.process_childrens', 'line', 1000, 10, 'hidden'],
        'lines': [ ]
    },
}
```

But running this plugin in debug mode gives me this ("empty" string on 10th position):

```CHART monit.process_children 'processes childrens' 'Child processes' 'childrens' 'applications' 'monit.process_childrens' line 60006 1 '' 'python.d.plugin' 'monit'```

Could you, please, clarify how to declare a hidden chart in python plugin for Netdata 1.10+?

Thanks.

### PR DESCRIPTION
**Pull request by l2isbad**
quick fix #4023

### CODE REVIEW

**Comment by l2isbad** [comment]
@n0guest 

please test it
add `hidden` right after the `line` (`priority` and `update_every` is not user configurable)

**Comment by n0guest** [comment]
> add hidden right after the line (priority and update_every is not user configurable)

Yep, it helped. Now chart is hidden from Netdata web interface, but via URL for Prometheus I can see required metrics:

```
$ curl -s 'http://netdata:19999/api/v1/allmetrics?format=prometheus_all_hosts' |grep netdata_monit | grep uptime | head -n 3
netdata_monit_process_uptime_seconds_average{chart="monit.processes_uptime",family="applications",dimension="syslog",instance="netdata"} 11944441.0639269 1533099443000
netdata_monit_process_uptime_seconds_average{chart="monit.processes_uptime",family="applications",dimension="sshd",instance="netdata"} 11944435.0639269 1533099443000
netdata_monit_process_uptime_seconds_average{chart="monit.processes_uptime",family="applications",dimension="smartd",instance="netdata"} 11944441.0639269 1533099443000
```

As i understand, this fix will be included in next release? But until that moment we have to manually 
 apply patch to charts.py.

Thank you.

**Comment by l2isbad** [comment]
Just update netdata after this PR is merged @ktsaou

**Comment by n0guest** [comment]
> Just update netdata after this PR is merged @ktsaou

Thanks for info. I hope, my PR #4027 would be merged too ;)

**Comment by ktsaou** [comment]
merged it
Thank you!

**Pull request merged**
