### PR TITLE
Health monitoring (alarms) & other improvements

### PR DESCRIPTION
**Pull request by ktsaou**
This PR adds health monitoring.

Currentlly, it only sends emails with the alerts. There is no UI on the dashboard yet.

## Examples

I tried to create a very flexible mechanism that can handle alarms for almost anything.

---

Checking the latest collected values, raise an alarm if the disk is low on available disk space. This is a template that is applied on all disks

```
template: disk_full_percent
      on: disk.space
    calc: $used * 100 / ($avail + $used)
   every: 1m
    warn: $this > 80
    crit: $this > 95
```

---

Again a template for all disks to calculate the rate the disk fills, during the last 10 minutes.
It gives a warning if the disk is going to be full in less than 2 days and a critical alarm if it going to be full in the next 24 hours.

```
template: disk_fill_rate
      on: disk.space
  lookup: max -1s at -10m unaligned of avail
    calc: ($this - $avail) / (10 * 60)
   every: 30s

template: disk_full_after_hours
      on: disk.space
    calc: $avail / $disk_fill_rate / 3600
   every: 10s
    warn: $this > 0 and $this < 48
    crit: $this > 0 and $this < 24

```

---

Template for all disks: raise an alarm if the disk backlog is above 1000ms (1s) per second for 5 minutes (i.e. the disk cannot catch up the load)

```
template: 5min_disk_backlog
      on: disk.backlog
  lookup: average -5m every 1m unaligned
   green: 1000
     red: 2000
    warn: $this > $green
    crit: $this > $red
```

---

Template for all network interfaces to report the number of dropped packets in the last 10 minutes:

```
template: 10min_packet_drops
      on: net.drops
  lookup: sum -10m unaligned absolute
   every: 10s
    crit: $this > 0
```

---

## health configuration

Everything related to health configuration is in `/etc/netdata/health.d`. In this directory you can put any number of files with a suffix `.conf` to have them processed by netdata.

### Entities in the `/etc/netdata/health.d/*.conf` files

There are 2 key entities:

1. **alarms**, which are attached to specific charts, and 

2. **templates**, which define rules that should be applied to all charts having a specific `context`. You can use this feature to apply **alarms** to all disks, all network interfaces, all mysql databases, all nginx web servers, etc.

Both of these entities have exactly the same format and feature set. The only difference is the label `alarm` or `template`.

### The format

The following lines are parsed:

- `alarm: NAME` or `template: NAME`

  This line has to be first on each alarm or template. `NAME` is anything you would like to name it (the only symbols allowed are `.` and `_`).

- `on: CHART` (for alarms) or `on: CONTEXT` (for templates)

  This line defines the scope of the alarm or the context.

  For `CHART` you can use a chart `id` or `name`, as shown on the dashboard.

  `CONTEXT` is the template of a chart. For example the charts `mysql_local.net` and `mysql_server2.net` have the same context: `mysql.net`. So, you can use this to apply alarms to all `mysql.net` charts.

  To find the `CONTEXT` of a chart download the latest `netdata.conf`, find the chart you are interested and you will see its context in its configuration section. You can also find it if you fetch `http://your.netdata:19999/api/v1/charts` (again search for the chart and you will find its context).

  HELP: Contexts in netdata exists from the first day, but I have never verified that all charts have the correct one. A quick scan I made shows that everything is right. So, if you find a chart with a wrong context, please post.

  TODO: we have to show this on the dashboard - the information is already there.

- `lookup: METHOD AFTER [at BEFORE] [every DURATION] [OPTIONS] [of DIMENSIONS]`

  This makes a database lookup to find a value. Everything is the same with [badges](https://github.com/firehol/netdata/wiki/Generating-Badges). In short:

    - `METHOD` is one of `average`, `min`, `max`, `sum`, `incremental-sum`. This is required.
    - `AFTER` is a relative number of seconds, but it also accepts a single letter for changing the units, like `1s` = 1 second, `1m` = 1 minute, `1h` = 1 hour, `1d` = 1 day. You probably need a negative number of `AFTER` (i.e. how far in the past to look for the value). This is required.
    - `at BEFORE` is by default 0 and is not required. Check the badges documentation to find out how this works.
    - `every DURATION` sets the updated frequency of the lookup (supports single letter units as above too).
    - `OPTIONS` can be `percentage`, `absolute`, `min2max`, `unaligned`. Check also the the badges documentation for more info.
    - `of DIMENSIONS` is optional and has to be the last parameter. Dimensions have to be separated by `,` or `|`. The space characters found in dimensions will be keps as-is (a few dimensions have spaces in their names).

  So, the above will just lookup a value from the database.

- `green: NUMBER` and `red: NUMBER`

  Sets the green and red thresholds of a chart. Currently these are not visualized, but they are available as `$green` and `$red` in expressions.

- `every: DURATION`

  Sets the update frequency of this alarm.  

- `calc: EXPRESSION`

  This expression is evaluated just after the lookup. Its purpose is to apply some calculation before using the value looked up from the db. You can also have an expression without a lookup, using other variables that are available (so you can also create variables).

  Check expressions below for more information.

- `warn: EXPRESSION` and `crit: EXPRESSION`

  These expressions should evaluate to true or false (alternatively non-zero or zero). These trigger the alarm.

### Expressions

netdata has an internal infix expression parser. This parses expressions and creates an internal structure that allows fast execution of them.

These operators are supported `+`, `-`, `*`, `/`, `<`, `<=`, `<>`, `!=`, `>`, `>=`, `&&`, `||`, `!`, `AND`, `OR`, `NOT`. Boolean operators result in either `1` (true) or `0` (false).

Expression also support the `abs()` function.

Expressions can have variables. Variables start with `$`. Check below for more information.

There are two special value you can use:

  - `nan`, for example `$this != nan` will check if `this` is available. A variable can be `nan` if the database lookup failed. All calculations (i.e. addition, multiplication, etc) with a `nan` result in a `nan`. netdata will log an error if any `calc`, `warn` or `crit` expressions result in `nan`.

  - `inf`, for example `$this != inf` will check if `this` is not infinite. A value or variable can be infinite if divided by zero. All calculations (i.e. addition, multiplication, etc) with a `inf` result in a `inf`. netdata will log an error if any `calc`, `warn` or `crit` expressions result in `inf`.

### Variables

netdata supports 3 new internal indexes for variables that will be used in health monitoring:

  - chart local variables. All the dimensions of the chart are exposed as local variables. All chart alarms are exposed too.

  charts define a few special variables:

   - `last_collected_t` is the unix timestamp of the last data collection
   - `collected_total_raw` is the sum of all the dimensions (their last collected values)
   - `update_every` is the update frequency of the chart in seconds
   - `green` and `red` the threshold defined in alarms (these are per chart - the charts inherits them from the the first alarm that defined them)

  dimensions define their last calculated (i.e. interpolated) value, exactly as shown on the charts, but also a variable with their name and suffix `_raw` that resolves to the last collected value - as collected and another with suffix `_last_collected_t` that resolves to unix timestamp the dimension was last collected (i.e. there may be dimensions that fail to be collected while others continue normaly).

  - family variables. Same to local variables, but if there are overlapping variables, only the first are exposed.

  - host variables. All the dimensions of all charts, including all alarms, in fullname. Fullname is `CHART.VARIABLE`, where `CHART` is either the chart id or the chart name (both work).

There is also a few special variables:

  - `$this`, which is resolved to the value of the current alarm
  - `$now`, which is resolved to current unix timestamp

### Tracing health monitoring

Edit your netdata.conf and set `debug flags = 0x00800000`. Then check your `/var/log/netdata/debug.log`. It will show you how it works.

---

## other improvements

1. code cleanup.
2. log files can now be re-opened by sending a SIGHUP to netdata (no more restarts for logrotation).
3. improved systemd service.
4. netdata now runs with the IDLE process scheduler, which allows it to have an even lower priority compared to nice 19.
5. netdata charts now report both average and max API response time.
6. global netdata statistics now use gcc extensions (when available) for atomic operations on the counters, to allow lock free collection of internal statistics.
7. there is some work towards a multi-host database management. I will not proceed further though, until several other features are done.

### CODE REVIEW

**Comment by ktsaou** [comment]
I am preparing a document on how to test it.
I'll post here when ready.

**Comment by davidak** [comment]
I'm interested in testing but i'm currently low on time.
Keep up the good work!

**Comment by ktsaou** [comment]
I have done all the tests I could. This is stable, alarms do work, the overheads are minimal.

The crucial part for a C program, stability (i.e. no-crashes, no memory leaks, no-infinite loops, etc), is achieved, so this is ready to be merged.

Is anyone testing it?

**Comment by ktsaou** [comment]
fixes #785 (netdata.service)
fixes #773 (netdata.service)
fixes #769 (netdata.service)
fixes #753 (qemu VMs reported as containers)
fixes #744 (apps.plugin option to disable files/sockets processing)
fixes #318 (alarms) - I will open a new issue for rendering the UIs
fixes #110 (null pointers check)

**Comment by paulfantom** [comment]
Wow! I am impressed! :+1:

**Comment by ktsaou** [comment]
Added also the script that sends notifications via email. The email is sent to root, so you can change the routing using your MTA to come to you.

So, this is now complete (no UI on the dashboard yet). **But we do have ALARMS** !

**Comment by ktsaou** [comment]
Example alarm email:

image

**Comment by ktsaou** [comment]
@alonbl could you please this logrotate script:

https://github.com/ktsaou/netdata/blob/health/system/netdata.logrotate.in

Is it right to use kill like that?

**Comment by alonbl** [comment]
No... you cannot expect a single instance in system. If you want to kill
based on pid, the daemon should create its pidfile in non systemd
environment.
In systemd environment you should systemctl reload the service and in
service kill $MAINPID

**Comment by davidak** [comment]
I checked out this branch, compiled it, filled the disk to 97% for 6 minutes and got 22 e-mail notifications.

- i get the same notifications for `dm-1` and `xvda` what is the same disk
- in recovery mail is SEVERITY still CRITICAL
- layout broken in Open-Xchange Webinterface (see screenshot), works in Apple Mail
- `-0` (see screenshot)
- i don't like the striped header of the mail

bildschirmfoto 2016-08-17 um 12 55 50

but it's already very good! i will let it run and see if i get other notifications or problems.

do you have a ticket for further improvements like acknowledgement and time to wait before sending the first mail (only when CRITICAL for 15 minutes, after that only every 20 minutes)?

http://docs.icinga.org/icinga2/latest/doc/module/icinga2/toc#!/icinga2/latest/doc/module/icinga2/chapter/monitoring-basics#notification-delay

**Comment by ktsaou** [comment]
@alonbl thanks! Though, I cannot differentiate between systemd and non-systemd currently. I think I'll let it as-is, sending SIGHUP to all processes. SIGHUP instructs netdata to just close and open the log files. Nothing else is happening. So, I think this is a safe default for a log rotation on all systems, even if all running netdata processes are instructed to do so.

@davidak thanks for reporting back!

1. You received too many emails - I fixed it. netdata was sending emails for both CLEAR, WARNING and CRITICAL conditions for all alarms. So you received at least 3 times the emails you should.

2. Fixed the messages, and the `-0`.

3. I think I fixed the broken rendering (I cannot test it - so please do) and also removed the stripe from the header.

4. Regarding `dm-1` and `xvda`, this is a different problem. If they are the same disk, netdata should not maintain charts for both. Is there a way for netdata to figure out they are the same disk? Keep in mind netdata will track performance metrics for disk partitions, only if they are mounted. So please a github issue to settle this.

5. Delays in notifications. I am a bit sceptical about this. Let me explain:

  NMS systems do simple checks and based on these checks they trigger alarms and notifications. They need to delay notifications because it is very probably that a failure will result in a banch of notifications.

  netdata however can control the sensitivity of the trigger. Let's take an example:

  ```
template: 2min_disk_utilization
      on: disk.util
  lookup: average -2m every 1m unaligned
   green: 80
     red: 95
    warn: $this > $green
    crit: $this > $red
```

  the above will check if the average utilization of a disk is above 80% or 95% for the last 2 minutes and it will check this condition every 1 minute. If this is too sensitive for you, you can make it use 5 minutes of data.

  Another example:

  ```
template: disk_full_after_hours
      on: disk.space
    calc: $avail / $disk_fill_rate / 3600
   every: 10s
    warn: $this > 0 and $this < 48
    crit: $this > 0 and $this < 24
```

  the above will trigger if a disk is filling up too fast. It is going to be critical if the disk will fill within the next 24 hours. Let's asume we had a delay implemented, and the first alarm (disk utilization) was triggered a minute ago because an application was reading and updaring disk data. Then another application start filling up the disk and now this (disk full after hours) triggers with an estimasted time of 30 minutes. So, if this condition continues, in 30 minutes there will be no space left. What now? Is this an alarm that should be delayed for 20 minutes?

  I think that before adding a delay, we should consider the following:

  - send multi-alarm emails, so every email will have a full status report of all the alarms that are in WARNING or CRITICAL state or just changed state.

  - send multi-alarm emails, at most every N minutes (N = user configured, default = 5). So you will receive at most 12 emails per hour per netdata. We could also have a calculation here. For example, dynamically add a 1 minute delay every time a notification is sent, up to 5 minutes in total (so if your system triggers an alarm every 10 seconds, you will receive multi-alarm emails with these delays (in minutes): 0, 1, 2, 3, 4, 5, 5, 5, 5, 5, ...). 

  - if the are alarms in WARNING or CRITICAL state, send repeating emails at least once every N hours (N = user configured, default = 24). So if your disk is low on disk space, you will receive a daily email reminding that to you.

I am still examining alternatives. If you have any other leads which we could consider, please let me know.

**Comment by ktsaou** [comment]
I will add a github issue to discuss the future of notifications.

I'll be in a trip for 2 days. So, please test it. If you can't find any issues as-is, I suggest to merge it and discuss its future after this is merged.

**Comment by alonbl** [comment]
You cannot implement a system component to affect more than the minimum
requirement this is huge mistake, and log rotate only a specific location.
I am unsure why you choose these type of solutions while you have proper
method to solve it.
In your terms, you should provide two logroatates configuration, one for
systemd and one for init.d, distribution/packaging should install the right
one based on what suitable for their system, exactly the same as they
install the right init system.
In any case systemd unit file (and openrc) should support reload/refresh
whatever to enable sysadmin to perform his tasks using standard tools.

**Comment by ktsaou** [comment]
You are right @alonbl. However this is a bit more tricky. There is no universal reload in netdata. SIGHUP re-opens the log files, SIGUSR2 reloads health configuration. You cannot currently reload the core - you have to restart netdata. Does systemd support multiple actions, like openrc? I'll research a bit.

**Comment by alonbl** [comment]
unfortunately, systemd does not support custom action. A major mistake.
reload in systemd is implementation specific, you can document that reload
only clears logs... even if you do not wish to use this capability, you can
create pid file also in systemd to be used externally.

**Comment by davidak** [comment]
to your reply:

1. one should be able to configure to get only CRITICAL or WARNING and CRITICAL states

3. it is fixed. header looks much better :)

4. https://github.com/firehol/netdata/issues/800

5. the purpose of delayed notifications in Icinga is to get only really critical states. we get an e-mail if the last 3 checks (1 check/min.) was CRITICAL (called "hard state") and a push mail (also simple e-mail to another account) if that is the case for 15 minutes. I think with good sensitivity settings it is possible to have sane checks. With Icinga we currently don't have so advanced checks that predicts future failures like a filling disk. (it's really cool!)

I don't like multi-alarm emails. maybe that could be an optional feature. I want to be able to get the important information from the subject (SEVERITY HOST SERVICE). most of the time i don't need to open the mail because i know my servers and services.

I like the idea to add a higher delay after every notification. That could be set with an array like: 0 5 10 20 30 60 120 (minutes)
The user could overwrite it. Your example: 0 1 2 3 4 5 (would be very much mails for every check)

>so if your system triggers an alarm every 10 seconds

That is way to early. It can be OK again after 15 sec!

10:36 CRITICAL disk_full_after_hours = 0
10:37 Recovered from CRITICAL

I think i restarted netdata there with the newest commits. So this is an aditional error. Don't calculate checks when netdata has no data!

bildschirmfoto 2016-08-18 um 13 08 27

**Comment by paulfantom** [comment]
@ktsaou I was looking at `alarm.sh` and I have some thoughts:
- what is the reason for sending mails in html format instead of plain text?
- `sendmail` is not installed on many distros (ex. Fedora 24). I think more generic solution is to use `mail`, but I can be wrong.

**Comment by ktsaou** [comment]
> what is the reason for sending mails in html format instead of plain text?

more professional look and feel. I checked what others are doing (datadog, new relic, etc). I just followed their lead.

> sendmail is not installed on many distros (ex. Fedora 24). I think more generic solution is to use mail, but I can be wrong.

I believe the opposite is the case. sendmail is the de facto way of sending emails, and the more portable one. All mailers provide a sendmail interface. I have fedora 24. sendmail is there. mail is used for both sending and receiving and is not always there.

**Comment by ktsaou** [comment]
merged it.
@davidak let's discuss the pending issues in separate threads.

**Comment by paulfantom** [comment]
About MTA, I checked on my Fedora 24 (KDE spin, recently installed) and there is no `mail` or `sendmail`, and by default it is using `postfix`. However on debian 8, there is `mail` and `sendmail` and by default it is using `sendmail`.

**Comment by ktsaou** [comment]
Are you sure there is no `/usr/sbin/sendmail`? I work on a fedora 24 too and this sendmail is available.

Also, I see that postfix does provide a sendmail interface: http://www.postfix.org/sendmail.1.html

**Comment by paulfantom** [comment]
Pretty sure:
```
[root@hiccup paulfantom]# ls -la /usr/sbin/sendmail
ls: cannot access '/usr/sbin/sendmail': No such file or directory
```

**Comment by ktsaou** [comment]
so, is there a way to send an email on your system? We could support multiple methods at the script.

**Comment by paulfantom** [comment]
Since `alternatives --display mta` doesn't show anything, I think this system cannot send mails. I had to mix my other instance of Fedora 24 with this one while thinking about this issue.
Sorry for this causing trouble, my bad. Using `sendmail` seems to be ok.

**Pull request merged**
