### PR TITLE
better python logging

### PR DESCRIPTION
**Pull request by paulfantom**
I have added some logging messages and improved previous ones.

It is tested. Works as expected.

### CODE REVIEW

**Comment by ktsaou** [comment]
is this ok to be merged?

**Comment by paulfantom** [comment]
Yes it is.

**Comment by paulfantom** [comment]
It is still ready to be merged. I just added more logging messages.

**Comment by paulfantom** [comment]
Still mergable. 
Added logging messages to `SocketService`.

**Comment by ktsaou** [comment]
merge?

**Comment by paulfantom** [comment]
I think I got everything connected to logging from #692 and #694 .

Merge.

**Comment by ktsaou** [comment]
ok, waiting travis to finish...

**Comment by paulfantom** [comment]
wait

**Comment by ktsaou** [comment]
waiting you...

**Comment by paulfantom** [comment]
I forgot to wrap args in `str()`. Now it is ok.

I need to implement logging based on `logger` module. This is getting too complicated.

**Comment by ktsaou** [comment]
ok. waiting travis again.

Does logging has flood protection?

**Comment by ktsaou** [comment]
ready. merge?

**Comment by paulfantom** [comment]
merge.

**Comment by ktsaou** [comment]
merged

**Comment by paulfantom** [comment]
> Does logging has flood protection?`

`logger` module can do so many thing that I don't know. However I found this:
- https://docs.python.org/2/howto/logging-cookbook.html#buffering-logging-messages-and-outputting-them-conditionally
- https://docs.python.org/2/howto/logging-cookbook.html#using-a-context-manager-for-selective-logging
which might be used do do flood protection.

**Comment by paulfantom** [comment]
Also with it we could log directly to file, but I don't know if you want this.

**Comment by ktsaou** [comment]
> Also with it we could log directly to file, but I don't know if you want this.

no, don't log directly to a file. I think netdata daemon will at some point do something with the logs.

Since python.d.plugin is running 100% of time, we only need something to prevent a log flood: log entries that appear every second forever. I can only think of one solution: have a counter and an interval and do the checks in code if a log entry should be dispatched or not.

**Comment by paulfantom** [comment]
> I think netdata daemon will at some point do something with the logs.

Like forward them to something like ElasticSearch? Because that would be awesome.

**Pull request merged**
