### PR TITLE
Code cleanup + bug fixes in base.py

### LINKED ISSUE #720: python.d should not give microseconds on first BEGIN
@paulfantom it is important for netdata the first `BEGIN` line, for all charts, to have microseconds 0 or empty.

This is the only way to avoid unrealistic spikes on the charts.

Example:
```
# /usr/libexec/netdata/plugins.d/python.d.plugin debug 1 apache
 INFO: Using python v2
python.d INFO: reading configuration file: /etc/netdata/python.d.conf
python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['apache']
python.d DEBUG: apache: loading module configuration: '/etc/netdata/python.d/apache.conf'
python.d DEBUG: apache: reading configuration
python.d DEBUG: apache/localipv4: job added
python.d DEBUG: apache/localipv6: job added
python.d DEBUG: apache/localhost: job added
python.d DEBUG: all job objects [<Service(localipv4, initial daemon)>, <Service(localipv6, initial daemon)>, <Service(localhost, initial daemon)>]
python.d DEBUG: apache_localipv4 check succeeded
python.d DEBUG: apache_localipv4 changing chart name to: 'apache_local'
python.d ERROR: apache_localipv6 <urlopen error [Errno -2] Name or service not known>
python.d ERROR: apache_localipv6 check function failed.
python.d INFO: Disabled apache/localipv6
python.d DEBUG: apache_localhost check succeeded
python.d ERROR: apache_localhost already exists. Stopping 'localhost'
python.d INFO: Disabled apache/localhost
python.d DEBUG: overridden job names: ['apache_local']
python.d DEBUG: all remaining job objects: [<Service(local, initial daemon)>]
CHART apache_local.requests '' 'apache Requests' requests/s requests apache.requests line 60000 1
DIMENSION requests requests incremental 1 1
CHART apache_local.connections '' 'apache Connections' connections connections apache.connections line 60001 1
CHART apache_local.conns_async '' 'apache Async Connections' connections connections apache.conns_async stacked 60002 1
CHART apache_local.net '' 'apache Bandwidth' kilobytes/s bandwidth apache.net area 60003 1
DIMENSION sent sent incremental 1 1
CHART apache_local.workers '' 'apache Workers' workers workers apache.workers stacked 60004 1
DIMENSION idle idle absolute 1 1
DIMENSION busy busy absolute 1 1
CHART apache_local.reqpersec '' 'apache Lifetime Avg. Requests/s' requests/s statistics apache.reqpersec area 60005 1
DIMENSION requests_sec requests_sec absolute 1 1
CHART apache_local.bytespersec '' 'apache Lifetime Avg. Bandwidth/s' kilobytes/s statistics apache.bytesperreq area 60006 1
DIMENSION size_sec size_sec absolute 1 1000
CHART apache_local.bytesperreq '' 'apache Lifetime Avg. Response Size' bytes/request statistics apache.bytesperreq area 60007 1
DIMENSION size_req size_req absolute 1 1

CHART netdata.plugin_pythond_apache_local '' 'Execution time for apache_local plugin' 'milliseconds / run' python.d netdata.plugin_python area 145000 1
DIMENSION run_time 'run time' absolute 1 1

python.d DEBUG: created charts for apache_local
python.d DEBUG: apache_local will be run in 231 ms
python.d DEBUG: apache_local ready to run, after 231 ms (update_every: 1000 ms, latency: 0 ms
BEGIN apache_local.requests 231818
SET requests = 1971427
END
BEGIN apache_local.connections 231818
END
BEGIN apache_local.conns_async 231818
END
BEGIN apache_local.net 231818
SET sent = 28707390
END
BEGIN apache_local.workers 231818
SET idle = 11707
SET busy = 53
END
BEGIN apache_local.reqpersec 231818
SET requests_sec = 8
END
BEGIN apache_local.bytespersec 231818
SET size_sec = 129614
END
BEGIN apache_local.bytesperreq 231818
SET size_req = 14911
END

BEGIN netdata.plugin_pythond_apache_local 231818
SET run_time = 5
END
python.d DEBUG: apache_local updated in 5 ms
python.d DEBUG: apache_local ready to run, after 1000 ms (update_every: 1000 ms, latency: 1 ms
BEGIN apache_local.requests 1000944
SET requests = 1971443
END
BEGIN apache_local.connections 1000944
END
BEGIN apache_local.conns_async 1000944
END
BEGIN apache_local.net 1000944
SET sent = 28707686
END
BEGIN apache_local.workers 1000944
SET idle = 11702
SET busy = 58
END
BEGIN apache_local.reqpersec 1000944
SET requests_sec = 8
END
BEGIN apache_local.bytespersec 1000944
SET size_sec = 129614
END
BEGIN apache_local.bytesperreq 1000944
SET size_req = 14911
END

BEGIN netdata.plugin_pythond_apache_local 1000944
SET run_time = 2
END
python.d DEBUG: apache_local updated in 2 ms
```

### LINKED ISSUE #721: python.d logservice parses the whole file when starting
@paulfantom the LogService should not parse the whole file on the first iteration. The way it is now, if the log file monitored is huge, it takes a considerable amount of time to start.

Of course, special care has to be taken so that this happens only on the first iteration. If the file is closed and re-opened it should attempt to continue from the point it was the last time, or fallback to parse the whole file only if the length of the file is smaller that then last known length.

### PR DESCRIPTION
**Pull request by paulfantom**
1. Merged `BaseService` and `SimpleService` into one.
2. Added more comments and some debug statements
3. Little speed improvements with moving to local variables
4. Fix #720 
5. Fix #721 
6. replace `sys.stdout.write` with appropriate method
7. implement proxy handling in `UrlService` (currently commented-out since it is not tested)
8. Increase timeout for http responses
9. `_get_raw_data` in `LogService` now returns empty list if no new lines were added to log file. This should be used in module `_get_data` method.

### CODE REVIEW

**Comment by paulfantom** [comment]
I am swamped with work now, but I finished some things that were started earlier, to the level at which they should work. Some basic test were run, but I don't have time to properly test this.

**Comment by ktsaou** [comment]
Is this mergeable?

**Comment by paulfantom** [comment]
It should work, but I didn't have time to properly test it since I still don't have access to my machine (I am on a trip and will be back on Sunday).

If you could wait 3 days, I will test and merge it.

**Comment by ktsaou** [comment]
Of course, no hurry.

**Comment by paulfantom** [comment]
I believe it didn't broke anything and is working. merging.

**Pull request merged**
