### PR TITLE
Litespeed module

### PR DESCRIPTION
**Pull request by l2isbad**
fixes https://github.com/firehol/netdata/issues/3781

@lucasRolff  please check

what should i change/add?

add:

- [x] network trhoughput (http/https)
- [x] connections (http/https  used/free)
- [x] requests in processing

### CODE REVIEW

**Comment by lucasRolff** [comment]
Hi @l2isbad 

I pulled down your pull request and tested it out - sadly with no charts.

Apparently the `/tmp/lshttpd/` dir is owned by `nobody/nobody` with permissions `0751/drwxr-x--x` - so Netdata won't be able to read the files in there - running as the netdata user, it will give a permission denied:
```
bash-4.2$ ls -al /tmp/lshttpd/
ls: cannot open directory /tmp/lshttpd/: Permission denied
```

I tried temporarily to add netdata to the "nobody" group, which will make it work, however - I'm not sure how "safe" that is. - in this case, the permissions only give read and execute to the netdata user which should be fine.

The stats provided (net throughput, requests, cache, static requests), for my use, is perfectly fine.

The connections would be awesome too (http|https free|used) - and maybe the "In Processing" (`REQ_RATE[]: REQ_PROCESSING`) under requests would be cool as well, however, it's not really something I would personally make use of.

**Comment by lucasRolff** [comment]
I found another thing that I'm curious about after reading through the code.

In https://github.com/firehol/netdata/pull/3782/files#diff-557e504ed8ca229fefdba2bf9809739fR63 it uses the `TOT_REQS`, I understand this is done to send netdata an increment of the requests processed over your `update_every` and thus it can calculate the requests per second by itself by doing a difference calculation between the first and last number.

However, after letting netdata run for roughly 1 hour, I saw this:
REQ Spike

It causes a spike in the graph - without the `TOT_REQS` seeing the same spike of 20k requests in the `.rtreport*` files.

One issue I can see with relying on `TOT_REQS`, is that it's being an absolute number and netdata calculates the difference, so let's say that netdata decides to fetch data at same time as litespeed is (re)writing the .rtreportX files, the data might temporarily be missing from one or more files.

-----
## Using incremental numbers (`TOT_REQS`):

netdata run 1:
`.rtreport`: TOT_REQS: 10
`.rtreport.2`: TOT_REQS: 10000

Total: 10010

netdata run 2:
`.rtreport`: TOT_REQS: 20
`.rtreport.2`: TOT_REQS: 10020

Total: 10040
(increase of 30 req / 10 = 3 req/s)

netdata run 3:
`.rtreport`: TOT_REQS: 20
`.rtreport.2` Nothing (since file is rewritten/missing temporary while getting rewritten)

Total: 20
(decrease of 10020)

netdata run 4:
`.rtreport`: TOT_REQS: 30
`.rtreport.2`: TOT_REQS: 10040

Total: 10070
(increase of 10050 req / 10 = 1'005 req/s)

-----
## Using absolute numbers (`REQ_PER_SEC`):

netdata run 1:
`.rtreport`: REQ_PER_SEC: 1.1
`.rtreport.2`: REQ_PER_SEC: 10.1

Total: 11.2

netdata run 2:
`.rtreport`: REQ_PER_SEC: 1.3
`.rtreport.2`: REQ_PER_SEC: 12.1

Total: 13.4

netdata run 3:
`.rtreport`: REQ_PER_SEC: 1.1
`.rtreport.2` Nothing (since file is rewritten/missing temporary while getting rewritten)

Total: 1.1

netdata run 4:
`.rtreport`: REQ_PER_SEC: 1.1
`.rtreport.2`: REQ_PER_SEC: 12.1

Total: 13.2

-----

We will still experience a drop from 13.4 to 1.1 req/s and then up to 13.2 req/s again - however, because it's relative the impact on the graph will be a whole lot smaller, and would more be seen as a "drop" in traffic instead of a huge spike in traffic.

The same goes for pub/private cache hit and static hits as well, the change seems rather simple by renaming a few keys in the python script and changing `incremental` to `absolute`, but I wonder your take on it @l2isbad

**Comment by l2isbad** [comment]
@lucasRolff i think i did all changes you suggested, please check it again :smile:

**Comment by lucasRolff** [comment]
It's absolutely perfect @l2isbad! Thank you so much!

Small screenshot.. I couldn't make the static section fit into it, but that one works as well at least 👍 
alt

**Comment by l2isbad** [comment]
@lucasRolff 

According
https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:config:real-time-stats

> Make sure “lsadm” user belongs to “lshttpd” folder group and .status and .rtreport file group 

What about `lshttpd` group? 

> Or Through the local admin port:

```
curl -i -u username:password http://localhost:7080/status?rpt=detail 
curl -i -u username:password http://localhost:7080/status?rpt=summary 
```

^^ That seem much better solution than read stats from files. How often is it updated? Please check.

**Comment by lucasRolff** [comment]
@l2isbad 

## file ownership

> Make sure “lsadm” user belongs to “lshttpd” folder group and .status and .rtreport file group

`/tmp/lshttpd/.status` is owned by:
`Access: (0600/-rw-------)  Uid: (  978/   lsadm)   Gid: ( 1156/   lsadm)`

the .status contains a list of enabled/disabled vhosts and their corresponding IPs, so for netdata isn't useful.

`/tmp/lshttpd/` is owned by nobody:nobody on latest install
`/tmp/lshttpd/.status` is owned by lsadm:lsadm
`/tmp/lshttpd/lshttpd.pid` is owned by root:nobody
Every other file (swap files, socket files, .rtreport) in the directory is owned by nobody:nobody.

## curl interface

> ^^ That seem much better solution than read stats from files. How often is it updated? Please check.

The curl example calls a PHP function within litespeed's admin interface that reads `.rtreport*` files - so it's updated very 10 seconds as well, so basically their "real time" dashboard consumes the files in the same way (actually in a more complex way) than you've implemented, it does have the requirement of username and password

What I don't like about their http endpoint is the fact it requires username and password to query the status - the username and password at same time give access to change settings in litespeed so you go from a "read only" permissions in netdata to possibly read/write permissions in case credentials would somehow get exposed, there's no possibility to create a "read only" user for the stats.

Also in recent versions of litespeed they enforce https:// on the interface but doesn't issue an actual cert, so it would be required to use `--insecure` in curl.

###  Summary

- status page consumes `.rtreport*` (so update every 10s)
- requires username/password that gives read/write access to litespeed configuration
- enforces https over self-signed certificate

**Comment by l2isbad** [comment]
> The curl example calls a PHP function within litespeed's admin interface that reads .rtreport* files - so it's updated very 10 seconds as well,

Ok, let's leave it as it is. I will add `add to nobody group requirement` to the readme/conf files and looks like we are done if there is no any suggestions

**Comment by Ferroin** [comment]
FWIW, I'd actually question the reasoning behind the files having `nobody:nobody` ownership but not world readable in the first place.  `nobody` as a user or group is supposed to be no ownership, which means it should be accessible by everyone.  Might be worth opening a ticket for Litespeed itself asking why they're doing things this way.

**Comment by lucasRolff** [comment]
@Ferroin I'd indeed "assume" they'd use the `lsadm` user for their files in the /tmp/lshttpd/ directly and the directory itself, since it would make sense.

Now the reason why it's at least not readable by everyone, it's simply due to the fact the file contains a list of all vhosts and IPs on a given system - in a shared hosting environment it's not something you'd want to have exposed - so I understand why they're at least limiting the read permissions.

the litespeed processes run as `nobody` - so it make sense that the tmp dir is owned by nobody then as well - thus requires the more strict read perms

**Comment by l2isbad** [comment]
@Ferroin what do you think if we add `netdata` to `nobody` group?

**Comment by Ferroin** [comment]
@l2isbad it should be safe with most standard system configurations, provided we don't write any sensitive data to a file owned by that group.

**Comment by ktsaou** [comment]
you rock! (as always!)

**Pull request merged**
