### PR TITLE
Better logging from python.d and its modules

### PR DESCRIPTION
**Pull request by paulfantom**
Due to the fact that logs sent by python modules are usually insufficient to debug anything by other users of netdata, I refactored every piece of code responsible for sending messages to stderr. It is also a beginning of work to resolve issue #1155.
This pull request implements hierarchical python logger ("python" -> "base" -> "module") based on `logging` module. It also implements log rate limitation (spam prevention) in form of `TruncateFilter` class as well as logging full stack trace messages. I will also add configurable option to desired log level from configuration file (it may be possible to configure different log levels for different modules).

Currently testing is in progress.

### CODE REVIEW

**Comment by ktsaou** [comment]
nice!

**Comment by ktsaou** [comment]
hm... @paulfantom I made several changes to python.d.plugin, unfortunately without taking into account this. Now there are a few conflicts to be resolved.

**Comment by ktsaou** [comment]
First, I have to say that I hope @paulfantom is ok. He stopped his work suddenly, has not committed anything on any github project since this, so I am worried for his health. I hope everything is good for him.

@l2isbad I would like to close this. Do you need it open? Is there anything we would like to merge from this PR?

**Comment by l2isbad** [comment]
> I would like to close this
I agree

**Comment by ktsaou** [comment]
ok. closing it.

**Pull request closed without merging**
