### PR TITLE
Added charts for traefik reverse proxy

### PR DESCRIPTION
**Pull request by amenezes**
@l2isbad here is the new PR.

### CODE REVIEW

**Comment by ktsaou** [comment]
merged!

**Comment by ktsaou** [comment]
There are a few things missing about traefik:

1. a recent screenshot (I would appreciate it if this was from a live server with some data - the demo is pretty idle)
2. an entry to the wiki menu
3. an entry to the "add new charts" page
4. an entry at the netdata infographic
5. an entry at README.md
6. an icon at the dashboard
7. info text for the charts at the dashboard

@amenezes can you take care of them?

**Comment by ktsaou** [comment]
traefik logo for the infographic:
image

**Comment by ktsaou** [comment]
Added it to the infographic and the wiki menu.
Please add it to: https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata

**Comment by amenezes** [comment]
Added description on https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata.

@ktsaou I'll try to get a better screenshot.

**Pull request merged**
