### PR TITLE
[cleanup crusade] travis build stages

### PR DESCRIPTION
**Pull request by paulfantom**
Trying to introduce travis build stages, clean CI pipelines and introduce tests

Solves #4133

This is required to have a clean way to build distro packages in the future.

### CODE REVIEW

**Comment by paulfantom** [comment]
`addons` are incompatible with travis build stages so they were replaced by global `install` directive

**Comment by ktsaou** [comment]
I think we should just ignore third party javascript libraries. There is no need to lint bootstrap for example.
So, the only javascript files required are the `/web/*.js`, `plugins.d/node.d.plugin`, `node.d/*.js` and `node.d/node_modules/netdata.js`.

**Comment by ktsaou** [comment]
or, we should ignore `web/lib` and `node.d/node_modules` (except `node.d/node_modules/netdata.js`).

**Comment by ktsaou** [comment]
Work for unittesting javascript code has been done by @ccremer here: https://github.com/firehol/netdata/pull/2473

**Comment by paulfantom** [comment]
@ccremer how can I run those tests in travis (do they need graphical interface)?

**Comment by ktsaou** [comment]
Same for CSS. Our css is only `web/*.css`. All the other CSS files are third party.

**Comment by paulfantom** [comment]
Only `web/*.css` are linted.

**Comment by ccremer** [comment]
Ooof, it's been a while. At the time I documented the most important stuff in https://github.com/firehol/netdata/blob/master/tests/README.md
While I did these with CI in mind, I never tested this on a truly headless server. I configured it with ChromiumHeadless and it ran on a desktop Centos, but likely the installation of chromium could bring the whole GUI packages with it. Not cool for travis, but not sure either.

Otherwise the unittests are launched with `nodejs ./node_modules/karma/bin/karma start tests/web/karma.conf.js --single-run=true --browsers=ChromiumHeadless`. PhantomJS is probably the better "browser", as it's made for CI, but one needs to figure out the installation on travis (hopefully npm dev dependency is enough).
Also, I think we could/should move to mocha sometime instead of using the jasmine hack I did at the time.

My recommendation: Try using it with PhantomJS, with the jasmine framework. If somebody is adding unit tests later, we should move to mocha. **OR**
Somebody is willing to move to mocha now while we integrate unit testing in travis and configures it with phantomjs, and that someone is not me for the time being.

**Comment by paulfantom** [comment]
I don't know any node.js so I will create an issue and not implement testing here.

**Comment by ktsaou** [comment]
ok, let me know when it is ready to merge...

**Comment by paulfantom** [comment]
I have moved making github artifacts to a bash script, so it could be tested manually not only from travis. This should work now, but it also might need some fine-tuning after merging.

Explanation on how CI implemented here works and what it does:

There are two "modes" of operation:
- PR workflow (travis running on PR)
- master branch (travis running after PR got merged to master branch)

I am not sure if "master branch" mode will work on direct push to master, but it is not important as such option should be prohibited (see #4137).

Two main differences between those modes are:
1) in PR workflow travis secrets are not used to prevent leaking secure informations
2) PR workflow doesn't run "release" stage

So on every commit travis will run 3 stages in sequence with "steps" in parallel:
1) "lint" stage runs in parallel:
  - pylint
  - jslint
  - csslint
  - shellcheck
2) "test" stage runs:
  - netdata C tests
3) "build" stage:
  - installer on linux
  - installer on osx

Additionally in "master branch" mode it will run 4th stage called "release" which runs:
  - `docker/build.sh`
  - `travis/create_artifacts.sh` and depolys artifacts to github

Also I have added fossa notification after builds which should be enabled following my prev comment: https://github.com/firehol/netdata/pull/4142#issuecomment-419752639


In current state only `jslint` can cause pipeline to fail as other linter steps won't return exit code different than 0 (`.... || echo "OK"`). This is due to the fact, that our code is not following coding standards needed for pylint (PEP8), shellcheck, and csslint. This should be fixed in other PRs.


After merging this I suggest making travis a mandatory check in github workflow. Section "Require status checks to pass before merging".

**Comment by paulfantom** [comment]
And it is ready to be merged so :shipit:.

**Comment by ktsaou** [comment]
nice!

I can't figure out what I should do about fossa - travis integration from this: https://fossa.io/docs/integrating-tools/travisci/ 

Can you help?

> After merging this I suggest making travis a mandatory check in github workflow. Section "Require status checks to pass before merging".

I suggest to do this after a few days, to make sure it works properly.

**Comment by ktsaou** [comment]
Regarding FOSSA, the 2 issues they present, refer to old code. I tried ignoring them, but then most of the code is just ignored.

I think that somehow FOSSA has messed a bit with commits.

One way to attempt fixing the issue, is to delete the project at FOSSA and add it again.

@Ferroin what do you think?

**Comment by paulfantom** [comment]
About fossa:

> You will also have to update your project settings in FOSSA by navigating to Project > Settings > Update Hooks, and selecting TravisCI in the dropdown.

and that is all you need to do.

**Comment by ktsaou** [comment]
Not much there:

image

**Comment by ktsaou** [comment]
The TravisCI Docs is this page: https://docs.travis-ci.com/user/notifications#Configuring-webhook-notifications

**Comment by paulfantom** [comment]
From a screenshot I can say that this is already set up :+1:

**Comment by ktsaou** [comment]
ok. I still don't know how to make FOSSA ignore the past commits it processes and use the latest ones.

**Comment by paulfantom** [comment]
I don't know, but it not related to this PR

**Comment by ktsaou** [comment]
I sent an email to FOSSA support. 

If I delete the project from FOSSA and add it again, do we have to update something? I guess the github webhook will have to be updated, but what about travis?

**Comment by paulfantom** [comment]
Travis doesn't have to do anything with fossa. We just send a message to fossa after build is done and it doesn't affect build status, that's why this is not related to this PR.

**Comment by paulfantom** [comment]
:shipit: ?

**Comment by ktsaou** [comment]
So, merge?

**Comment by paulfantom** [comment]
yup, :shipit: == "ship it" :smile:

**Comment by ktsaou** [comment]
merged!

**Pull request merged**
