### PR TITLE
cpuidle.chart.py: add plugin for monitoring cpuidle states

### PR DESCRIPTION
**Pull request by tycho**
This implements a new 'cpuidle.chart.py' plugin which shows [cpuidle](https://www.kernel.org/doc/Documentation/cpuidle/sysfs.txt) residency metrics.

### CODE REVIEW

**Comment by ktsaou** [comment]
nice! does this need a config file?

**Comment by tycho** [comment]
@ktsaou Probably not. But I'd argue the cpufreq module doesn't either, for the same reason (why the hell would sysfs not be mounted at `<prefix>/sys`?). I can probably gut those config options in another patch.

**Comment by tycho** [comment]
I have future work for this module that I just discovered. When running this on a different kernel configuration, the stats don't always update before we read them. This results in some bizarre graphs where 100% of time was "spent" in C0 (actually C6). I think I'll just check whether the metrics changed between updates, and if not, just report the most recent change.

**Comment by ktsaou** [comment]
> But I'd argue the cpufreq module doesn't either, for the same reason (why the hell would sysfs not be mounted at <prefix>/sys?).

Well, people are using exotic configurations... so these config files allow them to override the internal defaults. In most of the cases this is needed when people map different host directories inside containers. The `<prefix>` is passed by netdata already, but people do get creative when mapping things in containers.

>  I can probably gut those config options in another patch.

Please do.

> I think I'll just check whether the metrics changed between updates, and if not, just report the most recent change.

ok. let me know when you are ready, to merge it.

**Comment by tycho** [comment]
Okay, I've fixed it. I found out the hard way that I needed to "tickle" the CPUs with a trivial amount of work in order to force them to update their cpuidle metrics (if they're totally idle, all the metrics will stop increasing).

The downside is that in order to wake the CPUs up, I need to temporarily bind the thread to each CPU in sequence. But there's no Python way to get a thread id (os.getpid doesn't cut it, I checked). So right now there's a really ugly ctypes-based syscall in there, and it currently only has the syscall numbers for gettid() on i386/x86_64. But I'm not sure whether this plugin would work correctly on anything but those architectures for the moment anyway (it might, but I can't test it).

**Comment by ktsaou** [comment]
Running on RPi, python2:

```
# /usr/libexec/netdata/plugins.d/python.d.plugin debug 1 cpuidle
2017-01-10 09:44:48:  INFO: Using python v2
2017-01-10 09:44:50: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
2017-01-10 09:44:50: python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['cpuidle']
2017-01-10 09:44:52: python.d ERROR: cpuidle: configuration file '/etc/netdata/python.d/cpuidle.conf' not found. Using defaults.
2017-01-10 09:44:52: python.d DEBUG: cpuidle: setting configuration for only one job
2017-01-10 09:44:52: python.d DEBUG: cpuidle: job added
2017-01-10 09:44:52: python.d DEBUG: all job objects [<Service(None, initial daemon)>]
2017-01-10 09:44:52: python.d ERROR: cpuidle Cannot get thread ID. Stats would be completely broken.
2017-01-10 09:44:52: python.d ERROR: cpuidle check() failed - disabling job
2017-01-10 09:44:52: python.d ERROR: DISABLED: cpuidle/None
2017-01-10 09:44:52: python.d DEBUG: overridden job names: []
2017-01-10 09:44:52: python.d DEBUG: all remaining job objects: []
2017-01-10 09:44:52: python.d FATAL: no more jobs
DISABLE
```

Running on RPi python3

```
# python3 /usr/libexec/netdata/plugins.d/python.d.plugin debug 1 cpuidle
2017-01-10 09:45:19:  INFO: Using python v3
2017-01-10 09:45:22: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
2017-01-10 09:45:22: python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['cpuidle']
2017-01-10 09:45:22: python.d ERROR: Problem loading cpuidle 'module' object has no attribute 'SourceFileLoader'
2017-01-10 09:45:22: python.d FATAL: no modules found.
DISABLE
```

**Comment by ktsaou** [comment]
on intel, it runs with python2 and python3.

**Comment by ktsaou** [comment]
merged!

**Comment by tycho** [comment]
@ktsau If you want to add RPi support (assuming the RPi's kernel has a cpuidle driver), that'd be neat. You may just need to add the syscall number to the dictionary in cpuidle.chart.py. I think on arm, the syscall number is 224:

```
arch/arm/include/uapi/asm/unistd.h:#define __NR_gettid                  (__NR_SYSCALL_BASE+224)
arch/arm64/include/asm/unistd32.h:#define __NR_gettid 224
```

But depends on the ABI:
```
arch/arm/include/uapi/asm/unistd.h:#define __NR_OABI_SYSCALL_BASE       0x900000
arch/arm/include/uapi/asm/unistd.h:#define __NR_SYSCALL_BASE    0
arch/arm/include/uapi/asm/unistd.h:#define __NR_SYSCALL_BASE    __NR_OABI_SYSCALL_BASE
```

So it may be (0x900000 + 224) or 224.

**Comment by tycho** [comment]
Also I wonder why RPi's python3 broke. I didn't add the SourceFileLoader thing, that's just in stock python.d.plugin...

**Comment by ktsaou** [comment]
image

**Comment by tycho** [comment]
@ktsaou Looks nice, but that's not what I asked. :)

**Comment by ktsaou** [comment]
oh, sorry! I just posted it to twitter and I needed an image...

So, what is the question? let me check again...

Regarding a RPi cpuidle driver I see it in `dmesg`, so I guess it is there. It would be nice to have it, if that is not too hard. Is there a way to find in code which ABI to use?

Regarding my python3, I don't know. The one I checked is raspbian 7.

**Comment by tycho** [comment]
@ktsaou Try compiling this and running it on the RPi, it should give you the appropriate line to add to the dictionary:

```c
#define _GNU_SOURCE
#include <unistd.h>
#include <sys/syscall.h>
#include <sys/utsname.h>
#include <stdio.h>

int main(int argc, char **argv)
{
        struct utsname host = {0};
        uname(&host);
        printf("{ '%s': %d },\n", host.machine, SYS_gettid);
        return 0;
}
```

**Comment by ktsaou** [comment]
Here it is:

```
$ ./test 
{ 'armv6l': 224 },
```

**Comment by tycho** [comment]
Neat, If you add that into cpuidle.chart.py in the dictionary, the cpuidle plugin might just work!

**Comment by ktsaou** [comment]
ok, I'll try it.

Here is for rpi2+:

```
$ ./test 
{ 'armv7l': 224 },
```

**Comment by ktsaou** [comment]
RPi 2+ does not work:

```
# /usr/libexec/netdata/plugins.d/python.d.plugin debug 1 cpuidle
2017-01-12 02:15:37:  INFO: Using python v2
2017-01-12 02:15:37: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
2017-01-12 02:15:37: python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['cpuidle']
2017-01-12 02:15:38: python.d ERROR: cpuidle: configuration file '/etc/netdata/python.d/cpuidle.conf' not found. Using defaults.
2017-01-12 02:15:38: python.d DEBUG: cpuidle: setting configuration for only one job
2017-01-12 02:15:38: python.d DEBUG: cpuidle: job added
2017-01-12 02:15:38: python.d DEBUG: all job objects [<Service(None, initial daemon)>]
2017-01-12 02:15:38: python.d ERROR: cpuidle couldn't find cstate stats
2017-01-12 02:15:38: python.d ERROR: cpuidle check() failed - disabling job
2017-01-12 02:15:38: python.d ERROR: DISABLED: cpuidle/None
2017-01-12 02:15:38: python.d DEBUG: overridden job names: []
2017-01-12 02:15:38: python.d DEBUG: all remaining job objects: []
2017-01-12 02:15:38: python.d FATAL: no more jobs
DISABLE
```

**Comment by tycho** [comment]
Can you do `find /sys/devices/system/cpu/cpuidle /sys/devices/system/cpu/cpu*/cpuidle` on there? Might shed light on what it makes available to us.

**Comment by ktsaou** [comment]
RPi 1 does not work:

```
# /usr/libexec/netdata/plugins.d/python.d.plugin debug 1 cpuidle
2017-01-12 02:17:38:  INFO: Using python v2
2017-01-12 02:17:39: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
2017-01-12 02:17:39: python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['cpuidle']
2017-01-12 02:17:41: python.d ERROR: cpuidle: configuration file '/etc/netdata/python.d/cpuidle.conf' not found. Using defaults.
2017-01-12 02:17:41: python.d DEBUG: cpuidle: setting configuration for only one job
2017-01-12 02:17:41: python.d DEBUG: cpuidle: job added
2017-01-12 02:17:41: python.d DEBUG: all job objects [<Service(None, initial daemon)>]
2017-01-12 02:17:41: python.d ERROR: cpuidle couldn't find cstate stats
2017-01-12 02:17:41: python.d ERROR: cpuidle check() failed - disabling job
2017-01-12 02:17:41: python.d ERROR: DISABLED: cpuidle/None
2017-01-12 02:17:41: python.d DEBUG: overridden job names: []
2017-01-12 02:17:41: python.d DEBUG: all remaining job objects: []
2017-01-12 02:17:41: python.d FATAL: no more jobs
DISABLE
```

**Comment by ktsaou** [comment]
RPi 2+:

```
# find /sys/devices/system/cpu/cpuidle /sys/devices/system/cpu/cpu*/cpuidle
/sys/devices/system/cpu/cpuidle
/sys/devices/system/cpu/cpuidle/current_driver
/sys/devices/system/cpu/cpuidle/current_governor_ro
find: `/sys/devices/system/cpu/cpu*/cpuidle': No such file or directory
```

RPi 1:

```
# find /sys/devices/system/cpu/cpuidle /sys/devices/system/cpu/cpu*/cpuidle
find: `/sys/devices/system/cpu/cpuidle': No such file or directory
find: `/sys/devices/system/cpu/cpu*/cpuidle': No such file or directory
```

**Comment by tycho** [comment]
Bummer. No useful stats!

Out of curiosity, does the cpufreq plugin work fine on those?

**Comment by ktsaou** [comment]
On RPi 1:

```
# /usr/libexec/netdata/plugins.d/python.d.plugin debug 1 cpufreq
2017-01-12 02:21:26:  INFO: Using python v2
2017-01-12 02:21:27: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
2017-01-12 02:21:27: python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['cpufreq']
2017-01-12 02:21:28: python.d DEBUG: cpufreq: loading module configuration: '/etc/netdata/python.d/cpufreq.conf'
2017-01-12 02:21:28: python.d DEBUG: cpufreq: reading configuration
2017-01-12 02:21:28: python.d DEBUG: cpufreq: job added
2017-01-12 02:21:28: python.d DEBUG: all job objects [<Service(None, initial daemon)>]
2017-01-12 02:21:30: python.d INFO: CHECKED OK: cpufreq
2017-01-12 02:21:30: python.d DEBUG: overridden job names: []
2017-01-12 02:21:30: python.d DEBUG: all remaining job objects: [<Service(None, initial daemon)>]
CHART cpu.cpufreq '' 'CPU Clock' MHz cpufreq '' line 90000 1
DIMENSION cpu0 cpu0 absolute 1 1000

CHART netdata.plugin_pythond_cpufreq '' 'Execution time for cpufreq plugin' 'milliseconds / run' python.d netdata.plugin_python area 145000 1
DIMENSION run_time 'run time' absolute 1 1

2017-01-12 02:21:30: python.d DEBUG: created charts for cpufreq
2017-01-12 02:21:30: python.d DEBUG: cpufreq starting data collection - update frequency: 1.0  retries allowed: 10
2017-01-12 02:21:30: python.d DEBUG: cpufreq sleeping for 0.66139793396 secs to reach frequency of 1.0 secs, now: 1484180490.34  next: 1484180491.0  penalty: 0
BEGIN cpu.cpufreq 0
SET cpu0 = 950000
END 

BEGIN netdata.plugin_pythond_cpufreq 0
SET run_time = 5
END
```

On RPi 2+:

```
# /usr/libexec/netdata/plugins.d/python.d.plugin debug 1 cpufreq
2017-01-12 02:22:10:  INFO: Using python v2
2017-01-12 02:22:10: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
2017-01-12 02:22:10: python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['cpufreq']
2017-01-12 02:22:10: python.d DEBUG: cpufreq: loading module configuration: '/etc/netdata/python.d/cpufreq.conf'
2017-01-12 02:22:10: python.d DEBUG: cpufreq: reading configuration
2017-01-12 02:22:10: python.d DEBUG: cpufreq: job added
2017-01-12 02:22:10: python.d DEBUG: all job objects [<Service(None, initial daemon)>]
2017-01-12 02:22:10: python.d INFO: CHECKED OK: cpufreq
2017-01-12 02:22:10: python.d DEBUG: overridden job names: []
2017-01-12 02:22:10: python.d DEBUG: all remaining job objects: [<Service(None, initial daemon)>]
CHART cpu.cpufreq '' 'CPU Clock' MHz cpufreq '' line 90000 1
DIMENSION cpu2 cpu2 absolute 1 1000
DIMENSION cpu3 cpu3 absolute 1 1000
DIMENSION cpu0 cpu0 absolute 1 1000
DIMENSION cpu1 cpu1 absolute 1 1000

CHART netdata.plugin_pythond_cpufreq '' 'Execution time for cpufreq plugin' 'milliseconds / run' python.d netdata.plugin_python area 145000 1
DIMENSION run_time 'run time' absolute 1 1

2017-01-12 02:22:10: python.d DEBUG: created charts for cpufreq
2017-01-12 02:22:10: python.d DEBUG: cpufreq starting data collection - update frequency: 1.0  retries allowed: 10
2017-01-12 02:22:10: python.d DEBUG: cpufreq sleeping for 0.369395017624 secs to reach frequency of 1.0 secs, now: 1484180530.63  next: 1484180531.0  penalty: 0
BEGIN cpu.cpufreq 0
SET cpu2 = 900000
SET cpu3 = 900000
SET cpu0 = 900000
SET cpu1 = 900000
END 

BEGIN netdata.plugin_pythond_cpufreq 0
SET run_time = 1
END

```

So, yes they work...

**Comment by tycho** [comment]
Neat. Too bad they don't provide idle state data.

**Comment by ktsaou** [comment]
ok. Thanks for your help!

**Pull request merged**
