### PR TITLE
fail2ban_plugin: jail auto detection improvements

### PR DESCRIPTION
**Pull request by l2isbad**
@ktsaou this is not ready yet

Jail auto detection order now the same as in `man jail.conf`

- jail.conf
- jail.d/*.conf (in alphabetical order)
- jail.local
- jail.d/*.local (in alphabetical order)

@pschiffe

Can you test it before merging?

### CODE REVIEW

**Comment by ktsaou** [comment]
ok, let me know when it is ready for merge.

**Comment by l2isbad** [comment]
@ktsaou 
ready

**Comment by ktsaou** [comment]
merged!

**Comment by pschiffe** [comment]
Detection seems to be correct now:
```
# fail2ban-client status
Status
|- Number of jail:	3
`- Jail list:	ssh-iptables, vesta-iptables, vsftpd-iptables
```
```
2017-03-28 15:44:25: python.d INFO: fail2ban Jails: ['vesta-iptables', 'ssh-iptables', 'vsftpd-iptables']
```

**Pull request merged**
