### PR TITLE
Make LogService support file path with pattern match

### PR DESCRIPTION
**Pull request by Wing924**
#2282

### CODE REVIEW

**Comment by l2isbad** [comment]
```python
    def _glob_path(self):
	if not self._real_log_path or not isfile(self._real_log_path):
            extract_paths = glob(self.log_path)
            self._real_log_path = extract_paths[0] if extract_paths else None
        return self._real_log_path
```

```bash
[~/logs]ls -l
total 0
-rw-r--r-- 1 lgz lgz 0 Jun  5 16:23 access_log.20170605
-rw-r--r-- 1 lgz lgz 0 Jun  5 16:23 access_log.20170606
-rw-r--r-- 1 lgz lgz 0 Jun  5 16:23 access_log.20170607  # <- most recent
```

```python
In [1]: from glob import glob

In [2]: extract_paths = glob('access_*')

In [3]: real_log_path = extract_paths[0] if extract_paths else Non

In [4]: real_log_path
Out[4]: 'access_log.20170605'
```

**Comment by Wing924** [comment]
@l2isbad I fixed the problem, please check it again.
CI test seems failed due to some unknown problem.

**Comment by l2isbad** [comment]
> I fixed the problem, please check it again

still not. And i really don't think we need to run ```isfile``` on every iteration. Let me think a bit.

**Comment by l2isbad** [comment]
Hey @Wing924 
That is what i think:

we have to re find log file only if:
1. current log file is not updated for N seconds
2. current log file is missing (rotated)

[LogService update](https://github.com/l2isbad/netdata/commit/fb11e88d5487d9c0b6de8a303917397cf46b426d)
[web_log update](https://github.com/l2isbad/netdata/commit/81199cfb4a24de547bbad3f1a863c14a1fcfc322)

What do you think?

**Comment by Wing924** [comment]
@l2isbad Thank you for your quickly response. I agree with you and your codes seem to be OK.

**Comment by ktsaou** [comment]
Another similar uses:

I have a few web servers that contain files like this: `SITE-access.log` where `SITE` is the name of virtual hosts. It would be nice if we could spawn jobs with all of them, without configuring each and every file.

**Comment by l2isbad** [comment]
Well, not sure it's similar 😄 i suggest to open a separate issue @ktsaou

**Comment by ktsaou** [comment]
> Well, not sure it's similar  i suggest to open a separate issue @ktsaou

ok, sorry...

**Comment by Wing924** [comment]
@l2isbad Could you send your pull request or should I change my PR based on your codes?

**Comment by l2isbad** [comment]
@Wing924 

> Could you send your pull request 

will do shortly

**Comment by Wing924** [comment]
Close it because #2288 solved this problem.

**Pull request closed without merging**
