### PR TITLE
postgres.chart.py Add python2.6 support + Fix sql query

### PR DESCRIPTION
**Pull request by moumoul**

### CODE REVIEW

**Comment by ktsaou** [comment]
@facetoe could you please review this?

**Comment by ktsaou** [comment]
I forgot: @moumoul thanks!

**Comment by facetoe** [comment]
Looks good. We're not using the replication SQL currently but the fix works great all the same. I'd say it's good to merge @ktsaou.

**Comment by ktsaou** [comment]
thanks!

**Pull request merged**
