### PR TITLE
charts toolbox can be sped up using SHIFT, ALT, CONTROL keys #246

### PR DESCRIPTION
**Pull request by ktsaou**
The toolbox button can be sped up using the following keys:

1. SHIFT x 2
2. ALT x 5
3. CONTROL x 10

Also, the help popover delays are now configurable.

### CODE REVIEW

**Comment by Ubiquitous** [comment]
One thing to note, on OS X the ```Control``` button might not work, since it normally open the browsers context menu - I believe it's basically the equivalent to right clicking in Windows.

**Comment by ktsaou** [comment]
> One thing to note, in OS X the Control button might not work, since it normally open the browsers context menu - I believe it's basically the equivalent to right clicking in Windows.

Ok. do you want me to remap the speeds? I can put CONTROL to x2, SHIFT to x5 and ALT to x10.

**Comment by Ubiquitous** [comment]
> I can put CONTROL to x2, SHIFT to x5 and ALT to x10.

That would be perfect! Thank you.

**Comment by ktsaou** [comment]
is it ok?
shall I merge it?

**Comment by Ubiquitous** [comment]
The only issue I've found is that if you hold down SHIFT or ALT and click ```+``` sometimes you'll encounter these warnings/errors:

```
system.load (dygraph aaa88f3c-981b-50c5-e5aa-da2dc0345fef): updateChartPanOrZoom(1460834920000, 1460834621000): flipped parameters, rejecting it.
```
This only seems to happen on the zoom in and could probably be solved simply by making before = after.

**Comment by ktsaou** [comment]
ok, that was a debugging message. I fixed it. I also fixed all typos I could find.
If it is not that much of a problem of you, I would appreciate a re-test before merging it.

**Comment by Ubiquitous** [comment]
I just tested it and I'm not seeing any errors, although I have one question about the behavior. When I use ```ALT``` and click ```-``` all the way it looks perfectly normal like this:

zoomout

Then if I click ```+``` just once using ```ALT``` the graph becomes this:

zoomin

Is that normal?

**Comment by ktsaou** [comment]
The second chart should be zoomed exactly at the center of first, using the max zoom available. This is what we have told it to do (0.1 * 10 = 1, so it takes the entire view and zooms it in completely).

It is not that useful, I agree.

Probably we have to give new meanings to keys:

button|description|no key|control|shift|alt
:------:|:-----------:|:------:|:-------:|:---:|:---:
<<, >>|move left or right by...|25% of the view|50% of the view|75% of the view|100% of the view
+|zoom in to...|80% of the view|60% of the view|40% of the view|20% of the view
-|zoom out to...|125% of the view|150% of the view|175% of the view|200% of the view

?

**Comment by Ubiquitous** [comment]
That makes sense, I figured it was doing something along those lines. If possible it would be nice to have it zoom in with the same behavior as the zoom out, so it would essentially transition back in.

zoom-gif

The zooming out works perfectly though, and I think that's the most important thing regarding the changes we made today. For zooming in it's almost easier just to use the mouse with SHIFT and select the area you want to zoom in on.

**Comment by ktsaou** [comment]
ok. I think I fixed it.
Now zoom in/out complement one another (almost - there is small difference due to the alignment done by the server, to points aggregation).

**Comment by ktsaou** [comment]
And by the way, my little table above, showed accidentally the right values for this :)

**Comment by ktsaou** [comment]
I merge it.
If there is something more, let me know.

**Comment by Ubiquitous** [comment]
Yes indeed, that works much better — great job! :+1:

**Pull request merged**
