### PR TITLE
pagerduty.com notifications

### PR DESCRIPTION
**Pull request by jimcooley**
This PR adds pagerduty.com notifications to alarm-notify.sh.

This requires the pagerduty agent to be installed.
https://www.pagerduty.com/docs/guides/agent-install-guide/

health_alarm_notify.conf configs:
```
SEND_PD="YES"
DEFAULT_RECIPIENT_PD="<service key for your pagerduty service>"
```

### CODE REVIEW

**Comment by ktsaou** [comment]
nice!

1. You pass-through the `roles` variable to pagerduty. This means you will not be able to map roles to users in netdata. You will have to do it in pagerduty (if it supports it - I don't know). For all other notification methods (except `kafka`), netdata allows mapping different roles to different users.

2. netdata supports multiple roles per alarm. You will receive in pagerduty a space separated list of them. Do you want it like that?

3. netdata supports the `silent` role, to prevent sending a notification for them. You will receive these notifications in pagerduty.

4. please add pagerduty to the [wiki page](https://github.com/firehol/netdata/wiki/health-monitoring) (some description for configuring the notifications and a screenshot), to have this merged.

Thanks!

**Comment by jimcooley** [comment]
@ktsaou Thanks for the review!
I think that https://github.com/firehol/netdata/pull/1373/commits/fcf9823df565109c0ec010f8963c0053e4c7b579 addresses 1 and 3.  Thanks for cluing me into that excellent functionality.  I already have a use for the `silent` or `disabled` role. :wink:

For 2, the space separated list of roles is fine.  I just pass them as extra information to the pagerduty.com notification, but don't really do anything with them.

I'll add documentation on this pagerduty integration to the wiki very soon.

**Comment by jimcooley** [comment]
Image for wiki (it's weird that I can't just add them directly to the wiki editing page):

pagerduty_netdata

**Comment by jimcooley** [comment]
@ktsaou - I've added the PagerDuty notifications section to the wiki:
https://github.com/firehol/netdata/wiki/health-monitoring#pagerduty-notifications

Let me know if you'd like to see any other changes before merging this.

Thanks!

**Comment by ktsaou** [comment]
excellent job!
Thank you!

**Comment by shellshock1953** [comment]
@jimcooley Does netdata supports "[Events API v2](https://v2.developer.pagerduty.com/docs/events-api-v2)"

**Comment by jimcooley** [comment]
Hi @shellshock1953,

netdata does not support Events API v2 as it currently stands.

This pagerduty integration relies on the [PagerDuty Agent](https://www.pagerduty.com/docs/guides/agent-install-guide/) to be installed, and uses that agent for all communication with PagerDuty.  The PagerDuty Agent uses the Events API v1 according to the documentation on the [agent-install-guide](https://www.pagerduty.com/docs/guides/agent-install-guide/) page.

**Pull request merged**
