### PR TITLE
Bundle urllib3

### PR DESCRIPTION
**Pull request by l2isbad**
- [x] bundle urllib3
- [x] update UrlService to use urllib3
- [x] update elasticsearch plugin
- [x] update rabbitmq plugin
- [x] bugfix: proxy auth
- [x] bugfix: `web_log` should stop to collect unique ips when all_time is set to false
- [x] bugfix: `haproxy`  and `redis` via socket: "a bytes-like object is required, not 'str'"

fixes https://github.com/firehol/netdata/issues/2446
fixes https://github.com/firehol/netdata/issues/2490
fixes https://github.com/firehol/netdata/issues/2475

### CODE REVIEW

**Comment by ktsaou** [comment]
Wow!

Please also add the urllib3 dir to excluded paths for codeclimate: https://github.com/firehol/netdata/blob/9825914b2276022eb32582f54a3e356021e1e19a/.codeclimate.yml#L54-L70

I am not sure how this is done for codacy...

**Comment by l2isbad** [comment]
> I am not sure how this is done for codacy...

https://support.codacy.com/hc/en-us/articles/115002130625-Codacy-Configuration-File

**Comment by l2isbad** [comment]
@ktsaou i am not familiar with this stuff

should i add `codacy.yml ` as a PR to merge it before this PR?

**Comment by ktsaou** [comment]
> should i add .codacy.yml as a PR to merge it before this PR?

Please do. I'll just set the various settings later...

**Comment by l2isbad** [comment]
Not sure how `codacy exclude_paths` thing works @ktsaou 
official answer

> Hey, to reanalyse your project you just need to enter the latest commit and click to reanalyse

same true for the PR's

But it doesn't works for me. (analyzing never stops after pushing the `analyze` button) 😢 

Maybe paths should be like `path/**`. Don't see much explanations [here](https://support.codacy.com/hc/en-us/articles/115002130625-Codacy-Configuration-File)

**Comment by ktsaou** [comment]
hm... it says it cannot find a configuration file

screenshot from 2017-07-23 01-59-17


but there is a page to exclude files manually

screenshot from 2017-07-23 02-03-38

**Comment by l2isbad** [comment]
> page to exclude files manually

i don't see such options from my account

Back to PR. i did different tests on debian8/9 python2/3 and all works fine.

**Comment by ktsaou** [comment]
> i did different tests on debian8/9 python2/3 and all works fine.

nice! Have you verified that keep-alive is working now?
I understand we should check more distros. I can give you access to build.my-netdata.io that I have almost every distro installed as a container. Would that be helpful?

Actually we could enhance that server to have rabbitmq, elasticsearch, etc available for tests...

**Comment by l2isbad** [comment]
> Have you verified that keep-alive is working now?

yes

All should work since `urllib3` is installed with netdata. I think you can check 1-2 random distros and if it works - it works 😄

**Comment by ktsaou** [comment]
ok, which modules use urllib3, to setup a simple test...

**Comment by l2isbad** [comment]
All derived from UrlService (`apache, elasticsearch, haproxy, ipfs, nginx, phpfm, rabbitmq, retroshare, tomcat`)

**Comment by ktsaou** [comment]
I confirmed it works on ubuntu 16.10 (nginx) and gentoo (apache - tested both python2 and python3).
It seems good.

Merge?

**Comment by l2isbad** [comment]
yes

**Comment by ktsaou** [comment]
merged!
Thank you! You rock!

**Pull request merged**
