### PR TITLE
Multi host support

### PR DESCRIPTION
**Pull request by ktsaou**
## the problem

There is a need to monitor hosts that their IP is unknown or ephemeral. Such cases are used for auto-scaling VMs at cloud providers (i.e. VMs are spawn on demand to join a load balancer).

Currently, this is one of the most difficult cases for netdata, mainly because netdata design relies on direct access to each node.

Example: #1311 

## possible solutions

I had 2 solutions in mind:

1. Add a proxy into netdata. So, the ephemeral nodes would connect to a central netdata via a socket, and the central netdata would proxy all requests to them.

2. Add the ability to have a central netdata host that gets in realtime the database (and manages the alarms) of multiple other nodes.

I chose 2. *I like this solution because it might also allow us to have netdata into containers, for collecting data from external plugins (i.e. applications running in the containers) and pushing them to the netdata running at the host.*

This design streams all data in real-time from the ephemeral hosts, to a central netdata. The ephemeral hosts do not maintain a database, do not process alarms and do not listen for incoming request. They just collect data and stream them to the central netdata.

At the central netdata nothing fancy happens. It does accept requests for `http://netdata.ip:19999/`, but also `http://netdata.ip:19999/host/X/` to respond using the database and alarms of host `X`.

---

This PR allows netdata to stream metrics, in real-time, in full-detail, to another netdata.

The following configurations are supported:

## netdata without a database or web API (headless collector)
Local netdata (`slave`), **without any database or alarms**, collects metrics and sends them to another netdata (`master`).

The user can take the full functionality of the `slave` netdata at http://master.ip:19999/host/slave.hostname/. Alarms for the `slave` are served by the `master`.

In this mode the `slave` is just a plain data collector. It runs with... **5MB** of RAM (yes, you read correct), spawns all external plugins, but streams all data to the `master`.

The same `master` can collect data for any number of `slaves`.

Status: **implemented and tested**

---

## database replication
Local netdata (`slave`), **with a local database (and alarms)**, collects metrics and sends them to another netdata (`master`).

The user can take the full function **at both** http://slave.ip:19999/ and http://master.ip:19999/host/slave.hostname/.

The `slave` and the `master` may have different data retention policies for the same metrics.

Alarms for the `slave` are triggered by **both** the `slave` and `master` (and actually each can have different alarms configuration or have alarms disabled).

Status: **implemented and tested**

---

## netdata proxies
Local netdata (`slave`), with or without a database, collects metrics and sends them to another netdata (`proxy`), which may or may not maintain a database, which forwards them to another netdata (`master`).

Alarms for the slave are triggered by any of the involved hosts that maintains a database.

Any number of daisy chaining netdata servers are supported, each with or without a database and with or without alarms for the `slave` metrics.

Status: **implemented and tested**

---

## mix and match with backends

All nodes that maintain a database can also send their data to a backend database. This allows quite complex setups. Example:

1. netdata `A`, `B` do not maintain a database and stream metrics to netdata `C`(live streaming functionality, i.e. this PR)
2. netdata `C` maintains a database for `A`, `B`, `C` and archives all metrics to `graphite` with 10 second detail (backends functionality)
3. netdata `C` also streams data for `A`, `B`, `C` to netdata `D`, which also collects data from `E`, `F` and `G` from another DMZ (live streaming functionality, i.e. this PR)
4. netdata `D` is just a proxy, without a database, that streams all data to a remote site at netdata `H`
5. netdata `H` maintains a database for `A`, `B`, `C`, `D`, `E`, `F`, `G`, `H` and sends all data to `opentsdb` with 5 seconds detail (backends functionality)
6. alarms are triggered by `H` for all hosts
7. users can use all the netdata that maintain a database to view metrics (i.e. at `H` all hosts can be viewed).

---

## netdata.conf configuration

This PR re-arranges `[global]` configuration a bit, moving all API/Web related configs to section `[web]` (existing configurations should work too - the options are migrated at runtime to their proper location).

So, these are options that affect the operation of netdata in this area:

```
[global]
    memory mode = none | ram | save | map
```

`[global].memory mode = none` disables the database at this host. This also disables health monitoring (there cannot be health monitoring without a database).

```
[web]
    mode = none | single-threaded | multi-threaded
```

`[web].mode = none` disables the API (netdata will not listen to any ports). This also disables the registry (there cannot be a registry without an API).

```
[backend]
    enabled = yes | no
    type = graphite | opentsdb
    destination = IP:PORT ...
    update every = 10
```

`[backend]` configures data archiving to a backend (it archives all databases maintained on this host).

---

## streaming configuration

A new file is introduced: `/etc/netdata/stream.conf`. This file holds streaming configuration for both the sending and the receiving netdata.

API keys are used to authorize the communication of a pair of sending-receiving netdata. Once the communication is authorized, the sending netdata can push metrics for any number of hosts.

You can generate an API key with the command `uuidgen`. API keys are just random GUIDs. You can use the same API key on all your netdata, or use a different API key for any pair of sending-receiving netdata.

### options for the sending node

This is the section for the sending netdata. One the receiving node, `[stream].enabled` can be `no`. If it is `yes`, the receiving node will also stream the metrics to another node (i.e. it will be a `proxy`).

```
[stream]
    enabled = yes | no
    destination = IP:PORT ...
    api key = XXXXXXXXXXX
```

So,

target | memory<br/>mode | web<br/>mode | stream<br/>enabled | backend | alarms | dashboard
-------|:-----------:|:---:|:------:|:-------:|:---------:|:----:
headless collector|`none`|`none`|`yes`|not possible|not possible|no
headless proxy|`none`|not `none`|`yes`|not possible|not possible|no
proxy with db|not `none`|not `none`|`yes`|possible|possible|yes
central netdata|not `none`|not `none`|`no`|possible|possible|yes

### options for the receiving node

That file looks like this:

```
[API_KEY]
    enabled = yes
    default history = 3600
    default memory mode = save
    health enabled by default = auto
```

You can add many such sections, one for each API key. The above are used as default values for all hosts pushed with this API key.

You can also add sections like this:

```
[MACHINE_GUID]
    enabled = yes
    history = 3600
    memory mode = save
    health enabled = yes
```

The above is the receiver configuration of a single host, at the receiver end. `MACHINE_GUID` is the unique id the netdata generating the metrics (i.e. the netdata that originally collects them `/var/lib/netdata/registry/netdata.unique.id`). So, metrics for netdata `A` that pass through any number of other netdata, will have the same `MACHINE_GUID`.

## tracing

When a `slave` is trying to push metrics to a `master` or `proxy`, it logs entries like these:

```
2017-02-25 01:57:44: netdata: ERROR: Failed to connect to '10.11.12.1', port '19999' (errno 111, Connection refused)
2017-02-25 01:57:44: netdata: ERROR: STREAM costa-pc [send to 10.11.12.1:19999]: failed to connect
2017-02-25 01:58:04: netdata: INFO : STREAM costa-pc [send to 10.11.12.1:19999]: initializing communication...
2017-02-25 01:58:04: netdata: INFO : STREAM costa-pc [send to 10.11.12.1:19999]: waiting response from remote netdata...
2017-02-25 01:58:14: netdata: INFO : STREAM costa-pc [send to 10.11.12.1:19999]: established communication - sending metrics...
2017-02-25 01:58:14: netdata: ERROR: STREAM costa-pc [send]: discarding 1900 bytes of metrics already in the buffer.
2017-02-25 01:58:14: netdata: INFO : STREAM costa-pc [send]: ready - sending metrics...
```

The receiving end (`proxy` or `master`) logs entries like these:

```
2017-02-25 01:58:04: netdata: INFO : STREAM [receive from [10.11.12.11]:33554]: new client connection.
2017-02-25 01:58:04: netdata: INFO : STREAM costa-pc [10.11.12.11]:33554: receive thread created (task id 7698)
2017-02-25 01:58:14: netdata: INFO : Host 'costa-pc' with guid '12345678-b5a6-11e6-8a50-00508db7e9c9' initialized, os: linux, update every: 1, memory mode: ram, history entries: 3600, streaming: disabled, health: enabled, cache_dir: '/var/cache/netdata/12345678-b5a6-11e6-8a50-00508db7e9c9', varlib_dir: '/var/lib/netdata/12345678-b5a6-11e6-8a50-00508db7e9c9', health_log: '/var/lib/netdata/12345678-b5a6-11e6-8a50-00508db7e9c9/health/health-log.db', alarms default handler: '/usr/libexec/netdata/plugins.d/alarm-notify.sh', alarms default recipient: 'root'
2017-02-25 01:58:14: netdata: INFO : STREAM costa-pc [receive from [10.11.12.11]:33554]: initializing communication...
2017-02-25 01:58:14: netdata: INFO : STREAM costa-pc [receive from [10.11.12.11]:33554]: receiving metrics...
```

---

## tasks

- [x] moves all global variables under RRDHOST.
- [x] re-arranges a lot of code and variables to allow RRDHOST have per-host settings.
- [x] adds the command `HOST hostname unique.guid` to the external plugins API
- [x] incoming sockets are routed to the external plugins mechanism (so the remote netdata will be sending the same format of data external plugins are sending - but at the beginning it will issue a `HOST` command to switch host).
- [x] the web API allows the prefix `/host/hostname/` or `/host/unique.guid/` to switch hosts (so the whole dashboard and every API call will work without modification)
- [x] allow netdata to start in push mode (i.e. send all metrics to another netdata host, without any database or alarms locally)
- [x] health alarms are attached to each host individually
- [x] health databases and event logs support multiple hosts
- [x] backends send all the metrics from all hosts
- [x] during refactoring all the above, 1.5KB per dimension is saved from RAM (unfortunately old databases will be discarded).

cc: @l2isbad @simonnagl @vlvkobal have a look. Comments?

---

- [x] validation / configuration of streaming API keys
- [x] chart configuration options used `type.id`. They now use `host/type.id`.
- [x] chart cache files should be `/var/cache/netdata/host/chart_id`.
- [x] health database files should be saved at `/var/lib/netdata/host/health/`
- [x] the registry does not need anything - it is global, independent of the hosts
- [ ] health configuration should allow another entry `hosts: *`, to limit certain alarms to specific hosts. It is relatively easy to add to the code the ability to have a different health configuration directory per host, but this will be confusing...
- [x] propagate host os type from the slave netdata to the master.
- [x] delay alarms checks when client reconnects to stream metrics.
- [x] implement an internal garbage collector that will free charts, only a certain amount of time has passed since the last disconnect from the netdata sending the metrics - this will also allow ephemeral nodes.
- [x] proxy nodes should disconnect from the receiving part when the sending netdata has been disconnected, to allow the receiving part handle alarms properly.

Then we come to the question: **what is `host` on the above**?

I used as host the netdata unique id: a GUID, except when the host is the localhost, in which case `host` will be empty (this will provide compatibility with the existing functionality).

### CODE REVIEW

**Comment by ktsaou** [comment]
So, all the changes made so far, are just code cleanup and re-arrangement. No visible change for the users.

Now it is time, to develop the 2 features (unticked above).

**Comment by ktsaou** [comment]
I made a few edits above.

**Comment by ktsaou** [comment]
It seems more complicated than I initially thought. I added a few more items.

**Comment by ktsaou** [comment]
The current status of the PR seems stable on linux and freebsd. I can't test on macos.

**Comment by ktsaou** [comment]
btw, the code now is a lot more cleaner and well organized...

**Comment by ktsaou** [comment]
guess what... **it works** !

**Comment by ktsaou** [comment]
haha.... this is very nice. Everything works. All charts, all alarms, even the registry found out it is the same host!

Of course, there are about 300kbps between the servers, constantly...

**Comment by ktsaou** [comment]
For anyone willing to try this out, [check this for info](https://github.com/ktsaou/netdata/blob/5f9addf32418c6b4b2a764f09940ebd5ce9edbde/conf.d/aggregated_hosts.conf).

Once you do what is described there, goto `http://central.netdata.ip:19999/host/REMOTE_HOSTNAME/` and enjoy real-time remote monitoring!

**Comment by ktsaou** [comment]
testers needed - please help me setup a few test cases to have this merged.

**Comment by l2isbad** [comment]
PR is huge and super great 👍 
i tried to create "mix and match with backends" setup (8 netdatawithout backend stuff) and failed.

Screenshot from "database replication" (this node dashboard not master) (same as headless but `exclusive = no`, right?) node after start/restart (randomly appear after several restarts).

screenshot_20170224_130601

And dashboard at master is empty when slave is not headless (database replication)

screenshot_20170224_133314

**Comment by ktsaou** [comment]
Yes, I need to add some more info:

1. `[global].memory mode = none` disables the database (and health monitoring)
2. `[stream].exclusive = yes` sets `[global].memory mode = none` and also disables the web server (so it cannot be a proxy).

From the screenshots I understand that somehow 2 hosts update the same database. Could you please describe how to reproduce it?

**Comment by ktsaou** [comment]
The problem of multiple streams updating the same database is pretty stupid. In my tests, I found that under certain network conditions, a socket at the receiver may have to timeout. The sender however may have found out faster and attempt to reconnect.

So, I chose not to lock the database and allow multiple senders to push metrics to the same database.

Probably this is a bad decision. The database of a slave should be locked while a slave is connected.

**Comment by l2isbad** [comment]
@ktsaou it's very easy to reproduce.
You need to change slave mode from "headless" to "database replication" (`exclusive = no`) and restart netdata service on the slave node. Sometimes you need to restart it several times to see the bug (huge numbers).
Slave dashboard is empty as in my post above.

**Comment by ktsaou** [comment]
fixed it.

I changed the configuration too. Check the first comment for instructions.

**Comment by ktsaou** [comment]
implemented and tested all cases, `slaves`, `proxies`, `masters`.

**Comment by l2isbad** [comment]
@ktsaou 
Works great! But i think a good idea is to have an option to not maintain remote databases for proxies (only local). I mean what if i don't wont to turn proxy node to master? It either headless or master now.

**Comment by ktsaou** [comment]
ok, both are there:

## proxy with its own database but passing through remote databases

1. at the proxy `netdata.conf` set `memory mode` to anything except `none`.
2. at the proxy `aggregated_hosts.conf` set `[API KEY].default memory mode = none` - this will disable the database of remote hosts at the proxy.

You can also do this per host.

## last_collected flood

At the receiving netdata you can set in `aggregate_hosts.conf`: `[API KEY].health enabled by default = auto`. This will stop health monitoring when the sending netdata disconnects and enable when it reconnects.

Any ideas how to make it better?

Possible solutions:

1. Work on alarms to detect alarm floods and do something about them. For example, alarm floods could send 1 aggregated alarm or delay the notifications for some time (in hope the issue will be resolved).

2. Increase the `last_collected` alarms to 1 minute or more. 10 seconds is too short for remote data collection. Any little network issue will create a storm of alarms in large scale.

Any other ideas?

**Comment by ktsaou** [comment]
I have renamed `aggregated_hosts.conf` to `stream.conf` and moved the `[stream]` section from `netdata.conf` to `stream.conf`.

So, all streaming configuration is in `stream.conf` and API keys appear only in that file (`netdata.conf` is a public file, so no private information should be there).

I have also added configuration options to allow routing databases to different masters. Check `stream.conf` for more information.

**Comment by l2isbad** [comment]
Chart from master node. 
screenshot_20170226_001843

Chart from slave node. 
screenshot_20170226_002114


Dimension id was changed

**Comment by ktsaou** [comment]
yes, I know.

I am trying to find a way to implement a garbage collector (there is already a point at the todo list above).

## the problem

netdata tries to work without locks. Internally it uses locks only when it is absolutely necessary (manipulating linked lists, indexes, etc).

Everything works pretty well, at full speed, but deleting data is problematic, since there are no means to know if another thread is accessing these data.

The right solution would be to get a read lock when data for a chart are accessed and a write lock to delete them.

But think of it a bit: netdata will execute constantly several thousand locks/unlocks per second, just because at some point, data may need to be deleted.

Another solution could be the implementation of a garbage collector. What I think is this:

Hosts, charts and dimensions will have a `use counter`. Every time they are accessed or updated, the `use counter` is incremented.

A garbage collector has another counter, the `last use counter`. Every 1 minute it evaluates all hosts, charts and dimensions, by examining if the 2 counters are the same. If they are, the data are marked as `garbage` (not removed).

While, data are marked as `garbage` they are not available for read, but they are available for write (which also removes the `garbage` mark).

Data need to stay marked as `garbage` for some time to be deleted.

Of course, for threads that have long standing pointers to the data, a `NEVER_DELETE` flag will be used. So, only data without any long standing pointers will be evaluated by the garbage collector.

I admit this looks like a hack though... (I totally understand why redis, node.js and so many more applications are single threaded...)

**Comment by ktsaou** [comment]
and yes... web api calls to read data and plugin api calls to update the same data, are executed in parallel, without any lock whatsoever. This is not a problem, because the structure allows it. The readers may miss an update, but they never get half a update.

**Comment by ktsaou** [comment]
ok. I think this is pretty stable. The old functionality is intact and the new is stable enough to be merged.

I have installed this in several machines without any memory leaks or crashes (actually I have fixed a few rare ones). So, it seems pretty safe to merge it.

Once this is merged, I'll try to add some functionality to visualize all the hosted hosts on a netdata, but it is better to do this incrementally instead of holding it back.

In general, the code is now a lot more cleaner and well organized and I have kept a note to rethink the whole locking concept (switch to single threaded or add proper locks everywhere).

So, I plan to merge it...

**Comment by mailinglists35** [comment]
does this work with tv.html so I can create a custom dashboard with specific metrics gatthered across different systems in a single page?

**Comment by l2isbad** [comment]
@mailinglists35 
Yes.
Netdata can maintain not only local but any number of remote hosts databases.
Since all databases are local you can add any metric from them to the custom dashboard.

Don't forget to change `data-host` parameter

example
```php
  <div data-netdata="system.load"
            data-title="load"
            data-chart-library="easypiechart"
            data-dygraph-theme="sparkline"
            data-width="170px"
            data-height="60px"
            data-after="-300"
            data-host="http://127.0.0.1:19999/host/REMOTE-HOSTNAME/"
            data-colors="#885588"
            > </div>
```

**Comment by mailinglists35** [comment]
awesome, thank you! :)

**Comment by samof76** [comment]
It would also be nice to have an API like GET http://master.ip:19999/hosts, you return a JSON of all the hosts that are submitting into the master, and their addressable URLs.

**Comment by ktsaou** [comment]
At `http://master.ip:19999/api/v1/charts` there is a `hosts` array with the information you need. I tried to avoid the extra call, since the dashboard already fetches `charts`.

**Comment by ktsaou** [comment]
netdata-for-ephemeral-nodes

**Comment by samof76** [comment]
Oh cool! I did not know that there was hosts array in that. But I guess still when you have a consolidated or central netdata as identified by the green element in the above diagram, it would be nice to have an API just to get the list of hosts and their addressable proxy URLs, which would really help if I would want build custom dashboards. And just give you an extended perspective, if I am building a custom dashboard I would like to group my nodes bases on the work that they do, say, web servers, redis servers, sidekiq servers etc, this where  tags would be really helpful as requested in the enhancement request #1900.

**Comment by ktsaou** [comment]
ok. I agree it would be helpful to have an API call for this (please open a new issue - I'll forget it). But keep in mind that:

1. netdata servers are not aware of their URLs. So, they cannot give URLs back to you. The url should be composed with `URL_OF_THIS_NETDATA + "/host/" + HOSTNAME_OF_MIRRORED_HOST + "/"`.

   `my-netdata` menu (that shows a list of the mirrored hosts) composes the URLs at the client (where `URL_OF_THIS_NETDATA` is known).

2. I still cannot narrow down to 1 function the "group of nodes". I have understood you need to tag/group them somehow, but I still cannot figure out how you expect to use this information. I mean, you have a UI in mind that does something with them. Could you please describe it at #1900 ?

**Comment by samof76** [comment]
> netdata servers are not aware of their URLs. So, they cannot give URLs back to you. The url should be composed with URL_OF_THIS_NETDATA + "/host/" + HOSTNAME_OF_MIRRORED_HOST + "/".
> my-netdata menu (that shows a list of the mirrored hosts) composes the URLs at the client (where URL_OF_THIS_NETDATA is known).

Sounds reasonable, since I have noticed that you serve the dashboards from the central server, but in my [blog](http://megam.me/post/157995246734/metrichill-centralizing-netdata) the gorouter proxies to the individual node's netdata. So in my case, if you ask for gorouter for the list of nodes that it routes to you would get something like this...

    {"w1.netdata.monitor.zapped.pigs":[{"address":"127.0.0.1:19999","ttl":0,"tags":{"name":"w1","type":"web"}}]}

**Comment by trieutulong89** [comment]
For example, I have 01 host for central server and 03 hosts slave. How can I show metrics of all hosts slave on one dashboard without use tv.html when I type http://host1:19999? 
Thanks for your support.

**Comment by cakrit** [comment]
@trieutulong89 could you please create an issue with your question? This PR was merged a while ago, an issue will help us better handle the request.

**Pull request merged**
