### PR TITLE
Remove some /proc remains from FreeBSD plugin

### PR DESCRIPTION
**Pull request by vlvkobal**
It fixes issues 3. and 4. in #1632.
3. @mmokhi I applied your FreeBSD port patches.
4. These were just needless comments.

### CODE REVIEW

**Comment by ktsaou** [comment]
merged! thanks!

**Comment by mmokhi** [comment]
@vlvkobal thanks for merging patches.
So it's no longer need for keeping them on FreeBSD tree, I'll remove them if you confirm :slightly_smiling_face: 
Just another check, Not all patches merged, yeah? (like configure.ac, ...), Though it's understandable cause they're too much FreeBSDish :wink: :smile:

**Comment by vlvkobal** [comment]
@mmokhi You are right. I didn't merge `configure.ac` patch. I'd like to make `netdata-install.sh` to work properly on FreeBSD so it requires slightly more work than just merging the patch. I'll do it later.

You can remove patches for future `netdata` releases, but not for `1.5.0`.

One more question. What do you think is better to use: 'hw.ncpu' or 'kern.smp.cpus'? Do we have any difference between them? They seem to be equal. I'm too lasy to trace their calculations in kernel 😄.

**Comment by mmokhi** [comment]
> @mmokhi You are right. I didn't merge configure.ac patch. I'd like to make netdata-install.sh to work properly on FreeBSD so it requires slightly more work than just merging the patch. I'll do it later.

Hmm :thinking: , Okay, But AFAIK The preferred way for the port system is working with Makefile/configure.ac instead of do-them-all installer.
BTW, until the `configure.ac` works (even with local patches on the port-tree) I see no problem on keeping the patches :smile:


> You can remove patches for future netdata releases, but not for 1.5.0.

Good point :+1: Thanks for it.
So, I'll keep them till the next release. :smile: 


> One more question. What do you think is better to use: 'hw.ncpu' or 'kern.smp.cpus'? Do we have any difference between them?

The number of `hw.ncpu` is what was detected from the hardware while `kern.smp.cpus` is what the kernel actually uses (assume it a kernel configuration switch :wink:)
I'd suggest using the first (That's why I used it in the patch :slightly_smiling_face:)


> I'm too lasy to trace their calculations in kernel :smile:.

No problem at all, I'm here to help on these :wink: , ask me and if I know I'll answer, otherwise I'll search and learn :smile:

**Comment by vlvkobal** [comment]
> The preferred way for the port system is working with Makefile/configure.ac

I thought about it. You are right. But applying `configure.ac` patch alone doesn't make `netdata` automatically installable neither with `make` nor with `netdata-install.sh` (well, it works, but there are issues with dependencies and paths) if you get it directly from github.

> I'd suggest using the first

I've verified `processor` variable usage. It's used in `apps.plugin` to calculate cpu time percentage for processes' statistics. Is `hw.ncpu` still better for the case? What is more informative for users - stats based on physical cores or configured cores? I think it can be quite confusing when you end up with free processor time available when you reach 100% load for configured cores.

**Comment by mmokhi** [comment]
> I thought about it. You are right. But applying configure.ac patch alone doesn't make netdata automatically installable neither with make nor with netdata-install.sh (well, it works, but there are issues with dependencies and paths) if you get it directly from github.

I see, So IMO the best option for now would be keep `configure.ac` patch locally on FreeBSD ports tree (to let each branch work :smile:)


> I've verified processor variable usage. It's used in apps.plugin to calculate cpu time percentage for processes' statistics. Is hw.ncpu still better for the case? What is more informative for users - stats based on physical cores or configured cores? I think it can be quite confusing when you end up with free processor time available when you reach 100% load for configured cores.

AFAIK, `kern.smp.cpus` is a kernel config thing, that lets people make changes on multiprocessing configs of kernel.
So If someone likes to change that (eg, from 4 to 3) you may have userspace apps (or even don't) running on CPU#4 but `netdata` won't be even aware of existing of CPU#4.

**Comment by vlvkobal** [comment]
OK. Then `hw.ncpu` is in the right place. Thank you :smile: !

**Comment by mmokhi** [comment]
Always, my pleasure to help :wink: :pray:

**Pull request merged**
