### PR TITLE
Patch to add support for messagebird.com SMS service

### PR DESCRIPTION
**Pull request by tech-no-logical**
I've added support for messagebird.com SMS alarms because we already have an account there and it looked easy to implement. I've copied all twilio code and modified the config variables and send_messagebird() code to match their API.

also, my first PR, no idea if I'm doing this right :)

### CODE REVIEW

**Comment by ktsaou** [comment]
seems good!

I would like to ask you the following:

1. at `alarms_notify.conf` try to give a short description of how a key can be obtained (like twilio).

2. add messagebird information and screenshots at the wiki page: https://github.com/firehol/netdata/wiki/health-monitoring (search for twilio and you will find out what to do).

Once these are done, I'll merge it.
Nice job!

**Comment by ktsaou** [comment]
perfect!
Shall I merge it now or is the pending?
(I assume you have tested it)

**Comment by tech-no-logical** [comment]
I have tested it, but for completeness sake I'll run a final test tomorrow with a fresh checkout and install. I'll report back after.

**Comment by ktsaou** [comment]
perfect! please also make sure that you receive an email (just to make sure it didn't break anything else).

**Comment by ktsaou** [comment]
You can test it with:

```sh
/usr/libexec/netdata/plugins.d/alarms-notify.sh test
```

**Comment by tech-no-logical** [comment]
``` 
root@muttley:/etc/netdata# /usr/libexec/netdata/plugins.d/alarm-notify.sh test

# SENDING TEST CRITICAL ALARM TO ROLE: sysadmin
2017-01-12 10:25:05: alarm-notify.sh: INFO: sent Messagebird SMS for: muttley test.chart.test_alarm is CRITICAL to '316XXXXXXX'
2017-01-12 10:25:05: alarm-notify.sh: INFO: sent email notification for: muttley test.chart.test_alarm is CRITICAL to 'root'
# OK

# SENDING TEST WARNING ALARM TO ROLE: sysadmin
2017-01-12 10:25:05: alarm-notify.sh: INFO: sent Messagebird SMS for: muttley test.chart.test_alarm is WARNING to '316XXXXXXX'
2017-01-12 10:25:05: alarm-notify.sh: INFO: sent email notification for: muttley test.chart.test_alarm is WARNING to 'root'
# OK

# SENDING TEST CLEAR ALARM TO ROLE: sysadmin
2017-01-12 10:25:06: alarm-notify.sh: INFO: sent Messagebird SMS for: muttley test.chart.test_alarm is CLEAR to '316XXXXXXX'
2017-01-12 10:25:06: alarm-notify.sh: INFO: sent email notification for: muttley test.chart.test_alarm is CLEAR to 'root'
# OK
```

test succesful :)

**Comment by ktsaou** [comment]
thanks!

**Pull request merged**
