### PR TITLE
Replaces deprecated pidfile argument with -P

### PR DESCRIPTION
**Pull request by isonet**
As mentioned in #497

### CODE REVIEW

**Comment by SanskritFritz** [comment]
Thanks!
You could fix the typo in the error message too :D

**Comment by isonet** [comment]
No problem!
I did, but I made a separate pull request: #499

**Comment by SanskritFritz** [comment]
Awesome :D

**Comment by ktsaou** [comment]
You are the best!

**Comment by isonet** [comment]
Wow, thank you!

**Pull request merged**
