### PR TITLE
redis: refactor + pika support

### LINKED ISSUE #3783: Enhancement  Redis protocol(Pika) ?
Hi. I want to use netdata monitor Pika(Pika is a nosql compatible with redis, it is developed by Qihoo's DBA and infrastructure team) (Github:https://github.com/Qihoo360/pika) .
 Any suggests will be helpful.Thanks.

---------------------------------------------------------------------
The error log:
`[root@dc-pika64 netdata]# usr/libexec/netdata/plugins.d/python.d.plugin debug redis 1
2018-06-04 14:39:44: python.d INFO: plugin: main: Using python 2
2018-06-04 14:39:44: python.d DEBUG: plugin: main: module load source: 'redis' => [OK]
2018-06-04 14:39:44: python.d DEBUG: plugin: main: module load config: 'redis' => [OK]
2018-06-04 14:39:44: python.d DEBUG: plugin: main: job initialization: 'redis socket1' => ['OK']
2018-06-04 14:39:44: python.d DEBUG: plugin: main: job initialization: 'redis socket2' => ['OK']
2018-06-04 14:39:44: python.d DEBUG: plugin: main: job initialization: 'redis socket3' => ['OK']
2018-06-04 14:39:44: python.d DEBUG: plugin: main: job initialization: 'redis localhostpika' => ['OK']
2018-06-04 14:39:44: python.d DEBUG: plugin: main: job initialization: 'redis localipv6' => ['OK']
2018-06-04 14:39:44: python.d DEBUG: plugin: main: module status: 'redis' => [OK] (jobs: 5)
2018-06-04 14:39:44: python.d DEBUG: redis: socket1: attempting DGRAM unix socket "/tmp/redis.sock"
2018-06-04 14:39:44: python.d DEBUG: redis: socket1: Failed to connect DGRAM unix socket "/tmp/redis.sock": [Errno 2] No such file or directory
2018-06-04 14:39:44: python.d DEBUG: redis: socket1: attempting STREAM unix socket "/tmp/redis.sock"
2018-06-04 14:39:44: python.d DEBUG: redis: socket1: Failed to connect STREAM unix socket "/tmp/redis.sock": [Errno 2] No such file or directory
2018-06-04 14:39:44: python.d INFO: redis: socket1: check() => [FAILED]
2018-06-04 14:39:44: python.d DEBUG: redis: socket2: attempting DGRAM unix socket "/var/run/redis/redis.sock"
2018-06-04 14:39:44: python.d DEBUG: redis: socket2: Failed to connect DGRAM unix socket "/var/run/redis/redis.sock": [Errno 2] No such file or directory
2018-06-04 14:39:44: python.d DEBUG: redis: socket2: attempting STREAM unix socket "/var/run/redis/redis.sock"
2018-06-04 14:39:44: python.d DEBUG: redis: socket2: Failed to connect STREAM unix socket "/var/run/redis/redis.sock": [Errno 2] No such file or directory
2018-06-04 14:39:44: python.d INFO: redis: socket2: check() => [FAILED]
2018-06-04 14:39:44: python.d DEBUG: redis: socket3: attempting DGRAM unix socket "/var/lib/redis/redis.sock"
2018-06-04 14:39:44: python.d DEBUG: redis: socket3: Failed to connect DGRAM unix socket "/var/lib/redis/redis.sock": [Errno 2] No such file or directory
2018-06-04 14:39:44: python.d DEBUG: redis: socket3: attempting STREAM unix socket "/var/lib/redis/redis.sock"
2018-06-04 14:39:44: python.d DEBUG: redis: socket3: Failed to connect STREAM unix socket "/var/lib/redis/redis.sock": [Errno 2] No such file or directory
2018-06-04 14:39:44: python.d INFO: redis: socket3: check() => [FAILED]
2018-06-04 14:39:44: python.d DEBUG: redis: localhostpika: Creating socket to "172.31.10.63", port 9221
2018-06-04 14:39:44: python.d DEBUG: redis: localhostpika: connecting socket to "172.31.10.63", port 9221
2018-06-04 14:39:44: python.d DEBUG: redis: localhostpika: connected to "172.31.10.63", port 9221
2018-06-04 14:39:44: python.d DEBUG: redis: localhostpika: set socket timeout to: 5.0
2018-06-04 14:39:44: python.d DEBUG: redis: localhostpika: sending request: INFO

2018-06-04 14:39:44: python.d DEBUG: redis: localhostpika: receiving response
2018-06-04 14:39:44: python.d DEBUG: redis: localhostpika: received data
2018-06-04 14:39:44: python.d DEBUG: redis: localhostpika: received full response from redis
2018-06-04 14:39:44: python.d DEBUG: redis: localhostpika: final response: $1321
# Server
pika_version:2.3.4
pika_git_sha:3b86e4a1c76313dd1f448a9317a4f5551e235b35
pika_build_compile_date: May 17 2018
os:Linux 2.6.32-696.el6.x86_64 x86_64
arch_bits:64
process_id:10159
tcp_port:9221
thread_num:20
sync_thread_num:6
uptime_in_seconds:874230
uptime_in_days:11
config_file:conf/pika.conf
server_id:1

# Data
db_size:57252174373
db_size_human:54599M
compression:snappy
used_memory:1676574536
used_memory_human:1598M
db_memtable_usage:133194920
db_tablereader_usage:1543379616

# Log
log_size:19183503438
log_size_human:18294M
safety_purge:write2file1871
expire_logs_days:7
expire_logs_nums:10
binlog_offset:1881 74942108

# Clients
connected_clients:3

# Stats
total_connections_received:2226
instantaneous_ops_per_sec:0
total_commands_processed:516545968
is_bgsaving:No, 20180528150116, 0
is_slots_reloading:No, , 0
is_slots_cleanuping:No, , 0
is_scaning_keyspace:No
is_compact:No
compact_cron:
compact_interval:

# CPU
used_cpu_sys:202135.27
used_cpu_user:995980.38
used_cpu_sys_children:87.66
used_cpu_user_children:177.82

# Replication(MASTER)
role:master
connected_slaves:1
slave0:ip=172.31.10.64,port=9221,state=online,sid=2,lag=0

# Keyspace
# Time:2018-06-04 11:45:46
kv keys:0
hash keys:174999283
list keys:0
zset keys:0
set keys:0

2018-06-04 14:39:44: python.d ERROR: redis: localhostpika: check() unhandled exception: 'rdb_bgsave_in_progress'
2018-06-04 14:39:44: python.d INFO: redis: localhostpika: check() => [FAILED]
2018-06-04 14:39:44: python.d DEBUG: redis: localipv6: Creating socket to "::1", port 6379
2018-06-04 14:39:44: python.d DEBUG: redis: localipv6: connecting socket to "::1", port 6379
2018-06-04 14:39:44: python.d ERROR: redis: localipv6: Failed to connect to "::1", port 6379, error: [Errno 111] Connection refused
2018-06-04 14:39:44: python.d DEBUG: redis: localipv6: closing socket
2018-06-04 14:39:44: python.d INFO: redis: localipv6: check() => [FAILED]
2018-06-04 14:39:44: python.d INFO: plugin: main: FINISHED
`

### PR DESCRIPTION
**Pull request by l2isbad**
Fixes #3783
Fixes #3140 

@zhangxin0112

please test it

any suggestions are welcome (not a `redis`/`pika` user)

### CODE REVIEW

**Comment by l2isbad** [comment]
Actually we can rename module to `pika` in `check` (like [apache->lighttpd](https://github.com/firehol/netdata/blob/master/python.d/apache.chart.py#L101-L102)). Personally I think that it is not necessary, but maybe i am wrong.

**Comment by zhangxin0112** [comment]
Sorry to disturb u . I could not find the modified source code(l2isbad:redis_pika).Could u give me a link?

**Comment by l2isbad** [comment]
@zhangxin0112 if you don't have any suggestions (monitor something `pika` specific?) i am done here.

**Comment by zhangxin0112** [comment]
Ye. Another question.  Pika monitor will be added to the netdata master ?

**Comment by ktsaou** [comment]
@l2isbad you rock!

**Pull request merged**
