### PR TITLE
Python Threading

### LINKED ISSUE #604: python plugins: threads
Today, python modules are executed one after another. This has the problem that delays in data collection of one module increase the latency of another. If for example we have to collect data from 30 servers, per second, and each server responds in 50ms, we will not be able to collect all data within 1 second.

To solve this in `node.d.plugin` I have done the following:

1. I utilized javascript async features to collect data concurrently. So all the tasks to collect data are executed in parallel (node.js is single threaded, but has async I/O allowing to behave like there are threads in place).

  So, the main loop keeps track of which jobs has started and which have finished, to avoid collecting data for the same job more than once concurrently.

2. To avoid multiplexing the output sent to netdata from multiple data collections, all modules generate data for netdata in a buffer and only when they finish one iteration, the whole data stream is send to netdata in a single print operation.

@paulfantom any ideas?

### PR DESCRIPTION
**Pull request by paulfantom**
Fixes #604

Implemented, tested, works. 
Also moved logging functions to new file so they can be used in other places.

### CODE REVIEW

**Comment by ktsaou** [comment]
Nice! Yes it works.

I think it would be better to have methods in the job object for `chart()`, `dimension()`, `begin()`, `set()`, `end()`. This way we could change the way they are collected and send to netdata without touching the  modules.

We could follow the same principle for `info()`, `error()`, `fatal()`, `debug()`. If they are part of the job object, we could change them according to the development of the plugin, without worrying about the modules.

Your call...

**Comment by paulfantom** [comment]
I have added also simple fix to resolve auto-detection. Currently it search for keyword 'override_name' but it can be easily changed in `base.py` on line 56 ( `self.override_name = config.pop('override_name')` )

So you want to add a couple of methods to `BaseService` class which would basically be wrappers of the `print` function? Sounds ok.

**Comment by ktsaou** [comment]
> So you want to add a couple of methods to BaseService class which would basically be wrappers of the print function?

Yes. This would allow us to adapt without touching the modules.

**Comment by paulfantom** [comment]
Wrappers on `print()` won't work since we are now multithreading. However `chart()`, `dimension()`, `begin()`, `set()`, `end()` could append to some data_stream variable, and something like `send()` could print it.
How about this approach?

**Comment by ktsaou** [comment]
What I have done in node.d.plugin is exactly that. Each module calls `self.begin()`, `self.set()`, etc with structured parameters (i.e. they are not called with just a string, but each parameter is passed to the method natively). All caching is done within these functions. The module knows nothing.

I have done the same for `error()`, `info()`, etc, so that logs are uniform across all modules.

**Comment by paulfantom** [comment]
Check my last commit. Is this what you had in mind?

**Comment by ktsaou** [comment]
something like that. I think what you have done can be used as a basis.

What I would change is to specify the parameters of each call explicitly. For example, the `begin()` call could check if `dt` is given or not and adapt to that. Similarly the `set()` call could check if the value is integer and log errors if it is not, the `chart()` call could also make several checks. I don't if what you have done is already like that.

I am reviewing the node.d.plugin to see how I implemented it there. node.d.plugin is a lot more structured and strict. Each job maintains a list a charts (so there is also a chart object) and tries to figure out if it needs to re-send the chart definition to netdata (probably due to a new dimension being added). It also makes a lot of checks on each parameter given to all the calls. Even `dt`, `next_t` and `last_t` is calculated in `begin()` and `end()`.

But anyway, I think we are on the right track. The whole idea is to abstract all this logic from the modules and handle it centrally. So, what you have done seems good so far.

**Comment by paulfantom** [comment]
@ktsaou Can you verify if something like this will be valid:
```
CHART 'example.python_random' '' 'A random number' 'random number' 'random' 'random' 'line' '90000' '4' 
DIMENSION 'random1' '' 'absolute' '1' '1' 

BEGIN 'example.python_random' '1756754' 
SET 'random1' '=' '68' 
END 
```

I just need to know if wrapping every argument with `'` will be ok.

**Comment by ktsaou** [comment]
ok. I cannot test it now. If you believe it will not break something, let me know and I'll merge it.

**Comment by paulfantom** [comment]
I think it is ready. Merge it.

**Comment by ktsaou** [comment]
merged. thanks!

**Pull request merged**
