### PR TITLE
add backwards compatibility for mac OSX 10.10 and 10.9

### PR DESCRIPTION
**Pull request by octomike**
Using macOS version detection macros from `Availability.h` I can skip TCP ECN statistics and inline a missing header file to support netdata on mac OSX 10.10 and 10.9 as discussed in #1915 .

It seems th ECN stats struct members have been added with OSX 10.11 and this is a simple workaround to support the older versions.

Going back even further (someone mentioned OSX 10.5! in the issue) looks to be a more complicated endeavour, as at least some udp and vm statistics are missing as well. The XNU sources on github are a super useful resource for that: https://github.com/apple/darwin-xnu/blame/0a798f6738bc1db01281fc08ae024145e84df927/osfmk/mach/vm_statistics.h#L155

I tested the changes on 10.9 through 10.12 with vagrant VMs and everything builds fine. 10.11+ show the ECN stats, where as they are skipped in 10.9/10.10.

### CODE REVIEW

**Comment by ktsaou** [comment]
nice work!
Thank you!

**Comment by ktsaou** [comment]
cc: @vlvkobal

**Comment by snigel** [comment]
It was me who tried building on 10.5. Indeed stops at UDP right now.

```
macos_sysctl.c: In function 'do_macos_sysctl':
macos_sysctl.c:541:78: error: 'struct udpstat' has no member named 'udps_nosum'; did you mean 'udps_badsum'?
                 rrddim_set(st, "InCsumErrors", udpstat.udps_badsum + udpstat.udps_nosum);
                                                                              ^~~~~~~~~~
                                                                              udps_badsum
macos_sysctl.c:542:56: error: 'struct udpstat' has no member named 'udps_filtermcast'; did you mean 'udps_noportbcast'?
                 rrddim_set(st, "IgnoredMulti", udpstat.udps_filtermcast);
                                                        ^~~~~~~~~~~~~~~~
                                                        udps_noportbcast
```
If I wanted to try to patch this, how would I go ahead? Are there any similar patches I could look at?

**Comment by octomike** [comment]
If you really want to go down this road you can try the MIN_REQUIRED macros used in this commit I guess. Put them around the unsupported block and see if you get further. But I suspect you will have to disable quite a lot. 

The error:

```
... has no member named 'udps_nosum'
```

is your clue here. You can see [on github](https://github.com/apple/darwin-xnu/blame/master/bsd/netinet/udp_var.h#L102) when it was added and [on wikipedia](https://de.m.wikipedia.org/wiki/XNU#Versionsgeschichte) which osx version it corresponds to. Good luck :)

**Comment by vlvkobal** [comment]
`udps_nosum` was added in xnu-344 but not for `__APPLE__`
https://github.com/apple/darwin-xnu/commit/d738f900846ed2d5f685e18bf85ce63b0176f61a#diff-70e8fbc5d7c5e0887785fdb591dead07R100

In xnu-2422.1.72 (OS X (10.9.x „Mavericks“) it became available for OS X
https://github.com/apple/darwin-xnu/commit/ff3a0c1e9808972592661c365ab368466b31ab20#diff-70e8fbc5d7c5e0887785fdb591dead07

I think it has to be something like that:

```
#if (defined __MAC_OS_X_VERSION_MIN_REQUIRED && __MAC_OS_X_VERSION_MIN_REQUIRED >= 1090)
                rrddim_set(st, "InCsumErrors", udpstat.udps_badsum + udpstat.udps_nosum);
#else
                rrddim_set(st, "InCsumErrors", udpstat.udps_badsum);
#endif
```

@snigel could you apply the diff and test the code:
```
diff --git a/src/macos_sysctl.c b/src/macos_sysctl.c
index 3c519ca2..6a62e0dd 100644
--- a/src/macos_sysctl.c
+++ b/src/macos_sysctl.c
@@ -538,7 +538,11 @@ int do_macos_sysctl(int update_every, usec_t dt) {
                 rrddim_set(st, "InErrors", udpstat.udps_hdrops + udpstat.udps_badlen);
                 rrddim_set(st, "NoPorts", udpstat.udps_noport);
                 rrddim_set(st, "RcvbufErrors", udpstat.udps_fullsock);
+#if (defined __MAC_OS_X_VERSION_MIN_REQUIRED && __MAC_OS_X_VERSION_MIN_REQUIRED >= 1090)
                 rrddim_set(st, "InCsumErrors", udpstat.udps_badsum + udpstat.udps_nosum);
+#else
+                rrddim_set(st, "InCsumErrors", udpstat.udps_badsum);
+#endif
                 rrddim_set(st, "IgnoredMulti", udpstat.udps_filtermcast);
                 rrdset_done(st);
             }
```

**Comment by snigel** [comment]
@vlvkobal I further now, the nosum error disappeared after I applied your patch.

```macos_sysctl.c: In function 'do_macos_sysctl':
macos_sysctl.c:546:56: error: 'struct udpstat' has no member named 'udps_filtermcast'; did you mean 'udps_noportbcast'?
                 rrddim_set(st, "IgnoredMulti", udpstat.udps_filtermcast);
                                                        ^~~~~~~~~~~~~~~~
                                                        udps_noportbcast
```

**Comment by vlvkobal** [comment]
OK... In that case try this one:

```
diff --git a/src/macos_sysctl.c b/src/macos_sysctl.c
index 3c519ca2..209d8c76 100644
--- a/src/macos_sysctl.c
+++ b/src/macos_sysctl.c
@@ -531,15 +531,21 @@ int do_macos_sysctl(int update_every, usec_t dt) {
                     rrddim_add(st, "InErrors", NULL, 1, 1, RRD_ALGORITHM_INCREMENTAL);
                     rrddim_add(st, "NoPorts", NULL, 1, 1, RRD_ALGORITHM_INCREMENTAL);
                     rrddim_add(st, "InCsumErrors", NULL, 1, 1, RRD_ALGORITHM_INCREMENTAL);
+#if (defined __MAC_OS_X_VERSION_MIN_REQUIRED && __MAC_OS_X_VERSION_MIN_REQUIRED >= 1090)
                     rrddim_add(st, "IgnoredMulti", NULL, 1, 1, RRD_ALGORITHM_INCREMENTAL);
+#endif
                 } else
                     rrdset_next(st);
 
                 rrddim_set(st, "InErrors", udpstat.udps_hdrops + udpstat.udps_badlen);
                 rrddim_set(st, "NoPorts", udpstat.udps_noport);
                 rrddim_set(st, "RcvbufErrors", udpstat.udps_fullsock);
+#if (defined __MAC_OS_X_VERSION_MIN_REQUIRED && __MAC_OS_X_VERSION_MIN_REQUIRED >= 1090)
                 rrddim_set(st, "InCsumErrors", udpstat.udps_badsum + udpstat.udps_nosum);
                 rrddim_set(st, "IgnoredMulti", udpstat.udps_filtermcast);
+#else
+                rrddim_set(st, "InCsumErrors", udpstat.udps_badsum);
+#endif
                 rrdset_done(st);
             }
         }
```

**Comment by snigel** [comment]
@vlvkobal getting further again. But this time, lots of new errors:

```
macos_mach_smi.c: In function 'do_macos_mach_smi':
macos_mach_smi.c:28:5: error: unknown type name 'vm_statistics64_data_t'; did you mean 'vm_statistics_data_t'?
     vm_statistics64_data_t vm_statistics;
     ^~~~~~~~~~~~~~~~~~~~~~
     vm_statistics_data_t
macos_mach_smi.c:76:24: error: 'vm_statistics64_data_t' undeclared (first use in this function); did you mean 'vm_statistics_data_t'?
         count = sizeof(vm_statistics64_data_t);
                        ^~~~~~~~~~~~~~~~~~~~~~
                        vm_statistics_data_t
macos_mach_smi.c:76:24: note: each undeclared identifier is reported only once for each function it appears in
macos_mach_smi.c:77:14: warning: implicit declaration of function 'host_statistics64'; did you mean 'host_statistics'? [-Wimplicit-function-declaration]
         kr = host_statistics64(host, HOST_VM_INFO64, (host_info64_t)&vm_statistics, &count);
              ^~~~~~~~~~~~~~~~~
              host_statistics
macos_mach_smi.c:77:38: error: 'HOST_VM_INFO64' undeclared (first use in this function); did you mean 'HOST_VM_INFO'?
         kr = host_statistics64(host, HOST_VM_INFO64, (host_info64_t)&vm_statistics, &count);
                                      ^~~~~~~~~~~~~~
                                      HOST_VM_INFO
macos_mach_smi.c:77:55: error: 'host_info64_t' undeclared (first use in this function); did you mean 'host_info_t'?
         kr = host_statistics64(host, HOST_VM_INFO64, (host_info64_t)&vm_statistics, &count);
                                                       ^~~~~~~~~~~~~
                                                       host_info_t
macos_mach_smi.c:104:58: error: request for member 'active_count' in something not a structure or union
                 rrddim_set(st, "active",    vm_statistics.active_count);
                                                          ^
macos_mach_smi.c:105:58: error: request for member 'wire_count' in something not a structure or union
                 rrddim_set(st, "wired",     vm_statistics.wire_count);
                                                          ^
macos_mach_smi.c:106:58: error: request for member 'throttled_count' in something not a structure or union
                 rrddim_set(st, "throttled", vm_statistics.throttled_count);
                                                          ^
macos_mach_smi.c:107:59: error: request for member 'compressor_page_count' in something not a structure or union
                 rrddim_set(st, "compressor", vm_statistics.compressor_page_count);
                                                           ^
macos_mach_smi.c:108:58: error: request for member 'inactive_count' in something not a structure or union
                 rrddim_set(st, "inactive",  vm_statistics.inactive_count);
                                                          ^
macos_mach_smi.c:109:58: error: request for member 'purgeable_count' in something not a structure or union
                 rrddim_set(st, "purgeable", vm_statistics.purgeable_count);
                                                          ^
macos_mach_smi.c:110:60: error: request for member 'speculative_count' in something not a structure or union
                 rrddim_set(st, "speculative", vm_statistics.speculative_count);
                                                            ^
macos_mach_smi.c:111:59: error: request for member 'free_count' in something not a structure or union
                 rrddim_set(st, "free",      (vm_statistics.free_count - vm_statistics.speculative_count));
                                                           ^
macos_mach_smi.c:111:86: error: request for member 'speculative_count' in something not a structure or union
                 rrddim_set(st, "free",      (vm_statistics.free_count - vm_statistics.speculative_count));
                                                                                      ^
macos_mach_smi.c:128:51: error: request for member 'swapins' in something not a structure or union
                 rrddim_set(st, "in", vm_statistics.swapins);
                                                   ^
macos_mach_smi.c:129:52: error: request for member 'swapouts' in something not a structure or union
                 rrddim_set(st, "out", vm_statistics.swapouts);
                                                    ^
macos_mach_smi.c:154:55: error: request for member 'faults' in something not a structure or union
                 rrddim_set(st, "memory", vm_statistics.faults);
                                                       ^
macos_mach_smi.c:155:52: error: request for member 'cow_faults' in something not a structure or union
                 rrddim_set(st, "cow", vm_statistics.cow_faults);
                                                    ^
macos_mach_smi.c:156:55: error: request for member 'pageins' in something not a structure or union
                 rrddim_set(st, "pagein", vm_statistics.pageins);
                                                       ^
macos_mach_smi.c:157:56: error: request for member 'pageouts' in something not a structure or union
                 rrddim_set(st, "pageout", vm_statistics.pageouts);
                                                        ^
macos_mach_smi.c:158:57: error: request for member 'compressions' in something not a structure or union
                 rrddim_set(st, "compress", vm_statistics.compressions);
                                                         ^
macos_mach_smi.c:159:59: error: request for member 'decompressions' in something not a structure or union
                 rrddim_set(st, "decompress", vm_statistics.decompressions);
                                                           ^
macos_mach_smi.c:160:58: error: request for member 'zero_fill_count' in something not a structure or union
                 rrddim_set(st, "zero_fill", vm_statistics.zero_fill_count);
                                                          ^
macos_mach_smi.c:161:59: error: request for member 'reactivations' in something not a structure or union
                 rrddim_set(st, "reactivate", vm_statistics.reactivations);
                                                           ^
macos_mach_smi.c:162:54: error: request for member 'purges' in something not a structure or union
                 rrddim_set(st, "purge", vm_statistics.purges);
                                                      ^
make[2]: *** [macos_mach_smi.o] Error 1
make[1]: *** [all-recursive] Error 1

**Comment by octomike** [comment]
same story ...  `vm_statistics64` seems to have been introduced to macOS with 10.6.0, see here: https://github.com/opendtrace/xnu/blame/81952f631f6a46b7580892be6c826231b2a1fc7a/osfmk/mach/vm_statistics.h#L116

**Comment by vlvkobal** [comment]
@snigel Apply this patch: https://github.com/vlvkobal/netdata/commit/584e7f6b9af433ad2d2033cd2406a80a12fafc7f.patch
or get patched `netdata` with `git clone https://github.com/vlvkobal/netdata.git --depth=1 --branch macOS_10.5`

**Comment by snigel** [comment]
Thank you @vlvkobal !
It looks like I still have the same errors still(?)
Tried both the 10.5 branch and patching the main branch using the diff:

```
macos_mach_smi.c: In function 'do_macos_mach_smi':
macos_mach_smi.c:29:5: error: unknown type name 'vm_statistics64_data_t'; did you mean 'vm_statistics_data_t'?
     vm_statistics64_data_t vm_statistics;
     ^~~~~~~~~~~~~~~~~~~~~~
     vm_statistics_data_t
macos_mach_smi.c:81:24: error: 'vm_statistics64_data_t' undeclared (first use in this function); did you mean 'vm_statistics_data_t'?
         count = sizeof(vm_statistics64_data_t);
                        ^~~~~~~~~~~~~~~~~~~~~~
                        vm_statistics_data_t
macos_mach_smi.c:81:24: note: each undeclared identifier is reported only once for each function it appears in
macos_mach_smi.c:82:14: warning: implicit declaration of function 'host_statistics64'; did you mean 'host_statistics'? [-Wimplicit-function-declaration]
         kr = host_statistics64(host, HOST_VM_INFO64, (host_info64_t)&vm_statistics, &count);
              ^~~~~~~~~~~~~~~~~
              host_statistics
macos_mach_smi.c:82:38: error: 'HOST_VM_INFO64' undeclared (first use in this function); did you mean 'HOST_VM_INFO'?
         kr = host_statistics64(host, HOST_VM_INFO64, (host_info64_t)&vm_statistics, &count);
                                      ^~~~~~~~~~~~~~
                                      HOST_VM_INFO
macos_mach_smi.c:82:55: error: 'host_info64_t' undeclared (first use in this function); did you mean 'host_info_t'?
         kr = host_statistics64(host, HOST_VM_INFO64, (host_info64_t)&vm_statistics, &count);
                                                       ^~~~~~~~~~~~~
                                                       host_info_t
macos_mach_smi.c:115:58: error: request for member 'active_count' in something not a structure or union
                 rrddim_set(st, "active",    vm_statistics.active_count);
                                                          ^
macos_mach_smi.c:116:58: error: request for member 'wire_count' in something not a structure or union
                 rrddim_set(st, "wired",     vm_statistics.wire_count);
                                                          ^
macos_mach_smi.c:121:58: error: request for member 'inactive_count' in something not a structure or union
                 rrddim_set(st, "inactive",  vm_statistics.inactive_count);
                                                          ^
macos_mach_smi.c:122:58: error: request for member 'purgeable_count' in something not a structure or union
                 rrddim_set(st, "purgeable", vm_statistics.purgeable_count);
                                                          ^
macos_mach_smi.c:123:60: error: request for member 'speculative_count' in something not a structure or union
                 rrddim_set(st, "speculative", vm_statistics.speculative_count);
                                                            ^
macos_mach_smi.c:124:59: error: request for member 'free_count' in something not a structure or union
                 rrddim_set(st, "free",      (vm_statistics.free_count - vm_statistics.speculative_count));
                                                           ^
macos_mach_smi.c:124:86: error: request for member 'speculative_count' in something not a structure or union
                 rrddim_set(st, "free",      (vm_statistics.free_count - vm_statistics.speculative_count));
                                                                                      ^
macos_mach_smi.c:171:55: error: request for member 'faults' in something not a structure or union
                 rrddim_set(st, "memory", vm_statistics.faults);
                                                       ^
macos_mach_smi.c:172:52: error: request for member 'cow_faults' in something not a structure or union
                 rrddim_set(st, "cow", vm_statistics.cow_faults);
                                                    ^
macos_mach_smi.c:173:55: error: request for member 'pageins' in something not a structure or union
                 rrddim_set(st, "pagein", vm_statistics.pageins);
                                                       ^
macos_mach_smi.c:174:56: error: request for member 'pageouts' in something not a structure or union
                 rrddim_set(st, "pageout", vm_statistics.pageouts);
                                                        ^
macos_mach_smi.c:179:58: error: request for member 'zero_fill_count' in something not a structure or union
                 rrddim_set(st, "zero_fill", vm_statistics.zero_fill_count);
                                                          ^
macos_mach_smi.c:180:59: error: request for member 'reactivations' in something not a structure or union
                 rrddim_set(st, "reactivate", vm_statistics.reactivations);
                                                           ^
macos_mach_smi.c:181:54: error: request for member 'purges' in something not a structure or union
                 rrddim_set(st, "purge", vm_statistics.purges);

**Comment by vlvkobal** [comment]
I think you should use `__MAC_OS_X_VERSION_MIN_REQUIRED >= 1060` instead of `__MAC_OS_X_VERSION_MIN_REQUIRED > 1050`. It seems that your OS X version is something between 1050 and 1060 that's why evaluation is positive (not inverted).

You can find information about user and group creation in #2152. Create them before installing `netdata`.

It doubt that you really need `sudo`. You can install `netdata` with `./netdata-installer.sh --install ~/opt`.

**Comment by vlvkobal** [comment]
I've updated repository so you can clone from
`https://github.com/vlvkobal/netdata.git --branch macOS_10.5`

**Comment by snigel** [comment]
@vlvkobal tried building your macOS_10.5 branch, it works fine now.
Compiles, installs and runs.

**Comment by vlvkobal** [comment]
@octomike Could you test `https://github.com/vlvkobal/netdata.git --branch macOS_10.5` on newer macOS just do be sure I haven't broken anything.

**Comment by octomike** [comment]
builds and starts fine on 10.9 throught 10.12 :+1:

**Comment by vlvkobal** [comment]
Thank you @octomike. In that case I'm going to make a PR.

**Comment by ktsaou** [comment]
merged it!

**Pull request merged**
