### PR TITLE
redis: "rdb_bgsave_in_progress" + "rdb_last_bgsave_status"

### PR DESCRIPTION
**Pull request by l2isbad**
fixes https://github.com/firehol/netdata/issues/2581

@ktsaou 
@jurgenhaas

please post the alarms you want here i will add them to the PR

### CODE REVIEW

**Comment by ktsaou** [comment]
It seems I forgot this.

I understand dimension `rdb_last_bgsave_status` of chart `redis.bgsave_health` takes either 0 or 1. So the alarm would be:

```
template: redis_bgsave_broken
families: *
      on: redis.bgsave_health
   every: 10s
    crit: $rdb_last_bgsave_status != 1
   units: ok/failed
    info: states if redis bgsave is working
   delay: down 5m multiplier 1.5 max 1h
      to: dba

template: redis_bgsave_slow
families: *
      on: redis.bgsave_now
   every: 10s
   warn: $rdb_bgsave_in_progress > 600
    crit: $rdb_bgsave_in_progress > 1200
   units: seconds
    info: the time redis needs to save its database
   delay: down 5m multiplier 1.5 max 1h
      to: dba
```

I have not tested them. Could you please load them to make sure the badges show up as they should?

**Comment by l2isbad** [comment]
screenshot_20170925_092235

**Comment by jurgenhaas** [comment]
This is looking great, thanks for implementing this.

**Comment by ktsaou** [comment]
merged!

**Pull request merged**
