### PR TITLE
Add beanstalkd monitor

### LINKED ISSUE #2820: Beanstalk monitoring
I was looking for a beanstalk monitor to use with netdata but couldn't find one and spoke to you guys on twitter and you weren't aware of one so I've put one together. It's rough and is all configured from within the chart.py file at the moment but it works. It creates a dimension with tubename_stat and then assigns the value to that.

Happy for someone to tear it apart or adapt it!
[beanstalk.chart.txt](https://github.com/firehol/netdata/files/1346426/beanstalk.chart.txt)

### PR DESCRIPTION
**Pull request by edwade3**
First attempt at writing a proper plugin which does use a configuration file to configure host and port

fixes #2820

### CODE REVIEW

**Comment by ktsaou** [comment]
nice!

@l2isbad please review this...

**Comment by ktsaou** [comment]
@edwade3 have a look at codacy. I don't know if its complaints are valid.

**Comment by edwade3** [comment]
Hey,

I've fixed all the issues (I hope) except the super invocation - I'm not a python developer and just used the code you guys had in the example so feel free to modify it as required!

**Comment by l2isbad** [comment]
Hey @edwade3 
please post some screenshots here

**Comment by edwade3** [comment]
Attached is a screenshot of the plugin in action (on a custom dashboard so it's a little bit clearer I hope!) - if theres other screenshots you want then let me know
screencapture-netdata-ecow-co-uk-test-html-1507018644596

**Comment by ktsaou** [comment]
hm... this chart is a little bit confusing...
What are the dimensions?

**Comment by edwade3** [comment]
The dimensions are labelled as tubename_stat so everytime you add a tube it will automatically pick up the tube along with all its associated statistics (current waiting jobs, current reserved jobs etc). On a plain beanstalkd install, theres always a tube named default which is the stats you can see on the graph in the screenshot. The dimension names are quite long so they're not fully visible in the legend unless you hover over them. I can PM you a link to a live chart if you want to see it?

**Comment by l2isbad** [comment]
```python
        tubes = beanstalk.tubes()
         for tube in tubes:
             print tube
             stats = beanstalk.stats_tube(tube)
             for stat, value in stats.iteritems():
                 self.set(tube + "_" + stat, value)
```

I see N number of tubes. Every tube has Y number of stats. ?
If so we need different charts for different stats?

Like 
```
chart STAT1
 dim tub1 stat1
 dim tub2 stat1

chart STAT2
 dim tub1 stat2
 dim tub2 stat2
```

?

**Comment by edwade3** [comment]
Yeah, so every tube has 13 stats. Would one chart per tube be better so if you only have one tube, you only have one chart with each charts dimensions on? I fear that may beyond my abilities to put in to a pull request for you though!!

**Comment by l2isbad** [comment]
>  Would one chart per tube be better so if you only have one tube, you only have one chart with each charts dimensions on?

Well, if you need to compare a stat among all the tubes better 1 chart per stat. If not - 1 chart per tube.
I don't even know what is tube/beanstalk 😄 So it's up to you.

> I fear that may beyond my abilities to put in to a pull request for you though!!

give me some time 😄

**Comment by edwade3** [comment]
> Well, if you need to compare a stat among all the tubes better 1 chart per stat. If not - 1 chart per tube.
I don't even know what is tube/beanstalk :smile: So it's up to you.

I think one chart per tube is probably better as it's more informational than for comparison. Beanstalkd is a job queuing system - it's really good!!

> give me some time :smile:

Ha - no problems. You guys are awesome so well done on making netdata as good as it is!! Sorry my python isn't up to scratch or I'd actually be of some use! :laughing:

**Comment by l2isbad** [comment]
> I think one chart per tube is probably better as it's more informational than for comparison. Beanstalkd is a job queuing system - it's really good!!

got it

What about number of tubes? Can it change while the plugin is running?

**Comment by edwade3** [comment]
> What about number of tubes? Can it change while the plugin is running?

Yeah - basically any time a script starts up and "watches" a tube, it creates that tube, even if it's empty so they can be created/destroyed at any point

**Comment by ktsaou** [comment]
Can you post the complete output of:

```python
pprint(beanstalk.stats_tube('default'))
{...
 'current-jobs-ready': 0,
 'current-jobs-reserved': 0,
 'current-jobs-urgent': 0,
 ...
 'name': 'default',
 ...}
```

Each netdata chart has common `units` for all its dimensions. So, I would like to check what are the units of the metrics returned.

We may end up having 2-3 charts per tube and use the tubes as families (i.e. netdata submenus). This will also allow us to have alarm templates for the charts.

**Comment by ktsaou** [comment]
btw, docs: http://beanstalkc.readthedocs.io/en/latest/tutorial.html#statistics

**Comment by ktsaou** [comment]
ok, found some info.

`tube_stats(tube)` returns this:

```
The stats-tube data is a YAML file representing a single dictionary of strings
to scalars. It contains these keys:

 - "name" is the tube's name.

 - "current-jobs-urgent" is the number of ready jobs with priority < 1024 in
   this tube.

 - "current-jobs-ready" is the number of jobs in the ready queue in this tube.

 - "current-jobs-reserved" is the number of jobs reserved by all clients in
   this tube.

 - "current-jobs-delayed" is the number of delayed jobs in this tube.

 - "current-jobs-buried" is the number of buried jobs in this tube.

 - "total-jobs" is the cumulative count of jobs created in this tube in
   the current beanstalkd process.

 - "current-using" is the number of open connections that are currently
   using this tube.

 - "current-waiting" is the number of open connections that have issued a
   reserve command while watching this tube but not yet received a response.

 - "current-watching" is the number of open connections that are currently
   watching this tube.

 - "pause" is the number of seconds the tube has been paused for.

 - "cmd-delete" is the cumulative number of delete commands for this tube

 - "cmd-pause-tube" is the cumulative number of pause-tube commands for this
   tube.

 - "pause-time-left" is the number of seconds until the tube is un-paused.
```


I understand we need **5 charts per tube**:

1. `jobs_rate` (area chart, with units `jobs/s`)
   - `total-jobs` as `jobs`, incremental

2. `jobs` (stacked chart, with units `jobs`)
   - `current-jobs-urgent` as `urgent`, absolute
   - `current-jobs-ready` as `ready`, absolute
   - `current-jobs-reserved` as `reserved`, absolute
   - `current-jobs-delayed` as `delayed`, absolute
   - `current-jobs-buried` as `buried`, absolute

3. `connections` (stacked chart, with units `connections`)
   - `current-using` as `using`, absolute
   - `current-waiting` as `waiting`, absolute
   - `current-watching` as `watching`, absolute

4. `commands` (line chart, with units `command/s`)
   - `cmd-delete` as `deletes`, incremental
   - `cmd-pause-tube` as `pauses`, incremental

5. `pause` chart
   - `pause` as `since`, absolute
   - `pause-time-left` as `left`, absolute

**Comment by ktsaou** [comment]
And there is another command `.stats()` that returns statistics for the entire server:

```
- "current-jobs-urgent" is the number of ready jobs with priority < 1024.

 - "current-jobs-ready" is the number of jobs in the ready queue.

 - "current-jobs-reserved" is the number of jobs reserved by all clients.

 - "current-jobs-delayed" is the number of delayed jobs.

 - "current-jobs-buried" is the number of buried jobs.

 - "cmd-put" is the cumulative number of put commands.

 - "cmd-peek" is the cumulative number of peek commands.

 - "cmd-peek-ready" is the cumulative number of peek-ready commands.

 - "cmd-peek-delayed" is the cumulative number of peek-delayed commands.

 - "cmd-peek-buried" is the cumulative number of peek-buried commands.

 - "cmd-reserve" is the cumulative number of reserve commands.

 - "cmd-use" is the cumulative number of use commands.

 - "cmd-watch" is the cumulative number of watch commands.

 - "cmd-ignore" is the cumulative number of ignore commands.

 - "cmd-delete" is the cumulative number of delete commands.

 - "cmd-release" is the cumulative number of release commands.

 - "cmd-bury" is the cumulative number of bury commands.

 - "cmd-kick" is the cumulative number of kick commands.

 - "cmd-stats" is the cumulative number of stats commands.

 - "cmd-stats-job" is the cumulative number of stats-job commands.

 - "cmd-stats-tube" is the cumulative number of stats-tube commands.

 - "cmd-list-tubes" is the cumulative number of list-tubes commands.

 - "cmd-list-tube-used" is the cumulative number of list-tube-used commands.

 - "cmd-list-tubes-watched" is the cumulative number of list-tubes-watched
   commands.

 - "cmd-pause-tube" is the cumulative number of pause-tube commands.

 - "job-timeouts" is the cumulative count of times a job has timed out.

 - "total-jobs" is the cumulative count of jobs created.

 - "max-job-size" is the maximum number of bytes in a job.

 - "current-tubes" is the number of currently-existing tubes.

 - "current-connections" is the number of currently open connections.

 - "current-producers" is the number of open connections that have each
   issued at least one put command.

 - "current-workers" is the number of open connections that have each issued
   at least one reserve command.

 - "current-waiting" is the number of open connections that have issued a
   reserve command but not yet received a response.

 - "total-connections" is the cumulative count of connections.

 - "pid" is the process id of the server.

 - "version" is the version string of the server.

 - "rusage-utime" is the cumulative user CPU time of this process in seconds
   and microseconds.

 - "rusage-stime" is the cumulative system CPU time of this process in
   seconds and microseconds.

 - "uptime" is the number of seconds since this server process started running.

 - "binlog-oldest-index" is the index of the oldest binlog file needed to
   store the current jobs.

 - "binlog-current-index" is the index of the current binlog file being
   written to. If binlog is not active this value will be 0.

 - "binlog-max-size" is the maximum size in bytes a binlog file is allowed
   to get before a new binlog file is opened.

 - "binlog-records-written" is the cumulative number of records written
   to the binlog.

 - "binlog-records-migrated" is the cumulative number of records written
   as part of compaction.

 - "id" is a random id string for this server process, generated when each
   beanstalkd process starts.

 - "hostname" the hostname of the machine as determined by uname.

```

This seems to be a fixed number of charts, like before.

1. `cpu_usage` based on `rusage-*` (area chart, incremental)
2. `jobs_rate` based on `total-jobs` and `job-timeouts` (line chart, incremental)
3. `connections_rate` based on `total-connections` (area chart, incremental)
4. `commands_rate` based on `cmd-*` (stacked, incremental)
5. `current_tubes` based on `current-tubes` (area, absolute)
6. `current_jobs` based on `current-jobs-*` (stacked, absolute)
7. `current_connections` with these `current-connections`, `current-producers`, `current-workers`, `current-waiting` as line chart (they are overlapping, so cannot be stacked)
8. `binlog` with `binlog-records-written` and `binlog-records-migrated` (line chart, incremental)
9. `uptime` with `uptime` (line chart, absolute)

**Comment by ktsaou** [comment]
btw, I really like beanstalkd ! I haven't checked the code, but the specs and the operation seem pretty nice!

**Comment by l2isbad** [comment]
Wow, gj @ktsaou 👍 

Seem I have to install it myself to figure out better 😄

**Comment by edwade3** [comment]
Wow! I dear I may have opened a can of worms for you but full marks for your research!! Sounds like what you have come up with will be a far more suitable and beneficial plugin then I had ever envisaged? Is this your full time job or do you do this voluntarily?

**Comment by ktsaou** [comment]
haha... nice you like it, but I just grouped them - a human version of `SELECT ... GROUP BY ...` :)

@edwade3 let's hope @l2isbad will work on it. It should be relatively easy for him to code this. His has implemented a few that are a lot more complex than this... :+1:

**Comment by l2isbad** [comment]
> Yeah - basically any time a script starts up and "watches" a tube, it creates that tube, even if it's empty so they can be created/destroyed at any point

Do we need to support dynamic addition of tube charts? 
Default is ignore all newly created tubes (after check()).
I don't know how many tubes can be created/deleted during lifetime. It can be dangerous to let module to create unlimited amount of charts.

**Comment by ecowed** [comment]
> Do we need to support dynamic addition of tube charts?
Default is ignore all newly created tubes (after check()).
I don't know how many tubes can be created/deleted during lifetime. It can be dangerous to let module to create unlimited amount of charts.

Theoretically, I guess the number of tubes is unlimited - I only use 4 but others may well use more. I think for me, it would be nice to have the ability to create a tube and it automatically appear. Whats the alternative; Creating a tube and then having to restart netdata? As I said, we only use 4 tubes so not much dynamic creation/deletion but others use cases may well be different.

**Comment by ktsaou** [comment]
@l2isbad I think we should support monitoring the tubes, so yes please support dynamic creation of tubes.

This could be controlled by a setting like:

```yaml
   tubes: all or none or [ tube1, tube2, tube3 ]
```

So, the user may select a list of tubes, `all` the tubes or `none` of the tubes.
If supporting a list is too much work, you can just support `all` and `none`.

The default should be `all`.

**Comment by ecowed** [comment]
> Another problem is adding a chart with name that already was deleted (create tube 'foo' -> delete tube 'foo' -> create tube 'foo'). How should i handle this? Should I interpret this as a new chart? (i mean push chart then push data or just push data)

Personally, I think it should use the same chart (if possible) rather than creating a new one so that when you scroll back through the stats, you can see historic information.

> What obsolete timeout should i use for beanstalk module?

I think if a tube is empty (and therefore deleted) it can disappear fairly quickly (10 iterations - is that 10 seconds or does it not work like that?)

**Comment by ktsaou** [comment]
> Obsolete feature already implemented and default timeout is 10 iterations (all charts that are not updated 10 iterations in a row are pushed to netdata with obsolete option).
> They are actually not deleted from job charts but suppressed.

The `obsolete` flag is used to allow netdata cleanup. If should only be used on charts the plugin believes are ephemeral.

Ideally this should be configurable per module. For example, user A knows that its tubes are permanent, so no cleanup. But user B knows that its app creates tubes for some time and then it closes them. So, a job configuration like:

```yaml
cleanup: 0 to disable or false, or N seconds
```

When a plugin sends the `obsolete` flag, the charts are not deleted from netdata immediately. They will be hidden immediately (not offered to dashboard viewer, streamed upstream and archived to backends) and deleted one hour later (configurable from netdata.conf).

> i am still a little bit confused about microseconds - The first time the plugin is started, no microseconds should be given to netdata
> 
> Does this applies to the plugin or to a separate chart?

netdata uses this per chart. For each set of values netdata collects **per chart**, it needs to know the time passed since the last data collection:

1. If you pass zero, netdata will use its own timings (`microseconds = now - chart_last_collection_t`).
2. If you pass non-zero, netdata will use the plugin timings (`chart_last_collection_t = chart_last_collection_t + microseconds`). So, the plugin can set the current time for the chart. Plugin timings are accepted with some tolerance: cumulative values for microseconds (i.e. `chart_last_collection_t`) , that lead the chart more than 8 seconds to the past or just 1 microsecond to the future, are ignored. netdata will use its own timings in such cases. This is a protection. You will see a chart left behind for up to 8 seconds, then a gap, and again back up to 8 seconds, then a gap, etc.
 
The whole idea with `microseconds` is to improve accuracy. I have found that under extreme system conditions, data collection latency influenced accuracy significantly. It still does, but when timings are supplied by the plugin, the result seems a lot better.

You can set microseconds to zero, any time you believe time has been lost for a chart and netdata should calculate it by itself (i.e. align the chart to current time). So, if you send the `obsolete` flag for a chart, it is best the next data collection to have `microseconds = 0`.

> Some charts can be pushed after module started at any time.
> Should microseconds be zero for them on first iteration?

Yes, send zero microseconds the first time you push metrics for a chart, or the first time after the `obsolete` flag.

> Another problem is adding a chart with name that already was deleted (create tube 'foo' -> delete tube 'foo' -> create tube 'foo'). How should i handle this? Should I interpret this as a new chart? (i mean push chart then push data or just push data)

Yes, once you push the `obsolete` flag for a chart, you should re-define it.

**Comment by ktsaou** [comment]
I am closing this in favor of #2959

**Comment by l2isbad** [comment]
> Yes, send zero microseconds the first time you push metrics for a chart, or the first time after the obsolete flag.

> Yes, once you push the obsolete flag for a chart, you should re-define it.

implemented

error in log

> 2017-11-03 09:33:17: netdata ERROR: Chart 'beanstalk.foo_jobs_rate' has the OBSOLETE flag set, but it is collected.
> 2017-11-03 09:33:17: netdata ERROR: Chart 'beanstalk.foo_connections' has the OBSOLETE flag set, but it is collected.
> 2017-11-03 09:33:17: netdata ERROR: Chart 'beanstalk.foo_pause' has the OBSOLETE flag set, but it is collected.
> 2017-11-03 09:33:17: netdata ERROR: Chart 'beanstalk.foo_jobs' has the OBSOLETE flag set, but it is collected.
> 2017-11-03 09:33:17: netdata ERROR: Chart 'beanstalk.foo_commands' has the OBSOLETE flag set, but it is collected

Is it ok (i thought that, redefining the schedule removes the flag)?

**Comment by ktsaou** [comment]
> Is it ok (i thought that redefining the chart removes the flag)?

hm... it should. let me check...

Yes it does: https://github.com/ktsaou/netdata/blob/e2389840cc5ff6de71e4d57b0f2bd1034912d50d/src/rrdset.c#L414

Are you sure you sent it again?

**Comment by ktsaou** [comment]
And the error does the same: https://github.com/ktsaou/netdata/blob/e2389840cc5ff6de71e4d57b0f2bd1034912d50d/src/rrdset.c#L1087

So, that little call works... (if it didn't the errors would have been repeating forever).

**Comment by l2isbad** [comment]
> Are you sure you sent it again?

100% sure

**Comment by ktsaou** [comment]
Could you please give me the output of the plugin?
I'll add a few `sleep` lines to re-produce this.

**Comment by l2isbad** [comment]
example output

<details>
<summary> (click) </summary>

```
CHART netdata.runtime_example '' 'Execution time for example' 'ms' 'python.d' netdata.pythond_runtime line 145000 1
DIMENSION run_time 'run time' absolute 1 1

CHART example.test '' 'A test number' 'test number' 'test' 'test' line 90001 1
DIMENSION 'test1' 'test1' absolute 1 1 ''

BEGIN example.test 0
SET 'test1' = 999
END

CHART example.random '' 'A random number' 'random number' 'random' 'random' line 90000 1
DIMENSION 'random1' 'random1' absolute 1 1 ''
DIMENSION 'random2' 'random2' absolute 1 1 ''
DIMENSION 'random3' 'random3' absolute 1 1 ''

BEGIN example.random 0
SET 'random1' = 29
SET 'random2' = 96
SET 'random3' = 35
END

BEGIN netdata.runtime_example 0
SET run_time = 0
END

BEGIN example.random 1000739
SET 'random1' = 82
SET 'random2' = 57
SET 'random3' = 28
END

BEGIN netdata.runtime_example 1000739
SET run_time = 0
END

BEGIN example.random 1000210
SET 'random1' = 53
SET 'random2' = 37
SET 'random3' = 44
END

BEGIN netdata.runtime_example 1000210
SET run_time = 0
END

BEGIN example.random 1000147
SET 'random1' = 28
SET 'random2' = 62
SET 'random3' = 75
END

BEGIN netdata.runtime_example 1000147
SET run_time = 0
END

CHART example.test '' 'A test number' 'test number' 'test' 'test' line 90001 1 'obsolete'

BEGIN example.random 999876
SET 'random1' = 31
SET 'random2' = 19
SET 'random3' = 41
END

BEGIN netdata.runtime_example 999876
SET run_time = 0
END

CHART example.test '' 'A test number' 'test number' 'test' 'test' line 90001 1
DIMENSION 'test1' 'test1' absolute 1 1 ''

BEGIN example.test 0
SET 'test1' = 999
END

BEGIN example.random 1000120
SET 'random1' = 42
SET 'random2' = 23
SET 'random3' = 53
END

BEGIN netdata.runtime_example 1000120
SET run_time = 0
END

BEGIN example.test 999506
SET 'test1' = 999
END

BEGIN example.random 999506
SET 'random1' = 36
SET 'random2' = 0
SET 'random3' = 15
END

BEGIN netdata.runtime_example 999506
SET run_time = 0
END

BEGIN example.test 1000413
SET 'test1' = 999
END

BEGIN example.random 1000413
SET 'random1' = 6
SET 'random2' = 90
SET 'random3' = 55
END

BEGIN netdata.runtime_example 1000413
SET run_time = 0
END

BEGIN example.test 999610
SET 'test1' = 999
END

BEGIN example.random 999610
SET 'random1' = 55
SET 'random2' = 91
SET 'random3' = 31
END

BEGIN netdata.runtime_example 999610
SET run_time = 0
END

BEGIN example.test 1000389
SET 'test1' = 999
END

BEGIN example.random 1000389
SET 'random1' = 19
SET 'random2' = 42
SET 'random3' = 65
END

BEGIN netdata.runtime_example 1000389
SET run_time = 0
END
```

</details>

**Comment by ktsaou** [comment]
There is no need to test. This is the fault:

```
CHART example.test '' 'A test number' 'test number' 'test' 'test' line 90001 1 'obsolete'

BEGIN example.random 999876
SET 'random1' = 31
SET 'random2' = 19
SET 'random3' = 41
END

BEGIN netdata.runtime_example 999876
SET run_time = 0
END

CHART example.test '' 'A test number' 'test number' 'test' 'test' line 90001 1
DIMENSION 'test1' 'test1' absolute 1 1 ''
```

So, you send `obsolete` and then you send values. You should recreate the chart before sending values.

It should be like this:

```
CHART example.test '' 'A test number' 'test number' 'test' 'test' line 90001 1 'obsolete'

CHART example.test '' 'A test number' 'test number' 'test' 'test' line 90001 1
DIMENSION 'test1' 'test1' absolute 1 1 ''

BEGIN example.random 999876
SET 'random1' = 31
SET 'random2' = 19
SET 'random3' = 41
END

BEGIN netdata.runtime_example 999876
SET run_time = 0
END
```

**Comment by ktsaou** [comment]
oh... its a different chart.
Forget it, I'll test it.

**Comment by ktsaou** [comment]
Found it.
Making a PR now.

**Comment by ktsaou** [comment]
merged it

**Pull request closed without merging**
