### PR TITLE
web_log plugin: response statuses chart added

### PR DESCRIPTION
**Pull request by l2isbad**
https://github.com/firehol/netdata/issues/1777
screenshot_20170213_212526

### CODE REVIEW

**Comment by ktsaou** [comment]
I cannot test it now. If you have, I can merge it.
What do you think?

**Comment by l2isbad** [comment]
It work for be but I think that there is no reason to hurry. Chart makes no sense until alarms not fixed.

**Comment by l2isbad** [comment]
Maybe we need to change something - dimension order for example?

**Comment by ktsaou** [comment]
merged!

**Pull request merged**
