### PR TITLE
New JSON backend

### PR DESCRIPTION
**Pull request by lfdominguez**
```
{
  "prefix": "netdata",
  "hostname": "dev-pc",
  "type": "netdata",
  "family": "cgroups",
  "context": "netdata.plugin_cgroups_cpu",
  "units": "milliseconds/s",
  "title": "NetData CGroups Plugin CPU usage (netdata.plugin_cgroups_cpu)",
  "id": "netdata.plugin_cgroups_cpu",
  "subid": "user",
  "value": 0.2898883,
  "timestamp": 1487364216
}
```

### CODE REVIEW

**Comment by ktsaou** [comment]
nice.

Let me think a bit:

1. There are host / global members
2. There are chart members
3. There are dimension members

## host / global members

- `prefix`
- `hostname`

## chart members

- `id` (I suggest `chart_id`)
- `name` (I suggest `chart_name`)
- `family` (this group multiple charts together to a family - the charts are different views of the same entity)
- `context` (this is the template upon which the chart is based - so all `disk.io` charts, for all disks, have the same context)
- `type` is a historical bug we have. It has 2 meanings. Check the problem here: https://github.com/firehol/netdata/issues/1519#issuecomment-272239925 and the fix we plan here: https://github.com/firehol/netdata/issues/807
- `units`
- `title` (are you sure you need this?)
- `timestamp` (this will be the same for all dimensions of the chart)

## dimension members

- `id`
- `name`
- `value`

---

So, I suggest to

1. rename `id` to `chart_id`
2. add `chart_name`
3. rename `subid` to `id`
4. add `name` (the dimension name)

### Why does netdata have both ids and names for charts and dimensions?

Well, they are needed at various stages of data collection. For example interrupt 9 has the name `X`, but we cannot know that at data collection. Special calls are needed to find the name of the interrupt and we should not perform these calls on every iteration.

So, they are an optimization. If you have to pick `id` or `name`, I suggest to pick `name`. This is human friendly.

**Comment by ktsaou** [comment]
You can also check this: http://registry.my-netdata.io/api/v1/chart?chart=system.cpu

And also this: http://registry.my-netdata.io/api/v1/data?chart=system.cpu&after=-1&options=jsonwrap

**Comment by ktsaou** [comment]
Keep in mind the naming I suggested applies only if you push to the backend database individual metrics.

I don't know if it would be better to push charts (i.e. one object for each chart with sub-objects all the dimensions of the chart). This is your call. I don't use backends, so I don't know which is better.

**Comment by lfdominguez** [comment]
Ok i will do, I need use this because i want put all the generated metrics of netdata to elasticsearch with logstash tcp input (json codec).
The next week i code all.... thanks

**Comment by lfdominguez** [comment]
Another commit, now i put all you suggestions and testing with my Logstash + ElasticSearch (json filter)

**Comment by lfdominguez** [comment]
Now is
``{
    "chart_name": "netdata.plugin_tc_time",
    "chart_id": "netdata.plugin_tc_time",
    "prefix": "netdata",
    "units": "milliseconds/run",
    "type": "netdata",
    "hostname": "dev-pc",
    "@timestamp": "2017-02-20T14:00:57.443Z",
    "port": 43180,
    "context": "netdata.plugin_tc_time",
    "name": "run time",
    "@version": "1",
    "host": "192.168.0.215",
    "id": "run_time",
    "family": "tc.helper",
    "value": 11,
    "timestamp": 1487597356
  }
``

**Comment by ktsaou** [comment]
seems nice!

I'll give it a test later today, to merge it.

Thank you!

**Comment by lfdominguez** [comment]
sorry, the ` "@timestamp": "2017-02-20T14:00:57.443Z",` and `"@version": "1",` are from elasticsearch, i copy the data that convert elastic, the output of netdata is without them.

**Comment by ktsaou** [comment]
yes, I understood that, from the code.

**Comment by ktsaou** [comment]
merged this. Thanks!

**Comment by tbarbette** [comment]
Would it be possible to add reference or documentation about a sample json setup? Json is probably the easiest of the backends. It would be useful to propose some available open source (or even online?) solutions.

**Comment by lfdominguez** [comment]
I use this JSON for input to logstash -> elasticsearch

2017-04-05 6:28 GMT-04:00 Tom Barbette <notifications@github.com>:

**Comment by urshari7** [comment]
Hi,
Is it possible to injest the json data to MongoDB?
If so, please provide a sample connection url.
I tried with  mongodb://user:password@host:port/database as the destination path. And its not working.

**Comment by ktsaou** [comment]
@urshari7 netdata cannot currently push its metrics to mongodb.

I am not sure mongodb is the right solution for this. netdata will push a lot of documents. If you believe this is right, please open another github issue. netdata will need to be compiled with libmongoc, format the documents in BSON and send them to mongodb.

This seems quite some work, so please make sure the result will be acceptable (i.e. mongodb will be able to handle the load).

**Pull request merged**
