### PR TITLE
add `_local` to postfix and exim bash scripts

### PR DESCRIPTION
**Pull request by paulfantom**
like in title.

Also phpfpm already has `_local` suffix in default configuration.

### CODE REVIEW

**Comment by ktsaou** [comment]
I am checking if we missed a module. I think the following need this too:

1. apache.chart.sh
2. squid.chart.sh

**Comment by paulfantom** [comment]
already done

**Comment by ktsaou** [comment]
nice! merge?

**Comment by paulfantom** [comment]
merge.

**Comment by ktsaou** [comment]
(I haven't tested it - have you?)

**Comment by paulfantom** [comment]
Not all. Wait a minute I will finish testing the rest.

**Comment by paulfantom** [comment]
works.

**Comment by ktsaou** [comment]
merged

**Pull request merged**
