### PR TITLE
netdata self-extracting binary package

### PR DESCRIPTION
**Pull request by ktsaou**
This PR includes scripts to build a statically linked binary netdata package, that can be run on any Linux system, with just the kernel and busybox (or the basic toolchain) installed.

The final package is a bash self-extracting script built with [makeself](https://github.com/megastep/makeself), that can be installed on any 64bit Linux system, even ancient ones, or non-standard ones (like coreos).

The package includes:

1. Statically linked `bash` v4.4 (required by several scripts to run properly)
2. Statically linked `fping` v3.16
3. Statically linked `netdata` v1.6 rolling (the git version)

I tried to also add a statically linked python and node.js but I couldn't compile it statically. @l2isbad do you have any idea how this can be done?

To build the binary package, the scripts have to run under alpine linux (glibc cannot be statically linked, but musl libc can).

Once you are inside the alpine container, run:

```sh
# cd /usr/src/netdata.git
# ./makeself/build.sh
```

The above will compile and install everything to `/opt/netdata`, and finally it will leave `/opt/netdata.gz.run`. This is the final shell script to be distributed.

### CODE REVIEW

**Comment by ktsaou** [comment]
@philwhineray I think it would be super if we could have such a binary package:

1. on every release, attached to the release at github, much like the other files.
2. on every successful merge to the main repo, possibly uploaded to github pages.

Do you believe we can do these with travis?
The build has to run with musl libc, so in a container...

**Comment by l2isbad** [comment]
> do you have any idea how this can be done?

unfortunately no

**Comment by philwhineray** [comment]
@ktsaou I have attached a set of three patches. This makes it a single-command to create the self-installer, including setup and running of docker - see what you think.

I believe this will make it easy to add to .travis.yml, just as an extra step after the .tar.gz is completed, then the file just needs to be added to the deploy file names which should complete (1).

(2) is a bit trickier since it requires managing additional credentials securely. This is mostly solved for sending versions to the firehol.org website - I'm not sure yet what is needed for gh-pages.

**Comment by philwhineray** [comment]
Here they are...
[patches.zip](https://github.com/firehol/netdata/files/888251/patches.zip)

**Comment by ktsaou** [comment]
@philwhineray excellent work!

Ideally, to really support even ancient Linux installations, we should add:

1. a statically linked `curl` command. This however, will also require openssl and root certificates.
2. a statically linked `python` v2 or v3. This will enable most python plugins.
3. a statically linked `node.js`. This will enable SNMP.

@philwhineray could you please give it a shot? I tried it, without luck.

For example, the curl script builds curl, libcurl is statically linked, by the curl command is not. Keep in mind I added openssl and gnutls to alpine, so you will have to rebuild the container.

**Comment by ktsaou** [comment]
I think static linking cannot be done without access to `.a` files. This means, that in order for curl to be statically linked, we need to also compile openssl. Alpine does provide `libcrypto.a`, so only `libssl.a` is missing.

Still I cannot figure out why `libz` and `libc` are not statically linked into `curl`:

```
# ldd /opt/netdata/bin/curl
	/lib/ld-musl-x86_64.so.1 (0x557911a5a000)
	libssl.so.1.0.0 => /lib/libssl.so.1.0.0 (0x7f375174b000)
	libcrypto.so.1.0.0 => /lib/libcrypto.so.1.0.0 (0x7f375132b000)
	libz.so.1 => /lib/libz.so.1 (0x7f3751114000)
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x557911a5a000)
```

The command executed by curl makefiles is this:

```
/bin/bash ../libtool --silent --tag=CC   --mode=link gcc  -static -DCURL_STATICLIB -g -O2 -pedantic -Wall -W -Wpointer-arith -Wwrite-strings -Wunused -Wshadow -Winline -Wnested-externs -Wmissing-declarations -Wmissing-prototypes -Wno-long-long -Wfloat-equal -Wno-multichar -Wsign-compare -Wundef -Wno-format-nonliteral -Wendif-labels -Wstrict-prototypes -Wdeclaration-after-statement -Wstrict-aliasing=3 -Wcast-align -Wtype-limits -Wold-style-declaration -Wmissing-parameter-type -Wempty-body -Wclobbered -Wignored-qualifiers -Wconversion -Wno-sign-conversion -Wvla -Wno-system-headers   -L/lib -static -o curl curl-slist_wc.o curl-tool_binmode.o curl-tool_bname.o curl-tool_cb_dbg.o curl-tool_cb_hdr.o curl-tool_cb_prg.o curl-tool_cb_rea.o curl-tool_cb_see.o curl-tool_cb_wrt.o curl-tool_cfgable.o curl-tool_convert.o curl-tool_dirhie.o curl-tool_doswin.o curl-tool_easysrc.o curl-tool_formparse.o curl-tool_getparam.o curl-tool_getpass.o curl-tool_help.o curl-tool_helpers.o curl-tool_homedir.o curl-tool_hugehelp.o curl-tool_libinfo.o curl-tool_main.o curl-tool_metalink.o curl-tool_mfiles.o curl-tool_msgs.o curl-tool_operate.o curl-tool_operhlp.o curl-tool_panykey.o curl-tool_paramhlp.o curl-tool_parsecfg.o curl-tool_strdup.o curl-tool_setopt.o curl-tool_sleep.o curl-tool_urlglob.o curl-tool_util.o curl-tool_vms.o curl-tool_writeenv.o curl-tool_writeout.o curl-tool_xattr.o ../lib/curl-strtoofft.o ../lib/curl-nonblock.o ../lib/curl-warnless.o  ../lib/libcurl.la  -lssl -lcrypto -lssl -ldl -lz -ldl -lz -lcrypto -ldl -lz -lz 
```

**Comment by philwhineray** [comment]
The other libraries are probably depended on indirectly by libssl.

**Comment by philwhineray** [comment]
Trying to confirm but I am on a very slow connection at the moment.

For curl in particular... just how ancient are we talking? I imagine it has been around a very long time and we are after all making 64-bit static intel builds so this will apply back only so far.

**Comment by philwhineray** [comment]
Telling curl to build without ssl and zlib gets rid of those libraries but it still appears to be dynamically linked so I guess there is more to it than that. I'll have a look at python later, there seems to be a number of pages on google.

**Comment by ktsaou** [comment]
Well, I understand this package will be good for:

1. ancient linux installations - most companies have a few of them. Linux is used for several "black boxed apps". I have 2-3 of them that are a decade old and cannot be updated. The oldest I have seen has 2.6 kernel and bash v3.

2. With the evolution of docker, many distros are created that boot a minimal Linux system, probably with busybox. In these distros there is no package management. So, installing a package that is missing is an adventure.

This binary package, requires a minimal toolchain from the host.

If totally static cannot be made, I think we could just copy the alpine dynamic libraries needed to `/opt/netdata/lib` and provide wrapper scripts for all commands that will set `LD_LIBRARY_PATH` and run the real binary. But, this should be avoided if possible...

**Comment by philwhineray** [comment]
Try the attached - it builds a static curl binary for me.

I didn't expect it to work with only a libssl.so but it would seem that it does; at least the binary appears to work as expected on my host system and a strace does not show it accessing any external libraries, even when connecting to an SSL site.
[0001-Create-static-curl-binary.patch.txt](https://github.com/firehol/netdata/files/888503/0001-Create-static-curl-binary.patch.txt)

**Comment by ktsaou** [comment]
@philwhineray you are a magician!
Added it!

**Comment by ktsaou** [comment]
I am testing this with cirros container under lxc. It seems to be the base minimum. Just a busybox system.

**Comment by ktsaou** [comment]
I tried gh-pages. Well... the problem is that the only way to upload something there is to clone it, which is not good enough.

Github has an [API to `PUT` files](https://developer.github.com/v3/repos/contents/#create-a-file) in a repo. 

So, I added a new repo: https://github.com/firehol/binary-packages

@philwhineray this requires a token. How does travis do it with releases? Can we upload files from travis to this repo?

**Comment by ktsaou** [comment]
and now I rembered we already have a packages repo. Probably we should use that...

**Comment by ktsaou** [comment]
I am merging this PR. I have tested all the changes made on various distros. It seems good.

@philwhineray your call. If we can have binary packages on the `packages` repo it would be awesome!

**Comment by philwhineray** [comment]
What I did for each project is use the "Travis CI command line client". There are some notes in the firehol/infrastructure README.

I don't know how easy it is to upload from one repo to another but I will take a look when I can. If it cannot be made to work we will be able to push the master builds out to the firehol.org server I guess. 

The versioned builds should upload to the netdata releases folder without problems when the file pattern is added to `.travis.yml`

**Comment by philwhineray** [comment]
Python and node.js builds may be hard:

http://www.openwall.com/lists/musl/2014/08/27/16

A solution along the lines of what you already proposed (include the extra files) is suggested later in the thread:

http://www.openwall.com/lists/musl/2014/08/27/19

**Comment by ktsaou** [comment]
ok. At least we have working netdata, apps.plugin and bash plugins in all cases. If the system has python and node installed, netdata will use those.

I understand that in order to have all the python modules working in all cases, we would need to copy alpine libc and probably more libraries in `/opt/netdata/lib`. It seems overkill though, at least for now.

> The versioned builds should upload to the netdata releases folder without problems when the file pattern is added to .travis.yml

@philwhineray I would appreciate it if you take care of this. I don't even know how to test this... so, if you find some time to do it, it would be perfect.

Given the amount of demo VMs donated to netdata, I guess we could have a build server somehere to receive web hooks from github and build and host these packages.

**Pull request merged**
