### PR TITLE
Elasticsearch plugin fixes

### PR DESCRIPTION
**Pull request by l2isbad**
"python-requests" not needed anymore

### CODE REVIEW

**Comment by ktsaou** [comment]
wow! nice. This was problematic... `py-requests` is not available everywhere as a package...

**Comment by l2isbad** [comment]
`python-requests`  available everywhere i believe and package is **very good** and popular. I like it a lot but the big problem is that it takes ~2-3 (!) sec to import it on old machines. 

```bash
cat 1.py 
from requests import get
print('imported!')

time python 1.py 
imported!

real    0m2.225s
user    0m2.072s
sys     0m0.136s
```


```bash
pacman --sync --search python-requests$
extra/python-requests 2.13.0-1 [installed]
    Python HTTP for Humans
```

**Comment by ktsaou** [comment]
ok. I think it is missing from old alpine releases (I found out during setting up the netdata [build](https://build.my-netdata.io) server).

merge?

**Comment by l2isbad** [comment]
yes

**Comment by ktsaou** [comment]
merged!

**Pull request merged**
