### PR TITLE
Mongodb plugin

### PR DESCRIPTION
**Pull request by l2isbad**
**[Initial version](https://github.com/firehol/netdata/issues/1717)**. Module uses `python-pymongo` so user need to install it manually.
(`pip install python-pymongo`)
'`serverStatus`' produces a lot of data and data depends on version/storage engine. I'm not fully understand what metrics do we need. 
All suggestions are very welcome.

TODO:
- [x] replica set member state
- [x] replica set heartbeat latency (current time - lastHeartbeatRecv)
- [ ] ~~replica set member lag (delay between a write operation on the primary and its copy to a secondary)~~
- [x] time when last entry from the oplog was applied (current time - optimeDate) diff between all members
- [x] oplog window (Interval of time between the oldest and the latest entries in the oplog)
- [x] lock metrics(acquireCount)

`Replication Lag`: delay between a write operation on the primary and its copy to a secondary = 
`members.optimeDate[primary] - members.optimeDate[secondary]`
According my tests it makes no sense.

from official documentation. `optimeDate`

> An ISODate formatted date string that reflects the last entry from the oplog that this member applied. If this differs significantly from lastHeartbeat this member is either experiencing “replication lag” or there have not been any new operations since the last update. Compare members.optimeDate between all of the members of the set.

The way i did it - "Compare members.optimeDate between all of the members of the set.".  current time - optimeDate

screenshot_20170226_140921

### CODE REVIEW

**Comment by l2isbad** [comment]
@ktsaou 
i'm done here 😄

**Comment by ktsaou** [comment]
wow! You rock!

**Comment by ktsaou** [comment]
Remember the wiki page: https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata

**Comment by ktsaou** [comment]
That wiki page is linked from the netdata dashboard, and is among the most popular:

image

**Comment by ktsaou** [comment]
hm... and I see web_log is also missing from this page.

Could you please check what else is missing?

**Comment by ktsaou** [comment]
And I added a link to the sidebar to this page, under "data collection"

**Comment by l2isbad** [comment]
sidebar and python reamde:
 + web_log, smartd_log, retrosnare, postgress, cpuidle (only sidebar).
 - nginx_log

**Comment by l2isbad** [comment]
didn't forget about it. will do later

**Pull request merged**
