### PR TITLE
Small enhancement to scrollspy

### PR DESCRIPTION
**Pull request by anthonytsavdaridis**
change hash based on selection while scrolling

### CODE REVIEW

**Comment by ktsaou** [comment]
Wow! welcome!

**Comment by ktsaou** [comment]
Hm... when you scroll down, all is good.

But when you scroll up, then depending on your mouse wheel speed, at exactly the first entry of a sub-menu, it does not allow you to scroll up. The page tries to scrolls up, but it jumps down again. If you push it (long/fast scrolls on the mouse wheel) it bypasses that point, but it is annoying.

Tested on chromium (linux).

**Comment by ktsaou** [comment]
on firefox (linux) happens too

**Comment by anthonytsavdaridis** [comment]
Yes location.hash is tricky. I think now it's ok with history.pushState

**Comment by ktsaou** [comment]
Nice! It is good now.
I am merging it...

**Comment by ktsaou** [comment]
hm... this is destroys the users' history through... When you go back you actually go to previous hash.

**Comment by simonnagl** [comment]
@anthonytsavdaridis, first of all, nice idea and good work!

Do you know about the event [onbeforeunload](http://www.w3schools.com/jsref/event_onbeforeunload.asp)?

**Pull request merged**
