### PR TITLE
Freeradius plugin

### PR DESCRIPTION
**Pull request by l2isbad**
Added freeradius plugin.
Data is collected via status server queries.

**Authentication counters:**
- access-accepts
- access-rejects
- auth-dropped-requests
- auth-duplicate-requests
- auth-invalid-requests
- auth-malformed-requests
- auth-unknown-types

**Accounting counters: [optional]**

- accounting-requests
- accounting-responses
- acct-dropped-requests
- acct-duplicate-requests
- acct-invalid-requests
- acct-malformed-requests
- acct-unknown-types

**Proxy authentication counters: [optional]**
- proxy-access-accepts
- proxy-access-rejects
- proxy-auth-dropped-requests
- proxy-auth-duplicate-requests
- proxy-auth-invalid-requests
- proxy-auth-malformed-requests
- proxy-auth-unknown-types

**Proxy accounting counters: [optional]**

- proxy-accounting-requests
- proxy-accounting-responses
- proxy-acct-dropped-requests
- proxy-acct-duplicate-requests
- proxy-acct-invalid-requests
- proxy-acct-malformed-requests
- proxy-acct-unknown-types

### CODE REVIEW

**Comment by ktsaou** [comment]
nice!

Could you please add it to the wiki page of all plugins: https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata ?

**Comment by ktsaou** [comment]
Keep in mind that running `radclient` every second, will increase both CPU and memory pressure.

I see there are python libraries that connect to radius, like this:

https://pypi.python.org/pypi/pyrad

I see that the status message is a normal radius message that any radius client can send: https://wiki.freeradius.org/config/Status#querying-with-radclient

So, the ideal solution to avoid wasting resources, is to use something like that.

**Comment by l2isbad** [comment]
Well, before i did it with radclient i tried to search another way and look into pyrad.. But project is kinda..not alive.
The issue about status query (https://github.com/wichert/pyrad/issues/27) still not answered. Bugs from 2013 not fixed..

**Comment by ktsaou** [comment]
hm... you are right.

I see that other data collectors also use `radclient`: https://github.com/kshcherban/collectd-freeradius/blob/master/freeradius.py

**Comment by l2isbad** [comment]
> add it to the wiki page of all plugins

will do later

**Comment by ktsaou** [comment]
> will do later

perfect. let me know when you do it, to merge this.

**Comment by l2isbad** [comment]
Done!

**Comment by ktsaou** [comment]
merged!

**Pull request merged**
