### PR TITLE
isc_dhcp fix: do not include leases without "ends"

### PR DESCRIPTION
**Pull request by l2isbad**
fixes https://github.com/firehol/netdata/issues/3442

@HammaBamma 
please check it

### CODE REVIEW

**Comment by ktsaou** [comment]
let me know when ready to merge...

**Comment by HammaBamma** [comment]
It works on my primary server as expected, just not on the backup server. I'm going to look further into the isc-dhcpd-server configs, to see why it does the backup state, and if there's a method for it to do some other output. Also, I'd be curious to see if the output changes once the server fails over, and then the script would read it correctly, and start outputting. Thus I could just add both service checks, and one as 0 until it's failed over.. ? Who knows... But thanks for this awesome tool and the quick replies.. I'm going to implement this for a few of my upcoming events and evangelize this!

**Comment by l2isbad** [comment]
@ktsaou merge then

**Comment by ktsaou** [comment]
merged! thanks!

**Pull request merged**
