### PR TITLE
web_log: add support for empty requests

### LINKED ISSUE #2201: web_log reports unmatched lines
web_log plugin reports unmatched lines.

This is my log:

```txt

37.159.226.69 - - [18/May/2017:12:52:15 +0200] "-" 408 0 "-" "-"

```

### PR DESCRIPTION
**Pull request by l2isbad**
fixes https://github.com/firehol/netdata/issues/2675
fixes #2201

@MartijnBraam
I did some changes can you test it?

### CODE REVIEW

**Comment by MartijnBraam** [comment]
My server only seems to create the failing log lines while under high load, I'll add your code and report back when I see the errors again

**Comment by ktsaou** [comment]
so, shall we merge this?

**Comment by l2isbad** [comment]
yes

**Comment by ktsaou** [comment]
merged! thanks!

**Pull request merged**
