### PR TITLE
New python d plugin

### PR DESCRIPTION
**Pull request by l2isbad**
WIP
there is still a lot to do
~~not really~~ tested 😄 
fixes https://github.com/firehol/netdata/issues/2757

Make sure all works on
- [x] python 2.7+
- [x] python 3+

Make sure all framework services works/fix them if needed
- [X] ExecutableService
- [X] LogService
- [X] MySQLService
- [X] SocketService
- [X] UrlService

Make sure all modules works/fix them if needed (no exception during initialization, check, create)
- [X] apache
- [X] bind_rndc
- [x] chrony 
- [x] couchdb 
- [x] cpuidle
- [X] cpufreq
- [X] dns_query_time
- [X] dovecot
- [x] elasticsearch
- [X] example
- [X] exim
- [X] fail2ban
- [X] freeradius
- [X] go_expvar
- [x] haproxy
- [X] hddtemp
- [X] ipfs
- [X] isc_dhcpd
- [X] mdstat
- [X] memcached
- [X] mongodb
- [X] mysql
- [X] nignx
- [X] nsd
- [X] ovpn_status_log (fixes https://github.com/firehol/netdata/issues/2842)
- [X] phpfpm
- [X] postfix
- [x] postgres
- [x] powerdns
- [x] rabbitmq
- [X] redis
- [X] retroshare
- [X] samba
- [X] sensors
- [X] squid
- [X] smartd_log (fixes https://github.com/firehol/netdata/issues/2889)
- [X] tomcat
- [x] varnish
- [x] web_log

Then
- [x] Modules configuration files update ()
- [x] more informative errors
- [X] chart variables support

### CODE REVIEW

**Comment by ktsaou** [comment]
Wow!

Can you give a few bullets of what is now different / better?

**Comment by l2isbad** [comment]
A lot of functionality was moved from python.d.plugin to reusable modules.

Now we have logger classes
https://github.com/firehol/netdata/pull/2872/commits/f06f2b329b30d0edbaf87916a1f19edded6e8cd2
which can be reused in other python plugins (libvirt)

Module/config load functionality which can be reused too
https://github.com/firehol/netdata/pull/2872/commits/fc3f21353e5efdb825faae1b47813f70fb3fb4fc

Charts and dimensions are classes now
https://github.com/firehol/netdata/pull/2872/commits/c59e0336a8838d829e16169d8167889b14bd632b
Easy to add charts/dimensions in runtime

Ordereddict shipped with netdata now 👍 

Every Service has its own file.

Python.d.plugin more clear now (it has Job, Module and Plugin classes).

The main goal was  to make changes which saves old interfaces and prepares the plugin to future changes 😄

**Comment by l2isbad** [comment]
And `autodetect_retry` implemented

**Comment by ktsaou** [comment]
nice!

**Comment by Rockstar04** [comment]
I will gladly roll this out to some of our less critical servers when its ready for some outside testing.

**Comment by ktsaou** [comment]
@l2isbad do you know if the new plugin is going to be backwards compatible with modules we are not aware of?

btw, I would like modify a bit the external plugins API to support:

1. something that will allow netdata to know the module that created each chart
2. the ability to set variables for alarms (e.g., if you can get the max connections supported by a server you will be able to set it once, and update it any time you like, so that the alarms will be able to calculate the % full).

Is it a good time to do these?

**Comment by l2isbad** [comment]
> @l2isbad do you know if the new plugin is going to be backwards compatible with modules we are not aware of?

I think yes. All the input the same - user have to define` order, definitions`, choose the framework service and redefine a `get_data` method.

Old [chart, commit, set](https://github.com/firehol/netdata/blob/master/python.d/example.chart.py) approach [works too](https://github.com/l2isbad/netdata/blob/new_python_d_plugin/python.d/python_modules/bases/collection.py#L63-L121).  But it's not preferable and i rewrite [example.chart](https://github.com/l2isbad/netdata/blob/new_python_d_plugin/python.d/example.chart.py). Now it has dynamic dimension adding. 

> Is it a good time to do these?

yes

**Comment by ktsaou** [comment]
nice progress!
chart-local variables are merged, waiting for you to bring them to life...

**Comment by l2isbad** [comment]
@ktsaou 
I added support for chart variables.

current syntax for chart variables:
```python
    'threads': {
        'options': [None, 'mysql Threads', 'threads', 'threads', 'mysql.threads', 'line'],
        'lines': [
            ['Threads_connected', 'connected', 'absolute'],
            ['Threads_created', 'created', 'incremental'],
            ['Threads_cached', 'cached', 'absolute', -1, 1],
            ['Threads_running', 'running', 'absolute'],
        ],
        'variables': [
             ['max_connections1'],  # will not be created at startup
             ['max_connections2', 9000]  # will be created at startup with a given value
         ]
}
```

> To update/set variable it's value should be returned in the `dict` that the `get_data()` method returns (with all other data). Once the variable is assigned a value it will be pushed to netdata in next `update()`



Q: Should I see the variables in /api/v1/charts?

**Comment by ktsaou** [comment]
> Should I see the variables in /api/v1/charts?

yes, of course in all 3 indexes: chart, family and host.

**Comment by ktsaou** [comment]
oops! my bad. You should see them in `/api/v1/alarm_variables?chart=CHART_NAME`.

**Comment by l2isbad** [comment]
@ktsaou @Rockstar04 please do some tests. All should work (except old `chart/commit/set` approach)

**Comment by ktsaou** [comment]
Wow! nice!
This seems huge. I don't know where to start.
Can you give a short checklist of what needs to be tested?

**Comment by l2isbad** [comment]
Everything should work after replacing the old plugin with a new one. 
1. check all your python modules is up and running after replacing
2. `autodetection_retry`

**Comment by Rockstar04** [comment]
Sorry, little late, I will merge this into my custom MySQL branch and push it out to my reserve server for testing.

**Comment by l2isbad** [comment]
> I did notice that graph lines that used to be negative

good finding! it's a bug

**Comment by Rockstar04** [comment]
I haven't pulled in those last 2 commits to my local branch, but the two servers I have rolled this out to are "randomly" (I havent spent enough time to see if there is a pattern, but it seems random) reporting Apache2 and MySQL last collected X ago alerts. When I load up netdata I dont see any gaps in the charts. If you have some suggestions or need more data from me I can dig into it more.

**Comment by l2isbad** [comment]
I enabled alarms on server with this PR and mysql/apache, let's see if i can reproduce it. Sounds strange to me - no gaps and l`ast collected X ago` alerts at the same time.

**Comment by l2isbad** [comment]
Ok, i think i found it. The problem is 
https://github.com/firehol/netdata/wiki/External-Plugins#data-collection
`microseconds` - is the number of microseconds **since the last update of the chart**.

**1.** Old plugin `microseconds` logic: 
* microseconds = START_RUN (get current time()) - LAST
* run update(microseconds)
  ... run get_date()
  ... update charts witch microseconds (which were measured before the update())
* LAST = START_RUN

So microseconds was not `since the last update of the chart` but `since the last time right before update() run`.

**2.** I change it to:

* run update()
  ... run get_data()
  ... current time = get time()
  ... microseconds = current time - LAST
 ... run update charts(microseconds)
* LAST = get current time() (right after charts update)

So it's literally `since the last update of the chart`.

Example:
update_every: 1

```python

class Service(SimpleService):
    def __init__(self, configuration=None, name=None):
        super(self.__class__, self).__init__(configuration=configuration, name=name)
        self.order = ORDER
        self.definitions = CHARTS
        self.data = dict()
        self.c = 0

    def get_data(self):
        self.c += 1
        #  RUNS 
        if self.c % 2 == 0:
            sleep(1.5)
        .....
```

<details>
<summary>OLD version debug (click) </summary

```
BEGIN example_test.random 0
SET 'random2' = 37
END

BEGIN netdata.runtime_example_test 0
SET run_time = 0
END

SET 'random1' = 97
SET 'random2' = 37
END

BEGIN netdata.runtime_example_test 999634
SET run_time = 1501
END

BEGIN example_test.random 2001482
SET 'random1' = 93
SET 'random2' = 37
END

BEGIN netdata.runtime_example_test 2001482
SET run_time = 0
END

BEGIN example_test.random 998632
SET 'random1' = 96
SET 'random2' = 37
END

BEGIN netdata.runtime_example_test 998632
SET run_time = 1500
END

BEGIN example_test.random 1999778
SET 'random1' = 19
SET 'random2' = 37
END

BEGIN netdata.runtime_example_test 1999778
SET run_time = 0
END

```
</details>

Microseconds: 999634, 2001482, 998632, 1999778 - interval between update() runs

---

<details>
<summary>NEW version debug (click) </summary

```
BEGIN example_test.random 0
SET 'random3' = 70
END

BEGIN netdata.runtime_example_test 0
SET run_time = 0
END

BEGIN example_test.random 2501698
SET 'random3' = 77
END

BEGIN netdata.runtime_example_test 2501698
SET run_time = 1501
END


BEGIN example_test.random 498176
SET 'random1' = 21
SET 'random3' = 77
END

BEGIN netdata.runtime_example_test 498176
SET run_time = 0
END

BEGIN example_test.random 2500459
SET 'random1' = 21
SET 'random3' = 77
SET 'random2' = 20
END

BEGIN netdata.runtime_example_test 2500459
SET run_time = 1500
END

BEGIN example_test.random 498868
SET 'random1' = 21
SET 'random3' = 76
SET 'random2' = 20
END

BEGIN netdata.runtime_example_test 498868
SET run_time = 0
END
```

</details>

Microseconds: 2501698, 498176, 2500459, 498868 - interval between charts update

---

But for some reason something is wrong in the new version

> I have rolled this out to are "randomly" (I havent spent enough time to see if there is a pattern, but it seems random) reporting Apache2 and MySQL last collected X ago alerts


Every N iterations `last collected secs` increases by 1 seconds
now -> 00:00:01 -> 00:00:02 -> and so on
Any ideas?

**Comment by l2isbad** [comment]
@Rockstar04 
i believe it fixed now, please pull new commits.
No problems for me since last update so far

**Comment by Rockstar04** [comment]
I pushed this out to both servers this morning and so far so good.

**Comment by ktsaou** [comment]
In general, the position of the timer is irrelevant, as long as it counts the whole iteration. So, netdata wants the total time for a full iteration. No time should be lost. 

The position of the timer may affect only the first iteration (it might be incomplete), but the specification says that for the first iteration you should push the value 0, so netdata will align the plugin to the current time. After the first iteration, all non-zero values should give the time needed for a single loop, everything included.

**Comment by ktsaou** [comment]
So, this is wrong:

```
run update()
... run get_data()
... current time = get current time()
... microseconds = current time - LAST
... run update charts(microseconds)
LAST = get current time() (right after charts update)(edit: this was wrong)
```

The whole idea is that for the calculation of microseconds, only one call to `get current time()` should be used. And yours, has 2.

**Comment by ktsaou** [comment]
Edited my answer above.

**Comment by l2isbad** [comment]
Ok, looks like it ready. I tested it on debian8/9/manjaro. All works ok.

new features:
 * chart variables
 * autedetection_retry

@ktsaou please check it (new features)

do i need to add something else?

**Comment by ktsaou** [comment]
nice!

I tried it on fedora 26 and gentoo. It works.

One question (I asked before, but let me check again): My only concern is if existing custom python modules, will work with the new python.d.plugin.

If they will, I think this is ready to be merged.
If they won't, we have to check 2 things:

1. Can we support them? This should be the best solution.
2. If we can't support them, is there anything we can do to make the transition easier?

**Comment by l2isbad** [comment]
> My only concern is if existing custom python modules, will work with the new python.d.plugin.

They will. Almost all my fixes to the existing modules were import fixes.

from
```python
from base import UrlService
```
to
```python
from bases.FrameworkServices.UrlService import UrlService
```

Old style import will work too
https://github.com/l2isbad/netdata/blob/new_python_d_plugin/python.d/python_modules/base.py

`base.py `will be removed in future releases but for now it will be used for backward compatibility.

**Comment by ktsaou** [comment]
perfect!
So, merge?

**Comment by l2isbad** [comment]
yes

**Comment by ktsaou** [comment]
merged it!

We should now stay a bit alert, in case people report issues with it.

@l2isbad you rock!

**Pull request merged**
