### PR TITLE
Haproxy module

### PR DESCRIPTION
**Pull request by l2isbad**
Works via url and via unix socket (actually there is a bug in [base.py](https://github.com/firehol/netdata/blob/master/python.d/python_modules/base.py#L698-L699) that prevents to obtain all data from socket, i will make a pr with fix later)

Should be tested.
Works ok in my lab env.
If **url is specified** plugin uses `UrlService`, if **no url and socket is specified** - `SocketService`

### CODE REVIEW

**Comment by jurgenhaas** [comment]
Nice work! It is doing what it should on my 4 proxy hosts.

**Comment by l2isbad** [comment]
@jurgenhaas Any suggestion?
1. Option to add via conf file 'Servers' family (bin, bout, scur, qcur for all backend servers) ?
2. More health charts? (more health charts = mor alarms) (i see there is server uptime, check time in ms, downtime in ms)

Also i think preferred method to poll is via socket. Can you check if it is working properly?

**Comment by jurgenhaas** [comment]
> 1. Option to add via conf file 'Servers' family (bin, bout, scur, qcur for all backend servers) ?

Not sure if that should also be added. You could argue that monitoring the health of the "Servers" should be done by NetData on those hosts and not through HaProxy.

> 2. More health charts? (more health charts = more alarms) (i see there is server uptime, check time in ms, downtime in ms) ?

A pretty good reference is from [Datadogs](https://www.datadoghq.com/blog/monitoring-haproxy-performance-metrics/) and you may want to follow their guide with the various aspects.

> 3. What about default alarm?

Looks like the datadogs article has some advise for this too.

**Comment by l2isbad** [comment]
Well the article is very good, but i dont use `haproxy`. so i'm lazy to read it)
I think i will add an alarm for up->down server and im done here.
All other stuff can be added later if someone will need to.

**Comment by ktsaou** [comment]
nice work @l2isbad . Let me know when you want this merged.

**Comment by l2isbad** [comment]
If there are no suggestions i think it is ready.

**Comment by ktsaou** [comment]
merged!

**Comment by ktsaou** [comment]
hm... I forgot the wiki...
@l2isbad can you update it?

**Comment by l2isbad** [comment]
sure!

**Comment by jurgenhaas** [comment]
Sorry, I haven't tested the alarms before and just got to that now. I realized that all my backends are reported as being down and I wonder why. They all work well and none of them is down, but the chart reports a value=1 for ALL of them. Not sure what the plugin expects and why it thinks they are down. Any idea?

**Comment by l2isbad** [comment]
@jurgenhaas 
Code is
https://github.com/firehol/netdata/blob/master/python.d/haproxy.chart.py#L163
What is your backend server status?
Is it not UP?

**Comment by l2isbad** [comment]
I got it! if there is no check
```
  server server1_1 127.0.0.1:81
  server server1_2 127.0.0.2:81 check
  server server1_3 127.0.0.3:81 check
```

status is not UP

@jurgenhaas want to make a PR to fix this? (UP->DOWN)

**Comment by jurgenhaas** [comment]
Looking at the attached CSV I would say they are UP but still the plugin shows a 1 for every backend in the health chart. No idea what that is, you?

[stat.csv.txt](https://github.com/firehol/netdata/files/699760/stat.csv.txt)

**Comment by l2isbad** [comment]
no check guy
screenshot_20170112_034321

**Comment by l2isbad** [comment]
all those servers are not UP in your CSV

**Comment by jurgenhaas** [comment]
The servers are not checked, but the backends are on UP. And I thought that status was on backends at not servers. I'm confused.

**Comment by l2isbad** [comment]
Well i am haproxy noob i thought backend = groups of servers. If servers from group is DOWN - alert

**Comment by l2isbad** [comment]
Anyway 
Can you change
!= 'UP' to = 'DOWN'
here
https://github.com/firehol/netdata/blob/master/python.d/haproxy.chart.py#L163
and check after this

**Comment by jurgenhaas** [comment]
I have changed that line 163 to this instead:

```
return server['# pxname'] == back_ends[_]['# pxname'] and server['status'] != 'UP' and server['status'] != 'no check'
```

That's working too.

**Comment by l2isbad** [comment]
Yep, but if server['status'] = UP it alarm will be triggered again
We need to catch all DOWN servers so the right decision is
`server['status'] == 'DOWN'`

it would be great if you did a PR to fix bug you found it!

**Comment by l2isbad** [comment]
i am wrong too tired don't see all your code (
still one check > two checks
so i vote for == DOWN

**Comment by jurgenhaas** [comment]
That's true, on the other hand, the kown states are "UP" and "no check" and those 2 are OK for us. If the status report would provide anything other than those 2, we would not recognize that as a potential problem. That's why I thought this explicit method would be more safe.

**Comment by l2isbad** [comment]
It makes sense. I am ok with that!

**Comment by ktsaou** [comment]
Please also put a `calc` line on the alarm definition, to be sure what `$this` is evaluated to.

**Comment by l2isbad** [comment]
```
lookup: average -10s
calc: $his
    crit: $this > 0
```
like that?
I thought that this is not necessary since there is no calculation

> This expression is evaluated just after the lookup. Its purpose is to apply some calculation before using the value looked up from the db.

**Comment by ktsaou** [comment]
hm... I can't recall what is the default for `$this`. I think that if neither `calc` nor `lookup` is given, the alarm is considered invalid and is not processed.

Can you see the alarm badge? What value does it report? Is it green? (if it is black or grey, it is not evaluated).

I don't know what this chart shows, so I cannot give you directions. Can you post an image of it?

**Comment by l2isbad** [comment]
lookup is given
https://github.com/firehol/netdata/blob/master/conf.d/health.d/haproxy.conf#L5
works ok in my lab env

**Comment by l2isbad** [comment]
screenshot_20170112_062501

**Comment by ktsaou** [comment]
hm... interesting...
Could you please also the chart?

**Comment by l2isbad** [comment]
The chart is also one the same screen (on the right side - backend1 value `1`, backend2 value `2`, sum = 3)

**Comment by l2isbad** [comment]
@jurgenhaas https://github.com/firehol/netdata/pull/1549

**Comment by ktsaou** [comment]
@l2isbad then it works ok as-is (I didn't recall that the default `$this` is the sum of all dimensions). Sorry...

**Comment by robbat2** [comment]
@l2isbad does this correctly handle the `nbprocs > 1` case? Any comments on using it with that?

**Comment by l2isbad** [comment]
@robbat2 What do you mean? Connect to several stats page (or sockets?) and graph summary stats? The short answer is no.
The plugin was made on @jurgenhaas and @hameno requests.

**Pull request merged**
