### PR TITLE
lighttpd status

### PR DESCRIPTION
**Pull request by xuefer**
lighttpd uses similar but yet different stats page

### CODE REVIEW

**Comment by ktsaou** [comment]
Thanks!

Can you post the whole output of lighttpd taken with `curl` or `wget`?
It would be good for reference.

@paulfantom I guess you agree with this change. Yes?

**Comment by xuefer** [comment]
http://demo4.0.tryton.org/server-status?auto

Total Accesses: 254218
Total kBytes: 7338769
Uptime: 311081
BusyServers: 1
IdleServers: 127
Scoreboard: h_______________________________________________________________________________________________________________________________

**Comment by ktsaou** [comment]
Thanks! The change you have made is small, but let's give a some time to @paulfantom to review it.

**Comment by paulfantom** [comment]
It looks ok. However there is one issue, it will still show web server statistics as "apache" stats, which for me is unacceptable.

**Comment by ktsaou** [comment]
We could copy the module and add it as lighttpd, but then 2 modules will autodetect the same server. I don't think there is any other solution to this problem, apart from mentioning it at the docs the config file, etc.

As I see it, this problem already exists and it is even worse, since a few values are not collected...

**Comment by ktsaou** [comment]
So, unless anyone has a better idea, I am prepared to merge this.

**Comment by paulfantom** [comment]
We can change chart naming, from "apache" to "web server", it would solve this problem.

**Comment by ktsaou** [comment]
> We can change chart naming, from "apache" to "web server", it would solve this problem.

hm... still not perfect (i.e. "a web server and an nginx on this machine").

What if we could detect based on the collected metrics if it is apache or lighttpd and update the proper chart? I mean the module could have 2 sets of dimensions and 2 sets of charts, one for apache and one for lighttpd. Based on the collected metrics it should update one of the two.

**Comment by ktsaou** [comment]
or it could somehow rename the python job to be `lighttpd_*`.

**Comment by paulfantom** [comment]
@xuefer Can you test if adding this custom check method:
```py
    def check(self):
        if not UrlService.check():
            return False
        # check if it is lighttpd server
        if 'IdleServers' in self._get_raw_data():
            name = self.chart_name.split('_')[1:]
            self.chart_name = 'lighttpd_' + '_'.join(name)
        return True
```
to `apache.chart.py` will change chart name when running with `lighttpd` data?

**Comment by ktsaou** [comment]
Is this ready to be merged?

**Pull request closed without merging**
