### PR TITLE
smartd_log, varnish modules improvements + other minor bugfixes

### PR DESCRIPTION
**Pull request by l2isbad**
WIP

- [X] fixes https://github.com/firehol/netdata/issues/3017
- [X] fixes https://github.com/firehol/netdata/issues/3041
- [X] fixes https://github.com/firehol/netdata/issues/3043
- [x] fixes https://github.com/firehol/netdata/issues/3054

@skibbipl

feel free to test 😄 

> Make the smartd plugin "smarter". Parse smartd_log files only if they're updated in the last X (configurable) days. 

Implemented. In minutes. 'age' option. Default is ~~60~~ 30.

> Allow plugin to detect external drives when they're connected to the machine

implemented

### CODE REVIEW

**Comment by l2isbad** [comment]
@ktsaou `codeclimate` setting seem wrong

**Comment by ktsaou** [comment]
> @ktsaou codeclimate settings seem wrong

yes I know. They changed the format of the config file. I have disabled these checks, but still it seems it enables them.

Making a PR now.

**Comment by ktsaou** [comment]
merge?

**Comment by l2isbad** [comment]
> merge?

@ktsaou ye

**Comment by ktsaou** [comment]
merged! thanks!

**Pull request merged**
