### PR TITLE
Create phpfpm.chart.sh

### PR DESCRIPTION
**Pull request by safeie**

### CODE REVIEW

**Comment by ktsaou** [comment]
Nice! Thank you for your contribution!
Can I make a suggestion?

**Comment by safeie** [comment]
yes, please.

**Comment by ktsaou** [comment]
Everything is very well done, except this line:

```sh
phpfpm_url="http://nginx.server/php-status"
```

I believe it should be:

```sh
phpfpm_url="http://localhost/php-status"
```

for auto-detection to work. So, if the user has already enabled `php-status` on its local nginx, it will work without any configuration.

**Comment by ktsaou** [comment]
Also, I would appreciate some information about this plugin, a screenshot, etc, to add it to the wiki. Anything you would like your users to know, will do.

Just posted here in a comment and I'll create the wiki page.

**Comment by glensc** [comment]
in [php-src](https://github.com/php/php-src/blob/php-7.0.5/sapi/fpm/status.html.in#L99) default is just `/status`, so it should be `phpfpm_url="http://localhost/status"`

it may be changed with `pm.status_path` in fpm config, i changed mine to `/fpm-status` as `/status` is waaaaay to generic. so maybe some more than one test url support?

**Comment by safeie** [comment]
1. i already change default, phpfpm_url="http://locahost/status"
2. my server php status, may be can help you. http://115.29.188.64/pageend-status
thanks.

**Comment by safeie** [comment]
e, let me try to support multi urls

**Comment by safeie** [comment]
@glensc i commit, support multi url now.

**Comment by glensc** [comment]
not directly related to this PR, but @ktsaou shouldn't all `curl` invocations be `curl -Ss` in plugins? as it would hard to diagnose problems if all curl errors are silently discarded

**Comment by ktsaou** [comment]
@safeie very nicely done! Bravo!

> shouldn't all curl invocations be curl -Ss in plugins? as it would hard to diagnose problems if all curl errors are silently discarded

You are right. I'll merge this and fix them all.

**Comment by ktsaou** [comment]
Added wiki page: https://github.com/firehol/netdata/wiki/phpfpm.chart.sh

I would appreciate some information about this plugin, a screenshot, etc, to add it to the wiki. Anything you would like your users to know, will do.

**Comment by epema** [comment]
Hi,
How can I add multiple pools from php-fpm?
I have done this:
`phpfpm_check() {
        phpfpm_urls['local']="http://localhost/status"
        phpfpm_urls['site2']="http://site1.example.com/status"
        phpfpm_urls['site3']="http://site2.example.com/status"
`
all status pages are working, and the /charts.d/phpfpm.chart.sh executing properly.
The problem is that I don't see the chart for site2 and site3 on the page.
What else has to be done? Thanks!

**Pull request merged**
