### PR TITLE
Smartd log plugin

### PR DESCRIPTION
**Pull request by l2isbad**
Initial version of smartd log plugin. https://github.com/firehol/netdata/issues/840
Thx to @ktsaou @simonnagl  for recommendation to prase smartd log files (didn't know about it!)
@vorph1 SMART_ATTR dict and _get_disk_lines (create_lines) method is from your code. So I added you to the authors.

Should be tested.

The logic is simple:
1. Finds all log files in `/path/to/smartd_logs`
2. Reads only the last line, parse and pass result to netdata
3. Check size. If current size = prev size - no reason to parse log file. Pass to netdata previous data.

So it reads log files (only the last line, file size does not matter) only when smartd append new data or logrotate recreate logfile.

> Anyway i dont understand one thing - which values do we need? Normalized or raw? 

Normilized is default. You can set raw in conf file.

There is a lot of smart attributes!

['1', '4', '5', '7', '9', '12', '193', '194', '197', '198', '200'] are default. You can add other attributes in conf file.

@vorph1 Can you help to test this one?

### CODE REVIEW

**Comment by vorph1** [comment]
You need to add the conf and chart.py files to makefiles, otherwise it works fine.

**Comment by ktsaou** [comment]
merge?

**Comment by l2isbad** [comment]
@ktsaou i think yes.

**Comment by ktsaou** [comment]
ok nice, I am merging it.
Any ideas how to configure codacy for python? I added you as a developer to it, so if you can find some time, play with it - it seems nice.

**Comment by l2isbad** [comment]
> Any ideas how to configure codacy for python?

first time I hear about it..

> if you can find some time, play with it - it seems nice.

ok. thx!

**Pull request merged**
