### PR TITLE
Adding HaProxy and Varnish to applications.

### PR DESCRIPTION
**Pull request by Flums**

### CODE REVIEW

**Comment by paulfantom** [comment]
@Flums Do you run Varnish or maybe you have some information on how to get metrics from it?

**Comment by LeeNX** [comment]
I run a few varnish servers and could help with testing a netdata varnish agent.  
  
Place to start looking at a basic agent - https://github.com/varnish/vagent2 ?

**Comment by ktsaou** [comment]
Check these:

- https://www.varnish-cache.org/trac/wiki/StatsExplained
- https://www.varnish-cache.org/docs/trunk/reference/varnish-counters.html

>  either `varnishstat -1` or by telneting to the management port and issuing the command stats. The output is identical.

I would go with a python module, much like redis: https://github.com/firehol/netdata/blob/master/python.d/redis.chart.py

@paulfantom do you agree?

**Comment by paulfantom** [comment]
Seems good.

**Pull request merged**
