### PR TITLE
added opentsdb host tags option;

### LINKED ISSUE #2217: Opentsdb multiple keys
Hi 

Is it possible to add multiple keys to the backend part for opentsdb right now the only key shipped to influxdb is the host need keys like
Environment
Location
Group
and so on

### PR DESCRIPTION
**Pull request by ktsaou**
fixes #2217 

Added option:

```
[backend]
    opentsdb host tags = space separated list of TAG=VALUE
```

The above setting is only available when the backend is set to `opentsdb`

### CODE REVIEW

**Comment by ktsaou** [comment]
Changed with PR #2354 to be propagated with metrics streaming.

**Comment by kmonsoor** [comment]
is it possible to do something like this with `Graphite` format backend-writes to InfluxDB? As expected, using `host tags` in the current conf, it don't work.

It would be particularly helpful to filter on the queries from Grafana end.
Thanks in advance.

**Comment by ktsaou** [comment]
Hi,

For what I read, graphite does not support host tags: https://graphite.readthedocs.io/en/latest/feeding-carbon.html#the-plaintext-protocol

If it did, it would be pretty simple to send them...

**Comment by ktsaou** [comment]
I read the influxdb supports the opentsdb protocol: https://docs.influxdata.com/influxdb/v1.3/data_sources/opentsdb/

So, just switch to opentsdb to get host tags in influxdb...

**Comment by kmonsoor** [comment]
@ktsaou thanks a lot for the reply. Switching to OpenTSDB should work in my case. 

I'm currently using Netdata --> InfluxDB solution to monitor 20+ instances. So, have to try out a migrating MVP for Graphite --> OpenTSDB.

**Pull request merged**
