### PR TITLE
Nginx plus

### PR DESCRIPTION
**Pull request by l2isbad**
~~WIP~~ (not a `nginx plus` user)

fixes https://github.com/firehol/netdata/issues/3049

[snapshot](https://github.com/firehol/netdata/files/1645530/netdata-workPc-20180119-153357-480.gz)

@kmhagan

### CODE REVIEW

**Comment by ktsaou** [comment]
this is nice!
If I recall correctly, only the streaming charts are missing. Right?

Also, I see auto-detection is disabled. Will it interfere with the plane `nginx` plugin?

**Comment by l2isbad** [comment]
> If I recall correctly, only the streaming charts are missing. Right?

https://github.com/firehol/netdata/issues/3049#issuecomment-349435486

> Also, I see auto-detection is disabled. Will it interfere with the plane nginx plugin?

No, but i don't know what default url should be. [http://127.0.0.1:8080/status](https://www.nginx.com/products/nginx/live-activity-monitoring/)?

**Comment by ktsaou** [comment]
> No, but i don't know what default url should be. http://127.0.0.1:8080/status?

It is not the standard http/https port? So nginx+ opens a new port for statistics?

**Comment by l2isbad** [comment]
you are right

**Comment by l2isbad** [comment]
@ktsaou we can merge it or wait @kmhagan. Maybe he has some comments as a `nginx plus` user.

**Comment by l2isbad** [comment]
@kmhagan current implementation doesn't support adding upstreams/upstream peers/servers zones in runtime (`netdata` restart required). Since it's initial version i think it's ok and we can add the support later 😄

**Comment by ktsaou** [comment]
So, merge?

**Comment by l2isbad** [comment]
yes

**Comment by ktsaou** [comment]
merged! perfect!

**Comment by ktsaou** [comment]
infographic logo: 
image

**Pull request merged**
