### PR TITLE
python megacli plugin

### LINKED ISSUE #3757: Do you have in plan to implement Megacli (hardware RAID) support metrics ?
Hi,
this is question only.
Do you have in plan to implement MegaCLI output for hardware RAID support and battery on hardware raid.
This is very useful for many. 
Thank's !

### PR DESCRIPTION
**Pull request by l2isbad**
fixes #3757 

yo @petarkozic

please test it

make sure that the `megacli` command can be executed by the `netdata` user

```bash
sudo su -s /bin/bash netdata
megacli -LDPDInfo -aAll
```

This is wip version so i am open to any suggestion :smile: 

screenshot_20180704_234538

___

todo:

- [x] battery stats (`megacli -AdpBbuCmd -a0`)
- [x] alarm on `megacli.adapter_degraded` chart
- [x] alarm on battery charts

### CODE REVIEW

**Comment by Ferroin** [comment]
So, I can't really test this myself (the last system I had access to with a MegaRAID card in it died over 2 years ago), but given what was discussed in #3757 and what I know of the CLI interface, this appears to do what was requested in the aforementioned issue.

**Comment by petarkozic** [comment]
@l2isbad 
I can't start megacli as netdata user. I can only with
`sudo megacli -LDPDInfo -aAll`

**Comment by l2isbad** [comment]
Done @petarkozic. Now it runs `sudo -n megacli ....`. For some reason i feel this is wrong.  @Ferroin What do you think?

Please add to `sudoers`
```
netdata ALL = (root) NOPASSWD: /path/to/megacli
```

and test it one more time

**Comment by petarkozic** [comment]
Yes, works like a charm ! Great job !

With this sudoers setup I think this is much safer way, becuase now we can limit user netdata which command can run.

For me this works good ! Thank you @l2isbad

**Comment by l2isbad** [comment]
@petarkozic

1. Please post here plugin chart from `python.d` and cpu chart from `Application` (highlight pyhton.d.plugin dimension)

2. About battery stats. What charts do we need?

**Comment by l2isbad** [comment]
Hm, [i see](https://github.com/firehol/netdata/issues/3757#issuecomment-398721388) it takes 11ms to run `time megacli -LDPDInfo -aAll > /dev/null`. And 55 ms in avg on your screenshot. 

Please run as netdata user, let's check whether `sudo` command adds additional 40ms
1. `time megacli -LDPDInfo -aAll > /dev/null`
2. `time sudo -n megacli -LDPDInfo -aAll > /dev/null`

**Comment by petarkozic** [comment]
@l2isbad 
> time megacli -LDPDInfo -aAll > /dev/null
```root@lab1:~# time megacli -LDPDInfo -aAll > /dev/null
real	0m0.044s
user	0m0.000s
sys	0m0.007s
```

> time sudo -n megacli -LDPDInfo -aAll > /dev/null
```root@lab1:~# time sudo -n megacli -LDPDInfo -aAll > /dev/null
real	0m0.049s
user	0m0.009s
sys	0m0.005s
```

**Comment by l2isbad** [comment]
> Here is very useful battery capacity chart-s. Alongside where we can see currently capacity we can see when capacity of our battery fall down, that is useful info for us that we need to change battery.

1 chart **Relative State of Charge: 91 %** ?

**Comment by petarkozic** [comment]
> 1 chart Relative State of Charge: 91 % ?
Yes, this one, and maybe usefull this:

**Cycle Count: 62**

That is enough. 

Please, pay attention, every Adapter can have it own battery.
As you can see in command output `megacli -AdpBbuCmd -a0` :


**BBU Capacity Info for Adapter: 0**

  Relative State of Charge: 98 %
  Absolute State of charge: 56 %
  Remaining Capacity: 1060 mAh
  Full Charge Capacity: 1083 mAh
  Run time to empty: Battery is not being charged.
  Average time to empty: Battery is not being charged.
  Estimated Time to full recharge: Battery is not being charged.
  Cycle Count: 62
Max Error = 7 %
Remaining Capacity Alarm = 190 mAh
Remining Time Alarm = 10 Min

**BBU Design Info for Adapter: 0**

  Date of Manufacture: 08/04, 2008
  Design Capacity: 1900 mAh
  Design Voltage: 3700 mV
  Specification Info: 49
  Serial Number: 4568
  Pack Stat Configuration: 0xe4bc
  Manufacture Name: SANYO
  Firmware Version   :
  Device Name: DLU8735
  Device Chemistry: LION
  Battery FRU: N/A
  Transparent Learn = 0
  App Data = 0

**BBU Properties for Adapter: 0**

  Auto Learn Period: 90 Days
  Next Learn time: Wed Jul 11 14:48:47 2018
  Learn Delay Interval:0 Hours
  Auto-Learn Mode: Enabled

**Comment by Ferroin** [comment]
@l2isbad I think using something for privilege elevation is fine, and would actually love to see some standardized method for that in the `ExecutableService` framework.  Hard-coding `sudo` for that is bad though.  Ideally, it should be something where the user can specify what command to run for privilege elevation, that way users don't have to use `sudo`, and could, for example, use `doas`, or even possibly `su` if they're really crazy.

**Comment by l2isbad** [comment]
@petarkozic battery stats added, it's additional call to `megacli` so it off by default (uncomment `battery_stats: yes`)

**Comment by petarkozic** [comment]
@l2isbad 
I have parse error for Battery. Below you can see debug message. 
I tried to start `/usr/bin/sudo -n /usr/sbin/megacli -AdpBbuCmd -a0` as netdata user and command works.

```
2018-07-06 10:33:57: python.d INFO: plugin: main: Using python 2
2018-07-06 10:33:57: python.d DEBUG: plugin: main: module load source: 'megacli' => [OK]
2018-07-06 10:33:57: python.d DEBUG: plugin: main: module load config: 'megacli' => [OK]
2018-07-06 10:33:57: python.d DEBUG: plugin: main: job initialization: 'megacli megacli' => ['OK']
2018-07-06 10:33:57: python.d DEBUG: plugin: main: module status: 'megacli' => [OK] (jobs: 1)
2018-07-06 10:33:57: python.d ERROR: megacli: megacli: failed to parse "/usr/bin/sudo -n /usr/sbin/megacli -AdpBbuCmd -a0" output
2018-07-06 10:33:57: python.d INFO: megacli: megacli: check() => [OK]
CHART netdata.runtime_megacli '' 'Execution time for megacli' 'ms' 'python.d' netdata.pythond_runtime line 145000 5
DIMENSION run_time 'run time' absolute 1 1
```

**Comment by l2isbad** [comment]
Ok, please post here full output from `megacli -AdpBbuCmd -a0`.

It works for me on https://github.com/firehol/netdata/issues/3757#issuecomment-398669410 output

**Comment by petarkozic** [comment]
Here is:

```
BBU status for Adapter: 0

BatteryType: BBU
Voltage: 4002 mV
Current: 0 mA
Temperature: 27 C
Battery State: Optimal
BBU Firmware Status:

  Charging Status              : None
  Voltage                                 : OK
  Temperature                             : OK
  Learn Cycle Requested	                  : No
  Learn Cycle Active                      : No
  Learn Cycle Status                      : OK
  Learn Cycle Timeout                     : No
  I2c Errors Detected                     : No
  Battery Pack Missing                    : No
  Battery Replacement required            : No
  Remaining Capacity Low                  : No
  Periodic Learn Required                 : No
  Transparent Learn                       : No
  No space to cache offload               : No
  Pack is about to fail & should be replaced : No
  Cache Offload premium feature required  : No
  Module microcode update required        : No


GasGuageStatus:
  Fully Discharged        : No
  Fully Charged           : No
  Discharging             : Yes
  Initialized             : Yes
  Remaining Time Alarm    : No
  Discharge Terminated    : No
  Over Temperature        : No
  Charging Terminated     : No
  Over Charged            : No
Relative State of Charge: 94 %
Charger Status: Complete
Remaining Capacity: 1023 mAh
Full Charge Capacity: 1083 mAh
isSOHGood: Yes
  Battery backup charge time : 0 hours

BBU Capacity Info for Adapter: 0

  Relative State of Charge: 94 %
  Absolute State of charge: 54 %
  Remaining Capacity: 1023 mAh
  Full Charge Capacity: 1083 mAh
  Run time to empty: Battery is not being charged.
  Average time to empty: Battery is not being charged.
  Estimated Time to full recharge: Battery is not being charged.
  Cycle Count: 62
Max Error = 7 %
Remaining Capacity Alarm = 190 mAh
Remining Time Alarm = 10 Min

BBU Design Info for Adapter: 0

  Date of Manufacture: 08/04, 2008
  Design Capacity: 1900 mAh
  Design Voltage: 3700 mV
  Specification Info: 49
  Serial Number: 4568
  Pack Stat Configuration: 0xe4bc
  Manufacture Name: SANYO
  Firmware Version   :
  Device Name: DLU8735
  Device Chemistry: LION
  Battery FRU: N/A
  Transparent Learn = 0
  App Data = 0

BBU Properties for Adapter: 0

  Auto Learn Period: 90 Days
  Next Learn time: Wed Jul 11 14:48:47 2018
  Learn Delay Interval:0 Hours
  Auto-Learn Mode: Enabled

Exit Code: 0x00
```

**Comment by l2isbad** [comment]
@petarkozic 
i believe it's fixed now

**Comment by l2isbad** [comment]
btw @petarkozic please suggest some alarms for battery, if i understand it right we need alarms for both charts (relative charge and cycle count)

**Comment by l2isbad** [comment]
What about media errors/ predictive failures?

**Comment by petarkozic** [comment]
> What about media errors/ predictive failures?

We need to have alert for any Media and Predictive errors.

**Comment by l2isbad** [comment]
@petarkozic alarms added, are we done with this? :smile:

**Comment by petarkozic** [comment]
Great job @l2isbad ! Thank you very much. Yes, we done with this ! 👍

**Comment by ktsaou** [comment]
nice!
merge?

**Comment by l2isbad** [comment]
> merge?

yes

**Comment by ktsaou** [comment]
merged! thank you!

**Pull request merged**
