### PR TITLE
Postgres : replslot and wal writes charts

### PR DESCRIPTION
**Pull request by anayrat**
Hello,
New charts to monitor wal files keeped for replication_slot, replslots files used for logical replication and  a chart to measure wal_writes.

selection_031
selection_030

I also find an error in unit for stat_bgwriter* metrics.

I you are ok, I will add help in dashboard_info.js

TODO : 

* [x] : complete dashboard_info.js

Regards,

### CODE REVIEW

**Comment by l2isbad** [comment]
@anayrat 
[Did you test it](https://github.com/firehol/netdata/pull/3400#issuecomment-366178598)?

**Comment by anayrat** [comment]
Yes, that's how I got screenshots above.

I'm not very sure about this part : https://github.com/firehol/netdata/pull/3530/files#diff-5ef060e57a8343e0b90f4fc5edb2cc9eR527

It works but maybe it is not correctly written.

**Comment by anayrat** [comment]
Oh, I forgot to remove this line:
```
self.error('Adrien: %s - %s - %s' % (self.old_lsn,self.current_lsn,self.wal_write))
```
Sorry, I'll remove it.

**Comment by l2isbad** [comment]
> screenshots above
i mean did you test it with different version of `postgres`.

> It works but maybe it is not correctly written

Well, if it works it is ok for now :smile:

**Comment by anayrat** [comment]
Yes I testedon  primary server with 9.3 to 10 and on standby with 9.6 and 10.

**Comment by ktsaou** [comment]
So, merge?

**Comment by l2isbad** [comment]
@ktsaou i see TODO

**Comment by ktsaou** [comment]
ok, sorry...

**Comment by anayrat** [comment]
It should be fine now ;)

**Comment by anayrat** [comment]
Please wait before merge, I found an easier way to get write rate  (thanks to @ioguix).

**Comment by anayrat** [comment]
Now it is ok. I compare current LSN with the position "0/0" instead of store previous LSN and compare current LSN with previous LSN.

https://github.com/firehol/netdata/pull/3530/commits/a1b572bd131a0bc5b59448570b3ded2d6d3b3447#diff-5ef060e57a8343e0b90f4fc5edb2cc9eR234

**Comment by ktsaou** [comment]
merged it!

**Pull request merged**
