### PR TITLE
update openrc init script

### PR DESCRIPTION
**Pull request by prometheanfire**
quote variables where able
switch to more posix double and
remove unused variables

### CODE REVIEW

**Comment by prometheanfire** [comment]
tested this, it's much more openrcified

**Comment by ktsaou** [comment]
Thanks!

@candrews I think this is ok. Do you have any comments?

**Comment by Ferroin** [comment]
Not exactly the person you mentioned, but I will comment that from the perspective of a Gentoo user who has had to deal with his share of init scripts, this does look a lot nicer and is much more consistent in terms of style with most of the scripts shipped as part of OpenRC.

**Comment by prometheanfire** [comment]
I did run this by him on irc.

    12:38 <           candrews@> prometheanfire, thanks! I don't use openrc, so this improvement is much appreciated

**Comment by ktsaou** [comment]
merged!

**Pull request merged**
