### PR TITLE
both installers download configuration netdata

### PR DESCRIPTION
**Pull request by ktsaou**
and provide a sane default when this is not possible.
also the static installer lsm states the correct version of netdata.

### CODE REVIEW

**Comment by tisc0** [comment]
\o/ testing tomorrow

**Comment by tisc0** [comment]
Tested that : 

>  curl -Ss https://my-netdata.io/kickstart-static64.sh -o netdata-kickstart-static64.sh
>  bash netdata-kickstart-static64.sh --dont-wait
Doesn't seem to be concerned by it, since the install is in /opt by default. At least no /etc/netdata DIR is created.

**Comment by ktsaou** [comment]
the static 64bit installer is built using `makeself`, which unfortunately uses a different set of command line switched. makeself prompts for acceptable of the license. It can by accepted by adding the `--accept` command line switch. Run it with `-h` to check its other options.

**Comment by tisc0** [comment]
Found it... I misused /etc/profile.d to put some script started everytime I open a session... and also when scripts like yours are really working in the system. 
The exit 1 came from a script of mine in between, thanks bash -x (We do better when we've slept a bit).
The weird is not anymore, victory of the Light again \o/

**Comment by ktsaou** [comment]
> But you might have changed something

Whatever I changed is recorded... ( open-source software does that :smile: ) but I don't think so. I don't recall changing anything on the installers since v1.8, before this PR.

**Comment by tisc0** [comment]
I admit, don't know much that deep of your code...  :)
Getting the liberty to close this issue..
Thanks again !

**Pull request merged**
