### PR TITLE
create apcupsd plugin

### PR DESCRIPTION
**Pull request by kmlucy**

### CODE REVIEW

**Comment by ktsaou** [comment]
thanks! I have a APC UPS somewhere... let me test it now...

**Comment by kmlucy** [comment]
One thing I'm not sure about is how it will behave on the lower end UPSs. I don't have one around to test, but if memory serves, you don't get as much information from apcaccess.

**Comment by ktsaou** [comment]
Well... I tested it on a very very very old `Back-UPS ES/CyberFort 500` I had spare (I think it is the definition of the low end UPS). Most values are just zero. Only `charge` and `time` have a non-zero value.

**Comment by ktsaou** [comment]
But I don't think there is anything else to show:

```sh
# apcaccess
APC      : 001,024,0637
DATE     : 2016-09-12 21:21:07 +0300
HOSTNAME : boxe
VERSION  : 3.14.14 (31 May 2016) unknown
UPSNAME  : boxe
CABLE    : USB Cable
DRIVER   : USB UPS Driver
UPSMODE  : Stand Alone
STARTTIME: 2016-08-24 05:02:19 +0300
MODEL    : Back-UPS ES/CyberFort 500
STATUS   : ONLINE
BCHARGE  : 100.0 Percent
TIMELEFT : 43.0 Minutes
MBATTCHG : 5 Percent
MINTIMEL : 3 Minutes
MAXTIME  : 0 Seconds
NUMXFERS : 3
XONBATT  : 2016-09-10 03:06:36 +0300
TONBATT  : 0 Seconds
CUMONBATT: 38 Seconds
XOFFBATT : 2016-09-10 03:06:38 +0300
STATFLAG : 0x05000008
SERIALNO : AB0218141242
FIRMWARE : 4.1.I USB FW: d1
END APC  : 2016-09-12 21:21:17 +0300
```

**Comment by kmlucy** [comment]
Is there a way to disable the zero valued charts?

**Comment by ktsaou** [comment]
You have to move chart creation (the `CHART` and `DIMENSION` lines of the script) inside the `awk` program and output them only if there are data collected for them.

I would do something like this (it is very draft):

```gawk
BEGIN {
    generated_voltage = 0;
    collected_voltage = 0;
}
/BATTV/ { collected_voltage = 1; }
END {
    if(collected_voltage == 1) {
        if(generated_voltage == 0) {
            // print CHART and BEGIN lines for voltage
            generated_voltage = 1;
        }
        // print BEGIN, SET, END lines for voltage
    }
}
```

**Comment by ktsaou** [comment]
edited my answer (had a typo on the lines to be printed)

**Comment by kmlucy** [comment]
I wan't able to get this working. If someone else wants to give it a shot, they are welcome.

**Pull request merged**
