### PR TITLE
ovpn_status_log plugin: support for "static key" status log files added

### PR DESCRIPTION
**Pull request by l2isbad**
https://github.com/firehol/netdata/issues/2075

@csamsel
@Zolotkey

Should work for both of you.

### CODE REVIEW

**Comment by ktsaou** [comment]
let me know when this is ready to merge.

**Comment by l2isbad** [comment]
ready

**Comment by ktsaou** [comment]
merged it!

**Comment by csamsel** [comment]
Nice, in case you were wondering. I tested it, it works.

**Pull request merged**
