### PR TITLE
postgres plugin improvements

### PR DESCRIPTION
**Pull request by ktsaou**
I made the following improvements to postgres plugin:

1. added it to the build/install system

2. added default configuration to auto-detect postgres, using alternative methods

3. switched all incremental dimensions to `incremental`.

  FYI, netdata is a lot better to manage incremental dimensions - it interpolates collected values to find the rate, even if data collection is not executed precisely on time.

  This change simplified the code a bit.

4. fixed the `context` of the charts  (the database charts should not have the database name in their context, or alarms templates will not be possible).

5. improved the titles of the charts

6. added database icon to it on the dashboard

7. added an alarm that monitors if netdata stops collecting data from postgres

8. tested everything works with both python2 and python3

### CODE REVIEW

**Comment by ktsaou** [comment]
CC: @facetoe @dangtranhoang @paulfantom

**Comment by ktsaou** [comment]
@facetoe @dangtranhoang @paulfantom

In debian 8 (jessie), I get this:

```
./plugins.d/python.d.plugin debug 1 postgres

2016-10-30 01:27:51:  INFO: Using python v2
2016-10-30 01:27:51: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
2016-10-30 01:27:51: python.d INFO: MODULES_DIR='/usr/src/netdata.git/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['postgres']
2016-10-30 01:27:51: python.d DEBUG: postgres: loading module configuration: '/etc/netdata/python.d/postgres.conf'
2016-10-30 01:27:51: python.d DEBUG: postgres: reading configuration
2016-10-30 01:27:51: python.d DEBUG: postgres/tcpipv6: job added
2016-10-30 01:27:51: python.d DEBUG: postgres/tcpipv4: job added
2016-10-30 01:27:51: python.d DEBUG: postgres/socket: job added
2016-10-30 01:27:51: python.d DEBUG: postgres/tcp: job added
2016-10-30 01:27:51: python.d DEBUG: all job objects [<Service(tcpipv6, initial daemon)>, <Service(tcpipv4, initial daemon)>, <Service(socket, initial daemon)>, <Service(tcp, initial daemon)>]
2016-10-30 01:27:51: python.d ERROR: postgres_tcpipv6 sequence item 1: expected string, OperationalError found
2016-10-30 01:27:51: python.d INFO: Disabled postgres/tcpipv6
2016-10-30 01:27:51: python.d ERROR: postgres_tcpipv4 sequence item 1: expected string, OperationalError found
2016-10-30 01:27:51: python.d INFO: Disabled postgres/tcpipv4
2016-10-30 01:27:51: python.d ERROR: postgres_socket sequence item 1: expected string, OperationalError found
2016-10-30 01:27:51: python.d INFO: Disabled postgres/socket
2016-10-30 01:27:51: python.d ERROR: postgres_tcp sequence item 1: expected string, OperationalError found
2016-10-30 01:27:51: python.d INFO: Disabled postgres/tcp
2016-10-30 01:27:51: python.d DEBUG: overridden job names: []
2016-10-30 01:27:51: python.d DEBUG: all remaining job objects: []
2016-10-30 01:27:51: python.d FATAL: no more jobs
DISABLE
```

This happens before and after my commit, so it seems irrelevant to the changes I made.
I tracked it down to this line: `self.connection = psycopg2.connect(**params)`.

debian has python-psycopg2 2.5.4+dfsg-1 installed.

Unfortunately, google search does not help.

Any ideas?

**Comment by facetoe** [comment]
@ktsaou, this is fine, it just means that one of your configured jobs failed for one reason or another. I've submitted a PR (#1184) that won't print errors for these sorts of failures.

**Comment by ktsaou** [comment]
> @ktsaou, this is fine, it just means that one of your configured jobs failed for one reason or another. I've submitted a PR (#1184) that won't print errors for these sorts of failures.

thanks! but how do I connect to the database on these cases?
I mean, if you don't throw an error, then how the user could know that something is wrong?

I guess, the error should be more descriptive of what is wrong. In my case, I don't know what to do to get it working...

**Comment by facetoe** [comment]
Yea fair enough. I'll see if I can find a way to get a more useful error message out of `psycopg2` when the connection fails.

**Comment by facetoe** [comment]
@ktsaou, I've been trying to reproduce this issue so I can try to improve the error message however I'm unable to trigger the same exception. Could you post the relevant parts of your `pg_hba.conf` so I can see how your postgres is configured?

**Comment by ktsaou** [comment]
> Could you post the relevant parts of your pg_hba.conf so I can see how your postgres is configured?

Sure, it is the default file shipped with debian 8:

```
# PostgreSQL Client Authentication Configuration File
# ===================================================
#
# Refer to the "Client Authentication" section in the PostgreSQL
# documentation for a complete description of this file.  A short
# synopsis follows.
#
# This file controls: which hosts are allowed to connect, how clients
# are authenticated, which PostgreSQL user names they can use, which
# databases they can access.  Records take one of these forms:
#
# local      DATABASE  USER  METHOD  [OPTIONS]
# host       DATABASE  USER  ADDRESS  METHOD  [OPTIONS]
# hostssl    DATABASE  USER  ADDRESS  METHOD  [OPTIONS]
# hostnossl  DATABASE  USER  ADDRESS  METHOD  [OPTIONS]
#
# (The uppercase items must be replaced by actual values.)
#
# The first field is the connection type: "local" is a Unix-domain
# socket, "host" is either a plain or SSL-encrypted TCP/IP socket,
# "hostssl" is an SSL-encrypted TCP/IP socket, and "hostnossl" is a
# plain TCP/IP socket.
#
# DATABASE can be "all", "sameuser", "samerole", "replication", a
# database name, or a comma-separated list thereof. The "all"
# keyword does not match "replication". Access to replication
# must be enabled in a separate record (see example below).
#
# USER can be "all", a user name, a group name prefixed with "+", or a
# comma-separated list thereof.  In both the DATABASE and USER fields
# you can also write a file name prefixed with "@" to include names
# from a separate file.
#
# ADDRESS specifies the set of hosts the record matches.  It can be a
# host name, or it is made up of an IP address and a CIDR mask that is
# an integer (between 0 and 32 (IPv4) or 128 (IPv6) inclusive) that
# specifies the number of significant bits in the mask.  A host name
# that starts with a dot (.) matches a suffix of the actual host name.
# Alternatively, you can write an IP address and netmask in separate
# columns to specify the set of hosts.  Instead of a CIDR-address, you
# can write "samehost" to match any of the server's own IP addresses,
# or "samenet" to match any address in any subnet that the server is
# directly connected to.
#
# METHOD can be "trust", "reject", "md5", "password", "gss", "sspi",
# "ident", "peer", "pam", "ldap", "radius" or "cert".  Note that
# "password" sends passwords in clear text; "md5" is preferred since
# it sends encrypted passwords.
#
# OPTIONS are a set of options for the authentication in the format
# NAME=VALUE.  The available options depend on the different
# authentication methods -- refer to the "Client Authentication"
# section in the documentation for a list of which options are
# available for which authentication methods.
#
# Database and user names containing spaces, commas, quotes and other
# special characters must be quoted.  Quoting one of the keywords
# "all", "sameuser", "samerole" or "replication" makes the name lose
# its special character, and just match a database or username with
# that name.
#
# This file is read on server startup and when the postmaster receives
# a SIGHUP signal.  If you edit the file on a running system, you have
# to SIGHUP the postmaster for the changes to take effect.  You can
# use "pg_ctl reload" to do that.

# Put your actual configuration here
# ----------------------------------
#
# If you want to allow non-local connections, you need to add more
# "host" records.  In that case you will also need to make PostgreSQL
# listen on a non-local interface via the listen_addresses
# configuration parameter, or via the -i or -h command line switches.




# DO NOT DISABLE!
# If you change this first entry you will need to make sure that the
# database superuser can access the database using some other method.
# Noninteractive access to all databases is required during automatic
# maintenance (custom daily cronjobs, replication, and similar tasks).
#
# Database administrative login by Unix domain socket
local   all             postgres                                peer

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     peer
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
# Allow replication connections from localhost, by a user with the
# replication privilege.
#local   replication     postgres                                peer
#host    replication     postgres        127.0.0.1/32            md5
#host    replication     postgres        ::1/128                 md5
```

**Comment by ktsaou** [comment]
And `postgresql  9.4+165+deb8u1`

**Comment by ktsaou** [comment]
@facetoe, I really need some help here. I don't know how to debug this and for some reason, I can't even setup this plugin on the demo sites.

Any ideas how to solve it?

**Comment by facetoe** [comment]
Sorry @ktsaou I've been flat out at work and haven't had a chance to investigate this yet. 

I'm pretty sure the reason you are unable to set it up on the demo sites is your postgresql configuration is preventing the plugin connecting. I usually change the following line:

```
# "local" is for Unix domain socket connections only
local   all             all                                     peer
```

To 

```
# "local" is for Unix domain socket connections only
local   all             all                                    trust
```

Which allows users that have access to the Unix socket can connect without a password (by default the socket is owned by root). This should allow the plugin to connect as the postgres user (as by default the postgres user doesn't have a password). 

As for why the error message is so undescriptive, I'll need to investigate a bit more. I'll try to get to it sometime this week.

**Comment by ktsaou** [comment]
thanks! I also changed the localhost tcp and tcp6 to trust and it works.
The problem however is the error displayed, or actually its absence... as a user I cannot know what is happening and why it does not work.

**Comment by ktsaou** [comment]
live: http://registry.my-netdata.io/#menu_postgres_local_submenu_db_postgres

**Comment by facetoe** [comment]
I haven't forgot about this @ktsaou, just been really busy. Hopefully I will get the chance to look at providing some better error messages this weekend!

**Comment by ktsaou** [comment]
ok no problem.
Thanks!

**Pull request merged**
