### PR TITLE
Rpm packaging

### PR DESCRIPTION
**Pull request by breed808**
Referencing desired package state from #1302 

- [x] Create the `netdata` user and group
- [x] If the `docker` group is available, add `netdata` user to the `docker` group
- [x] Install the netdata files and make sure they have the proper permissions (make also sure `/var/lib/netdata` and `/var/cache/netdata` are created with the correct permissions).
- [x] Make sure `setcap` is used on `apps.plugin` (or setuid to root if `setcap` does not work)
- [x] Install the proper start-up file
- [x] Install the logrotate configuration
- [x] Install an empty `/etc/netdata/netdata.conf`
- [x] Soft packages runtime dependencies (curl, python, nodejs, etc)
- [x] Preservation of configuration files with `%config(noreplace)`
- [x] `/var/lib/netdata` and `/var/cache/netdata` are created

@ktsau this will create the `docker` group if it does not already exist, and add the `netdata` user to it.
Can you let me know what capabilities `apps.plugin` will need from `setcap` so I can add that?
Let me know if anything is missing from the above task list and I will add it.

### CODE REVIEW

**Comment by ktsaou** [comment]
Nice!

Here are the apps.plugin capabilities: https://github.com/firehol/netdata/blob/e8ba513c991ecae87a7fcb79397df0a2ee8e2fc8/netdata-installer.sh#L795

```sh
setcap cap_dac_read_search,cap_sys_ptrace+ep apps.plugin
```

**Comment by ktsaou** [comment]
hm... I don't know if adding the docker group will break something else. For example, is the docker group expected to have a fixed GID on a few systems?

**Comment by ktsaou** [comment]
This is the list of all packages that can benefit netdata:


package|description
:-----:|-----------
`bash`|for shell plugins and alarm notifications
`curl`|for shell plugins and alarm notifications
`tc`|for monitoring Linux QoS
`python`|for most of the external plugins
`python-yaml`|for parsing `python.d.plugin` configuration (netdata ships a version of it too)
`python-mysqldb`|used for monitoring mysql databases
`python-psycopg2`|used for monitoring postgres databases
`nodejs`|used for `node.js` plugins for monitoring `named` and SNMP devices
`lm_sensors`|for monitoring hardware sensors
`libmnl`|for collecting netfilter metrics
`netcat`|for shell plugins to collect metrics from remote systems

**Comment by breed808** [comment]
Thanks @ktsaou. I've added the additional runtime requirements for Fedora/CentOS. I will need to find a way of defining the OpenSUSE requirements without using a conditional.
I've added the capabilities to `apps.plugin`.

I briefly searched for 'docker static gid' and these was the most relevant result I could find: https://github.com/docker/docker/issues/21184
It doesn't appear that docker currently uses or expects a static GID, and the process for acquiring one in Debian is difficult, and not supported in Fedora. Unsure of CentOS/RHEL policy on this.

**Comment by ktsaou** [comment]
seems nice.
The only problem if there is a way to setuid to root `apps.plugin` if `setcap` fails. Can we do this?

**Comment by breed808** [comment]
I've changed the `setcap` application to an rpm macro (`%cap`). If the `setcap` operation fails, the build will fail. So, no installation will have an unprivileged `apps.plugin`.

It should be possible to add a capability check and setuid if you think it necessary.

**Comment by ktsaou** [comment]
Unfortunately setcap fails on containers, so I think this will limit netdata significantly...

---
Sent from my iphone.

23 Δεκ 2016, 02:11, ο/η Ben R <notifications@github.com> έγραψε:

**Comment by breed808** [comment]
We could create a second `netdata-container` package which will conflict with the `netdata` package (only one of the two can be installed at a time) which has setuid on `apps.plugin`.
I think this would be better than setuid on all netdata installs, at least from a security perspective.

However, this would increase build complexity with build server(s) now building two distinct packages.

**Comment by ktsaou** [comment]
> However, this would increase build complexity with build server(s) now building two distinct packages.

I agree. 

What about `setcap ... || chmod ...` ?

I don't know if there is another way to do it. @alonbl any ideas?

**Comment by breed808** [comment]
I've had more of a search and the following could work:

```
%post
setcap cap_dac_read,cap_sys_ptrace+ep /usr/libexec/netdata/plugins.d/apps.plugin || chmod 1755 /usr/libexec/netdata/plugins.d/apps.plugin
```

**Comment by ktsaou** [comment]
merry christmas!

is this ready to be merged?

**Comment by breed808** [comment]
Yes, I've just added the `libcap` line to the `%post` area.

**Comment by ktsaou** [comment]
merged! thanks!

**Pull request merged**
