### PR TITLE
self-cleaning obsolete cgroups and network interfaces from memory

### LINKED ISSUE #1163: Docker containers, networks interfaces, alarms
Not sure how this one should be handled. I'm bringing it up so that we can probably collect ideas on what we want and how that could be achieved.

My problem is that when working with Docker containers, we are getting new network interfaces every time we fire up a new container. The great thing is that NetData immediately starts monitoring those network interfaces as well, which is a bonus that I had not thought about before. But it's great.

Now, when shutting down one of the containers, its interface(s) are being killed on purpose. The problem is, NetData is still monitoring them and soon after will trigger an alarm that it couldn't read from the interface anymore.

Now, the catch 22 is that when I shut down a container deliberately, I want NetData to stop monitoring it as well and don't alert me about dead interfaces. On the other hand, if a container crashed, it is probably important to get exactly those alerts.

Any ideas on how that could be resolved?

### LINKED ISSUE #1358: ephemeral containers - netdata does not cleanup
I have a server on which I'm running docker engine and creating lots of docker containers. On that server netdata consumes huge amount of inodes. During the weekend netdata managed to consumed 15gb of disk space and quite a lot of inodes. The disk used is mostly in /var/cache/netdata. I guess netdata it's not cleaning unexisting docker container.
Is there something I can do or is this a bug in netdata?

### PR DESCRIPTION
**Pull request by ktsaou**
fixes #1163 
fixes #1358

## the problem

Containers are ephemeral by nature. Prior to this PR, netdata had 2 issues:

1. network interface alarms where triggering when containers were stopped
2. charts were never cleaned up, so after some time dozens of containers were showing up on the dashboard, and they were occupying memory.

## the solution

network interfaces and cgroups are now self-cleaned.

So, when a network interface or container stops, netdata might log a few errors in error.log complaining about files it cannot find, but immediately:

1. it will detect this is a removed container or network interface
2. it will freeze/pause all alarms for them
3. it will mark their charts as obsolete
4. obsolete charts are not be offered on new dashboard sessions (so hit F5 and the charts are gone)
5. existing dashboard sessions will continue to see them, but of course they will not be refreshing
6. obsolete charts will be removed from memory, 1 hour after the last user viewed them (configurable with `[global].cleanup obsolete charts after seconds = 3600` (at netdata.conf).
7. when obsolete charts are removed from memory they are also deleted from disk (configurable with `[global].delete obsolete charts files = yes`)

### CODE REVIEW

**Comment by mailinglists35** [comment]
I have git cloned the netdata main repository as instructed in the installation file. (git clone https:... )
I'd like to test this, what is the easiest way to merge this pull request?

**Comment by l2isbad** [comment]
@mailinglists35 

```
mkdir netdata_ktsaou
cd netdata_ktsaou
git clone https://github.com/ktsaou/netdata.git --depth=1
```

**Comment by mailinglists35** [comment]
@l2isbad  yes but what if I wanted only to pull the changed files and not have to download everything again from the fork?

**Comment by mailinglists35** [comment]
@l2isbad also, the steps you provided gives an error at the end

```
[root@el7c src]# mkdir netdata_ktsaou
[root@el7c src]# cd netdata_ktsaou
[root@el7c netdata_ktsaou]# git clone https://github.com/ktsaou/netdata.git --depth=1
Cloning into 'netdata'...
remote: Counting objects: 547, done.
remote: Compressing objects: 100% (501/501), done.
remote: Total 547 (delta 83), reused 194 (delta 32), pack-reused 0
Receiving objects: 100% (547/547), 2.26 MiB | 605.00 KiB/s, done.
Resolving deltas: 100% (83/83), done.
[root@el7c netdata_ktsaou]#  Show all checks
bash: Show: command not found...
```

**Comment by l2isbad** [comment]
What error are you talking about?

**Comment by mailinglists35** [comment]
sorry i must have accidentally pasted "show all checks" :)

**Comment by ktsaou** [comment]
made 2 fixes:

1. cgroups now switch charts to obsolete, immediately, at the next iteration (no need for the up to 10 secs delay).
2. charts marked as obsolete are also deleted from disk (by default, there is an option for that).

**Comment by mailinglists35** [comment]
yey, found how to apply the pull request

inside
git remote add ktsaou https://github.com/ktsaou/netdata
git fetch ktsaou
git cherry-pick <sha256 of each commit>

**Comment by simonnagl** [comment]
If you only want to test it you can do:
```
git remote add ktsaou https://github.com/ktsaou/netdata
git fetch ktsaou
git checkout ktsaou/master
```

If you want to transform it to a local branch simply `checkout -b <new-branch-name>`

Don't blame me if you already knew that.

**Comment by mailinglists35** [comment]
> git checkout ktsaou/master

wouldn't that give me all commits from ktsaou? I only wanted this particular PR consisting of 7 commits

**Comment by ktsaou** [comment]
merged it

**Comment by simonnagl** [comment]
> wouldn't that give me all commits from ktsaou? I only wanted this particular PR consisting of 7 commits

No. And it is the right way to do it. If you cherry-pick you create new commits.

**Pull request merged**
