### PR TITLE
Python plugin for MySQL

### PR DESCRIPTION
**Pull request by paulfantom**
As I said here is MySQL plugin rewritten to python. Everything needed to run it is supplied in this PR. I am using [PyMySQL](https://github.com/PyMySQL/PyMySQL) module and it would be good to give them credit somewhere.

I have fixed some bugs in `python.d.plugin` and also in `Makefile.am` responsible for `python_modules` directory.

This PR is tested on clean Ubuntu 16.04, and it works.

### CODE REVIEW

**Comment by paulfantom** [comment]
Also as a precaution I set this module to be disabled in `python.d.conf`. This way we can prevent loading `mysql.chart.sh` and `mysql.chart.py` at the same time.

**Comment by paulfantom** [comment]
I have also modified README.md to include information about `mysql.chart.py` plugin.

**Comment by glensc** [comment]
bundling (in this repo) third party library is wrong.

perhaps just skip plugin (catch ImportError) if PyMysql can't be imported and suggest them to yum/dnf/apt/pip install missing modules.

**Comment by paulfantom** [comment]
I have removed pymysql from this PR and included information about dependency in readme. 
Also considering ImportError, `python.d.plugin` catches every exception when loading modules and logs them in `error.log`.

**Comment by ktsaou** [comment]
nice! Can you also add PyMySQL to `LICENCE.md`?

**Comment by ktsaou** [comment]
my bad. It has been be removed. sorry.

I am testing it now.

**Comment by ktsaou** [comment]
I get these:

```sh
 # /usr/libexec/netdata/plugins.d/python.d.plugin debug 1
python.d: started from /usr/libexec/netdata/plugins.d/python.d.plugin with options: debug 1
python.d: loading chart: '/usr/libexec/netdata/python.d/example.chart.py'
python.d: 'module' object has no attribute 'write'
python.d: No plugins loaded
DISABLE
```

**Comment by paulfantom** [comment]
Fixed.

**Comment by ktsaou** [comment]
thanks.

```sh
# ./plugins.d/python.d.plugin debug 1
python.d: started from ./plugins.d/python.d.plugin with options: debug 1
python.d: loading chart: '/data/src/netdata-paulfantom.git/python.d/example.chart.py'
You need to install PyMySQL module to use mysql.chart.py pluginpython.d: loading chart: '/data/src/netdata-paulfantom.git/python.d/mysql.chart.py'
python.d: loading chart options: '/etc/netdata/python.d/mysql.conf'
python.d: Malformed configuration file: Source contains parsing errors: '<string>'
        [line 21]: ']\n'
Traceback (most recent call last):
  File "./plugins.d/python.d.plugin", line 354, in <module>
    run()
  File "./plugins.d/python.d.plugin", line 348, in run
    charts = PythonCharts(interval, modules, modules_dir, modules_conf, disabled)
  File "./plugins.d/python.d.plugin", line 36, in __init__
    self._load_configs()
  File "./plugins.d/python.d.plugin", line 102, in _load_configs
    for k, v in read_config(configfile).items():
AttributeError: 'NoneType' object has no attribute 'items'
```

It should not stop like that if the config is wrong.

**Comment by ktsaou** [comment]
```sh
# ./plugins.d/python.d.plugin debug 1
python.d: started from ./plugins.d/python.d.plugin with options: debug 1
python.d: loading chart: '/data/src/netdata-paulfantom.git/python.d/example.chart.py'
You need to install PyMySQL module to use mysql.chart.py pluginpython.d: loading chart: '/data/src/netdata-paulfantom.git/python.d/mysql.chart.py'
python.d: loading chart options: '/etc/netdata/python.d/mysql.conf'
python.d: chart 'mysql' check() function reports failure.
python.d: No plugins loaded
DISABLE
```

The error message should start with 'python.d/MODULE: MESSAGE`.
This way we could grep the log file for `python.d/mysql` to find all the errors of mysql for python.plugin.

**Comment by ktsaou** [comment]
```sh
# ./plugins.d/python.d.plugin debug 1
python.d: started from ./plugins.d/python.d.plugin with options: debug 1
python.d: loading chart: '/data/src/netdata-paulfantom.git/python.d/example.chart.py'
python.d: loading chart: '/data/src/netdata-paulfantom.git/python.d/mysql.chart.py'
python.d: loading chart options: '/etc/netdata/python.d/mysql.conf'
python.d: chart 'mysql' check() function reports failure.
python.d: No plugins loaded
DISABLE
```

hm... this should say something more. What was the error exactly, what to look for?

**Comment by ktsaou** [comment]
1. regarding the config errors, we should make to most for `python.d.plugin` to survive all errors. If a module fails it should not take down the entire plugin.

2. Regarding the `check()` failure, does pymysql return an error? Like "cannot connect", or "authentication failed"? If yes, we should log these.

**Comment by ktsaou** [comment]
Check this: https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/connections.py#L551
If I understand correctly, we could just point this option to `/etc/mysql/my.cnf` and it will do the rest.

**Comment by ktsaou** [comment]
> If I understand correctly, we could just point this option to /etc/mysql/my.cnf and it will do the rest.

I don't suggest to remove the other options. But support `read_default_file` too, which could also be the default.

**Comment by ktsaou** [comment]
Check this:

```sh
# ./plugins.d/python.d.plugin debug 1 mysql
python.d: started from ./plugins.d/python.d.plugin with options: debug 1 mysql
python.d: loading chart options: '/etc/netdata/python.d/mysql.conf'
mysql.chart.py has problem connecting to server: (2003, "Can't connect to MySQL server on None ([Errno -2] Name or service not known)")
python.d: chart 'mysql' check() function reports failure.
python.d: No plugins loaded
DISABLE
```

```sh
# cat /etc/netdata/python.d/mysql.conf
# Example configuration of mysql.chart.py
# Indentation is important

update_every=1

config=[
        {
                'name'     : 'local',
                'user'     : 'root',
                # 'password' : 'blablablabla',
                'socket'   : '/var/run/mysqld/mysqld.sock'
        }
#,{
#        'name'     : 'remote',
#        'user'     : 'admin',
#        'password' : 'bla',
#        'host'     : 'example.org',
#        'port'     : '3306'
#    }
        ]
```

**Comment by paulfantom** [comment]
I agree with both of those statement. I am trying to make `python.d.plugin` as bulletproof as I can but sometimes something slips. 
Second part I have just implemented.

So you think I should check user config and if it is wrong point `mysql.chart.py` to `/etc/mysql/my.cnf` ? I know you implemented something like this in bash counterpart.
I could also try to add autodetected configuration from `read_default_file` to other configurations or create . What do you think?

I will try to find the reason of 2003 connection error.

**Comment by ktsaou** [comment]
> So you think I should check user config and if it is wrong point mysql.chart.py to /etc/mysql/my.cnf ? I

No. I am suggesting to support this:

```sh
update_every=1

config=[
        {
                'name'     : 'local',
                'user'     : 'root',
                # 'password' : 'blablablabla',
                'socket'   : '/var/run/mysqld/mysqld.sock'
        },
        {
                'name'     : 'local_tcp',
                'user'     : 'root',
                # 'password' : 'blablablabla',
                'host'   : 'localhost'
                'port'   : '3306'
        },
        {
                'name'     : 'local_cnf',
                'my.cnf'   : '/etc/mysql/my.cnf'
        }
        ]
```

So 3 types to configure it: socket, tcp, mysql config file.

**Comment by ktsaou** [comment]
> sometimes something slips

no problem. We will find them... :)


> I could also try to add autodetected configuration from read_default_file

I think that when this will be enabled, we will just ship a configuration file with this:

```sh
update_every=1
config=[
        {
                'name'     : 'local_cnf',
                'my.cnf'   : '/etc/mysql/my.cnf'
        }
        ]
```

**Comment by paulfantom** [comment]
Ok, I will mitigate this 2003, implement reading config from `my.cnf`, test it and call you when ready.

**Comment by ktsaou** [comment]
perfect!

**Comment by paulfantom** [comment]
I have added option to include `my.cnf` and I can only hope it works because I don't have any server on which I can test it.
Also I tried to reproduce this 2003 error and I failed miserably but I changed configuration parsing, maybe it will help.
@ktsaou maybe you will have more luck.

**Comment by glensc** [comment]
i think you should rebase this commit (squash it?) so that the pyMySQL in and out won't stay in git history...

and `git push -f` to update the PR

**Comment by paulfantom** [comment]
Rebased and squashed commits to exclude pymysql, then pushed it. @glensc can you confirm it worked?

**Comment by ktsaou** [comment]
With my.cnf:

```sh
# ./plugins.d/python.d.plugin debug 1 mysql
python.d: started from ./plugins.d/python.d.plugin with options: debug 1 mysql
python.d: loading chart options: '/etc/netdata/python.d/mysql.conf'
mysql.chart.py has problem connecting to server: While reading from '/etc/mysql/my.cnf' [line 120]: section 'mysqldump' already exists
python.d: chart 'mysql' check() function reports failure.
python.d: No plugins loaded
DISABLE
```

My `my.cnf` file does have a few sections multiple times. This seems to be pefrectly valid for mysql (each section adds options), but pymysql seems to be confused.

With the unix socket it still fails:

```sh
# ./plugins.d/python.d.plugin debug 1 mysql
python.d: started from ./plugins.d/python.d.plugin with options: debug 1 mysql
python.d: loading chart options: '/etc/netdata/python.d/mysql.conf'
mysql.chart.py has problem connecting to server: (2003, "Can't connect to MySQL server on None ([Errno -2] Name or service not known)")
python.d: chart 'mysql' check() function reports failure.
python.d: No plugins loaded
DISABLE
```

I understand that pymysql is trying to connect on a TCP server and it takes `None`. I think you pass this. What if you don't set `host` and `port` at all?

With TCP, I get this:

```sh
 ./plugins.d/python.d.plugin debug 1 mysql
python.d: started from ./plugins.d/python.d.plugin with options: debug 1 mysql
python.d: loading chart options: '/etc/netdata/python.d/mysql.conf'
mysql.chart.py has problem connecting to server: (2003, "Can't connect to MySQL server on 'localhost' (%d format: a number is required, not str)")
python.d: chart 'mysql' check() function reports failure.
python.d: No plugins loaded
DISABLE
```

I don't really get this.

**Comment by paulfantom** [comment]
I think I got it. Looking at http://pymysql.readthedocs.io/en/latest/modules/connections.html I found that `password` must always be a string type. Changed it and now it should be ok.

**Comment by paulfantom** [comment]
Also if something is not set, I am passing defaults that pymysql has in its __init__().

**Comment by ktsaou** [comment]
sorry. Still same errors on all 3 cases...

**Comment by paulfantom** [comment]
Port was a string not a number. Changed it. I don't know how to enforce pymysql to read my.cnf correctly.
I am repeating myself but now it should work.

**Comment by ktsaou** [comment]
ok. Now the TCP works.

Nice!

There is something that bothers me though. charts.d.plugin needs about 40ms for each mysql iteration. python.d.plugin needs 26-30 ! For per second updates, python.d.plugin uses about 2.5% to 3.0% of CPU constantly.

Is this supposed to be so slow?

**Comment by ktsaou** [comment]
python.d.plugin:

```
SET run_time = 26
SET run_time = 40
SET run_time = 42
SET run_time = 26
SET run_time = 27
SET run_time = 56
SET run_time = 35
SET run_time = 25
SET run_time = 42
SET run_time = 35
SET run_time = 50
SET run_time = 38
SET run_time = 25
SET run_time = 37
SET run_time = 50
SET run_time = 26
SET run_time = 24
SET run_time = 27
SET run_time = 24
SET run_time = 32
SET run_time = 23
```

charts.d.mysql

```
SET run_time = 42
SET run_time = 50
SET run_time = 53
SET run_time = 42
SET run_time = 54
SET run_time = 43
SET run_time = 41
SET run_time = 50
SET run_time = 50
SET run_time = 49
SET run_time = 53
SET run_time = 40
SET run_time = 50
SET run_time = 43
SET run_time = 43
SET run_time = 42
SET run_time = 43
SET run_time = 51
```

**Comment by paulfantom** [comment]
Unfortunately it is. First of all mysql connection protocol implemented by pymysql isn't the fastest one (about 3/4 of the run time is caused only by executing query). 
I don't have any explanation for high CPU usage.

**Comment by paulfantom** [comment]
Run time was even higher, but now I am keeping every connection open and its object in `connections` list.

**Comment by paulfantom** [comment]
I have checked it on my VM and the run time is about 3-5 ms. Strange.

**Comment by ktsaou** [comment]
I thought was my mysql server. So I wrote a sample C code for this:

```c
#include <my_global.h>
#include <mysql.h>

unsigned long long timems(void) {
        struct timeval now;
        gettimeofday(&now, NULL);
        return now.tv_sec * 1000000ULL + now.tv_usec;
}

int main(int argc, char **argv) {
        MYSQL *con = mysql_init(NULL);

        if(con == NULL) {
                fprintf(stderr, "%s\n", mysql_error(con));
                exit(1);
        }

        // if(mysql_real_connect(con, NULL, "root", NULL, NULL, 0, "/var/run/mysqld/mysqld.sock", 0) == NULL) {
        if(mysql_real_connect(con, "localhost", "root", NULL, NULL, 0, NULL, 0) == NULL) {
                fprintf(stderr, "%s\n", mysql_error(con));
                mysql_close(con);
                exit(1);
        }

        int i, j;
        for(j = 0; j < 100 ; j++) {
                unsigned long long start = timems();
                if(mysql_query(con, "SHOW GLOBAL STATUS")) {
                        fprintf(stderr, "Cannot execute query: %s\n", mysql_error(con));
                        break;
                }
                MYSQL_RES *result = mysql_store_result(con);
                if(!result) {
                        fprintf(stderr, "Cannot store results: %s\n", mysql_error(con));
                        break;
                }
                int num_fields = mysql_num_fields(result);
                MYSQL_ROW row;
                while ((row = mysql_fetch_row(result))) {
                        for(i = 0; i < num_fields; i++) {
                                // printf("%s ", row[i] ? row[i] : "NULL");
                                ;
                        }
                        // printf("\n");
                }
                mysql_free_result(result);
                unsigned long long end = timems();
                printf("%0.2f ms\n", (float)((end - start) / 1000));
        }

        mysql_close(con);
        exit(0);
}
```

compile with:

```sh
gcc -Wall mytest.c -o mytest $(mysql_config --cflags --libs)
```

and it gives this:

```sh
# ./mytest
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
1.00 ms
```

so, it is not the database server!

**Comment by paulfantom** [comment]
No. I think it is PyMySQL implementation. I will search for a better library.

**Comment by ktsaou** [comment]
gentoo, that I use for development has an old pymysql (0.6.7). So I checkout out the pymysql github repo and installed it in `python_modules`. Same results.

**Comment by ktsaou** [comment]
> I will search for a better library

ok. we could test a sample loop before spending several hours integrating it into the plugin. You choose.

**Comment by paulfantom** [comment]
Simple script to test pymysql:

```py
import pymysql.cursors
import time

connection = pymysql.connect(host='localhost',
                             user='user',
                             password='passwd')

t_begin = time.time()
for i in range(100):
    with connection.cursor() as cursor:
        sql = "SHOW GLOBAL STATUS"
        cursor.execute(sql)
        result = cursor.fetchall()

print( (time.time() - t_begin) / 100.0 )
connection.close()

```

Executes query 100 times.
At my VM with ubuntu I got ~0.004s which is 2-3ms slower than `mysql.chart.py` on the same machine.

**Comment by ktsaou** [comment]
This is mine:

```sh
# python3 test.py
0.022290704250335695
```

So, this 22ms for 100 loops? If this is the case, the time is somewhere else...

**Comment by paulfantom** [comment]
22ms is for one loop. I haven't been clear on this. It executes 100 queries, but result is divided by 100.
I have been investigating and the slowest part is `cursor.execute(sql)`.

**Comment by ktsaou** [comment]
Oh... I see... it is slow, 22.9 times slower than native C !

**Comment by ktsaou** [comment]
Do we have other libraries?

**Comment by ktsaou** [comment]
And guess what: python 2 is faster:

```sh
# python2 test.py
0.018563349247
```

**Comment by paulfantom** [comment]
There is also [mysql-connector](https://pypi.python.org/pypi/mysql-connector-python/2.0.4) which I will test after checking why pymysql is so slow.

**Comment by ktsaou** [comment]
ok, perfect.

**Comment by paulfantom** [comment]
I have tried [mysql-connector](https://pypi.python.org/pypi/mysql-connector-python/2.0.4) and it is even slower (about 10ms).
Next on my list was forked version of [MySQLdb](https://github.com/PyMySQL/mysqlclient-python) which is a python wrapper on a C library and it is noticably faster. 

Also it was easy to implament fallback to PyMySQL if someone doesn't have MySQLdb, so I have implemented it.

Can you run it?

**Comment by paulfantom** [comment]
I found why pymysql is so sluggish.
It uses `socket.makefile()` which is slow and it is a known [issue](https://bugs.python.org/issue18329).

**Comment by ktsaou** [comment]
> Can you run it?

Yes of course, but later today.

**Comment by ktsaou** [comment]
I am testing it now.

It is a lot better: 5-6ms, CPU 0.7%.

**Comment by paulfantom** [comment]
Merge?

**Comment by ktsaou** [comment]
merged

**Comment by ktsaou** [comment]
I suggest 2 changes:

It would be great if we could have different `update_every` for every mysql server. In `node.d.plugin` I have followed this approach:

1. `node.d.plugin` calls the check function, which responds with zero, one or more *jobs*. Each job has all the details the plugin should now to execute it. It also provides an `update_every` for every job.
2. `node.d.plugin` then calls the module's update with the given job data. It calls it once for every job at the required time to update this specific job

This means that each module can handle any number of servers with different update frequency each.
Also, the return value of the `update()` call, controls only the specific job, not the whole module.

The other change is about failures reported by `update()`. In `charts.d.plugin` and in netdata plugin logic, I have done this when a failure is reported:

1. if the job had collected data in the past, then retry up to 10 times with 10 second delay each. If it fails for 10 consecutive attempts, then disable it. Otherwise, on each successful update, set `failures = 0`.
2. if the job had not collected data in the past, then disable it.

This way, if I just restart mysql, netdata will catch up.

What do you think?

**Comment by paulfantom** [comment]
I think those are great ideas and I'll try to implement them. Probably not today, but in near future.

**Comment by paulfantom** [comment]
With our current `python.d.plugin` different `update_every` intervals for different servers would be nearly impossible to implement without using some hacks in `mysql.chart.py`. Currently `python.d.plugin` doesn't care what and how frequent is done in module update() function, as was expected.

It would be possible if every module was a class of its own and `python.d.plugin` would create one object for one mysql/php-fpm/etc server.

Considering that `python.d.plugin` has only 6 days and `mysql.chart.py` is even younger I am going to change both of them to be more object-oriented, by the end of this week.

@ktsaou what do you think about it?

**Comment by paulfantom** [comment]
More thinking:

Modules would follow this prototype:
```py

# update_every is a numer or a collection of numbers (list/tuple)
update_every = [2,3,6]
update_every = 2

# configuration for every service
config = [{ 'name' : 'bla'}, {'name' : 'bla2'}, {'name' : 'local_bla'}]

class Service(object):
# Service could be for example one of mysql servers.
# `python.d.plugin` could register many Services for module
  def __init__(self, config):
    # object constructor
    # same thing as in previously used check() functions
    # do not create object if it cannot connect / grab data
  def create(self):
    # stuff needed to create charts
    # same as previous create() function but for only one server/service
  def update(self,interval):
    # same as previously used update() functions but for only one server/service
```

Also I think we can forget using `configparser` and just import configurations as python modules and assign variables from them to execution modules.

**Comment by ktsaou** [comment]
@paulfantom I still think this would be limited.

I suggest that `python.d.plugin` will have 2 different objects:

1. modules

  module is for example `mysql.chart.py` or `example.chart.py`. `update_every` inside a module is just the default value for the `update_every` of jobs, but jobs should have their own `update_every`.

2. jobs

   The main iteration/loop is performed on a list of jobs. Each job should state the module it belongs to.

So the config could be something like this:

```
config = [{ 'name' : 'bla', 'update_every': 1, 'retries_on_failure': 10}, { 'name' : 'bla', 'update_every': 2, 'retries_on_failure': 20}]
```

I think this would greatly improve our flexibility.

**Comment by paulfantom** [comment]
That's what I was thinking about:)

**Comment by paulfantom** [comment]
@ktsaou I need some help. 
While fixing shortcomings of `python.d.plugin` I found that current version of  configuration files used by me is dumb. Every configuration file for every new python module would be the same:
```py
update_every = X
priority = Y
retries = Z
config = {some dictionary/list actually used by a plugin}
```
And only `config` dictionary/list is passed to plugin (for example `mysql.chart.py`), the other 3 are used by `python.d.plugin` as a fallback when they are not in `config`. I think that configuration file shouldn't look like this.

As a resolution to this problem I can change the way configuration is stored to one of following formats:
1. JSON (pros: default parser is included in python; cons: cannot have comments)
2. INI (pros: basic parser included in python; cons: hard to write a good parser when configuration is unknown, default parser has some minor problems with py2/py3 compatibility)
3. YAML (pros: clean, easy to understand, popular; cons: parser is not included although there is a good 3rd party lib)
4. As is (pros: I can import it as a python module and just use variables; cons: configuration file is ugly, probably some security issues)

I can write `python.d.plugin` to use any of those above, but my favorite is YAML. Or maybe you have some more ideas, what do you think?

Probably it would be best to use the same configuration file schema for every plugin (C, bash, node, python, maybe more will come...), but I don't think it is possible. However we can now choose one for the future and stick to it.

P.S. Since my code changes are not exactly an issue, and we started taking about `python.d.plugin` changes here, I didn't want to open a new issue.
P.P.S. I know I am a pain in the ass with so many PRs and issues lately, sorry:)

**Comment by ktsaou** [comment]
Yaml is good :+1: 

Make as many PRs and issues as you like (or you can take). I like this!

**Pull request merged**
