### PR TITLE
apps.plugin optimization and new grouping of applications

### PR DESCRIPTION
**Pull request by ktsaou**

### CODE REVIEW

**Comment by ktsaou** [comment]
what happened to travis?

**Comment by paulfantom** [comment]
> what happened to travis?

@ktsaou What do you mean?

**Comment by ktsaou** [comment]
It didn't kick in. I had to add the `fixed typo` commit to wake it up.

**Comment by paulfantom** [comment]
Strange. I know you can skip travis build by adding `[ci skip]` anywhere in commit message, but I don't think this is an issue here.

**Pull request merged**
