### PR TITLE
fix #296

### LINKED ISSUE #296: NetData failed to build on Centos 6 x64
./configure: line 5030: syntax error near unexpected token newline'
./configure: line 5030:        PKG_CHECK_MODULES('

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Sorry! NetData failed to build...

You many need to check these:

1. The package zlib1g-dev has to be installed.

2. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required

3. If your system cannot find ZLIB, although it is installed
   run me with the option:  --zlib-is-really-here

If you still cannot get it to build, ask for help at github:

   https://github.com/firehol/netdata/issues

root@kn007:/data/src/netdata> yi gcc make autoconf automake pkg-config zlib1g-dev

Loaded plugins: auto-update-debuginfo, axelget, fastestmirror, priorities, refresh-packagekit, security
Setting up Install Process
Loading mirror speeds from cached hostfile

 * base: mirror.hostduplex.com
 * elrepo: ftp.osuosl.org
 * elrepo-kernel: ftp.osuosl.org
 * extras: mirror.hostduplex.com
 * ius: mirrors.kernel.org
 * ius-debuginfo: mirrors.kernel.org
 * rpmforge: mirror.hmc.edu
 * updates: centos.mirror.lstn.net

Package gcc-4.4.7-16.el6.x86_64 already installed and latest version
Package 1:make-3.81-20.el6.x86_64 already installed and latest version
Package autoconf-2.63-5.1.el6.noarch already installed and latest version
Package automake-1.11.1-4.el6.noarch already installed and latest version
No package pkg-config available.
No package zlib1g-dev available.
Nothing to do

root@kn007:/data/src/netdata> /usr/bin/pkg-config --version 
0.23

root@kn007:/data/src/netdata> autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.

root@kn007:/data/src/netdata> automake --version
automake (GNU automake) 1.15
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.

Same problem when using `--zlib-is-really-here`

### PR DESCRIPTION
**Pull request by kn007**
fix PKG_CHECK_MODULES error

### CODE REVIEW

**Comment by ktsaou** [comment]
Thanks! Can we change it to this:

```sh
if [ -d /usr/share/aclocal ]
then
        ACLOCAL_PATH=${ACLOCAL_PATH-/usr/share/aclocal}
        export ACLOCAL_PATH
fi
```

People may be overriding it already.

**Comment by kn007** [comment]
Of course, It looks better. Thank you.

**Comment by kn007** [comment]
I change it

**Comment by ktsaou** [comment]
merged!

**Comment by glensc** [comment]
not sure what's the difference, but i usually use `ACLOCAL_PATH=${ACLOCAL_PATH:-/usr/share/aclocal}`

**Comment by glensc** [comment]
also, if people are overriding it, shouldn't you append?

`ACLOCAL_PATH=${ACLOCAL_PATH}${ACLOCAL_PATH:+:}/usr/share/aclocal`

or prepend?
`ACLOCAL_PATH=/usr/share/aclocal${ACLOCAL_PATH:+:}${ACLOCAL_PATH}`

**Comment by ktsaou** [comment]
> not sure what's the difference, but i usually use ACLOCAL_PATH=${ACLOCAL_PATH:-/usr/share/aclocal}, note the :-

strange... both with `:` and without it, work...

> ACLOCAL_PATH=${ACLOCAL_PATH}${ACLOCAL_PATH:+:}/usr/share/aclocal

If they are overriding it, let them do whatever they like themselves.

**Comment by glensc** [comment]
maybe just portability issue

**Pull request merged**
