### PR TITLE
web_log bugfix: properly parse squid response codes

### LINKED ISSUE #2530: web_log: sets values for dimensions it has not created
@l2isbad check this:

```
2017-07-28 20:50:27: netdata ERROR: PLUGINSD: '/opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin' is requesting a SET to dimension with id 'NONE' on stats 'web_log_sq_viva.squid_code' (web_log_sq_viva.squid_code) on host 'igw2', which does not exist. Disabling it.
```

So, web_log sets values for dimensions it has not created.

Any ideas?

### PR DESCRIPTION
**Pull request by l2isbad**
Attempt to fix #2530
@ktsaou please check the fix
fixes https://github.com/firehol/netdata/issues/2603

### CODE REVIEW

**Comment by ktsaou** [comment]
Thanks!

I will be on a trip for a few days. I'll install it on the proxy in question as soon as I get back.

**Comment by ktsaou** [comment]
I have installed it.
It seems stable. I am not sure I can reproduce the issue though (I couldn't even before this PR).
So, unless you any reason not to, I suggest to merge this.
What do you think?

**Comment by ktsaou** [comment]
This is stable.
Merge?

**Comment by l2isbad** [comment]
> Merge?

👍

**Comment by ktsaou** [comment]
merged it.

**Pull request merged**
