### PR TITLE
multi-os, multi-host alarms and alarm-templates; fix streaming on freebsd; more bug fixes

### LINKED ISSUE #2586: Set FROM header with more specific parameters
Hi, 

Very happy to see #2548 being implemented so fast with #2552 

In my case (very restrictive outgoing rules on the smtp server) I have to patch plugins.d/alarm-notify.sh further. So far I've got it to work by adding flags to sendmail : 

```
        "${sendmail}" -t -f 'example@host.com' -F "Full Name Example"
```

The SMTP server also checks for "Full Name Example"... 

Do you know if there is a better way to use sendmail in this script ? 

In any case, would it be possible to make this configurable from conf.d/health_alarm_notify.conf ? 

Thanks for a great piece of software!

### LINKED ISSUE #2608: multi-os alarms at netdata master
The way alarms are handled for different O/Ses, it is impossible for a netdata master to process alarms for multiple operating system types (linux, freebsd, macos). Today a different set of alarms is installed, depending on the operating system.

Ideally, netdata should support an `os` match on alarms and allow the same alarm to be loaded multiple times, each for different conditions (families, os, etc). So, O/S should be a runtime decision.

CC: @simonnagl (we had discussed this in the past, and I had agreed with your suggestion - but unfortunately, it now limits netdata so we have to turn this around).

### LINKED ISSUE #2665: fping does not run under user netdata
The fping plugin aborts every time after a few ms:

> 2017-09-01 17:54:11: netdata INFO : PLUGINSD: '/opt/netdata/usr/libexec/netdata/plugins.d/fping.plugin' running on pid 31449
> ...
> (null): can't create socket (must run as root?) : Permission denied
> 2017-09-01 17:54:11: netdata ERROR: PLUGINSD: /opt/netdata/usr/libexec/netdata/plugins.d/fping.plugin : read failed.

It seems that the `(null)` message applies to fping, as it's always close to fping failing.

I've tried setuid:
```
$> ls -l /usr/bin/fping
-rwsr-xr-x 1 root root 39232 Jan 11  2017 /usr/bin/fping
```

I've tried running it directly as user `netdata`, this works:
```
$> sudo -u netdata bash /opt/netdata/usr/libexec/netdata/plugins.d/fping.plugin 1
CHART fping.google_com_packets '' 'FPing Packets for host google.com' packets 'google_com' fping.packets line 110020 1
DIMENSION xmt sent absolute 1 1
DIMENSION rcv received absolute 1 1
BEGIN fping.google_com_packets
SET xmt = 1
SET rcv = 1
END
CHART fping.google_com_quality '' 'FPing Quality for host google.com' percentage 'google_com' fping.quality area 110010 1
DIMENSION returned '' absolute 1 1
BEGIN fping.google_com_quality
SET returned = 100
END
CHART fping.google_com_latency '' 'FPing Latency for host google.com' ms 'google_com' fping.latency area 110000 1
DIMENSION min minimum absolute 10 1000
DIMENSION max maximum absolute 10 1000
DIMENSION avg average absolute 10 1000
BEGIN fping.google_com_latency
SET min = 1246
SET avg = 1246
SET max = 1246
END
BEGIN fping.google_com_packets
SET xmt = 0
SET rcv = 0
END
BEGIN fping.google_com_quality
SET returned = 0
END
BEGIN fping.google_com_latency
END
^Cgoogle.com : xmt/rcv/%loss = 2/2/0%, min/avg/max = 12.4/12.4/12.4
```

I've verified that the plugin runs as user netdata:
```bash
#!/bin/bash
# fp-sample
while true; do
    ps ax -o pid,user,group,cmd | grep -e "[f]ping"
done
```
```
$> sudo service netdata restart && ./fp-sample
 5566 netdata  netdata  /usr/bin/env bash /opt/netdata/usr/libexec/netdata/plugins.d/fping.plugin 1
^C
```

No idea what else I can do :(

Similar closed issue here: #2133 
Envrionment:
```
$> uname -a
Linux spg-ops 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux
$> /opt/netdata/bin/netdata -v
netdata 1.7.0-189-g06de36a9_rolling
```

### LINKED ISSUE #2683: streaming / replication does not work on freebsd
I've just setup a master netdata node with a single slave, with the following details:

Master: Ubuntu 16.04.3, netdata v1.7.0-211-gaebbd49_rolling
Slave: pfSense 2.3.4-RELEASE-p1, netdata v1.7.0

Here's the stream config I've got on the master (hostname: maine, ip: 192.168.1.3):

```
[111-222-333-444-555]
    enabled = yes
    default history = 3600
    default memory mode = ram
    health enabled by default = auto
    default postpone alarms on connect seconds = 60
```

And on the slave (hostname: router, ip: 192.168.1.1):

```
[stream]
    enabled = yes
    destination = maine:19999
    api key = 111-222-333-444-555
    timeout seconds = 60
    default port = 19999
    buffer size bytes = 1048576
    reconnect delay seconds = 5
    initial clock resync iterations = 60
```

But I'm seeing repeated connection failures when the slave is trying to send.

Master log (grepped for STREAM):

```
2017-09-06 00:23:51: netdata INFO : STREAM [receive from [192.168.1.1]:39920]: new client connection.
2017-09-06 00:23:51: netdata INFO : STREAM router [192.168.1.1]:39920: receive thread created (task id 7754)
2017-09-06 00:23:51: netdata INFO : STREAM router [receive from [192.168.1.1]:39920]: initializing communication...
2017-09-06 00:23:51: netdata INFO : STREAM router [receive from [192.168.1.1]:39920]: receiving metrics...
2017-09-06 00:23:51: netdata ERROR: STREAM router [receive from [192.168.1.1]:39920]: disconnected (completed updates 11).
2017-09-06 00:23:51: netdata INFO : STREAM router [receive from [192.168.1.1]:39920]: receive thread ended (task id 7754)
2017-09-06 00:23:51: netdata INFO : STREAM [receive from [192.168.1.1]:39921]: new client connection.
2017-09-06 00:23:51: netdata INFO : STREAM router [192.168.1.1]:39921: receive thread created (task id 7756)
2017-09-06 00:23:51: netdata INFO : STREAM router [receive from [192.168.1.1]:39921]: initializing communication...
2017-09-06 00:23:51: netdata INFO : STREAM router [receive from [192.168.1.1]:39921]: receiving metrics...
2017-09-06 00:23:51: netdata ERROR: STREAM router [receive from [192.168.1.1]:39921]: disconnected (completed updates 0).
2017-09-06 00:23:51: netdata INFO : STREAM router [receive from [192.168.1.1]:39921]: receive thread ended (task id 7756)
2017-09-06 00:23:51: netdata INFO : STREAM [receive from [192.168.1.1]:39922]: new client connection.
2017-09-06 00:23:51: netdata INFO : STREAM router [192.168.1.1]:39922: receive thread created (task id 7758)
2017-09-06 00:23:51: netdata INFO : STREAM router [receive from [192.168.1.1]:39922]: initializing communication...
2017-09-06 00:23:51: netdata INFO : STREAM router [receive from [192.168.1.1]:39922]: receiving metrics...
2017-09-06 00:23:52: netdata ERROR: STREAM router [receive from [192.168.1.1]:39922]: disconnected (completed updates 0).
2017-09-06 00:23:52: netdata INFO : STREAM router [receive from [192.168.1.1]:39922]: receive thread ended (task id 7758)
2017-09-06 00:23:52: netdata INFO : STREAM [receive from [192.168.1.1]:39923]: new client connection.
2017-09-06 00:23:52: netdata INFO : STREAM router [192.168.1.1]:39923: receive thread created (task id 7760)
2017-09-06 00:23:52: netdata INFO : STREAM router [receive from [192.168.1.1]:39923]: initializing communication...
2017-09-06 00:23:52: netdata INFO : STREAM router [receive from [192.168.1.1]:39923]: receiving metrics...
2017-09-06 00:23:53: netdata ERROR: STREAM router [receive from [192.168.1.1]:39923]: disconnected (completed updates 0).
2017-09-06 00:23:53: netdata INFO : STREAM router [receive from [192.168.1.1]:39923]: receive thread ended (task id 7760)
2017-09-06 00:23:53: netdata INFO : STREAM [receive from [192.168.1.1]:39924]: new client connection.
2017-09-06 00:23:53: netdata INFO : STREAM router [192.168.1.1]:39924: receive thread created (task id 7763)
2017-09-06 00:23:53: netdata INFO : STREAM router [receive from [192.168.1.1]:39924]: initializing communication...
2017-09-06 00:23:53: netdata INFO : STREAM router [receive from [192.168.1.1]:39924]: receiving metrics...
2017-09-06 00:23:54: netdata ERROR: STREAM router [receive from [192.168.1.1]:39924]: disconnected (completed updates 0).
2017-09-06 00:23:54: netdata INFO : STREAM router [receive from [192.168.1.1]:39924]: receive thread ended (task id 7763)
2017-09-06 00:23:54: netdata INFO : STREAM [receive from [192.168.1.1]:39925]: new client connection.
2017-09-06 00:23:54: netdata INFO : STREAM router [192.168.1.1]:39925: receive thread created (task id 7765)
2017-09-06 00:23:54: netdata INFO : STREAM router [receive from [192.168.1.1]:39925]: initializing communication...
2017-09-06 00:23:54: netdata INFO : STREAM router [receive from [192.168.1.1]:39925]: receiving metrics...
2017-09-06 00:23:54: netdata ERROR: STREAM router [receive from [192.168.1.1]:39925]: disconnected (completed updates 0).
2017-09-06 00:23:54: netdata INFO : STREAM router [receive from [192.168.1.1]:39925]: receive thread ended (task id 7765)
2017-09-06 00:23:54: netdata INFO : STREAM [receive from [192.168.1.1]:39926]: new client connection.
2017-09-06 00:23:54: netdata INFO : STREAM router [192.168.1.1]:39926: receive thread created (task id 7767)
2017-09-06 00:23:54: netdata INFO : STREAM router [receive from [192.168.1.1]:39926]: initializing communication...
2017-09-06 00:23:54: netdata INFO : STREAM router [receive from [192.168.1.1]:39926]: receiving metrics...
2017-09-06 00:23:55: netdata ERROR: STREAM router [receive from [192.168.1.1]:39926]: disconnected (completed updates 0).
2017-09-06 00:23:55: netdata INFO : STREAM router [receive from [192.168.1.1]:39926]: receive thread ended (task id 7767)
2017-09-06 00:23:55: netdata INFO : STREAM [receive from [192.168.1.1]:39927]: new client connection.
2017-09-06 00:23:55: netdata INFO : STREAM router [192.168.1.1]:39927: receive thread created (task id 7769)
2017-09-06 00:23:55: netdata INFO : STREAM router [receive from [192.168.1.1]:39927]: initializing communication...
2017-09-06 00:23:55: netdata INFO : STREAM router [receive from [192.168.1.1]:39927]: receiving metrics...
2017-09-06 00:23:56: netdata ERROR: STREAM router [receive from [192.168.1.1]:39927]: disconnected (completed updates 0).
2017-09-06 00:23:56: netdata INFO : STREAM router [receive from [192.168.1.1]:39927]: receive thread ended (task id 7769)
2017-09-06 00:23:56: netdata INFO : STREAM [receive from [192.168.1.1]:39928]: new client connection.
2017-09-06 00:23:56: netdata INFO : STREAM router [192.168.1.1]:39928: receive thread created (task id 7773)
2017-09-06 00:23:56: netdata INFO : STREAM router [receive from [192.168.1.1]:39928]: initializing communication...
2017-09-06 00:23:56: netdata INFO : STREAM router [receive from [192.168.1.1]:39928]: receiving metrics...
2017-09-06 00:23:57: netdata ERROR: STREAM router [receive from [192.168.1.1]:39928]: disconnected (completed updates 0).
2017-09-06 00:23:57: netdata INFO : STREAM router [receive from [192.168.1.1]:39928]: receive thread ended (task id 7773)
2017-09-06 00:24:58: netdata INFO : STREAM [receive from [192.168.1.1]:48927]: new client connection.
2017-09-06 00:24:58: netdata INFO : STREAM router [192.168.1.1]:48927: receive thread created (task id 7885)
2017-09-06 00:24:58: netdata INFO : STREAM router [receive from [192.168.1.1]:48927]: initializing communication...
2017-09-06 00:24:58: netdata INFO : STREAM router [receive from [192.168.1.1]:48927]: receiving metrics...
2017-09-06 00:24:58: netdata ERROR: STREAM router [receive from [192.168.1.1]:48927]: disconnected (completed updates 0).
2017-09-06 00:24:58: netdata INFO : STREAM router [receive from [192.168.1.1]:48927]: receive thread ended (task id 7885)
2017-09-06 00:24:58: netdata INFO : STREAM [receive from [192.168.1.1]:31240]: new client connection.
2017-09-06 00:24:58: netdata INFO : STREAM router [192.168.1.1]:31240: receive thread created (task id 7887)
2017-09-06 00:24:58: netdata INFO : STREAM router [receive from [192.168.1.1]:31240]: initializing communication...
2017-09-06 00:24:58: netdata INFO : STREAM router [receive from [192.168.1.1]:31240]: receiving metrics...
2017-09-06 00:24:59: netdata ERROR: STREAM router [receive from [192.168.1.1]:31240]: disconnected (completed updates 0).
2017-09-06 00:24:59: netdata INFO : STREAM router [receive from [192.168.1.1]:31240]: receive thread ended (task id 7887)
```

Slave log:

```
2017-09-06 00:23:51: netdata INFO : STREAM router [send]: thread created (task id 100353)
2017-09-06 00:23:51: netdata ERROR: STREAM router [send]: not ready - discarding collected metrics.
2017-09-06 00:23:51: netdata INFO : STREAM router [send to maine:19999]: connecting...
2017-09-06 00:23:51: netdata INFO : STREAM router [send to maine:19999]: initializing communication...
2017-09-06 00:23:51: netdata INFO : STREAM router [send to maine:19999]: waiting response from remote netdata...
2017-09-06 00:23:51: netdata INFO : STREAM router [send to maine:19999]: established communication - sending metrics...
2017-09-06 00:23:51: netdata INFO : STREAM router [send]: ready - sending metrics...
2017-09-06 00:23:51: netdata ERROR: STREAM router [send to maine:19999]: failed to send metrics - closing connection - we have sent 12536 bytes on this connection. (errno 32, Broken pipe)
2017-09-06 00:23:51: netdata INFO : STREAM router [send to maine:19999]: connecting...
2017-09-06 00:23:51: netdata ERROR: STREAM router [send]: not ready - discarding collected metrics.
2017-09-06 00:23:51: netdata INFO : STREAM router [send to maine:19999]: initializing communication...
2017-09-06 00:23:51: netdata INFO : STREAM router [send to maine:19999]: waiting response from remote netdata...
2017-09-06 00:23:51: netdata INFO : STREAM router [send to maine:19999]: established communication - sending metrics...
2017-09-06 00:23:51: netdata ERROR: STREAM router [send]: discarding 21980 bytes of metrics already in the buffer.
2017-09-06 00:23:51: netdata INFO : STREAM router [send]: ready - sending metrics...
2017-09-06 00:23:51: netdata ERROR: STREAM router [send to maine:19999]: failed to send metrics - closing connection - we have sent 6899 bytes on this connection. (errno 32, Broken pipe)
2017-09-06 00:23:51: netdata INFO : STREAM router [send to maine:19999]: connecting...
2017-09-06 00:23:51: netdata ERROR: STREAM router [send]: not ready - discarding collected metrics.
2017-09-06 00:23:51: netdata INFO : STREAM router [send to maine:19999]: initializing communication...
2017-09-06 00:23:51: netdata INFO : STREAM router [send to maine:19999]: waiting response from remote netdata...
2017-09-06 00:23:51: netdata INFO : STREAM router [send to maine:19999]: established communication - sending metrics...
2017-09-06 00:23:51: netdata ERROR: STREAM router [send]: discarding 8988 bytes of metrics already in the buffer.
2017-09-06 00:23:52: netdata INFO : STREAM router [send]: ready - sending metrics...
2017-09-06 00:23:52: netdata ERROR: STREAM router [send to maine:19999]: failed to send metrics - closing connection - we have sent 6992 bytes on this connection. (errno 32, Broken pipe)
2017-09-06 00:23:52: netdata INFO : STREAM router [send to maine:19999]: connecting...
2017-09-06 00:23:52: netdata ERROR: STREAM router [send]: not ready - discarding collected metrics.
2017-09-06 00:23:52: netdata INFO : STREAM router [send to maine:19999]: initializing communication...
2017-09-06 00:23:52: netdata INFO : STREAM router [send to maine:19999]: waiting response from remote netdata...
2017-09-06 00:23:52: netdata INFO : STREAM router [send to maine:19999]: established communication - sending metrics...
2017-09-06 00:23:52: netdata ERROR: STREAM router [send]: discarding 32840 bytes of metrics already in the buffer.
2017-09-06 00:23:52: netdata INFO : STREAM router [send]: ready - sending metrics...
2017-09-06 00:23:53: netdata ERROR: STREAM router [send to maine:19999]: failed to send metrics - closing connection - we have sent 6484 bytes on this connection. (errno 32, Broken pipe)
2017-09-06 00:23:53: netdata INFO : STREAM router [send to maine:19999]: connecting...
2017-09-06 00:23:53: netdata ERROR: STREAM router [send]: not ready - discarding collected metrics. (errno 2, No such file or directory)
2017-09-06 00:23:53: netdata INFO : STREAM router [send to maine:19999]: initializing communication...
2017-09-06 00:23:53: netdata INFO : STREAM router [send to maine:19999]: waiting response from remote netdata...
2017-09-06 00:23:53: netdata INFO : STREAM router [send to maine:19999]: established communication - sending metrics...
2017-09-06 00:23:53: netdata ERROR: STREAM router [send]: discarding 25114 bytes of metrics already in the buffer.
2017-09-06 00:23:53: netdata INFO : STREAM router [send]: ready - sending metrics...
2017-09-06 00:23:54: netdata ERROR: STREAM router [send to maine:19999]: failed to send metrics - closing connection - we have sent 6452 bytes on this connection. (errno 32, Broken pipe)
2017-09-06 00:23:54: netdata INFO : STREAM router [send to maine:19999]: connecting...
2017-09-06 00:23:54: netdata ERROR: STREAM router [send]: not ready - discarding collected metrics. (errno 2, No such file or directory)
2017-09-06 00:23:54: netdata INFO : STREAM router [send to maine:19999]: initializing communication...
2017-09-06 00:23:54: netdata INFO : STREAM router [send to maine:19999]: waiting response from remote netdata...
2017-09-06 00:23:54: netdata INFO : STREAM router [send to maine:19999]: established communication - sending metrics...
2017-09-06 00:23:54: netdata ERROR: STREAM router [send]: discarding 20532 bytes of metrics already in the buffer.
2017-09-06 00:23:54: netdata INFO : STREAM router [send]: ready - sending metrics...
2017-09-06 00:23:54: netdata ERROR: STREAM router [send to maine:19999]: failed to send metrics - closing connection - we have sent 6109 bytes on this connection. (errno 32, Broken pipe)
2017-09-06 00:23:54: netdata INFO : STREAM router [send to maine:19999]: connecting...
2017-09-06 00:23:54: netdata INFO : STREAM router [send to maine:19999]: initializing communication...
2017-09-06 00:23:54: netdata INFO : STREAM router [send to maine:19999]: waiting response from remote netdata...
2017-09-06 00:23:54: netdata INFO : STREAM router [send to maine:19999]: established communication - sending metrics...
2017-09-06 00:23:54: netdata ERROR: STREAM router [send]: discarding 16124 bytes of metrics already in the buffer.
2017-09-06 00:23:55: netdata ERROR: STREAM router [send to maine:19999]: failed to send metrics - closing connection - we have sent 6992 bytes on this connection. (errno 32, Broken pipe)
2017-09-06 00:23:55: netdata INFO : STREAM router [send to maine:19999]: connecting...
2017-09-06 00:23:55: netdata ERROR: STREAM router [send]: not ready - discarding collected metrics. (errno 2, No such file or directory)
2017-09-06 00:23:55: netdata INFO : STREAM router [send to maine:19999]: initializing communication...
2017-09-06 00:23:55: netdata INFO : STREAM router [send to maine:19999]: waiting response from remote netdata...
2017-09-06 00:23:55: netdata INFO : STREAM router [send to maine:19999]: established communication - sending metrics...
2017-09-06 00:23:55: netdata ERROR: STREAM router [send]: discarding 40585 bytes of metrics already in the buffer.
2017-09-06 00:23:55: netdata INFO : STREAM router [send]: ready - sending metrics...
2017-09-06 00:23:56: netdata ERROR: STREAM router [send to maine:19999]: failed to send metrics - closing connection - we have sent 7414 bytes on this connection. (errno 32, Broken pipe)
2017-09-06 00:23:56: netdata INFO : STREAM router [send to maine:19999]: connecting...
2017-09-06 00:23:56: netdata ERROR: STREAM router [send]: not ready - discarding collected metrics. (errno 2, No such file or directory)
2017-09-06 00:23:56: netdata INFO : STREAM router [send to maine:19999]: initializing communication...
2017-09-06 00:23:56: netdata INFO : STREAM router [send to maine:19999]: waiting response from remote netdata...
2017-09-06 00:23:56: netdata INFO : STREAM router [send to maine:19999]: established communication - sending metrics...
2017-09-06 00:23:56: netdata ERROR: STREAM router [send]: discarding 33457 bytes of metrics already in the buffer.
2017-09-06 00:23:56: netdata INFO : STREAM router [send]: ready - sending metrics...
2017-09-06 00:24:58: netdata ERROR: STREAM router [send to maine:19999]: could not send metrics for 60 seconds - closing connection - we have sent 8192 bytes on this connection.
2017-09-06 00:24:58: netdata INFO : STREAM router [send to maine:19999]: connecting...
2017-09-06 00:24:58: netdata INFO : STREAM router [send to maine:19999]: initializing communication...
2017-09-06 00:24:58: netdata ERROR: STREAM router [send]: not ready - discarding collected metrics. (errno 2, No such file or directory)
2017-09-06 00:24:58: netdata INFO : STREAM router [send to maine:19999]: waiting response from remote netdata...
2017-09-06 00:24:58: netdata INFO : STREAM router [send to maine:19999]: established communication - sending metrics...
2017-09-06 00:24:58: netdata ERROR: STREAM router [send]: discarding 956127 bytes of metrics already in the buffer.
2017-09-06 00:24:58: netdata INFO : STREAM router [send]: ready - sending metrics...
2017-09-06 00:24:58: netdata ERROR: STREAM router [send to maine:19999]: failed to send metrics - closing connection - we have sent 4950 bytes on this connection. (errno 32, Broken pipe)
2017-09-06 00:24:58: netdata INFO : STREAM router [send to maine:19999]: connecting...
2017-09-06 00:24:58: netdata INFO : STREAM router [send to maine:19999]: initializing communication...
2017-09-06 00:24:58: netdata INFO : STREAM router [send to maine:19999]: waiting response from remote netdata...
2017-09-06 00:24:58: netdata INFO : STREAM router [send to maine:19999]: established communication - sending metrics...
2017-09-06 00:24:58: netdata ERROR: STREAM router [send]: discarding 8185 bytes of metrics already in the buffer.
```

There's obviously a connection being established, but I'm not sure why it keeps dropping. Any suggestions would be gratefully received...

### LINKED ISSUE #2694: master netdata does not execute alarm-notify.sh for all alarms of all hosts
When a netdata is hosting multiple databases for multiple hosts, the action script defined for each alarm is not executed for all alarms of all hosts.

The problem seems to be a caching made by netdata that uses ids of one host to resume alarms execution on another host.

### PR DESCRIPTION
**Pull request by ktsaou**
This PR adds the following configuration lines to alarms and alarm templates:

#### alarm line `os`

This alarm or template will be used only if the O/S of the host loading it, matches this pattern list. The value is a space separated list of simple patterns (use `*` as wildcard, prefix with `!` for a negative match, order is important).

```
os: linux freebsd macos
```

#### alarm line `hosts`

This alarm or template will be used only if the hostname of the host loading it, matches this pattern list. The value is a space separated list of simple patterns (use `*` as wildcard, prefix with `!` for a negative match, order is important).

```
hosts: server1 server2 database* !redis3 redis*
```

The above says: use this alarm on all hosts named `server1`, `server2`, `database*`, and all `redis*` except `redis3`.

---

This PR also allows the same alarm template to be loaded multiple times, with different `families` line each.

---

Also:

1. fixes #2608 (multi-os alarms)
2. fixes #2665 (fping is not setuid in binary packages - fping.plugin logs the exact fping it runs)
3. fixes a minor issue (a conditional jump was sometimes depend on an uninitialized value)
4. cpu metrics collection is now a lot faster
5. fixes #2586 (removed single quotes from the `-f` option to `sendmail`)
6. streaming was not working on freebsd. fixes #2683 . There were 2 problems:
   i. freebsd is using metric IDs with spaces (mainly interrupts). I fixed the streaming protocol to handle them properly, but @vlvkobal I think we should fix them. Actually the metrics names have fixed length like `'irq1: atkbd0       '`. These spaces were making the master netdata reject the client (close its socket).
   ii. netdata was not properly handling all error cases when acting as a slave, this resulted in 100% cpu utilization (the socket was closed by the master, but the slave was repeating forever to send metrics without reopening the socket).
7. fixes #2694 (not all per host alarm actions are executed by netdata masters)
8. slack and discord notifications show the sending host at their footer

### CODE REVIEW

**Comment by ktsaou** [comment]
not tested yet

**Comment by ktsaou** [comment]
this is now tested.

**Comment by ktsaou** [comment]
updated the wiki too: https://github.com/firehol/netdata/wiki/health-configuration-reference

**Comment by vlvkobal** [comment]
> i. freebsd is using metric IDs with spaces (mainly interrupts). I fixed the streaming protocol to handle them properly, but @vlvkobal I think we should fix them. Actually the metrics names have fixed length like 'irq1: atkbd0 '. These spaces were making the master netdata reject the client (close its socket).

@ktsaou Should I delete trailing spaces and change other ones to underscores? Is it worth having so many char operations in every cycle?

**Pull request merged**
