### PR TITLE
fail2ban: jailes search function bugfix

### PR DESCRIPTION
**Pull request by l2isbad**
fixes https://github.com/firehol/netdata/issues/2702

@G4Zz0L1 
i think i fixed the bug, please check

### CODE REVIEW

**Comment by G4Zz0L1** [comment]
Nope, same resut from the debug:

2017-09-09 17:58:57: python.d INFO: fail2ban Jails: ['pam-generic', 'apache-overflows', 'apache-shellshock', 'apache-modsecurity', 'apache-nohome', 'recidive', 'apache-badbots', 'apache-botsearch', 'apache-auth', 'webmin-auth', 'sendmail-auth', 'apache-noscript', 'php-url-fopen', 'apache-fakegooglebot']

**Comment by l2isbad** [comment]
Ok, i replaced my jail.local with https://pastebin.com/c4JKnjaE


[/opt/netdata/usr/libexec/netdata/plugins.d]./python.d.plugin 1 debug fail2ban
...
2017-09-10 01:05:19: python.d INFO: fail2ban Jails: ['php-url-fopen', 'sshd', 'webmin-auth', 'apache-noscript', 'apache-modsecurity', 'sendmail-reject', 'sendmail-auth', 'apache-badbots', 'apache-nohome', 'postfix-sasl', 'apache-auth', 'postfix', 'apache-botsearch', 'apache-overflows', 'apache-fakegooglebot', 'postfix-rbl', 'recidive', 'apache-shellshock', 'pam-generic']
2017-09-10 01:05:19: python.d INFO: CHECKED OK: fail2ban

All 19 jails were found.

Did you use new version?

**Comment by G4Zz0L1** [comment]
I've manually edit the fail2ban.chart.py with your commit, but the debug still shows only that:

2017-09-09 18:14:04: python.d INFO: fail2ban Jails: ['apache-badbots', 'apache-noscript', 'sendmail-auth', 'apache-nohome', 'php-url-fopen', 'apache-overflows', 'pam-generic', 'recidive', 'apache-auth', 'webmin-auth', 'apache-modsecurity', 'apache-shellshock', 'apache-botsearch', 'apache-fakegooglebot']

**Comment by l2isbad** [comment]
Well, my `jail.local `is identical to yours and if code is identical too results should be the same. It works for me.

**Comment by l2isbad** [comment]
lets merge it and then you will try again
@ktsaou ready

**Comment by ktsaou** [comment]
merged

**Comment by G4Zz0L1** [comment]
Just pulled, everything's the same... I don't understand...

`2017-09-09 18:46:48: python.d INFO: fail2ban Jails: ['apache-nohome', 'apache-auth', 'recidive', 'sendmail-auth', 'pam-generic', 'php-url-fopen', 'apache-shellshock', 'webmin-auth', 'apache-badbots', 'apache-fakegooglebot', 'apache-overflows', 'apache-noscript', 'apache-modsecurity', 'apache-botsearch']
2017-09-09 18:46:48: python.d INFO: CHECKED OK: fail2ban`

**Comment by l2isbad** [comment]
Lets do step by step in python interpreter
```
cd to dir with jail.local
python
```
```python
lgz@lgz-homepc[~]python
Python 3.6.2 (default, Jul 20 2017, 03:52:27) 
[GCC 7.1.1 20170630] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pprint import pprint
>>> import re
>>> f = [l for l in open('jail.local').readlines() if l.startswith(('[', 'enabled'))]
>>> pprint(f)
['[INCLUDES]\n',
 '[DEFAULT]\n',
 'enabled = false\n',
 '[sshd]\n',
 'enabled = true\n',
 '[apache-auth]\n',
 'enabled = true\n',
 '[apache-badbots]\n',
 'enabled = true\n',
 '[apache-noscript]\n',
 'enabled = true\n',
 '[apache-overflows]\n',
 'enabled = true\n',
 '[apache-nohome]\n',
 'enabled = true\n',
 '[apache-botsearch]\n',
 'enabled = true\n',
 '[apache-fakegooglebot]\n',
 'enabled = true\n',
 '[apache-modsecurity]\n',
 'enabled = true\n',
 '[apache-shellshock]\n',
 'enabled = true\n',
 '[php-url-fopen]\n',
 'enabled = true\n',
 '[webmin-auth]\n',
 'enabled = true\n',
 '[postfix]\n',
 'enabled = true\n',
 '[postfix-rbl]\n',
 'enabled = true\n',
 '[sendmail-auth]\n',
 'enabled = true\n',
 '[sendmail-reject]\n',
 'enabled = true\n',
 '[postfix-sasl]\n',
 'enabled = true\n',
 '[recidive]\n',
 'enabled = true\n',
 '[pam-generic]\n',
 'enabled = true\n']
>>> pprint(list(enumerate(re.findall(r'\[([a-zA-Z0-9_-]+)\][^\[\]]+?enabled\s+= (true|false)', ' '.join(f)))))
[(0, ('DEFAULT', 'false')),
 (1, ('sshd', 'true')),
 (2, ('apache-auth', 'true')),
 (3, ('apache-badbots', 'true')),
 (4, ('apache-noscript', 'true')),
 (5, ('apache-overflows', 'true')),
 (6, ('apache-nohome', 'true')),
 (7, ('apache-botsearch', 'true')),
 (8, ('apache-fakegooglebot', 'true')),
 (9, ('apache-modsecurity', 'true')),
 (10, ('apache-shellshock', 'true')),
 (11, ('php-url-fopen', 'true')),
 (12, ('webmin-auth', 'true')),
 (13, ('postfix', 'true')),
 (14, ('postfix-rbl', 'true')),
 (15, ('sendmail-auth', 'true')),
 (16, ('sendmail-reject', 'true')),
 (17, ('postfix-sasl', 'true')),
 (18, ('recidive', 'true')),
 (19, ('pam-generic', 'true'))]
>>> 


```

**Comment by G4Zz0L1** [comment]
As soon as I get home I'll try that and report, thanks for your time in the
meantime.

**Comment by G4Zz0L1** [comment]
I've tried those commands, and they works ok.
I've force updated via the script (-f option) and the jail are 19 now, the module works as it should.
I don't know why the manually edited script doesn't get all the jails though, maybe I've made something wrong, but now it's everything's fine!
Thanks for all!

**Pull request merged**
