### PR TITLE
Support older autoconf versions

### LINKED ISSUE #1767: fail to build cloudlinux 6
Hello,

When ibuild in cloudlinux 6 i have error belows:

configure.ac:15: error: possibly undefined macro: m4_esyscmd_s
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

Someone help me !

Best Regard

### PR DESCRIPTION
**Pull request by simonnagl**
Tries to fix #1767

I do not have access to a old version. 

- [ ] Verify this is fixed.

### CODE REVIEW

**Comment by ktsaou** [comment]
works for centos 6.8, but version is like this: `1.5.1_rolling`

**Comment by ktsaou** [comment]
oh! I see `git describe` does not work at all.

**Comment by ktsaou** [comment]
```sh
git describe
fatal: No tags can describe '8d5fab2806c78aea4f431dce23a4eae46dcce120'.
Try --always, or create some tags.
```

**Comment by ktsaou** [comment]
I think this `git describe` issue is triggered by `git clone ... --depth=1`.
So, most new users will not have a commit id.

**Comment by simonnagl** [comment]
You are right. But I do not think we can solve this without rechecking against GitHub. And this is something I do not like because it needs internet connection.

**Pull request merged**
