### PR TITLE
dashboard improvements related to health monitoring

### PR DESCRIPTION
**Pull request by ktsaou**
much better I think:

image

### CODE REVIEW

**Comment by paulfantom** [comment]
Looks great!

**Comment by ktsaou** [comment]
I did a few more:

image

**Comment by ktsaou** [comment]
I am searching for a timeline plugin to visualize the log of alarms...

**Comment by ktsaou** [comment]
hm... can't find anything very good for a timeline...
I am merging this now and I'll continue later.

**Comment by LucaDev** [comment]
What do you think about http://stoicloofah.github.io/chronoline.js/ and http://timeglider.com/widget/?p=intro

**Comment by paulfantom** [comment]
I can only say that cronoline.js doesn't work on [Vivaldi](https://vivaldi.com/).

**Comment by ktsaou** [comment]
timeglider could do it, but does not have a license I like...

http://timeline.knightlab.com/ is nice, but seems heavy.

So far, I am flerting with http://almende.github.io/chap-links-library/js/timeline/examples/example02_interactive.html (full docs at: http://almende.github.io/chap-links-library/timeline.html)

**Comment by ktsaou** [comment]
This is also impressive: https://github.com/wellcometrust/timeline
demo: http://wellcomelibrary.org/collections/digital-collections/makers-of-modern-genetics/genetics-timeline/

Imagine that once you click on a flag, the information box below will show all the details of the alarm.
You can navigate from alarm to alarm using the arrow buttons on the information box too.

This requires a lot more components to be distributed with netdata...

**Comment by LucaDev** [comment]
We could try forking wellcometrust/timeline to simplify it to meet our needs

**Pull request merged**
