### PR TITLE
Fixing python

### PR DESCRIPTION
**Pull request by paulfantom**
Probably fixed your previous commit.

Global variable `UPDATE_EVERY` (previously `INTERVAL`) was used in a very strange way (it was very unreadable what was it doing). I fixed it, and now default value of `update_every` is stored properly in `BASE_CONFIG`.

To enable overriding it in debug mode (like `python.d.plugin debug mysql 1`) I have added `OVERRIDE_UPDATE_EVERY`.

Also passing `*sys.argv` to `parse_cmdline()` is probably resolved. I don't know since I don't know what was the issue, but it works.

### CODE REVIEW

**Comment by ktsaou** [comment]
Thanks.
Could you please add a few `debug()` statements to show the operation in key places? For example, running:

```sh
./plugins.d/python.d.plugin debug >/dev/null
```

Should give an overview of what the plugin is doing (including timing calculations).
I need this to verify it works properly.

**Comment by paulfantom** [comment]
Ok, I will add it in about 3-4 hours.

**Comment by paulfantom** [comment]
I have added some more `debug()` invocations in `python.d.plugin`. Not too many, because I really don't know where to add more.

**Comment by ktsaou** [comment]
Well... it does not work for me:

```sh
# ./plugins.d/python.d.plugin debug
python.d INFO:  Using python v2
python.d DEBUG:  started from ./plugins.d/python.d.plugin with options: debug
python.d INFO:  MODULES_DIR='/home/costa/src/netdata-paulfantom.git/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=[]
python.d DEBUG:  [Errno 2] No such file or directory
python.d FATAL:  no modules found.
DISABLE

# ls -l /home/costa/src/netdata-paulfantom.git/python.d/
total 108
-rw-rw-r-- 1 costa costa   992 Jun 21 15:27 example.chart.py
-rw-r--r-- 1 costa costa  1799 Jun 21 15:27 example.chart.pyc
-rw-r--r-- 1 costa costa 18149 Jun 21 15:27 Makefile
-rw-rw-r-- 1 costa costa   300 Jun 19 12:53 Makefile.am
-rw-r--r-- 1 costa costa 18016 Jun 21 15:27 Makefile.in
-rw-rw-r-- 1 costa costa 18569 Jun 21 19:10 mysql.chart.py
-rw-r--r-- 1 costa costa 18793 Jun 21 15:27 mysql.chart.pyc
-rw-rw-r-- 1 costa costa   195 Jun 21 15:27 pip_install.sh
drwxrwxr-x 2 costa costa  4096 Jun 20 09:01 __pycache__
drwxrwxr-x 3 costa costa  4096 Jun 21 15:27 python_modules
-rw-rw-r-- 1 costa costa  2932 Jun 21 09:21 README.md

```

**Comment by ktsaou** [comment]
I confirm that the merged version works in the same system.

**Comment by paulfantom** [comment]
My big mistake. I left some code from debugging future nginx plugin.
The line 
`modules = ['nginx']` 
before 
`charts = PythonCharts(modules, MODULES_DIR, CONFIG_DIR + "python.d/", disabled)`

I have removed it. Now it should work.

**Comment by paulfantom** [comment]
Now on my test machine it works. What about yours?

**Comment by ktsaou** [comment]
merged

**Pull request merged**
