### PR TITLE
Add macOS build to travis.

### PR DESCRIPTION
**Pull request by simonnagl**

### CODE REVIEW

**Comment by simonnagl** [comment]
`make dist-xz` does not work on macOS. This is the reason why I close this for now.

**Comment by simonnagl** [comment]
Reopen. Installed `xz` on macOS now dist-xz works ;)

**Comment by ktsaou** [comment]
hm... re-open is not enabled for some reason.
Can you re-do the PR?

**Comment by simonnagl** [comment]
Check #1733

**Pull request closed without merging**
