### PR TITLE
add variable system.cpu.processors for alarms; 

### LINKED ISSUE #3003: Alarm for big system load
Perhaps it will be good to have alarm for big system load, calculated by number of CPUs on machine.

### PR DESCRIPTION
**Pull request by ktsaou**
This PR adds variable `$system.cpu.processors` that resolves to the number of processors on the system. For systems with dynamic number of processors, this variable is updated together with chart `system.cpu` to match the number of processors listed in `/proc/stat`.

fixes #3003

### CODE REVIEW

**Comment by Ferroin** [comment]
I'll check this overnight on my home server (as mentioned in the associated issue, it shuts down half it's CPU cores overnight to save power), but it looks from here like it works as intended with some manual testing on my laptop.

For reference for anyone else who wants to test this on Linux, individual CPU cores can be toggled on and off by writing 1 or 0 respectively to the `online` file in the core's directory in `/sys/devices/system/cpu`.

**Comment by ktsaou** [comment]
You can check the number of processors reports by this variables, by fetching:

http://localhost:19999/api/v1/alarm_variables?chart=system.cpu

You should see something like this:

```json
{
	"chart": "system.cpu",
	"chart_name": "system.cpu",
	"chart_context": "system.cpu",
	"chart_variables": {
    
                ... many variablesm ...

		"processors": 8.00000,

                ... many variables ...

	},
```

**Comment by Ferroin** [comment]
Oh, nice.  I had actually set up some alarms to trigger on changes to and from certain values to check it here, but that approach makes it _so_ much easier.

**Comment by ktsaou** [comment]
@Ferroin , merge?

**Comment by ktsaou** [comment]
Merged!
Looking forward for that PR...

**Pull request merged**
