### PR TITLE
nginx_log plugin: code optimization, bandwidth + unique visitors charts

### PR DESCRIPTION
**Pull request by l2isbad**
Optimization i made yesterday while talking in https://github.com/firehol/netdata/pull/1337

Do the same job but plus two more charts.
For unique users count script uses bisect algorithm so it's fast.

screenshot_20170204_185139

Works for me, but pls test it @ktsaou 
@shadycuz looks like you are using plugin. Can you test this version?

And what is ['other'](https://github.com/firehol/netdata/blob/master/python.d/nginx_log.chart.py#L22)
Status codes always are (i google it!) 1x|2x|3x|4x|5x
'other' was removed..

### CODE REVIEW

**Comment by ktsaou** [comment]
nice!

standard response codes are 1xx, 2xx, 3xx, 4xx, 5xx but APIs may use whatever they like. So `other` is all the rest. In general, I prefer to never silently ignore data (hence the `other`).

Bandwidth charts have a glitch: if the response takes too long to be dispatched, the whole size of the response is accounted at the final second only. I don't think we can fix this, but we can add a note at `dashboard_info.js`.

Also, please change the title and family to `Response Codes` and `responses` respectively, instead of `Status codes` and `requests`.

I suggest to rename `visitors`, to `clients` and `unique visitors` to `Unique Client IPs` (visitors have a special meaning in web applications, which we cannot track without cookies).

I suggest to add a module configuration option `log_format`, where (http://nginx.org/en/docs/http/ngx_http_log_module.html):

- `combined` is this:

```
log_format combined '$remote_addr - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent"';
```

- `netdata` should be this (suggestions welcome):

```
log_format netdata '$remote_addr - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '$request_length $request_time '
                    '"$http_referer" "$http_user_agent"';
```

The later, logs also the request size (i.e. dimension `received` in the bandwidth chart) and the time it took to process the request (new chart).

Of course the user would also need to configure nginx to use it.

I would also suggest a boolean configuration option `detailed_response_codes` which would enable another chart, that response codes are not grouped (i.e. each response code takes its own dimension).

All these would be a great improvement. What will be missing is:

- a way to group URLs into categories. This would enable another chart: requests per URL category.
- a way to request a different set of all the above charts, per URL category.

**Comment by l2isbad** [comment]
> i.e. each response code takes its own dimension

More then 60 response codes. Are you sure?

**Comment by ktsaou** [comment]
I think we need 3 charts: min, average, max with absolute dimensions calculated by the plugin.

**Comment by ktsaou** [comment]
also, time should be in its own family (not under bandwidth).

**Comment by l2isbad** [comment]
> I think we need 3 charts: min, average, max 

Why different charts? Maybe 1 stacked?

Is it ok now?
screenshot_20170204_223532

> I would also suggest a boolean configuration option detailed_response_codes which would enable another chart, that response codes are not grouped (i.e. each response code takes its own dimension).

Give me a list of response codes which should be in detailed_response_codes chart

**Comment by l2isbad** [comment]
ok, it works with both formats (log_format combined, log_format netdata).
if format is netdata additional chart will appear.

**Comment by ktsaou** [comment]
> Is it ok now?

yes it is.

> Give me a list of response codes which should be in detailed_response_codes chart

hm... it should be dynamic, from whatever the log has

> ok, script works with both formats (log_format combined, log_format netdata).
> if format is netdata additional chart will appear.

nice. Give me some time to install it and test it

**Comment by shadycuz** [comment]
@ktsaou @l2isbad I pull my logs from another server using rsyslog. I don't think that will effect me so I will test this as well.

**Comment by ktsaou** [comment]
@shadycuz nice! thanks!

**Comment by alibo** [comment]
Awesome job! 👍

Also, I added some charts for each status category (5xx, 4xx, ...). We needed to know which 4xx error or 5xx error has occurred. 
If you think it's useful, I can make a PR, or could you please add this feature to this PR too?

status codes

screen shot 2017-02-05 at 10 36 24

Note: I couldn't make it dynamic. I don't know how I can dynamically add new HTTP status codes in `update` method, so I added common HTTP status codes to the config file:

```yaml
...
 2xx: "200 201 206"
 5xx: "500 501 502 503 504"
...
```

**Comment by l2isbad** [comment]
@alibo 

@ktsaou suggested
> I would also suggest a boolean configuration option detailed_response_codes which would enable another chart, that response codes are not grouped (i.e. each response code takes its own dimension).

i will do it

**Comment by alibo** [comment]
@l2isbad Oh, I didn't see it. Thank you so much :)

**Comment by l2isbad** [comment]
@ktsaou @alibo 
Is it ok to have one chart with all codes?
How many different colors can be on chart?

What about to add 2 options to conf file

- `detailed_exclude` - exclude from all status codes 
- `detailed_include` - include to detail view only status codes

screenshot_20170205_204625

**Comment by ktsaou** [comment]
> Is it ok to have one chart with all codes?

I think it is. I have never seen applications/APIs using more than 10-15 of them.
The dashboard has 20 different colors per chart, after that it reuses the same colors. But we could add a slight luminance every time we reuse the same set, to make them a little bit different.

Don't be afraid of it too much. apps.plugin and systemd services generates already a lot more dimensions.

The problem with performance appears when there are more than 20-30 visible dimensions. This chart however will not have more than 5-10 visible at any given time (usually I see only 3-4 of them).

So, the key here is to make the dimensions dynamic. Add them only if the codes are found in the file.

> What about to add 2 options to conf file

I don't mind, as long long as the default is to show all the codes the file has.

**Comment by ktsaou** [comment]
> The reason i didn't do it yet - not fully understand how it should be

hm... I totally understand this. The plugin should re-send the whole chart definition to netdata when dimensions are added. But, I don't know how this can be done in python.d.plugin...

**Comment by alibo** [comment]
@l2isbad 

> Is it ok to have one chart with all codes?
How many different colors can be on chart?

I've tested myself, for our REST API server, it was like a painting :D 
We respond clients with a lot of different status codes:
101, 200, 201, 204, 206, 301, 302, 304, 400, 401, 403, 404, 405, 406, 410, 422, 428, 429, 451, 499, 500, 501, 502, 503, 504
(http://www.restapitutorial.com/httpstatuscodes.html)

Also this was hard to filter a category of status codes. (ex. 4xx, 5xx)

**Comment by l2isbad** [comment]
@ktsaou 

> hm... I totally understand this. The plugin should re-send the whole chart definition to netdata when dimensions are added. But, I don't know how this can be done in python.d.plugin...

What if:
1. Initialize ALL dimension on start ({all codes: 0})
2. After first iteration pass to netdata ONLY status codes from logs (never do step 1)

I think @alibo is right and we need 5 charts - 1xx, 2xx...5xx

screenshot_20170205_232102

**Comment by ktsaou** [comment]
> I think @alibo is right and we need 5 charts - 1xx, 2xx...5xx

make it configuration option then. On my sites, 3 of the 5 charts will be empty all the time. So, let's give the option to have one or another.




> What if:
> 
> Initialize ALL dimension on start ({all codes: 0})
> After first iteration pass to netdata ONLY status codes from logs (never do step 1)

Well, what would you do if someone uses a non-standard response code?

I am confused a bit. If you create the chart with all dimensions (i.e. you send the whole definition to netdata with all possible dimensions), netdata will allocate memory for all dimensions. A total waste of memory.

If you initialize all dimensions in python, but send only the used ones to netdata, it means you already have the means to incrementally send the chart to netdata. So, why to initialize all the possible dimensions in the first place?

Could you please describe the problem you face?

**Comment by l2isbad** [comment]
Ok, now it works the way you suggested @ktsaou 

The only prolbem you need to F5 browser after new dimension added.

screenshot_20170206_035137

And after F5

screenshot_20170206_035333

Am i missing something? How to fix it?

**Comment by shadycuz** [comment]
@l2isbad The dimensions are working fine for me without refreshing, for example after a restart of the netdata service. I have only 5xx in yellow, and then when 2xx showed up it was in blue. It looks very nice =) the work you put into the log plugin.

**Comment by l2isbad** [comment]
@shadycuz you are not on the latest version of the [script](https://github.com/l2isbad/netdata/blob/nginx_log_optimization/python.d/nginx_log.chart.py). 
The problem is on `Detailed` chart.

**Comment by ktsaou** [comment]
I installed the latest version at the registry: http://registry.my-netdata.io/#menu_nginx_log_local
(I didn't restart the registry, so there is a left over chart from the previous version of the module - ignore it - it is the one that is not being refreshed any more).

Nice job! @l2isbad you rock!

Comments:

1. please don't capitilize families

2. `responses`

   1. you are sending to netdata not-used dimensions (they use memory)
   2. please use lowercase family: `responses`

image

3. `timings`

   1. I suggest to use family `timings`
   2. turn it to an area chart
   3. You can reorder the dimensions to get: `min` = green, `max` = red, `avg` = blue.
   4. I suggest to use `milliseconds` for units (too many fraction digits now)
   5. Is the calculation of `min` is wrong? I see it zero constantly.

image

4. `bandwidth`

   1. please use family `bandwidth` (lowercase)
   2. turn it to an `area` chart and make `sent` negative (negative multiplier or divider).
   3. re-arrange the dimensions to have `received` = green, `sent` = red

image

5. `clients`

   1. please use family `clients` (lowercase too)
   2. please lose dimension `foo`
   3. I suggest to also lose dimension `all_time`. The chart will not have any meaning after a day, since `all_time` will take all the visible space. If you do this, turn it to a `line` chart too.

image

6. `detailed`

   1. excellent job !
   2. I think it should be under family `responses`, together with the other chart.

image

**Comment by ktsaou** [comment]
I did a few edits, so please read it on github...

**Comment by ktsaou** [comment]
I did even more edits...

**Comment by l2isbad** [comment]
@ktsaou 
> Is the calculation of min is wrong? I see it zero constantly.

No. There is no calculation. List ordered (bisect). Min - first element. Max - last.

screenshot_20170206_084859

> please lose dimension foo

foo here because of color - i don't like BIG READ all_time dimension.. 😄 

All other suggestion - ok!

**Comment by l2isbad** [comment]
I think I did everything @ktsaou

**Comment by ktsaou** [comment]
installed it at http://registry.my-netdata.io/#menu_nginx_log_local

perfect!

**Comment by ktsaou** [comment]
hm... the detailed chart is missing. Did you remove it?

**Comment by ktsaou** [comment]
hm... I am sceptical about the chart `all_clients`. Does this mean that the plugin is maintaining a list of all client IPs ever seen? On a busy server will this use huge amounts of memory?

**Comment by ktsaou** [comment]
> On a busy server will this use huge amounts of memory?

if it will, is it possible to limit it to an hour or a day? (it is nice - I like it, but make sure it is not problematic).

**Comment by ktsaou** [comment]
@l2isbad this is very nice!

it would be perfect if the users could configure an array of URL patterns to provide a chart with requests per URL category.

So, for example, in the netdata registry nginx log, I would match:

- chart refreshes
- registry calls
- badges

**Comment by l2isbad** [comment]
> hm... the detailed chart is missing. Did you remove it?

You need to enable it. Default is `no`
https://github.com/firehol/netdata/pull/1716/commits/ab170994bacae9e5d0c618e3869e92bb935fda63#diff-686eb6f7f394c280a9acfff1a9e3bfb7R70

**Comment by l2isbad** [comment]
And @ktsaou can you check your logs manually? 
`min` is always 0 it's strange..

**Comment by ktsaou** [comment]
> You need to enable it. Default is no. Or should we set to yes by default?

ok, I added it. Yes, you can enable it by default I think. Is there a reason, not to?

> I think we need to exclude something. /stub_status can be 0.000. Or not. If 0 is min let it be..

hm... netdata is also that fast:

```
127.0.0.1 - - [06/Feb/2017:10:43:48 +0000] "GET /stub_status HTTP/1.1" 200 120 123 0.000 "-" "Python-urllib/2.7"
182.253.121.75 - - [06/Feb/2017:10:43:48 +0000] "OPTIONS /api/v1/data?chart=netdata.net&format=array&points=300&group=average&options=absolute|jsonwrap|nonzero&after=-300&dimensions=in&_=1486377578943 HTTP/1.1" 200 29 730 0.000 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
182.253.121.75 - - [06/Feb/2017:10:43:48 +0000] "GET /api/v1/data?chart=system.ipv4&format=json&points=118&group=average&options=ms|flip|jsonwrap|nonzero&after=-300&_=1486377578941 HTTP/1.1" 200 1882 832 0.000 "http://localhost:19999/tv.html" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
```

I think nginx rounds it to ms, so 0.0002 sec = 0 ms.

**Comment by l2isbad** [comment]
> it would be perfect if the users could configure an array of URL patterns to provide a chart with requests per URL category.

Added
screenshot_20170206_194055


How it works.
You need to specify a list or patterns. Separator - space.

In my example: `'images/icons js/observium cacti'`. 

If url matches by first pattern - break (if `pattern` 'cacti cacti/images' - cacti/images will never match)

```python
def _get_url_pattern_data(self, url, detailed_dict):
    for pattern in self.url_pattern:
        regex = pattern[1]
        if regex.search(url):
            detailed_dict[pattern[0]] += 1
            break
```

Is it what you want?

**Comment by ktsaou** [comment]
hm... I am not sure.

Normally I would need to configure 2 things:

1. the name of the category (i.e. the dimension)
2. a regular expression for matching the URLs of the category

The plugin should also create the category `other`, matching all URLs that have not been matched by any category.

**Comment by l2isbad** [comment]
> Normally I would need to configure 2 things:
> 
> the name of the category (i.e. the dimension)
> a regular expression for matching the URLs of the category

Show an example please

```yaml
'url_pattenr' : ????
```

**Comment by ktsaou** [comment]
> 50K addresses = 400 kilobytes
> 
> Huge?

No, it is not. I would love an option to disable it though. Just in case.


> Show an example please

```yaml
   categories:
      name1: 'pattern1'
      name2: 'pattern2'
```

etc. I don't know if there is support for something like this in `yaml`...

**Comment by l2isbad** [comment]
@ktsaou done

Yeah it works
```yaml
categories:
      name1: 'pattern1'
      name2: 'pattern2'
```

**Comment by ktsaou** [comment]
nice!

I am trying to set it up, like this:

```yaml
nginx_log:
  name: 'local'
  path: '/var/log/nginx/access.log'
  detailed_response_codes: yes
  all_time: yes
  categories:
    badges      : '/api/v1/badge\.svg.*'
    charts      : '/api/v1/(data|chart|charts).*'
    registry    : '/api/v1/registry.*'
    alarms      : '/api/v1/alarm.*'
    allmetrics  : '/api/v1/allmetrics.*'
    api_other   : '/api/v.*'
    netdata_conf: '/netdata.conf'
    api_old     : '/(data|datasource|graph|list|all\.json).*'
```

but the `api_other` takes everything. In which order they are evaluated?

**Comment by ktsaou** [comment]
What is interesting is that if I configure `api_other: '/api/.*` (i.e. without the `v`), it seems that the other categories do match something...

**Comment by l2isbad** [comment]
@ktsaou 
Yeah..dict is unordered object. I need to find a workaround

**Comment by ktsaou** [comment]
I deployed the latest to the registry (with `api_other` commented).

Could you please also set the units of client ips to `unique ips` instead of `number`:

image

btw, this plugin is amazing!

**Comment by shadycuz** [comment]
@ktsaou @l2isbad 

I agree, who would have thought the nginx logging module would have become so powerful. Wish I would have gave it some attention a while ago. I think this has given me the courage to write some log modules for some other applications I would like to see in plex =).

**Comment by ktsaou** [comment]
@l2isbad I am curious: what if this module is renamed to `web_log` and we provide another parameter called `web_server` with values `apache2`, `nginx`, `lighttpd` which will determine the format to parse? Is something like that possible?

**Comment by l2isbad** [comment]
Well, actually we don't need such parameter, plugin itself should determine which parser it needs to use.

**Comment by shadycuz** [comment]
Yeah but what if you want to monitor 1 of each of those types of webserver?
You can just make multiple jobs and point it to log files using path and
the plugin will Auto determine?

**Comment by l2isbad** [comment]
> You can just make multiple jobs and point it to log files using path

Exactly.

**Comment by shadycuz** [comment]
Sweet, it will need a new name, how will you deal with naming it in the
chart list on the right hand side of the GUI?

**Comment by l2isbad** [comment]
>  will you deal with naming

I did not think about that. If plugin name is `web_log` jobs names are `web_log_apache`, `web_log_nginx_local` etc.
Looks ok to me but if it's not ok any suggestion are welcome as always.

**Comment by ktsaou** [comment]
well, `web_log_NAME` is good enough. If someone wants to show the web server type in it, he can add it to `NAME`.

If we rename `nginx_log` to `web_log` that will support all kinds of web server logs, it is important to require all previous versions to be "forced", so that this version will not start the old (installed) `nginx_log`, `apache_log` and the new `web_log`. This can be done, by requiring `nginx: force` and `apache: force` in `/etc/netdata/python.d.conf`.

**Comment by shadycuz** [comment]
Naming looks okay to me.

**Comment by ktsaou** [comment]
@l2isbad I installed python.d.plugin from #1737 to the registry. nice work! I now have `api_other` working.

**Comment by ktsaou** [comment]
@l2isbad I think you can provide also charts:

1. showing the HTTP methods (`GET`, `POST`, `OPTIONS`, etc) (easy)
2. browsers (hard, we need the patterns) - this could be updated every 30 seconds
3. unique referrers (probably easy) - this could be updated every 30 seconds


I think we can add the following alarms:

alarm|warning|critical|description
------|:--------:|:------:|----------
`5xx ratio`|1%|2%|over the last 1 minute
`4xx ratio`|3%|10%|over the last 1 minute
`redirect loops`|2%|5%|3xx requests over the last 1 minute
`web slow`|>500ms and 2x the 10min average|>1000ms and 4x the 10min average|this will compare 2 periods: the last 1 minute and the last 10 minutes using the average response timings
`web abuse`|10x the 10min average|20x the 10 min average|this will calculate the average requests per IP over the last 10minutes and over the last 1 minute. We can do it for both requests and bandwidth (received and sent).


I would also love to somehow detect "too many" or "too few" requests. I am thinking something like: the average of the last 5 mins  should be 0.5 to 1.5 the average of the 5 mins before that. But I need to test it to avoid false alarms.

**Comment by l2isbad** [comment]
@ktsaou 

> showing the HTTP methods (GET, POST, OPTIONS, etc) (easy)

Looks easy, yes.

> unique referrers (probably easy) - this could be updated **every 30 seconds**

log_format combined '$remote_addr - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"**$http_referer**" "$http_user_agent"';

Counter for unique http_referer per ....update_interval?
Why every 30 seconds? Job runs every updade_interval.
How this supposed to work?

**Comment by ktsaou** [comment]
yeah, you are right. These need some more thinking... we will end up with thousands of dimensions...

**Comment by l2isbad** [comment]
> , it is important to require all previous versions to be "forced"

I do not understand why we need `'force'` option (and how it supposed to work). Current implementation is replacement only for `nginx_log`/`gunicorn_log` (we have no `apache_log`).
We can add 'nginx_log:  no', 'gunicorn_log: no' to python.d.conf. Or even remove - why we need them?

**Comment by l2isbad** [comment]
@ktsaou for requests per url plugin uses `search` 

> Scan through string looking for the first location where the regular expression pattern produces a match

You don't need **.*** to match in your example. Without .* it's ~20% faster and the result is the same

```yaml
badges      : '/api/v1/badge\.svg.*'
    charts      : '/api/v1/(data|chart|charts).*'
    registry    : '/api/v1/registry.*'
    alarms      : '/api/v1/alarm.*'
    allmetrics  : '/api/v1/allmetrics.*'
    api_other   : '/api/v.*'
```

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/pulls

**Comment by ktsaou** [comment]
> I do not understand why we need 'force' option (and how it supposed to work). Current implementation is replacement only for nginx_log/gunicorn_log (we have no apache_log).
> We can add 'nginx_log: no', 'gunicorn_log: no' to python.d.conf. Or even remove - why we need them?

If you rename it to `web_log`, then new installations will have just `web_log` but existing/updated installations will have both `web_log` and `nginx_log` in `/usr/libexec/netdata/plugins.d/python.d`.

Since both are installed, we need to find a way to prevent them from running concurrently.

Now there 2 cases:

1. `python.d.conf` is stock version. This is easy, since the new one will replace the old and `nginx_log: no` will be set.
2. `python.d.conf` has been edited by the user. In this case, the file will not be replaced, so both `web_log` and `nginx_log` will be started.

   One way to fix this issue, is to require `nginx_log: force` to enable `nginx_log`. This way, `web_log` will be automatically started and `nginx_log` won't.

**Comment by ktsaou** [comment]
> You don't need .* to match in your example. Without .* it's ~20% faster and result is the same

nice!

**Comment by l2isbad** [comment]
You are right.
But do we really need them to be force/noforce?
Simplest solution is to add `'nginx_log' `to
https://github.com/firehol/netdata/blob/master/plugins.d/python.d.plugin#L503
from start

**Comment by ktsaou** [comment]
Of course, this can be done too.
I was not aware of this functionality (it is used I think for disabling all modules when a specific is given at the command line).

The `force` method has been used for `charts.d.plugin` when we migrated the modules to python. This allowed the users to fallback to the charts.d.plugin ones in case the python versions did not work for them for some reason.

**Pull request closed without merging**
