### PR TITLE
Powerdns plugin init

### PR DESCRIPTION
**Pull request by l2isbad**
Works only for powerdns version 4.x . Version 3.x is [unsupported according official documentation](https://doc.powerdns.com).
closes https://github.com/firehol/netdata/issues/2666

@pschiffe
I did https://github.com/firehol/netdata/issues/2666#issuecomment-326816450

Please check it.

Not sure about:
1. cache_size units (count)
2. chart types (all of them - `line`)

### CODE REVIEW

**Comment by l2isbad** [comment]
@ktsaou its kinda ready. it works 😄

**Comment by ktsaou** [comment]
merged! you rock!

**Comment by ktsaou** [comment]
@l2isbad remember the "add more charts" page and please give me a screenshot to add to the change log.

**Comment by ktsaou** [comment]
image

**Comment by l2isbad** [comment]
> add more charts" page

added

> a screenshot 

Not sure i can help, all my charts have no data (clean powerdns install, no load)

**Comment by pschiffe** [comment]
Hi, sorry for late response.. but I've tested it and it works perfectly, thanks!

pdns

**Pull request merged**
