### PR TITLE
Update freebsd_getifaddrs.c and dashboard.js to scalableUnits packages(pps)

### PR DESCRIPTION
**Pull request by RicardoSette**
For monitor storm packages pps/Kpps/Mpps is crucial ;D

### CODE REVIEW

**Comment by ktsaou** [comment]
nice.
Waiting for CLA... Just once for all PRs is ok.

**Comment by ktsaou** [comment]
hm... somehow your other PR appeared here too.
Can you fix it?

**Comment by RicardoSette** [comment]
I closed and deleted the other branch, ok?

**Comment by ktsaou** [comment]
ok, merged!

**Comment by ktsaou** [comment]
I tested this on a KVM freebsd VM. The interface I have is `vtnet0`. Should this be considered physical?

**Comment by chalfling** [comment]
Hello @ktsaou,  I was working with @RicardoSette in this PR!

If your interface `vtnet0` is bind to a physical interface or on your VM's point of view it's a physical interface, you need to add `vtnet0` in `netdata.conf` the same way in `"disable by default interfaces matching"` where you exclude interfaces.
In this PR was created `"set physical interfaces for system.net"`, so in `netdata.conf` on section `[plugin:freebsd:getifaddrs]` you need to add something like this: `set physical interfaces for system.net = vtnet*`

The PR was preconfigured with some commons physical interfaces from FreeBSD as you can see in: [https://github.com/firehol/netdata/pull/3894/commits/6b3d0efd196b90499ac7ec7cd942e80be2c82762#diff-1dc52a9bf8e2444c858a60421861fa0dR145](url)

> #define DEFAULT_PHYSICAL_INTERFACES "igb* ix* cxl* em* ixl* ixlv* bge* ixgbe*"

**Pull request merged**
