### PR TITLE
Added gunicorn log conf and chart.py files

### PR DESCRIPTION
**Pull request by deltaskelta**
Added .conf chart.py files for gunicorn. Mimicking the way that nginx_log.chart.py works. This will allow users to easily add and monitor different instances of gunicorn (with modification to the conf file)

### CODE REVIEW

**Comment by ktsaou** [comment]
thanks!

**Comment by l2isbad** [comment]
Yo @deltaskelta 
Are you sure algorithm should be incremental?
https://github.com/firehol/netdata/blob/master/python.d/gunicorn_log.chart.py#L18-L21

**Comment by l2isbad** [comment]
Oh, i found https://github.com/firehol/netdata/commit/fc0109c6aa0c62b86208653a1d1b1b73391e8729
@ktsaou fixed the bug in nginx_log
But why not just incremental -> absolute?

**Comment by ktsaou** [comment]
> But why not just incremental -> absolute?

it would require to reset the variables to zero, on every iteration. I don't have any issues with either. The faster the better.

**Comment by l2isbad** [comment]
> it would require to reset the variables to zero

Yes. But it was already in code.
Since there is no reset in python because all "variables" are references. Integers  immutable. 
Every operation with them = change reference to new object in memory. Super fast.

**Comment by deltaskelta** [comment]
@l2isbad not sure about the incremental bit. I was just copying and repurposing code and it seemed to work well enough when I was playing with it

**Comment by l2isbad** [comment]
@deltaskelta 
incremental is for continuous incrementing counters.
In your code absolute is the right choice (data dict zeroed every iteration).

**Comment by l2isbad** [comment]
Actually do we need all that `if else` stuff since dict 'key' already in search object?
```python
        regex = self.regex
        for line in raw:
            code = regex.search(line)
            try:
                beginning = code.group(1)[0]
            except AttributeError:
                continue

            if beginning == '2':
                data["2xx"] += 1
            elif beginning == '3':
                data["3xx"] += 1
            elif beginning == '4':
                data["4xx"] += 1
            elif beginning == '5':
                data["5xx"] += 1
        return data
```

VS

```python
for i in f:
    r = re.search(r'((?<=\s)\d{3})', i).group()
    if r:
            d[''.join([r[0], 'xx'])] += 1
return data
```

**Comment by ktsaou** [comment]
@l2isbad your call...
Keep in mind we always need the fastest execution time (not always the fastest development time).

I am just afraid that if we don't optimize every bit, when netdata will be used to collect many thousands of metrics per second, we will be forced to drop the "per second" aspect of it.

So, if in doubt, pick the faster execution.

**Comment by l2isbad** [comment]
Agree!
But back to this - there is a bug in gunicorn plugin. @deltaskelta are you willing to fix it?

btw gunicorn looks identical to nginx_log. Why we need both?

**Comment by ktsaou** [comment]
@l2isbad regarding log parsing, I think we need a universal log parser. web servers support different formats and we can extract a lot more information from such files I see this need all the time.

It would be somewhat complicated. Initially, I was considering to write this in C, for speed, but then in C it would be a tremendous project.

I guess it would be a lot easier in python. Think of it a bit and if you find it interesting, let's discuss it on a separate issue.

**Comment by l2isbad** [comment]
> let's discuss it on a separate issue

ok!

> I see this need all the time

Well, if i need a deeper analysis of webserver logfiles i will user es/kibana stack or smth similar.

> a lot more information from such files 

What kind of information are you talking about in context of netdata (real-time, 1hr history) ?

**Comment by ktsaou** [comment]
> Well, if i need a deeper analysis of webserver logfiles i will use es/kibana stack or smth similar.

Sure. But this would require quite a setup and you will not get alarms.

> What kind of information are you talking about in context of netdata (real-time, 1hr history)

Today we only chart responses per code (2xx, 4xx, 5xx, etc).

Web servers also log bytes per response and have the ability to log response timings (usually in ms).

Using these 3 (response codes, timings and size), combined with the URLs and the methods (GET, POST, PUT, etc), there can be quite a few very interesting charts.

For APIs, a lot of people ask for grouping the URLs (i.e. there are 50 API calls, grouped in 10 categories). 

For each of these categories we could have a set of charts, each with the URLs as dimensions, rendering:

1. count of responses per response code (the one we have, probably in more detail)
2.. count of responses per URL
3. bandwidth per URL
4. timing per URL in 3 charts (min, average, max)

This would require a configuration where URLs are anonymized and categorized (grouped).

Adding alarms to it and we have a very strong API monitoring system, without any cooperation from the API itself...

**Comment by deltaskelta** [comment]
@l2isbad, I haven't used netdata in a while so I don't think I would be the best choice for this one. If you need me to do it, I can, but I am not actively using the project anymore.

**Comment by ktsaou** [comment]
> but I am not actively using the project anymore

@deltaskelta can you give us some feedback? What make you decide to drop it?

**Comment by deltaskelta** [comment]
@ktsaou from what I remember, it was because there was no data persistence in any kind of database. It was great for seeing a snapshot but I wanted to be able to change timeframes and see past states

**Comment by ktsaou** [comment]
ok. thanks!

keep in mind you can archive netdata metrics to time-series databases (graphite, opentsdb, prometheus, etc) and use grafana or other tools to get statistics of past performance.

**Comment by deltaskelta** [comment]
ok, I recently had to scrap my graphite install so I will keep that in mind and take a look when I redo my monitoring soon

**Comment by l2isbad** [comment]
@deltaskelta 
Can you post here some gunicorn logs?

**Comment by deltaskelta** [comment]
@l2isbad here is a small sample of them...
```
172.18.0.5 - - [09/Feb/2017:01:36:41 +0000] "GET /post/scanning-for-options-with-a-small-bidask-spread-free-thinkorswim-study/ HTTP/1.0" 200 8122 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
172.18.0.5 - - [09/Feb/2017:01:36:48 +0000] "GET /robots.txt HTTP/1.0" 301 - "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
172.18.0.5 - - [09/Feb/2017:01:42:58 +0000] "GET /robots.txt HTTP/1.0" 301 - "-" "Mozilla/5.0 (compatible; linkdexbot/2.0; +http://www.linkdex.com/bots/)"
172.18.0.5 - - [09/Feb/2017:01:49:19 +0000] "GET /post/project-euler-problem-7-solution-in-python/ HTTP/1.0" 200 6383 "https://www.google.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393"
```

**Comment by deltaskelta** [comment]
@l2isbad I can probably get around to fixing this if you can wait about a week or so, IDK how urgent it is, let me know

**Comment by l2isbad** [comment]
@deltaskelta 
gunicorn plugin is not needed anymore
https://github.com/firehol/netdata/pull/1744

**Comment by l2isbad** [comment]
@deltaskelta 
One more question 😄 
What permissions/group membership netdata needs to read gunicorn log files?

**Comment by deltaskelta** [comment]
@l2isbad I would say `adm`..I'm not an expert on by the book system setups, but I think `adm` would be a good standard since `/var/log` uses it. Most people will either have it there, or under some custom user. Gunicorn actually needs to be setup to start logging so someone who does all that should be smart enough to change it if they need to

**Pull request merged**
