### PR TITLE
Fix memory leak in FreeBSD plugin

### PR DESCRIPTION
**Pull request by vlvkobal**

### CODE REVIEW

**Comment by ktsaou** [comment]
so, you are saying that `getifaddrs()` may fail and still allocate memory?

**Comment by vlvkobal** [comment]
I didn't think so before. But now I'm searching in `getifaddrs()` sources to find out if it is possible .

**Comment by vlvkobal** [comment]
No. It isn't possible. You can have a look at https://github.com/freebsd/freebsd/blob/master/lib/libc/net/getifaddrs.c

I'm closing the PR.

**Comment by jordanhubbard** [comment]
I just reviewed the getifaddrs() implementation in FreeBSD and there don't look to be any possible leaks - all error returns also free(buf) and data is allocated late in the implementation such that only success can ever be returned with allocated data.  As long as getifaddrs() is being properly checked for success return and freeifaddrs() always called in this case, there should be no leak there.

**Pull request closed without merging**
