### PR TITLE
Some small changes on simple functions.

### PR DESCRIPTION
**Pull request by fredericopissarra**
Instead of using memset to fill a structure with zeros, we can initialize the structure on stack. All not explicit initialized members will, automatically, be zeroed.

And small changes on string functions in common.h. Notice two commits on that file. I made a mistake in the first one... sorry...

About the comma operator. I think this style can lead to confusion... the sequence of statements will always be respected by the compiler?!

[]s
Fred

### CODE REVIEW

**Comment by ktsaou** [comment]
this fails:

image

**Comment by fredericopissarra** [comment]
Sorry.... there is a comma after ifds (the comment was suppose to be 
before)...

And I apologise... Some changes seems to be so trivial I don't test 
them... I will...

[]s
Fred

**Comment by ktsaou** [comment]
ok. no problem. This repo gets cloned 700+ times per day, so we have to be careful.
Your last commit has been already fixed by me with PR #301 

Can you see travis checks at the bottom of this page? If you follow it, you will find why this PR fails.

**Comment by simonnagl** [comment]
@fredericopissarra I think this can be closed? Could you please do so?

Please do not treat me if I am wrong ;)

**Comment by ktsaou** [comment]
We have to check if #395 includes them. It should...

**Comment by fredericopissarra** [comment]
Why I would treat anybody as if they were wrong?!?!
Closed!

**Comment by simonnagl** [comment]
I just tried to be gentle...

**Pull request closed without merging**
