### PR TITLE
non-blocking `SocketService`

### PR DESCRIPTION
**Pull request by paulfantom**
Do not merge it yet. It needs testing.

Although I haven't found any issue, yet.

### CODE REVIEW

**Comment by paulfantom** [comment]
@ktsaou I have run some more test and haven't found issues. If you could test on your machine it would be great.

**Comment by ktsaou** [comment]
I will do, later today.

**Comment by ktsaou** [comment]
it seems good. redis and squid work, as all the others.
Merge?

**Comment by paulfantom** [comment]
merged.

**Pull request merged**
