### PR TITLE
added systemd services detailed memory charts (disabled by default)

### PR DESCRIPTION
**Pull request by ktsaou**
This PR adds detailed memory charts to systemd services charts.

The configuration option is `enable systemd services detailed memory` and by default is `no`. Once enabled 8 new charts will be reported for systemd services memory:

1. RSS memory
2. File Mapped memory
3. Cache memory
4. Writeback memory
5. Charging memory activity
6. Uncharging memory activity
7. Minor page faults
8. Major page faults

This option increases the CPU utilization of the cgroups thread by 25%. Check here the diff (on the right half of the chart, is with this enabled).

image

Ok, I know this is still very fast (2.5ms compared to 3.2ms per second), but I think it should be disabled by default.

cc @tycho 

---

This PR also fixes the negative options that were added yesterday for cgroups, to positive (so instead of disabling features with patterns, they are now enabled by patterns).

### CODE REVIEW

**Comment by tycho** [comment]
These are all, good, but... How about adding a memory chart that is simply "used minus cache"? I basically want to know what 'top' or 'ps' or similar would tell me about the utilization. I don't particularly care whether it's file-mapped, RSS, etc for just an overview. The super detailed breakdown is most useful for debugging scenarios. And assuming a "used minus cache" chart is implemented, I also don't want to have to turn on 8 other charts I don't really care about to get the 1 that I do -- they should each be optional.

**Comment by ktsaou** [comment]
ok, here it is. The option `report used memory without cache = yes` affects both containers and systemd services. It is by default enabled.

**Comment by tycho** [comment]
Awesome! I'll test this out in a moment, but on a read through, it looks great.

**Comment by tycho** [comment]
Only thing I think I'd change is the title, because "Systemd Services Used RAM with Cache (services.mem_usage)" should vary depending on that flag now.

Also there's [this](https://github.com/firehol/netdata/issues/1586), that I discovered a few minutes ago.

**Comment by ktsaou** [comment]
done everything, including the title.
fixes #1586 too

**Comment by tycho** [comment]
Looks good to me!

**Comment by ktsaou** [comment]
merged!

**Pull request merged**
