### PR TITLE
add chrony monitory

### PR DESCRIPTION
**Pull request by fooltux**

### CODE REVIEW

**Comment by ktsaou** [comment]
Hi. Thanks!

@l2isbad please review.

If chrony is not running, will this disable itself?

There is something with the paths of the files. The diff reports 3 files changed, but only 1 is available and it is at the wrong path. Can you check it?

**Comment by l2isbad** [comment]
yo @fooltux 
i suggest to use [ExecutableService](https://github.com/firehol/netdata/wiki/How-to-write-new-module#executableservice) framework.
https://github.com/firehol/netdata/blob/master/python.d/python_modules/base.py#L914-L986

**Comment by domschl** [comment]
I made a suggestion using ExecutableService at #2639.

**Comment by ktsaou** [comment]
#2639 has been merged, so I think we can close this.
Thank @fooltux and @domschl !

**Comment by ktsaou** [comment]
image for the infographic:

image

**Comment by kmai007** [comment]
how do i disable chrony on netdata ? or is it a requirement?

**Comment by ktsaou** [comment]
edit `/etc/netdata/python.d.conf` and set `chrony: no`.
If you update your netdata, [it is disabled  by default](https://github.com/firehol/netdata/blob/223f504a6d7277bcfc5dcae244ce70991b8179c4/conf.d/python.d.conf#L33).

**Pull request closed without merging**
