### PR TITLE
Delete ebuild because it is now in Gentoo

### PR DESCRIPTION
**Pull request by candrews**
Gentoo now has net-analyzer/netdata, so there is no need to have an ebuild in this repository, as it will only cause confusion.

See https://github.com/gentoo/gentoo/commit/76a80a3953dcb014877e3390fcd9923de9c23469 and https://bugs.gentoo.org/show_bug.cgi?id=586970

### CODE REVIEW

**Comment by ktsaou** [comment]
nice! Thank you!

I thought the ebuild found here will be the one to track for changes. For example, soon we will replace most of the BASH plugins with python ones (check the recent PRs, @paulfantom is actively contributing code on this area).

So, if we delete the ebuild, how the gentoo devs will know what has changed?

**Comment by candrews** [comment]
I think the best thing to do would be to submit pull requests to the Gentoo github project.
Another option would be to keep the the ebuild here (but please update it to match what Gentoo has first, it had some changes made in order to meet Gentoo standards) and note that the ebuild changed in the release notes. I'll watch for the new changes and get them into Gentoo (I'm currently the Gentoo maintainer for netdata).

**Comment by ktsaou** [comment]
Perfect! I will open a new issue when something changes and mention you.

**Comment by ktsaou** [comment]
Can you give me a few instructions to add to the wiki?

What the users should run to install the git version and what to install the latest release?

**Comment by ktsaou** [comment]
Keep in mind the next version will need:

- dev-python/pyyaml (to have the python plugin @paulfantom develops read its config files)
- dev-python/mysqlclient (only if mysql monitoring is required)

Both of these could be added to the git version of the ebuild.

**Comment by ktsaou** [comment]
Also I think the dependency to `wget` can be removed.  In v1.2.0 only proprietary plugins were using it and today no plugin at all uses it.

**Comment by ktsaou** [comment]
Finally, `/var/lib/netdata` and `/var/lib/netdata/registry` should be owned much like `/var/cache/netdata`, or people will not be able to enable the registry.

**Comment by candrews** [comment]
@ktsaou is there a configure flag to toggle installation of the plugins that require mysql?

Also, /var/cache/netdata shouldn't be created at install time - the contents of /var/cache should be created at runtime. See #648

I've updated the ebuild in my fork, can you take a look? https://github.com/candrews/gentoo/blob/netdata/net-analyzer/netdata/netdata-9999.ebuild feel free to submit PRs, too. I'll aggregate them and send a PR to Gentoo at some point.

**Comment by ktsaou** [comment]
> is there a configure flag to toggle installation of the plugins that require mysql?

no. The plugin will be installed but it will fail to load if the required python libraries are missing.
The same happens for all plugins.
Is this a problem?

Regarding `/var/cache` I have a few questions. I'll discuss them at the issue #648 .

Regarding the ebuild:

1. I see in the code that `/var/lib/netdata/registry` is created by netdata if it does not exist. `/var/lib/netdata` has to exist though.

2. Currently for mysql there are 2 options: BASH plugin that requires the `mysql` command, or python plugin that requires python (i.e. `dev-python/pyyaml`) and `dev-python/mysqlclient`. Of course the python plugin is more optimal.

  I don't know if an IUSE `+python` should be there or not. I can think of a few cases that the user is not willing to install any plugin. So it might be useful to have it enabled by default but optional.

**Comment by paulfantom** [comment]
Just a note: `mysql.chart.py` requires `dev-python/mysqlclient` or `dev-python/pymysql`.

**Comment by ktsaou** [comment]
nice. I'll try to write a wiki page with the dependencies of each plugin.

**Comment by paulfantom** [comment]
@ktsaou I am wrote every dependency for python modules in `readme.md` in #643

**Pull request merged**
