### PR TITLE
Add Dockerfile to run as a Docker container

### PR DESCRIPTION
**Pull request by hectorj2f**
Hello there!

I hope PRs are welcomed :).

I found very fancy your monitoring application as well as an interactive web UI. I think it would be cool if you can run your application within a container. Therefore I decided to make this PR to be able to run your monitoring tool as a Docker container in my cluster.

As an example, you could run `netdata` as a container by simply:

`docker run -it --privileged --pid=host --net=host -p 19999:19999 hectorj2f/netdata`

### CODE REVIEW

**Comment by ktsaou** [comment]
Of course PRs are welcomed.

There is also some work done by a few folks at #10 

So, do we need it?

**Comment by daenney** [comment]
I think it would be nicer to use the Alpine image as a base, since it's super tiny. But that rests on #66 being solved.

**Comment by hectorj2f** [comment]
I agree that running on Alpine would be better :+1:

**Comment by daenney** [comment]
@titpetric Fair point. In that case though what you could do instead is submit PRs to the author of #10 and fix the issues you're currently having with their Docker image until the other problems can be resolved.

**Comment by ktsaou** [comment]
You are so nice!
I am downloading alpine too. I'll do my best to settle all issues related to this in the weekend.

**Comment by titpetric** [comment]
@daenney technically, I am the only one who created a working dockerfile in #10. But yeah, I'm all for pushing the changes into the upstream repo, mainly because it's currently manual work to update it in docker hub. I am excited to resolve this whenever possible :)

**Comment by daenney** [comment]
@titpetric Ho sorry, I got you and the op confused. The comment was meant the other way around!

**Comment by daenney** [comment]
@squash That's not exactly true. Since it uses `/proc` to do most of its monitoring you can mount read-only from the host into the container and achieve much the same as running it on the actual host.

**Comment by squash** [comment]
@daenney That's exactly my point. Some things will be accessible at the host level, some things will be at the container level. It largely goes against the spirit/concept of a docker container as well, and instead is just using Docker as a convenient way to package the install.

As an add-on to a container with a real workload, this would be much more useful. At the host level, being able to group processes by uid (or some native Docker hooks) to aggregate your containers stats on the host's view seems a lot more valuable to me.

**Comment by rothgar** [comment]
I also made a Dockerfile (didn't search first) and I agree running on Alpine would be ideal (via #10 and #66 ) but I also think there are a few things missing from the existing Dockerfiles I found.

- `docker logs` won't work as intended because netdata still writes to access.log and error.log
- some containers were adding --privileged and --net=host which are not needed and possible security concerns

Here's [my Dockerfile](https://github.com/rothgar/netdata/blob/master/Dockerfile) and related [wiki changes](https://github.com/rothgar/netdata-wiki/commit/f2e76cbe524a35083e94a0aa0bee583b83bef023?short_path=ed91098#diff-ed910981ef0746b8d8e60712cad092ca).

I do think it would be handy if netdata had an official and up to date container on docker hub that could be advertised so `docker run ... firehol/netdata:latest` would be easier for people but I didn't want to put it under my name because I have no intention of keeping it up to date with new netdata releases.

**Comment by hectorj2f** [comment]
There are some possible solutions:

> docker logs won't work as intended because netdata still writes to access.log and error.log

`RUN ln -sf /dev/stdout /var/log/netdata/access.log && \ ln -sf /dev/stderr /var/log/netdata/error.log `

> some containers were adding --privileged and --net=host which are not needed and possible security concerns

You can omit using `--privileged` by passing the `/proc` of the host to the container in a different location.

**Comment by rothgar** [comment]
@hectorj2f yes exactly. That is what I do in my Dockerfile (view link above) and include `docker run` instructions in the wiki edits (link above) and as a comment in the Dockerfile

**Comment by hectorj2f** [comment]
@rothgar Yes.

Generally to collect the system/network metrics, you could do it by using volumes like `/proc:<dest>` `/sys:<dest>` as other options. I didn't do it in my initial, and it seems someone else will do it :).

The main benefit of the collected metrics, when running within a docker container, is extracting the ones the host produces. Obviously there isn't too much benefit by collecting the ones from the container, as certainly pointed it out @squash

**Comment by rothgar** [comment]
Just FYI for anyone looking. I updated my Dockerfile (was missing tc and which causing errors) [here](https://github.com/rothgar/netdata/blob/master/Dockerfile)

It's not designed to be a minimal/slim container (it's 359 MB) but instead builds the current git master branch in a container so it needs additional build tools. Once things are fixed on Alpine I'll probably make a pre-compiled netdata:slim Dockerfile for people who just want to run a release from docker hub.

**Comment by titpetric** [comment]
Hi guys,

@hectorj2f I'll add the ln -s for access.log/error.log *exactly* as you suggested :)

@hectorj2f & @rothgar - can you please clarify - the way to run netdata in an optimal way is with `-v /proc:/host/proc:ro -v /sys:/host/sys:ro` and a switch to read data from `/host` (it's in run.sh ... -ch /host or similar). This needs SYS_PTRACE cap. I'm getting all the metrics from the host, but I might be missing something?

I guess when it comes to monitoring docker hosts, it would be useful to have some kind of additional plugin which would monitor per-container statistics (disk, ram, cpu). As far as I know, the data is available via the docker (stats?) command, and some munin plugins exist to graph this data. Apps plugin graphs individual processes inside containers (ie, it will graph 'nginx' which is running in a docker container). Are you having some issues about network graphing when you add -v for /proc of the host?

Once things are fixed in Alpine, I guess I'll publish a corrected version of my existing Dockerfile to firehol/netdata as a PR as a first step, so it's up to date. As for instalation of netdata itself - I'd wait on the debian packaging. But that's just me. Alpine has dpkg?

**Comment by rothgar** [comment]
My dockerfile has a comment on how to run the container after it's built.

docker run -d -v /proc:/host/proc:ro -v /sys:/host/sys:ro --cap-add SYS_PTRACE -h $(hostname) -p 19999:19999 netdata

The CMD in the dockerfile should be `CMD ["/opt/netdata/usr/sbin/netdata","-nd","-ch","/host"]` to read from the /host path and not fork to the background.

If you want/need per container monitoring you should use something like [sysdig](https://sysdig.com/blog/let-light-sysdig-adds-container-visibility/) but that's more of a hosted solution (for web-ui) or cli

**Comment by titpetric** [comment]
@rothgar some configs will not be written with -nd (read issue #10 comments), this is why I run it in the background, and run sleep infinity in the fg. I doubt this behavior has changed? cc: @ktsaou

**Comment by titpetric** [comment]
I'm quoting @ktsaou here:

> One issue that will exist if you use the -nd option, is that the config file will never be created. netdata.start relies on netdata being forked for it to download the config file for the first time.
> 
> So, if you use -nd you will have to download the initial config file yourself.

**Comment by titpetric** [comment]
I updated the `titpetric/netdata` image on docker hub:

1. I'm using netdata-install.sh now,
2. I reduced the size from about 370MB down to about 150MB(docker hub) vs. 165MB(local build).
    - mainly I cleaned up build deps.
3. Added symlinks to error/access log files as suggested @hectorj2f 

I am happy with this. I'm doing final tests, so everything should be up soon.

**Comment by ktsaou** [comment]
Keep in mind the netdata conf file is not required. Actually the default that is downloaded from the server is commented entirely. It is only for the benefit of the user that the installer downloads it (so that he/she can uncomment a setting and change its value, instead of searching all over the net for the proper option to do something).

This is also why the configuration names are so long and self-explanatory.

**Comment by titpetric** [comment]
@ktsaou my bad, I did double check, as I expected at least the `-ch` option would be a reason to uncomment some config settings. So, time for me to move towards `-nd`. :+1:

**Comment by ktsaou** [comment]
ok, nice!
I am planning for a new release tomorrow. Shall we include this?

**Comment by andyshinn** [comment]
Is there a reason the `Dockerfile` clones from git instead of just COPYing?

Probably orthogonal to the first iteration of `Dockerfile`, here is a `APKBUILD` to build a Alpine package once #66 is working: https://gist.github.com/andyshinn/15fd7ab5c0d118c59b864802a6ecaaf5. We can then just push an Alpine package upstream. The `Dockerfile` for this would be something like:

```
FROM alpine:3.3
RUN apk --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing add netdata
USER netdata
ENTRYPOINT ["netdata", "-nd"]
```

**Comment by ktsaou** [comment]
docker experts have a look at #115 
I would like to have your view.

**Comment by titpetric** [comment]
@andyshinn If you would COPY the netdata sources in the container, the build wouldn't be automatic. Your way seems file for netdata. When debian packaging will be done, it will also mean a smaller docker image without any clone/build steps, very much similar to what you have for alpine. But who cares for debian at that point :)

**Comment by titpetric** [comment]
@ktsaou I would honestly wait for #66 and use exacly what @andyshinn proposes. It's the "final" form of what a netdata image should be.

**Comment by ktsaou** [comment]
#66 is solved

**Comment by titpetric** [comment]
@andyshinn Can you test your suggested Dockerfile and submit a PR?

Best, T.

**Comment by ktsaou** [comment]
When this is ready for merge, please let me know.

**Comment by psi-4ward** [comment]
Consider following:

* `VOLUME /var/cache/netdata`
* Is it clever to use `ENTYPOINT` over `CMD`
* `ENV NETDATA_PORT=19999` ... `ENTRYPOINT ["/usr/sbin/netdata", "-nd", "-p", "$NETDATA_PORT"]`
* Would be nice to be able to alter the default config using env-vars. I've used `envsubst` in different Images
* Pipe `error.log` to `/dev/stderr`

**Comment by hectorj2f** [comment]
@ktsaou Is there any progress or blocker in here ? Could we close this PR ?

**Comment by ktsaou** [comment]
I don't know. @titpetric is this mergeable?

**Comment by titpetric** [comment]
Suggesting to close without merge, but open to suggestions:

1. Alpine apk is not part of dockerfile so i asume it will always be out of date,
2. Dockerfile is out of date with titpetric/netdata (which implements env var on build, and other things @psi-4ward mentioned
3. There's a way to build docker images with tags which could also include versioning (feature for all including titpetric/netdata)

Can we address these issues if important?

**Comment by ktsaou** [comment]
@titpetric can we have titpetric/netdata merged into netdata? I am sorry if I ask stupid questions, but it seems the files are not in conflict.

Am I missing something?

**Comment by titpetric** [comment]
Hi, sorry for the long reply. If you want to merge it, it's fine with me. I'd suggest a netdata-docker repository however, as some things may need to be extended (builds for alpine, etc.). I am swamped with projects for the next month so I will not get around to it before then (unless someone is very nice to me). How should we proceed? I can transfer the repo to you as netdata-docker, or you can just copy the files into netdata repo.

**Comment by ktsaou** [comment]
No need to transfer it. I can copy the files.

The files added will be:

1. `Dockerfile`, as-is
2. `Makefile`, may I add this to Makefile.am and work with the standard installation as `make docker`?
3. `README.md` will become `DOCKER.md` and I'll change the instructions accordingly
4. `build.sh` will becone `netdata-docker-build.sh` and I'll change the `Dockerfile` accordingly
5. `package.json`, I guess I will just change the URLs

Will these work?

**Comment by pierreozoux** [comment]
I think an independent repo would be a huge win on the road to official docker image.
You could have sub directory for different versions (alpine, debian...)

**Comment by titpetric** [comment]
@ktsaou I suggest you do an import if needed, I'll keep maintaining my Dockerfile for some time. I think only the Dockerfile and related build.sh is needed to copy into the netdata, the rest are there for convenience/documentation/ and can be fully omitted.

@pierreozoux yes, it has been on my roadmap for a while now, alas with an image that takes about 33MB from what I remember, I'm not actively working on it. I'm not highly motivated as the same value is contained with the current image, and storage of a few MB is not such a big deal that I'd duplicate my work in this case :)

**Comment by ktsaou** [comment]
@titpetric I did that. I renamed `build.sh` to `docker-build.sh` and changed `Dockerfile` to reflect this change. Please check PR #835

**Comment by ktsaou** [comment]
ok, we have `Dockerfile` in netdata repo copied from @titpetric repo.
I am closing this.
Thank you all.

**Pull request closed without merging**
