### PR TITLE
Adding a Fronius Solar power metrics plugin

### PR DESCRIPTION
**Pull request by BrainDoctor**
Produces charts such as this:
fronius_charts

### CODE REVIEW

**Comment by ktsaou** [comment]
nice!
So, you decided to do it in `node.js`.
Is it stable? Do you want me to merge it or wait a bit in case you need to modify it?

**Comment by BrainDoctor** [comment]
Haven't had any issues so far. But didn't do any long time testing either. Also I would like to observe the breakeven in the evening, to see if the area chart type is appropriate or maybe lines are better suited.
Question though: Is it possible to set the value range in the code? e.g. the autonomy chart unit is percentage and the graphic above shows the range from ~15 % to 100%, while I think it would be better to show the range from 0 to 100. This way the perception of the chart wouldn't be "stretched". I know it can be set in a custom dashboard, but maybe it can be done without it?

**Comment by ktsaou** [comment]
You need to add it here: https://github.com/firehol/netdata/blob/master/web/dashboard_info.js
You can also add more information, change colors, etc.

**Comment by ktsaou** [comment]
Before merging it, I would be grateful if you also do these:

1. Create a wiki page about it, to explain it to people willing to set it up. Link it to the main menu too. Remember: by merging it you are commit to help a bit other users willing to use it. I don't have this setup so, I cannot test it, trace issues, etc - We will rely on you.

2. Add references to the "Add charts" page (click it on the dashboard and edit that page on the wiki), so other people will be able to find it in the list of available plugins.

3. Add it to the infographic. You can edit it directly in draw.io by opening it from your git fork (in the diagrams directory). To add images / logos, please add them to a github issue first (or this PR) and use the github URL in draw.io (this will use the github CDN when people view https://my-netdata.io/infographic.html) - You will need to resize a bit a few other icons to make room for your icon.

**Comment by BrainDoctor** [comment]
I see what I can do. Furhtermore I just detected a bug. While it worked on my test machine, the "productive" is complaining about usage of const in strict mode. Well, that's beginner's nodejs for me ;)
Lets put this PR on hold for now.

**Comment by BrainDoctor** [comment]
I just realized that codacy is making suggestions that lead to syntax errors on my production machine :/ Now I have to revert some changes. Is it possible to tweak it or is it just my machine?

**Comment by BrainDoctor** [comment]
1. PR #2428 and this PR (fronius.conf.md)
2. PR #2428
3. included in this PR (added above mongoDB, below RabbitMQ)

cheers

**Comment by ktsaou** [comment]
ok, let me know when you are ready to merge it.

**Comment by BrainDoctor** [comment]
I've found another discrepancy coming from the remote API :( I would like to observe the behavior for a few days. I'll get back here if I think it's stable.

**Comment by ktsaou** [comment]
Perfect. Take your time.

**Comment by BrainDoctor** [comment]
Alright, I couldn't find any new issues. It can be merged now. Same for PR #2428

**Comment by ktsaou** [comment]
merged it! thanks!

**Comment by BrainDoctor** [comment]
leaving the fronius logo here for the infographic
fronius logo

**Pull request merged**
