### PR TITLE
Isc dhcpd ipv6

### PR DESCRIPTION
**Pull request by l2isbad**
fixes https://github.com/firehol/netdata/issues/3174

### CODE REVIEW

**Comment by l2isbad** [comment]
@agross
please check the fix

**Comment by agross** [comment]
Hi,

thanks for the quick implementation. Unfortunately now I get 0 leases for both IPv4 and IPv6. I've attached the leases files, please check here: https://router.netdata.home.therightstuff.de/#menu_isc_dhcpd_IPv4_submenu_active_leases

[dhcpd.leases.txt](https://github.com/firehol/netdata/files/1586244/dhcpd.leases.txt)
[dhcpd6.leases.txt](https://github.com/firehol/netdata/files/1586245/dhcpd6.leases.txt)

**Comment by l2isbad** [comment]
Hm, i checked and it works with both leases files for me (v4, v6).
I need your help to debug the problem.

Please add
```python
self.error(new_lease.address, new_lease.is_active(current_time), new_lease.state)
```

after
https://github.com/l2isbad/netdata/blob/isc_dhcpd_ipv6/python.d/isc_dhcpd.chart.py#L176

and run module 
```bash
sudo /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 2 isc_dhcpd
```

wait a few seconds and post the output here

**Comment by agross** [comment]
```
2017-12-26 03:02:21: python.d INFO: plugin: main: Using python 2
2017-12-26 03:02:21: python.d INFO: isc_dhcpd: dhcpd: check() => [OK]
2017-12-26 03:02:21: python.d INFO: isc_dhcpd: dhcpd6: check() => [OK]
CHART netdata.runtime_isc_dhcpd_IPv4 '' 'Execution time for isc_dhcpd_IPv4' 'ms' 'python.d' netdata.pythond_runtime line 145000 2
DIMENSION run_time 'run time' absolute 1 1

CHART netdata.runtime_isc_dhcpd_IPv6 '' 'Execution time for isc_dhcpd_IPv6' 'ms' 'python.d' netdata.pythond_runtime line 145000 2
DIMENSION run_time 'run time' absolute 1 1

2017-12-26 03:02:22: python.d ERROR: isc_dhcpd: dhcpd: update() unhandled exception: local variable 'new_lease' referenced before assignment
2017-12-26 03:02:22: python.d ERROR: isc_dhcpd: dhcpd6: update() unhandled exception: local variable 'new_lease' referenced before assignment
```

**Comment by agross** [comment]
Oh, sorry, I added the error line in the `except` block. Here's the output in the `else`:

```
2017-12-26 03:06:09: python.d INFO: plugin: main: Using python 2
2017-12-26 03:06:09: python.d INFO: isc_dhcpd: dhcpd: check() => [OK]
2017-12-26 03:06:09: python.d INFO: isc_dhcpd: dhcpd6: check() => [OK]
CHART netdata.runtime_isc_dhcpd_IPv4 '' 'Execution time for isc_dhcpd_IPv4' 'ms' 'python.d' netdata.pythond_runtime line 145000 2
DIMENSION run_time 'run time' absolute 1 1

CHART netdata.runtime_isc_dhcpd_IPv6 '' 'Execution time for isc_dhcpd_IPv6' 'ms' 'python.d' netdata.pythond_runtime line 145000 2
DIMENSION run_time 'run time' absolute 1 1

CHART isc_dhcpd_IPv4.leases_total '' 'All Active Leases' 'leases' 'active leases' 'isc_dhcpd.leases_total' line 60002 2 '' 'python.d.plugin' 'isc_dhcpd'
DIMENSION 'leases_total' 'leases' absolute 1 1 ''

BEGIN isc_dhcpd_IPv4.leases_total 0
SET 'leases_total' = 0
VARIABLE CHART 'leases_size' = 7
END

CHART isc_dhcpd_IPv4.pools_active_leases '' 'Active Leases Per Pool' 'leases' 'active leases' 'isc_dhcpd.active_leases' line 60001 2 '' 'python.d.plugin' 'isc_dhcpd'
DIMENSION '172_16_0_0_24_active_leases' '172.16.0.0/24' absolute 1 1 ''

BEGIN isc_dhcpd_IPv4.pools_active_leases 0
SET '172_16_0_0_24_active_leases' = 0
END

CHART isc_dhcpd_IPv4.pools_utilization '' 'Pools Utilization' '%' 'utilization' 'isc_dhcpd.utilization' line 60000 2 '' 'python.d.plugin' 'isc_dhcpd'
DIMENSION '172_16_0_0_24_utilization' '172.16.0.0/24' absolute 1 100 ''

BEGIN isc_dhcpd_IPv4.pools_utilization 0
SET '172_16_0_0_24_utilization' = 0
END

BEGIN netdata.runtime_isc_dhcpd_IPv4 0
SET run_time = 1
END

CHART isc_dhcpd_IPv6.leases_total '' 'All Active Leases' 'leases' 'active leases' 'isc_dhcpd.leases_total' line 60002 2 '' 'python.d.plugin' 'isc_dhcpd'
DIMENSION 'leases_total' 'leases' absolute 1 1 ''

BEGIN isc_dhcpd_IPv6.leases_total 0
SET 'leases_total' = 0
VARIABLE CHART 'leases_size' = 2
END

CHART isc_dhcpd_IPv6.pools_active_leases '' 'Active Leases Per Pool' 'leases' 'active leases' 'isc_dhcpd.active_leases' line 60001 2 '' 'python.d.plugin' 'isc_dhcpd'
DIMENSION '2001_470_1f0b_c9a_64_active_leases' '2001:470:1f0b:c9a::/64' absolute 1 1 ''

BEGIN isc_dhcpd_IPv6.pools_active_leases 0
SET '2001_470_1f0b_c9a_64_active_leases' = 0
```

**Comment by agross** [comment]
FYI, to update I `git fetch`ed your PR branch, `git checkout FETCH_HEAD` and then ran `./netdata-installer.sh`.

**Comment by l2isbad** [comment]
@agross thx
i believe it's fixed now. Please check it one more time

**Comment by agross** [comment]
@l2isbad It works! Many thanks for the quick implementation!

**Comment by l2isbad** [comment]
thx @agross 
if you have no more suggestions it's ready to merge

**Comment by agross** [comment]
LGTM! 👍

**Comment by l2isbad** [comment]
@ktsaou ready

**Comment by ktsaou** [comment]
super! merged it!

**Pull request merged**
