### PR TITLE
auto-detection of partitions based on /sys/dev/block/MAJOR:MINOR/partition

### PR DESCRIPTION
**Pull request by ktsaou**
#259, #258

netdata now reads `/sys/dev/block/MAJOR:MINOR/partition` to get the partition id of the block device in question. The result is cached, so that for each disk, this file is read just once.

### CODE REVIEW

**Comment by glensc** [comment]
so, do you detect that the device was changed? i.e to support hotplug ejeect and insert device by same device name.

**Comment by ktsaou** [comment]
I think that if the device has changed and is of a different type, new `major:minor` will be created. Only the same type gets the same ids. Even the `misc-util` used by `lsblk` caches this info.

**Comment by ktsaou** [comment]
The only problem is when a MAJOR:MINOR was a partition, and has switched to a main block device. Can you think of such a scenario?

**Comment by glensc** [comment]
no, if /dev/sdc is removed and inserted back it will always have same major:minor even across reboots. but it may be already different disk (for example usb storage). altho for your usecase you probably don't care that it's not the same disk anymore?

**Comment by ktsaou** [comment]
> altho for your usecase you probably don't care that it's not the same disk anymore

exactly

**Pull request merged**
