### PR TITLE
Freeradius plugin bugfix; should return empty list if there is no command

### PR DESCRIPTION
**Pull request by l2isbad**
Also freeradius plugin is not in Makefile. Do I need to add it myself?

### CODE REVIEW

**Comment by ktsaou** [comment]
> Also freeradius plugin is not in Makefile. Do I need to add it myself?

yes please...

**Comment by ktsaou** [comment]
merge?

**Comment by l2isbad** [comment]
One more quiestion - what about config.signatures file?

**Comment by ktsaou** [comment]
You can run:

```sh
./netdata-installer.sh get_git_config_signatures
```

to update them. This is normally needed when config files are changed.

**Comment by ktsaou** [comment]
I have to leave... I'll merge it in a few hours...

**Comment by l2isbad** [comment]
> This is normally needed when config files are changed.

if this is not necessary when creating the file i will leave it as is
then ready to merge

**Pull request merged**
