### PR TITLE
SCTP monitoring

### LINKED ISSUE #1218: SCTP Information
I would like to know if it is possible to get sctp connectivity details in netdata, just like TCP.
The number of SCTP Associations that are active,
SCTP Read/Write Queues
SCTP Errors
SCTP Handshake details, etc.

### PR DESCRIPTION
**Pull request by ktsaou**
fixes #1218

### CODE REVIEW

**Comment by Ferroin** [comment]
I'll try and test this within the next hour or so using both `iperf` and OpenSSH.  Just looking at the code though, it should cover what's asked for in #1218.

**Comment by ktsaou** [comment]
Perfect! I'll do.
Could you please a screenshot?

**Comment by Ferroin** [comment]
Yeah, give me a few minutes.

**Comment by Ferroin** [comment]
Images from a version before updating the title, while streaming data from `/dev/urandom` from one system to `/dev/null` on another using netcat wrapped with `withsctp` form lksctp-tools:

image

image

**Comment by ktsaou** [comment]
ok seems nice!

**Comment by ktsaou** [comment]
@Ferroin give it a run please.
If it looks good for you too, I'll merge it.

**Comment by l2isbad** [comment]
i see `sent` and `received` packets are both positive. Just notice.

**Comment by ktsaou** [comment]
nice catch. fixed it.

**Comment by ktsaou** [comment]
done!

**Pull request merged**
