### PR TITLE
FreeBSD plugin refactoring

### PR DESCRIPTION
**Pull request by vlvkobal**
Work in progress. Not completed yet.

### CODE REVIEW

**Comment by ktsaou** [comment]
Wow! You rock!

**Comment by vlvkobal** [comment]
@ktsaou It's finished. You can merge the PR. I still have to implement self-cleanup for removed disks, filesystems and network interfaces but I don't think it makes sense to do it hastily.

**Comment by ktsaou** [comment]
merged!

**Comment by ktsaou** [comment]
@vlvkobal it seems the `system.io` chart is gone: http://freebsd.my-netdata.io

**Pull request merged**
