### PR TITLE
Adds postfix monitoring for specific queues.

### PR DESCRIPTION
**Pull request by FarhadF**
This PR will add a new chart in postfix queues section, monitoring 4 postfix queues stated below.
- Incoming
- Active
- Deferred
- Bounced

This requires "netdata" to run with root privileges.

### CODE REVIEW

**Comment by paulfantom** [comment]
@FarhadF  ok, so now when I see whole code, we can do some optimizations. 

First of all we need to get rid of `run as root` situation. Can you test if running command `/usr/sbin/postconf` as normal user gives you some output (on CentOS 7 it does)?

Secondly, since you are not using `postqueue` but `postconf`, this module needs custom `check()` method to find if `postconf` is available on this system.

At last I think you should split `_get_data` to use some one method per command, same way it is done in `ipfs.chart.py` for getting data from many urls.

**Comment by FarhadF** [comment]
> First of all we need to get rid of run as root situation. Can you test if running command /usr/sbin/postconf as normal user gives you some output (on CentOS 7 it does)?

I'm on Debian jessie with final updates (8.5) and it works for normal users but you have to specify the full path.
I'm gonna find files in postfix queues directories and thats where I need the root access, look at active, deferred, incoming and bounced directories. owners and permissions in image below are all postfix defaults.
image

**Comment by FarhadF** [comment]
> At last I think you should split _get_data to use one method per command, same way it is done in ipfs.chart.py for getting data from many urls.
@paulfantom  awesome example, now I know how to fix it.

> Secondly, since you are not using postqueue but postconf, this module needs custom check() method to find if postconf is available on this system.
Can you explain more on this one? I found a check function in ExecutableService Class in base.py but I don't know how to fix it, and I guess I need to add my commands into postfix.conf but it only has a command variable.

**Comment by paulfantom** [comment]
About custom `check()` method, look at [tomcat.chart.py](https://github.com/firehol/netdata/blob/master/python.d/tomcat.chart.py)

**Comment by ktsaou** [comment]
@l2isbad please review this one too.

**Comment by l2isbad** [comment]
well, this one 'requires "netdata" to run with root privileges'..

**Comment by l2isbad** [comment]
Another problem is that this PR adds 5 more `Popen` calls.
But since 'root privileges' is  required there is nothing to review.

**Comment by ktsaou** [comment]
> requires "netdata" to run with root privileges'.

yes, you are right. This is a breaking issue.

@FarhadF I am closing this. I am very sorry, but we cannot merge it.

**Pull request closed without merging**
