### PR TITLE
isolated statvfs(); improved netdata cleanup/exit

### PR DESCRIPTION
**Pull request by ktsaou**
## the problem

`statvfs()`, the call that is used for disk space monitoring, is veeeeeery slow, causing the whole `proc` and `sys` plugins to be delayed.

The result is that under heavy system load, most internal plugins show gaps on the charts.

## the solution

disk space monitoring is now moved to its own thread, totally independent of the other `proc` and `sys` plugins.

---

additionally, this PR includes several improvements that allow netdata to exit in a more manageable way.

### CODE REVIEW

**Comment by ktsaou** [comment]
@vlvkobal you may want to check this for freebsd and macos.

**Comment by vlvkobal** [comment]
@ktsaou Verified it on FreeBSD and macOS. Everything is working.

**Comment by ktsaou** [comment]
thanks!

If you make `statvfs()` calls on them, remember to have them on separate threads...

**Comment by vlvkobal** [comment]
I make `getmntinfo()` calls. I haven't verified them for speed yet.

**Pull request merged**
