### PR TITLE
web_log dashboard improvements

### PR DESCRIPTION
**Pull request by ktsaou**
1. added `web_log` alarms
2. removed the obsolete `nginx_log` and `gunicorn_log` plugins
3. fixed a bug in the dashboard javascript code, that prevented information to be shown on submenu items where the chart `type` is dynamic (i.e. python modules).
4. added a lot of information about `web_log` charts on the dashboard.
5. updated `gauge.js` to the just released version 1.3.2
6. made a minor optimization in alarms parsing

---

the `web_log` plugin is AWESOME !
Once I merge it, I'll install it at the registry to see it in action.

**Thank you @l2isbad !**

### CODE REVIEW

**Comment by l2isbad** [comment]
@ktsaou 
https://github.com/firehol/netdata/blob/master/python.d/web_log.chart.py#L210-L215

**Comment by l2isbad** [comment]
still `Response Codes` `web_log.detailed_resp` and  `HTTP Methods `

**Comment by l2isbad** [comment]
And i'm not sure about `sum` [here](https://github.com/firehol/netdata/blob/master/conf.d/health.d/web_log.conf#L78)

**Comment by l2isbad** [comment]
btw dashboard looks awesome with all those descriptions!

**Comment by ktsaou** [comment]
yes it is.

I am making a PR now.

**Pull request merged**
