### PR TITLE
Cpufreq + exim + postfix

### PR DESCRIPTION
**Pull request by paulfantom**
Changed description for every python module (since they are modules not plugins)

Created `exim.chart.py` and `postfix.chart.py` which are based on `ExecutableService` class.
Also added `cpufreq.chart.py`.
Added their configuration files, which are almost empty (they can have also `retries` and `priority` just like every conf file).

I have tested it. It should be ready to merge.

(Modules left: 4)

### CODE REVIEW

**Comment by ktsaou** [comment]
merged.

If you plan to add sensors, it would be better if we could do it with libsensors (https://github.com/Sensirion/libsensors-python)

**Comment by ktsaou** [comment]
Wrong python library. I guess this is the one: https://pypi.python.org/pypi/PySensors/

**Comment by paulfantom** [comment]
I thought so too since looking for them in /sys/devices is a little complicated.

**Comment by paulfantom** [comment]
But there is a problem with this library. I don't think it is compatible with python3, but I will check it.

**Comment by ktsaou** [comment]
ok. Your call.

**Comment by ktsaou** [comment]
Regarding the required packages, I am experimenting with an automatic package installer here: https://github.com/firehol/netdata-demo-site/blob/master/install-required-packages.sh

I keep a map of the packages required per distribution: https://github.com/firehol/netdata-demo-site/blob/e2efb8fc8c2815b7f7e18e229d8776e446ea9bb3/install-required-packages.sh#L576-L594

To test it:

```sh
curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh netdata-all
```

I does not do anything without confirming it with the user first, so it is safe to test.

**Comment by paulfantom** [comment]
It look quite good. However I think there might be an issue when distro default python interpreter is `python3` and package names are installed for `python2`. I think you could test it on fedora 24 since they are using python3 as default.

Also:
```
FIXME
# 1. add zypper (opensuse)
# 2. add rpm (who uses it now?)
```
Maybe I can help since my main distro is openSUSE Leap. 
And no one uses `rpm` these days.

**Comment by paulfantom** [comment]
Also unfortunately `PySensors` isn't included in many distro repositories (ex. openSUSE).

**Comment by ktsaou** [comment]
> I think you could test it on fedora 24 since they are using python3 as default.

hm... if the package names change based on the python version, we should run $(python --version) and pick the right ones.

**Comment by ktsaou** [comment]
Do we have a preference on python version? If both are available, I guess we should use the version that $(python --version) returns. Right?

**Comment by paulfantom** [comment]
Yes that's the idea.

**Comment by paulfantom** [comment]
As I recall in ubuntu and openSUSE python packages are named `python-some_name` for `python2` and `python3-some_name` for `python3`. I don't remember how it is in other distros.

**Comment by paulfantom** [comment]
I will just leave it here and go back to writing python modules. You can include it into installer or wait until I rewrite 4 remaining modules to python and then take care of it.

openSUSE dependencies to build netdata:
- zlib-devel
- libuuid-devel
- libmnl0

other:
- nodejs
- python-MySQL-python  (stupidest name I have seen)
- python-PyYAML

release file path: "/etc/SuSE-release"

`nc` is in `netcat-openbsd` but can be installed by using `netcat` capability package (`zypper install netcat`)
`pkgconfig` is in `pkg-config`

**Comment by ktsaou** [comment]
cat you give me the contents of `/etc/SuSE-release` and `/etc/os-release`?

**Comment by paulfantom** [comment]
/etc/SuSE-release:
```
openSUSE 42.1 (x86_64)
VERSION = 42.1
CODENAME = Malachite
# /etc/SuSE-release is deprecated and will be removed in the future, use /etc/os-release instead
```
/etc/os-release:
```
NAME="openSUSE Leap"
VERSION="42.1"
VERSION_ID="42.1"
PRETTY_NAME="openSUSE Leap 42.1 (x86_64)"
ID=opensuse
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:opensuse:42.1"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://opensuse.org/"
ID_LIKE="suse"
```

**Comment by paulfantom** [comment]
Also `openSUSE Leap` should be compatible with `SuSE linux` but I don't have any platform to confirm it.

**Comment by ktsaou** [comment]
Could you please test it again?

Run it like this:

```sh
curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh ignore-installed all
```

It will try to install everything it knows (including nginx).
If you don't mind, let it do it to check all the package names are right.

also, is there a `python-pip`?

I think it might would have to install via pip if everything else fails.

**Comment by ktsaou** [comment]
and the `python-dev` packages.
If we are going to install via pip, I think `libyaml-dev` and `libmysqlclient-dev` will be needed too.

**Comment by paulfantom** [comment]
I will test it tomorrow since I don't have time today. But I glanced on code and found some minor issues regarding openSUSE:
- no information about SuSE support in `Supported distributions`
- package python3-PyYAML exists in opensuse repository

And yes there are `python-pip` and `python3-pip`

**Comment by ktsaou** [comment]
thanks! Fixed.
I also refactored it a bit to be cleaner and more flexible.
When you test it, let me know.

**Comment by paulfantom** [comment]
I am testing it now. Fedora 24 first (live ISO).

install line:
`dnf install autoconf autoconf-archive autogen automake curl gcc gdb git iproute2 ipset iptables jq libmnl-devel make nginx nmap-ncat nodejs pkgconfig python python3 python-mysql python-yaml screen tcpdump traceroute ulogd unzip uuid-devel valgrind zip zlib-devel`

On fedora `python3` is installed but not aliased to `python` (and I think it should, according to [PEP 394](https://www.python.org/dev/peps/pep-0394/)). This way shebang command `/usr/bin/env python` won't work and we need to install `python2`. 

Fedora 24 issues:
- installation fails (no package `iproute2`. `iproute2` is provided by `iproute` package)
- assumes not installed `python2` instead of installed `python3`
- no package `python3-yaml` (it is called `python3-PyYAML`)
- it should install `python3-mysql` but doesn't

**Comment by paulfantom** [comment]
openSUSE Leap 42.1:

install line:
`sudo zypper install autoconf autoconf-archive autogen automake curl gcc gdb git iproute2 ipset iptables jq libmnl0 libuuid-devel make netcat-openbsd nginx nodejs pkgconfig python python3 python3-PyYAML python-MySQL-python python-PyYAML screen tcpdump traceroute ulogd unzip valgrind zip zlib-devel`

Packages were installed sucessfully.

Also why does it install packages for python2 and python3?

**Comment by ktsaou** [comment]
I have pushed a few changes to fix the fedora issues.

Well, regarding python2 and python3 I guess I am confused. As it is today, python3 modules are installed on top of python2. I found that python2 is always there, so I thought it would be good to do it this way.

Of course I am open to other ideas too.

**Comment by paulfantom** [comment]
They aren't installed on top of each other, they are in different folders (`/usr/lib64/python3.4/site-packages` and `/usr/lib64/python2.7/site-packages` on openSUSE). It doesn't make sense to install python3 packages when system uses python2. It is not a mistake, you just install packages which won't be be used.

Also fedora 24 uses some clever tricks to install packages for python2 (when installing `python` interpreter package it also installs `python-pip` and `python-setuptools` thus I think they are somehow using [pypi](pypi.python.org) package repository).

**Comment by ktsaou** [comment]
What I meant was that if you enable python3, then python2 packages will be installed too. This is what I called "on top". The script will also attempt to install python itself (the proper version).

Did it work now on fedora?

**Comment by paulfantom** [comment]
Ok, I misunderstood you. For demo sites this approach is ok, but for installation on servers I don't think we should install python interpreter, especially if one already exists.

I will retest fedora in a moment.

Ubuntu 16.04:

install line:
apt-get install autoconf autoconf-archive autogen automake git libmnl-dev nodejs python-mysqldb python-yaml uuid-dev zlib1g-dev

Packages installed ok.
Netdata runs ok.

**Comment by ktsaou** [comment]
> apt-get install autoconf autoconf-archive autogen automake git libmnl-dev nodejs python-mysqldb python-yaml uuid-dev zlib1g-dev

You didn't give the `ignore-installed` parameter. It is important to test with it since it may conditionally fail to install a few packages.

> I don't think we should install python interpreter, especially if one already exists.

It only includes the python interpreter if the `ignore-installed` option is given.

**Comment by paulfantom** [comment]
I copied same line as in [previous comment](https://github.com/firehol/netdata/pull/665#issuecomment-231506938) which has `ignore-installed` in it. 
I will test it again in case I haven't copied everything.

**Comment by paulfantom** [comment]
You were right, I copied wrong line.

Ubuntu 16.04:

install line:
`apt-get install autoconf autoconf-archive autogen automake curl gcc gdb git iproute2 ipset iptables jq libmnl-dev make netcat nginx nodejs pkg-config python python3 python3-mysql.connector python3-yaml python-mysqldb python-yaml screen tcpdump traceroute ulogd unzip uuid-dev valgrind zip zlib1g-dev`

Issues:
- `python3-mysql.connector` is a different mysql connector from the one `mysql.chart.py` uses. It should be `python3-mysqldb`

Everything else is ok. 
Netdata works.

**Comment by paulfantom** [comment]
Fedora 24:

install line:
`dnf install autoconf autoconf-archive autogen automake curl gcc gdb git iproute ipset iptables jq libmnl-devel make nginx nmap-ncat nodejs pkgconfig python python3 python3-mysql python3-PyYAML python-mysql python-yaml screen tcpdump traceroute ulogd unzip uuid-devel valgrind zip zlib-devel`

Netdata cannot be build. 
`No package 'uuid' found`

It should install `libuuid-devel` instead of `uuid-devel`

With `libuuid-devel` netdata works.

**Comment by paulfantom** [comment]
Do you want me to test some more systems (apart from gentoo and arch)?

**Comment by ktsaou** [comment]
> It should install libuuid-devel instead of uuid-devel

Nice finding! I fixed it.

> Do you want me to test some more systems (apart from gentoo and arch)?

please do, if you have access to...

**Comment by ktsaou** [comment]
> python3-mysql.connector is a different mysql connector from the one mysql.chart.py uses. It should be python3-mysqldb

fixed that too. The script however assumes debian and ubuntu are the same. I hope this is ok.

**Comment by paulfantom** [comment]
Will see, I will test debian next.

**Comment by paulfantom** [comment]
Debian 8:

install line:
`apt-get install autoconf autoconf-archive autogen automake curl gcc gdb git iproute2 ipset iptables jq libmnl-dev make netcat nginx nodejs pkg-config python python3 python3-mysqldb python3-yaml python-mysqldb python-yaml screen tcpdump traceroute ulogd unzip uuid-dev valgrind zip zlib1g-dev`

And of course it couldn't be so simple. Debian doesn't have `python3-mysqldb` (`mysql.chart.py` won't work on debian with python3 since they don't have required packages)

Installation fails.

**Comment by ktsaou** [comment]
do they have pymysql? python3-pip (so that we can install it using pip)?

**Comment by paulfantom** [comment]
No they don't have `pymysql`. Yes there is `python3-pip`. Just remember that default python interpreter on debian is `python2`.

I will also test Debian 7, Ubuntu 14.04, CentOS 7 and maybe CentOS 6.

**Comment by ktsaou** [comment]
nice.

I see on ubuntu and debian there is only `python3-mysql.connector`.

**Comment by ktsaou** [comment]
If you can also test suse would be nice.

**Comment by paulfantom** [comment]
Ubuntu 16.04 has `python3-mysqldb` in default repository. Look:
http://packages.ubuntu.com/xenial/python/python3-mysqldb

`mysql.connector` is something incompatible with `mysql.chart.py`

**Comment by paulfantom** [comment]
Sadly I don't have any suse images.

**Comment by ktsaou** [comment]
This is becoming increasingly complex... All derivatives of ubuntu-16.04 and later have it, but older ones don't.

If we could have a command line to check the availability of package on each system, it would be a lot better.

**Comment by paulfantom** [comment]
You are right. I propose to switch to `pip` and leave installing packages from repositories to packagers.

**Comment by paulfantom** [comment]
CentOS 7:

install line:
`yum install autoconf autoconf-archive autogen automake curl gcc gdb git iproute ipset iptables jq libmnl-devel libuuid-devel make MySQL-python nginx nmap-ncat nodejs pkgconfig python python3 python3-PyYAML python-yaml screen tcpdump traceroute unzip uuid-devel valgrind zip zlib-devel`

`ERROR/I don't know how to install ulogd here`

Installs cleanly.
Netdata installs and works.

**Comment by ktsaou** [comment]
probably. Even pip though have its issues. For example, to install python-mysqldb, there should be mysqlclient and python3-devel installed.

**Comment by ktsaou** [comment]
> yum install autoconf autoconf-archive autogen automake curl gcc gdb git iproute ipset iptables jq libmnl-devel libuuid-devel make MySQL-python nginx nmap-ncat nodejs pkgconfig python python3 python3-PyYAML python-yaml screen tcpdump traceroute unzip uuid-devel valgrind zip zlib-devel

There is no python3-mysql. Is it available? There should be an ERROR line about it too.

**Comment by paulfantom** [comment]
So maybe just disable python3 on almost every distro apart from fedora 23, 24 and arch since they are using it as default interpreter. And then I can test it again (I've set up VMs with clean OSes, so it should be quick).

**Comment by paulfantom** [comment]
Ah sorry I didn't paste it, but yes there is no `python3-mysql`.

**Comment by ktsaou** [comment]
> So maybe just disable python3 on almost every distro apart from fedora 23, 24

It is disabled by default. It is enabled only if `$(python --version)` gives 3.x or if `python3` is given on the command line. The `all` option enabled `python3` too.

**Comment by ktsaou** [comment]
Users will by using the script with option `netdata` (basic setup with python - no mysql, no nodejs) or `netdata-all` (all netdata modules, including mysql and nodesj).

**Comment by paulfantom** [comment]
Ok, so basically we have following options:
1. install everything with package installer
2. install `pyyaml` and `pymysql` via pip/pip3

To make things worse second option needs some packages from repository (`mysqlclient-dev` or whatever it is called).

There is also another issue with Fedora, when `/usr/bin/env python` cannot find python interpreter, we need to execute: `update-alternatives --install /usr/bin/python python /usr/bin/python3 1`.

**Comment by paulfantom** [comment]
Also according to other python devs and distribution maintainres, symlink returned by `/usr/bin/env python` should always point to `python2`, so basically we can ditch `python3` in installer.

**Comment by ktsaou** [comment]
> so basically we can ditch python3 in installer.

To make things even more interesting Arch Linux comes with python3 by default and on gentoo the user can pick python2 or python3 as the default python interpreter.

I think, the way I have it now is the best. If `$(python --version)` gives 3.x then install python3.

To totally ignore python3, we should change the shebang of `python.d.plugin` to `$!/usr/bin/env python2`. This way, we will always use python2. Or even better find something exotic, like the one I have at `node.d.plugin`:

```sh
#!/bin/sh
':' //; exec "$(command -v nodejs || command -v node || command -v js || echo "ERROR node.js IS NOT AVAILABLE IN THIS SYSTEM")" "$0" "$@"
```

This works because the second line is a valid line in both bash and node.js.

**Comment by paulfantom** [comment]
> To make things even more interesting Arch Linux comes with python3 by default and on gentoo the user can pick python2 or python3 as the default python interpreter.

I know about it, but both of them have symlinks to `python` command (fedora doesn't) thus you can execute `$(python --version)` (on fedora it will produce an error). 
Also I don't want to ditch python3 in code.

I will search for some exotic method like the one you use in `node.d.plugin`

**Comment by ktsaou** [comment]
This works for me:

```sh
#!/usr/bin/env bash
'''':; exec "$(command -v python2 || command -v python3 || command -v python || echo "ERROR python IS NOT AVAILABLE IN THIS SYSTEM")" "$0" "$@" # '''

import sys
import os

print("parameters: ")
print(sys.argv)

print("")
print("python version: ")
print(sys.version_info)
```

The string `ERROR python IS NOT AVAILABLE IN THIS SYSTEM` does not need `>&2`. It is considered a command name bash attempts to execute, so if python is not found it prints:

```sh
./test.py: line 2: exec: ERROR python IS NOT AVAILABLE IN THIS SYSTEM: not found
```

Tested on:

- gentoo (runs python2)
- arch (runs python2)
- debian 8 (runs python2)
- ubuntu 14.04 (runs python2)
- ubuntu 10.04 (runs python2)

**Comment by paulfantom** [comment]
Wow! It really works. I will test it in netdata and probably implement with some bug fixes and redis module.

**Comment by ktsaou** [comment]
Idea from here. It didn't work right away, so I had to touch it a bit.

http://stackoverflow.com/questions/18993438/shebang-env-preferred-python-version

The node.js one comes from stackoverflow too.

**Comment by ktsaou** [comment]
Here is the node.js version:
http://stackoverflow.com/questions/20638520/appropriate-hashbang-for-node-js-scripts

**Comment by ktsaou** [comment]
And this is its source: http://unix.stackexchange.com/questions/65235/universal-node-js-shebang/65295#65295

**Comment by ktsaou** [comment]
I added the packages installer to the installation page at the wiki: https://github.com/firehol/netdata/wiki/Installation

Let's see what happens...

**Comment by paulfantom** [comment]
Ok, tomorrow I'll try to finish `redis.chart.py` and make will make PR with it and some minor fixes.

**Pull request merged**
