### PR TITLE
Added SHIFT/ALT increment (5x-10x) to zoom out button

### PR DESCRIPTION
**Pull request by Ubiquitous**
Allows the ability to zoom out at 900% the default increment for quickly viewing a larger range of data.

### CODE REVIEW

**Comment by ktsaou** [comment]
Instead of adding another button, I would prefer a check if a keyboard key is pressed while clicking on the other buttons.

For example:

- without any keyboard, use `pan_and_zoom_step * 1`
- with SHIFT pressed, use `pan_and_zoom_step * 2`
- with ALT pressed, `pan_and_zoom_step * 5`
- with CONTROL pressed, `pan_and_zoom_step * 10`

What do you think?

**Comment by Ubiquitous** [comment]
Sure that would work also, and I think it's a better solution. The only reason I added another button was because I wasn't certain the using modifier keys as you mentioned would be compatible across browsers.

**Comment by ktsaou** [comment]
Actually I have kept this little space there for a `volume` button, that once pressed will show the volume of each dimension in the visible area.

ok. Would you update your PR with the keyboard adaptation or you want me to do it?

**Comment by Ubiquitous** [comment]
I noticed the volume area that was commented out, so I presumed you had intentions along the same lines. 

I'm a bit unfamiliar with how to implement the modifier keys, although I think that there's probably such an example within the ```dashboard.js```. As far as browser compatibility and other platforms are concerned, do you know if there will be any issues in that regard?

**Comment by Ubiquitous** [comment]
I've added the SHIFT/ALT functionality to the zoom out toolbox button (minus) only.

**Comment by ktsaou** [comment]
> I've added the SHIFT/ALT increment (5x-10x) functionality to the zoom out toolbox button (minus) only.

we were doing the same thing at the same time!

I added them to all buttons.

**Comment by ktsaou** [comment]
created PR #252

**Comment by Ubiquitous** [comment]
Great! ... I'll test them out asap :)

**Comment by ktsaou** [comment]
I close this. Done with #252

**Pull request closed without merging**
