### PR TITLE
tomcat module: add desired port into account (multiple connectors)

### PR DESCRIPTION
**Pull request by l2isbad**
https://github.com/firehol/netdata/issues/1623
Must be tested (works for me)

@KaelBaldwin
can you test this one?

### CODE REVIEW

**Comment by KaelBaldwin** [comment]
Sure I'll try it out!

**Comment by KaelBaldwin** [comment]
Yeah this is working great for me thanks!

**Comment by l2isbad** [comment]
@KaelBaldwin thx!
@ktsaou this one is ready

**Comment by ktsaou** [comment]
thanks!

**Pull request merged**
