### PR TITLE
uptime plugin added

### PR DESCRIPTION
**Pull request by l2isbad**
screenshot_20170112_030422

### CODE REVIEW

**Comment by ktsaou** [comment]
hm... this would be difficult to badge... Ideally it should be a simple number of seconds. Badges accept multipliers and dividers at the URL, so it would be possible to display `14.5` days. Now it will be either `14` or `15`.

**Comment by ktsaou** [comment]
Also, uptime will be needed for #1527, so netdata will most probably collect it internally (IoT may not have python, and we really need that metric for detecting if a device was rebooted), so my suggestion is drop this and implement it in netdata.

**Comment by l2isbad** [comment]
> is drop this and implement it in netdata

ok ok I hurried with that)

**Comment by jvantslot** [comment]
I2isbad:  That looks great!  How would this info look in a badge? It would be nice if it could be formatted something like this:
uptime 
Otherwise it might make for lengthy badge with the words days, hours, minutes.

**Comment by l2isbad** [comment]
@jvantslot  PR is closed
It is too sexy to be implemented )
see comments above

**Comment by ktsaou** [comment]
implemented in `C`: #1547

**Pull request closed without merging**
