### PR TITLE
Time improvements

### PR DESCRIPTION
**Pull request by rlefevre**
Hi,

Let's begin to use monotonic clocks where this could prevent some issues.

It's not complete and there are some more controversial changes to discuss later, but I tried to start by most "benign" changes, and there is already a lot to comment I'm sure.

Also note that this is not very tested yet, I may require some help there once we are settled.

Thanks

PS: I do a review for myself on mobile because I can't modify the code right now, you can ignore those of you want (or not ;)

### CODE REVIEW

**Comment by vlvkobal** [comment]
You have a typo in plugin_freebsd.c
```
diff --git a/src/plugin_freebsd.c b/src/plugin_freebsd.c
index e48bb7f..0370f57 100644
--- a/src/plugin_freebsd.c
+++ b/src/plugin_freebsd.c
@@ -29,7 +29,7 @@ void *freebsd_main(void *ptr)
     heartbeat_t hb;
     heartbeat_init(&hb);
     for(;;) {
-        usec_t hb_dt = heatbeat_next(&hb, step);
+        usec_t hb_dt = heartbeat_next(&hb, step);
 
         if(unlikely(netdata_exit)) break;

 ```
With this correction I can build `netdata` and it works. Shall I test anything in particular or is it enough?

**Comment by ktsaou** [comment]
nice work! Thank you!
I can't check this today.
So, please give me a day to review it in detail.

**Comment by rlefevre** [comment]
No problem. This requires some careful review, nothing in a hurry.

**Comment by ktsaou** [comment]
Sorry for the delay... it has been a loooooong week.

I see you have done an excellent job...

Just one comment:

Commit https://github.com/firehol/netdata/pull/1368/commits/1545f2f1b11147c6cd91bd584368c43b4e887589 I believe is wrong.

Since, all these modules work one after another sequentially, a delay in one of them will delay all the others after that one. The way it was, each of the modules had its own timings, so netdata knew how to interpolate the values for each module.

This commit, uses the same heartbeat for all of them. So, if one module is slow for some reason, the others will get their timings shifted, which will influence interpolation.

This is not a big deal most of the time. However, under severe system pressure, we may get wrong values.

I haven't gone through all the changes for checking if they break something other than the iteration loops (i.e. if the variables are used for something different to iterating). Once this is ready to be merged, I think we should test it extensively.

Thank you! You are the best!

**Comment by rlefevre** [comment]
>  So, if one module is slow for some reason, the others will get their timings shifted, which will influence interpolation.

Well, I'm not sure to understand the link with interpolation, `dt` is only used in 3 functions:

- `do_proc_loadavg()`
Here `dt` is used to run it no more than every 5 seconds:

```
// linux calculates this once every 5 seconds
#define MIN_LOADAVG_UPDATE_EVERY 5
...
    if(last_loadavg_usec <= dt) {
...
        last_loadavg_usec = load_chart->update_every * USEC_PER_SEC;
    }
    else last_loadavg_usec -= dt;
```
- `do_proc_diskstats()`
Here `dt` is used only as a `static firstrun` replacement:
```
        // --------------------------------------------------------------------
        // calculate differential charts
        // only if this is not the first time we run

        if(likely(dt)) {
```
- `do_proc_net_stat_conntrack()`
Here it is used to avoid updating the `nf_conntrac_max_filename` at every update:
```
        usec_since_last_max = get_max_every = config_get_number("plugin:proc:/proc/sys/net/netfilter/nf_conntrack_max", "read every seconds", 10) * USEC_PER_SEC;
...
    usec_since_last_max += dt;
    if(unlikely(rrdvar_max && usec_since_last_max >= get_max_every)) {
        usec_since_last_max = 0;

        unsigned long long max;
        if(likely(!read_single_number_file(nf_conntrack_max_filename, &max)))
            rrdvar_custom_host_variable_set(rrdvar_max, max);
    }
```

`dt` is not used in any other function, so it seems to me it is actually only used as an update frequency divider. Actually at first I removed it from all functions except `do_proc_loadavg()` and `do_proc_net_stat_conntrack()` and replaced it by a static variable in `do_proc_diskstats()`.

I don't think using each module `dt` makes much difference versus using the heatbeat one in these case. Actually some time can also pass in a specific module before `dt` is used. However if you think it is still better to have dedicated `dt` per module, we can just replace each:
```
do_proc_xxx(update_every, hb_dt);
```
by
```
do_proc_xxx(update_every, hb_dt ? hb_dt + heartbeat_dt_usec() : 0ULL);
```
It's just I found all the unused time functions calls wasted.

**Comment by ktsaou** [comment]
You are right. I thought we were using `dt` with `rrdset_next_usec()`: https://github.com/firehol/netdata/blob/master/src/rrd.c#L1012

The way it is now, your code is perfect.

I implemented `rrdset_next_usec()` to fix misleading charts under extreme system load. It is used in external plugins that I could verify that netdata is a lot better with it, but I never found the time to properly test the benefits of its use at the internal plugins.

**Comment by rlefevre** [comment]
I rebased the patchset and fixed the freebsd typo and some minor things from my own comments.

**Comment by rlefevre** [comment]
@ktsaou My patchset keeps the behavior of ticking on almost exact seconds (more exactly on multiples of update_every), but I have to admit I didn't really understood the point of doing this (compared to run at a precise frequency, but not rounded on multiples of update_every). Could you explain to me the motivation of this design ? Thanks.

**Comment by ktsaou** [comment]
> @ktsaou My patchset keeps the behavior of ticking on almost exact seconds (more exactly on multiples of update_every), but I have to admit I didn't really understood the point of doing this (compared to run at a precise frequency, but not rounded on multiples of update_every). Could you explain to me the motivation of this design ? Thanks.

Well, it is because of `incremental` metrics. Since the database works on `update_every` boundaries, it would also be useful to have data collection working on the same clock. The reason is simple: if we have 1 request in 1 second, I needed to find a way not to show 0.5 reqs/sec on the first second and 0.5 reqs/sec on the second.

The way it is now (and since netdata interpolates everything with microsecond detail), you get something like 0.999 reqs/sec on the first and 0.001 reqs/sec on the second, which is quite good, since spikes can be spotted easily.

**Comment by rlefevre** [comment]
I'm not sure to completely understand. For example considering `plugin_proc`, the data collection is sequential, so the last collected values are not anymore on a `update_every` boundary. Maybe it doesn't matter as long as collection does not take more than 1 second as the database will still put the value on the same boundary?

Also, don't we have an issue with my patchset as the monotonic clock `update_every` boundaries (used by heartbeat) do not match the realtime clock ones (used by RRDs)?

**Comment by ktsaou** [comment]
ok, let me explain in a bit more detail:

time|collected value
----|------------
00:00:00.500|1000
00:00:01.500|1001
00:00:02.500|1001

The dimension is `incremental` and without alignment is interpolated like this:

timeframe|value
------|------
00:00:01 to 00:00:02|0.5
00:00:02 to 00:00:03|0.5

With alignment, the source is collected like this:

time|collected value
----|------------
00:00:00.001|1000
00:00:01.001|1001
00:00:02.001|1001

and is interpolated like this:

timeframe|value
------|------
00:00:01 to 00:00:02|0.999
00:00:02 to 00:00:03|0.001

The fact the all proc modules are collected sequential does not change much. If you check the duration a full iteration on them takes on the dashboard (there is a chart for this), it is something like 1-3ms, which is still very early within each interpolation timeframe.

**Comment by ktsaou** [comment]
Keep in mind that a misalignment will not result in anything significant. I just thought the alignment gives better results.

**Comment by ktsaou** [comment]
When you believe it is ready for merge, let me know to install it on a few servers to test it.

**Comment by rlefevre** [comment]
Well, there are two important points to valid first :
1. Following your previous explanation about `update_every` boundaries, I think my patchset might break this. A monotonic clock second boundary will not match a real-time one. However I have a comment :
>  If you check the duration a full iteration on them takes on the dashboard (there is a chart for this), it is something like 1-3ms
Well, it depends on the system load. Also `apps_plugin` might take a little longer.
2. I added a `backends.c` patch that you may find controversial. Please review it.

**Comment by ktsaou** [comment]
> I think my patchset might break this

The fix could be quite easy. Keep a constant diff in microseconds, to align monotonic with realtime and add this diff to monotonic before returning it. So, the monotonic function will always return a value shifted by that diff.

This will result in wrong alignment only after hibernation, which I think is an acceptable tradeoff.

> Well, it depends on the system load. Also apps_plugin might take a little longer. I'm not able with my current knowledge to evaluate the severity of breaking this.

The whole idea of alignment is not that critical. It makes charts visually better, it is nice to have it, but under system pressure, or in situations that is unreasonable to do it (like apps.plugin), netdata will nicely work without it.

> I added a backends.c patch that you may find controversial. Please review it.

I'll do later - (too many tickets).

**Comment by ktsaou** [comment]
I think I have forgotten this.

Do you wait for me?

**Comment by ktsaou** [comment]
I added `now_monotonic_usec()` to plugin_proc.c
I have the impression this is a lot faster than `now_realtime_usec()`.

A few of the changes already merged, caused a few conflicts to this PR.

I don't see the controversial change in this PR. Can you help me?

**Comment by rlefevre** [comment]
Sorry, I didn't have much time to work on this recently.

The remaining issue to merge the patchset in the heart beat alignment to real-time clock as you proposed to avoid degrading charts visually. 

We have 3 choices :
* I rebase the patch and change the heartbeat API to work on real clock temporary to avoid any regression (this should still be tested more)
* I rebase it as is and we accept the alignment issue until an improvement
* I rework the patch to compensate the offset with real-time clock but need more time

What do you think

**Comment by ktsaou** [comment]
hm... I always prefer simple changes, one step at a time. So, for this to be merged, it has to be a safe change. So, my suggestion is to fix alignment at a later PR.

I am going to release v1.5 this weekend. So, I think we should not put this in it. Update it so that we can test it, and if it is ok, I will merge it next week.

**Comment by rlefevre** [comment]
Hi I'm back, sorry for the delay.

I rebased the patchset on current master. This still breaks the alignment. We could have kept using CLOCK_REALTIME in the heartbeat API until we have a fix to keep the exact same behavior as previously, but as I see that plugin_proc has already been converted to monotonic clock, this does not seem to make much sense now (also the issues fixed by the monotonic clock might be more severe than the alignment one).

I will have to work on a fix later if future clock patches do not fix it naturally, should we open a bug until then?

Anyway I think the patchset is ready for more testing and then merge if everything seems ok.

**Comment by rlefevre** [comment]
I just added patches for MacOS plugin and plugin_proc_diskspace as they did not exist before. It would be nice to have someone test that MacOS patch does not break anything.

**Comment by vlvkobal** [comment]
It can be built on macOS and it works. I haven't find any issues.

**Comment by tycho** [comment]
Curious: What's used for monotonic time on OS X? Just `mach_absolute_time()` or something?

**Comment by rlefevre** [comment]
@ktsaou, do you expect anything more from me to have this patchset go forward? 

Thank you

**Comment by ktsaou** [comment]
> do you expect anything more from me to have this patchset go forward?

no, it is just me delaying this. I need to test all modules touched, one-by-one. I can see you have done an excellent job in this, but I still need to be sure.

This repo is downloaded and installed hundreds of times per day. A lot of which are automated, through cron, so I just need to be sure there are no memory leaks, no infinite loops, no crashes, etc.

image
*the release doubled the clones - but even under normal work days, we have 500 unique cloners per day*

**Comment by ktsaou** [comment]
I commit I will merge this during the weekend!
(I know I have stalled you long enough)

**Comment by rlefevre** [comment]
@ktsaou I'm sorry if you fell some pressure in my question, this was not my intention. I perfectly understand the high level of maturity required by netdata master and I know that I cannot do enough tests of my own to guarantee that my patchset does not bring any regression or new bugs.

Therefore do exactly as you wish, I fully trust and support your decisions concerning merges.

**Comment by rlefevre** [comment]
@tycho Systems that do not support `clock_gettime(CLOCK_MONOTONIC, ...)` currently fall back to using `gettimeofday()`, so I suppose that on OSX, the netdata "monotonic" clock is actually the same as the realtime one. 

A specific implementation could be added for OSX to improve this, but I don't have any such system to do it myself.

**Comment by simonnagl** [comment]
Did some research on my macOS about clock_gettime.

from `man 3 clock_gettime`
```
     CLOCK_REALTIME     the system's real time (i.e. wall time) clock, expressed as the
                        amount of time since the Epoch.  This is the same as the value
                        returned by gettimeofday(2).

     CLOCK_MONOTONIC    clock that increments monotonically, tracking the time since an arbi-
                        trary point, and will continue to increment while the system is
                        asleep.

     CLOCK_MONOTONIC_RAW
                        clock that increments monotonically, tracking the time since an arbi-
                        trary point like CLOCK_MONOTONIC.  However, this clock is unaffected
                        by frequency or time adjustments.  It should not be compared to other
                        system time sources.

     CLOCK_MONOTONIC_RAW_APPROX
                        like CLOCK_MONOTONIC_RAW, but reads a value cached by the system at
                        context switch.  This can be read faster, but at a loss of accuracy
                        as it may return values that are milliseconds old.

     CLOCK_UPTIME_RAW   clock that increments monotonically, in the same manner as
                        CLOCK_MONOTONIC_RAW, but that does not increment while the system is
                        asleep.  The returned value is identical to the result of
                        mach_absolute_time() after the appropriate mach_timebase conversion
                        is applied.

     CLOCK_UPTIME_RAW_APPROX
                        like CLOCK_UPTIME_RAW, but reads a value cached by the system at con-
                        text switch.  This can be read faster, but at a loss of accuracy as
                        it may return values that are milliseconds old.

     CLOCK_PROCESS_CPUTIME_ID
                        clock that tracks the amount of CPU (in user- or kernel-mode) used by
                        the calling process.

     CLOCK_THREAD_CPUTIME_ID
                        clock that tracks the amount of CPU (in user- or kernel-mode) used by
                        the calling thread.

```
Example program.
https://gist.github.com/simonnagl/0ee3e05b87cf0b0673063f345b4b6f23

I hope this helps.

**Comment by rlefevre** [comment]
@simonnagl If macOS now supports `clock_gettime()` (I think it did not support it a few years ago), then `clock_gettime(CLOCK_MONOTONIC, ...)` will be used (this is an autotools detection). Thanks for the info.

**Comment by simonnagl** [comment]
I get the same output on macOS 10.12.2.

**Comment by tycho** [comment]
Interesting! I know for certain that OS X didn't support `CLOCK_MONOTONIC` ages ago, and I don't think it even had the `clock_gettime()` API. If it's there and works, that's fantastic!

**Comment by ktsaou** [comment]
tested. Seems excellent!
merging it.

Thank you @rlefevre !

**Comment by ktsaou** [comment]
I just found another "weakness" of misalignment: depending on the delta of MONOTONIC to REALTIME, the dashboard may be 1 second or 2 seconds behind reality...

Of course, since the dashboard is based on the clock of the web browser for calculating deltas, this might also happen if the client is not synced to realtime.

**Pull request merged**
