### PR TITLE
Py2 monotonic time

### PR DESCRIPTION
**Pull request by l2isbad**
@ktsaou 

https://github.com/firehol/netdata/issues/3752

i have a question about `clock_gettime(CLOCK_MONOTONIC_RAW, ctypes.pointer(t)) != 0`

if i understand it right i have to [check](https://github.com/l2isbad/netdata/blob/py2_monotonic_time/python.d/python_modules/bases/monotonic.py#L29) it [only once on start](https://github.com/l2isbad/netdata/blob/py2_monotonic_time/python.d/python_modules/bases/FrameworkServices/SimpleService.py#L12-L14), not on every call, right?

### CODE REVIEW

**Comment by ktsaou** [comment]
> if i understand it right i have to check it only once on start, not on every call, right?

We use `clock_gettime()` to read the time. So, to get the time in `t` you have to make that check every time.

In C we use `CLOCK_MONOTONIC = 1`, not `CLOCK_MONOTONIC_RAW = 4`. Which is trange, since the man page says `CLOCK_MONOTONIC` is affected by ntp adjustments...

Check https://github.com/firehol/netdata/blob/master/src/clocks.c for the clocks we use in C.

Check also my last comment on #3752

**Comment by ktsaou** [comment]
About the check I think I don't understand how this works:

```python

AVAILABLE = bool(time())

from bases.monotonic import AVAILABLE, time
    if not AVAILABLE:
        from time import time
```

But I understand you use this to check if the `time()` is available. I guess only once is enough...

**Comment by l2isbad** [comment]
[original code](https://stackoverflow.com/a/1205762)

```python
import ctypes, os

CLOCK_MONOTONIC_RAW = 4 # see <linux/time.h>

class timespec(ctypes.Structure):
    _fields_ = [
        ('tv_sec', ctypes.c_long),
        ('tv_nsec', ctypes.c_long)
    ]

librt = ctypes.CDLL('librt.so.1', use_errno=True)
clock_gettime = librt.clock_gettime
clock_gettime.argtypes = [ctypes.c_int, ctypes.POINTER(timespec)]

def monotonic_time():
    t = timespec()
    if clock_gettime(CLOCK_MONOTONIC_RAW , ctypes.pointer(t)) != 0:
        errno_ = ctypes.get_errno()
        raise OSError(errno_, os.strerror(errno_))
    return t.tv_sec + t.tv_nsec * 1e-9
```

i am curious about
```python
    if clock_gettime(CLOCK_MONOTONIC_RAW , ctypes.pointer(t)) != 0:
        errno_ = ctypes.get_errno()
        raise OSError(errno_, os.strerror(errno_))
```

so `clock_gettime(CLOCK_MONOTONIC_RAW , ctypes.pointer(t))` sometimes can return not zero and this is error.

I mean under what conditions can it arise? should i check it on evey call to `monotonic_time()`  or it is enough to check once.

> In C we use CLOCK_MONOTONIC = 1, not CLOCK_MONOTONIC_RAW = 4

i see `use CLOCK_MONOTONIC_RAW==4 (since Linux 2.6.28; Linux-specific) to avoid NTP adjustments` and ` see <linux/time.h>`  in the comments

**Comment by ktsaou** [comment]
> I mean under what conditions can it arise? should i check it on evey call to monotonic_time() or it is enough to check once.

from `man clock_gettime`:

```
RETURN VALUE
       clock_gettime(), clock_settime(), and clock_getres() return 0 for success, or -1 for failure
       (in which case errno is set appropriately).

ERRORS
       EFAULT tp points outside the accessible address space.

       EINVAL The clk_id specified is not supported on this system.

       EPERM  clock_settime() does not have permission to set the clock indicated.
```

So, `EPERM` is not valid for this (we don't set the time). `EINVAL` is probably the only possible error. 
I see the see code does not log anything about clock_gettime() failing. I'll add some logs there to make sure we never get such errors.

**Comment by l2isbad** [comment]
> EINVAL is probably the only possible error.

nice, so looks like this PR safe to merge

**Comment by ktsaou** [comment]
ok. I suggest to use `CLOCK_MONOTONIC` to match what netdata already does.

I think I get why we have used `CLOCK_MONOTONIC` instead of `CLOCK_MONOTONIC_RAW`:

netdata gets the realtime clock at the beginning and then it increments it by the microseconds supplied. If we don't get ntp adjustments into account, then the charts will never get aligned with wall clock. All ntp adjustements will be missing from it, so after some time the charts will show the wrong time.

The only way for the charts to have the right time is to use `CLOCK_MONOTONIC`. This means that netdata time can get out of sync with wall clock, only if someone manually adjusts the clock.

So, my suggestion is to use `CLOCK_MONOTONIC`. If this is wrong, we have to change it everywhere.

**Comment by ktsaou** [comment]
@l2isbad have you tested this under both python v2 and v3?
Is it ok to merge?

**Comment by l2isbad** [comment]
These changes only affect `py2`. `py3` has `monotonic` in `time` package (I don't know which monotonic it uses, raw or not)

**Comment by ktsaou** [comment]
merged it

**Comment by ktsaou** [comment]
thank you!

**Comment by amichelic** [comment]
Commit 20bbce31336b860af48a918046b7defd31be5ee8 seems to break Python plugins on FreeBSD; at least on this system:
```$ uname -mrs 
FreeBSD 10.4-RELEASE-p10 amd64
$ python --version
Python 2.7.15
```

After updating to the latest git version, python plugins no longer returned data (neither when running from netdata, nor when running directly in debug mode) (this isn't 100% true - once in a while (several minutes) a record is returned). I narrowed the problem down to the mentioned commit, reverting it makes the plugins run fine again.

Researching a bit more revealed that FreeBSD is using different constants for CLOCK_MONOTONIC (from /usr/include/time.h): 
```#define CLOCK_VIRTUAL   1
//...
#define CLOCK_MONOTONIC 4
```

So the Python code is now using CLOCK_VIRTUAL, which is defined as "for time that increments only when the CPU is running in user mode on behalf of the calling process". The old value 4 was actually good on FreeBSD, because it referenced CLOCK_MONOTONIC.

**Comment by ktsaou** [comment]
oops! @l2isbad check this.

**Pull request merged**
