### PR TITLE
Replace LICENSE symlink with actual file.

### PR DESCRIPTION
**Pull request by Ferroin**
Should fix poorly coded GitHub license checks (which _should_ be following symlinks inside the repo).

### CODE REVIEW

**Comment by ktsaou** [comment]
hm... I think LICENSE.md will have to be the same with LICENSES/GPL-3 for it to work.
Also, does the above change require a Makefile change?

Check also this for the detection process: https://help.github.com/articles/licensing-a-repository/#detecting-a-license

**Comment by Ferroin** [comment]
Unless I'm mistaken, there shouldn't be a Makefile change needed.  From what I can tell from the Ruby code (I am by no means an expert on Ruby, but I know enough to get a general idea what it's doing), it checks the `LICENSE` file first if it exists, so this should be enough to get it to flag Netdata correctly.

**Comment by ktsaou** [comment]
let's see

**Comment by ktsaou** [comment]
hm... no change

**Comment by Ferroin** [comment]
Yeah, I'll pull down a copy of the Ruby code they're using and experiment a bit with it to see if I can figure out what's up here.

**Comment by Ferroin** [comment]
OK, this is weird.  Licensee correctly ID's the LICENSE file as the main license and a perfect match for the GPL-3.

**Comment by ktsaou** [comment]
hm... it may be some caching on github. Let's give it a day... (although when I initialized it, I remember it was updated in real-time).

**Comment by ktsaou** [comment]
still no luck.
Something else is happening. Any ideas?

**Comment by Ferroin** [comment]
I'm not quite sure.  My only thought at this point is that they're ignoring `LICENSE` and just looking at `LICENSE.md`, which the ruby module correctly identifies as something it doesn't recognize.

**Comment by ktsaou** [comment]
Check this:

```sh
# curl -H "Accept: application/vnd.github.black-panther-preview+json" "https://api.github.com/repos/firehol/netdata/community/profile"
{
  "health_percentage": 50,
  "description": "Get control of your servers. Simple. Effective. Awesome! https://my-netdata.io/",
  "documentation": null,
  "files": {
    "code_of_conduct": null,
    "contributing": null,
    "issue_template": null,
    "pull_request_template": null,
    "license": {
      "key": "other",
      "name": "Other",
      "spdx_id": null,
      "url": null,
      "node_id": "MDc6TGljZW5zZTA=",
      "html_url": "https://github.com/firehol/netdata/blob/master/LICENSE"
    },
    "readme": {
      "url": "https://api.github.com/repos/firehol/netdata/contents/README.md",
      "html_url": "https://github.com/firehol/netdata/blob/master/README.md"
    }
  },
  "updated_at": "2018-05-10T15:23:33Z"
}
```

It says `spdx_id: null`...

hm... shall I contact github support?

**Comment by Ferroin** [comment]
I've never looked at the GitHub API's before, but based on the structure of the returned data, I'd expect the `spdx_id` key is set based on the detected licensing, just like the `name` should be.

That said, I would absolutely contact GitHub support, as they're pointing at a file that an up-to-date version of licensee is correctly identifying as GPL-3.0 on my system.

**Comment by ktsaou** [comment]
Sent them an email. Let's see...

**Comment by ktsaou** [comment]
This is what they replied:

>Thanks for getting in touch! I see that you currently have 3 files that begin with LICENSE in the root of the repository:
>
>https://github.com/firehol/netdata/blob/master/LICENSE (GPL v3 License)
>https://github.com/firehol/netdata/blob/master/LICENSE-REDISTRIBUTED.md
>https://github.com/firehol/netdata/blob/master/LICENSE.md
>
>Because your repository contains several licenses, we recommend keeping one of the files (the GPL v3 >License) and renaming the other two so that your license can be detected by our systems. Would such >an approach work for you?
>
>https://help.github.com/articles/licensing-a-repository/#detecting-a-license
>
>All the best,

The problem with `LICENSE-REDISTRIBUTED.md` is that it is linked a lot...

**Comment by Ferroin** [comment]
Linked a lot where exactly?  If it's all internal to the repository, then a change can easily be scripted.

Realistically, it might make sense to just combine `LICENSE.md` and `LICENSE-REDISTRIBUTED.md` into one file with a different name.  Perhaps `REDISTRIBUTING.md`?

**Comment by ktsaou** [comment]
> Linked a lot where exactly?

I mean wiki pages, and github issues.

> Realistically, it might make sense to just combine LICENSE.md and LICENSE-REDISTRIBUTED.md into one file with a different name. Perhaps REDISTRIBUTING.md?

Sounds good...

**Comment by Ferroin** [comment]
OK, I'll look at getting a PR together to do so, and once that gets merged I'll try and get all the links in the Wiki pages updated (can't really do much about the GitHub issues though I suppose).

**Comment by Ferroin** [comment]
Alternatively, would you be OK with just merging`LICENSE.md` and `LICENSE-REDISTRIBUTED.md` into the licensing info section at the end of `README.md`?  That would preserve the information somewhere where at least part of it already is.

**Comment by ktsaou** [comment]
> Alternatively, would you be OK with just mergingLICENSE.md and LICENSE-REDISTRIBUTED.md into the licensing info section at the end of README.md? That would preserve the information somewhere where at least part of it already is.

hm... README.md will become a monster with not so useful info. I don't like this. README.md is a "marketing tool"... :smile: ...so I would avoid having there irrelevant info.

I suggest to merge `LICENSE` with `LICENSE.md` and rename `LICENSE-REDISTRIBUTED.md` to `REDISTRIBUTED.md`.

> Oh, also, I assume you would like the Copyright notices updated to reflect the new company?

Yes, it would be fantastic if you also do this!

I also think we should add CNCF logo and info at the home page, README.md, etc, but I can do this later.

**Pull request merged**
