### PR TITLE
elasticsearch plugin

### PR DESCRIPTION
**Pull request by l2isbad**
This one is heavy. (update_interval every 5 sec by default)

**It uses 3 different api calls to get data.**

1. Node Stats API
2. Cluster Stats API
3. Cluster Health API

All of them enabled by default. Any of them can be disabled in conf file.
All requests executed simultaneously.

23 charts
I am not a ES expert (not even close). But I tried to follow [datadog](https://www.datadoghq.com/blog/monitor-elasticsearch-performance-metrics/) way choosing which metrics should be collected.
Must be tested.

### CODE REVIEW

**Comment by l2isbad** [comment]
@FarhadF can you test it?
@jurgenhaas are you using ES?

**Comment by FarhadF** [comment]
@l2isbad Yea sure. I just created 2 files:
sudo vim /opt/netdata/usr/libexec/netdata/python.d/elasticsearch.chart.py
sudo vim /opt/netdata/etc/netdata/python.d/elasticsearch.conf

and copied the respective contents from your pull request. but I dont see additional charts.
Am I doing it wrong? If so please give me deployment directions.

**Comment by l2isbad** [comment]
@FarhadF 
```
ls -l elasticsearch.conf 
-rw-r----- 1 **netdata netdata** 2711 янв 19 15:59 elasticsearch.conf
```

`[/opt/netdata/var/log/netdata]cp /dev/null error.log`

`systemctl restart netdata.service`

```
[/opt/netdata/var/log/netdata]grep elastic error.log
2017-01-19 16:31:48: python.d INFO: elasticsearch_local {'http://10.4.0.185:9200/_cluster/stats': True, 'http://10.4.0.185:9200/_nodes/_local/stats': True, 'http://10.4.0.185:9200/_cluster/health': True}
2017-01-19 16:31:48: python.d INFO: elasticsearch_local Plugin was started successfully
2017-01-19 16:31:48: python.d INFO: CHECKED OK: elasticsearch_local


```

**Comment by jurgenhaas** [comment]
Amazing, this is working too! Great job @l2isbad

**Comment by FarhadF** [comment]
@l2isbad  sry for late reply, Working  great.

**Comment by ktsaou** [comment]
@l2isbad you rock!

Can anyone post a few screenshots?

**Comment by jurgenhaas** [comment]
Here you go ...

2017-01-19 13 49 28 screen
2017-01-19 13 49 54 screen
2017-01-19 13 50 20 screen

**Comment by ktsaou** [comment]
@l2isbad let me know when you want this merged.

**Comment by l2isbad** [comment]
ready @ktsaou

**Comment by ktsaou** [comment]
perfect. remember the wiki...

**Pull request merged**
