### PR TITLE
shorten too long submenus in the middle of the string

### PR DESCRIPTION
**Pull request by ktsaou**

### CODE REVIEW

**Comment by ktsaou** [comment]
@agross one final touch for your disks...
The right way would be to move them under the container, but anyway this will fix the issue that all your mount points appear the same in the menu.

**Comment by agross** [comment]
@ktsaou My disks want me to say "thank you" :)

**Comment by ktsaou** [comment]
I saw it. I could make it a few chars shorter to avoid the horizontal scroll bar, but I will deal with it when I will change the scrollbar with something nicer.

btw, you can monitor your mariadbs with netdata. It would be a little tricky since they run in a container. I also need to find a way for netdata to have some of its plugins in different containers... until then, if you expose your dbs to the host, netdata can monitor them. Only the `CONNECT` access right is needed by netdata, so this would not be a security threat for you...

**Comment by ktsaou** [comment]
and you use FireQoS too! nice!

**Comment by agross** [comment]
> btw, you can monitor your mariadbs with netdata. It would be a little tricky since they run in a container.

Seems to be. I haven't used MariaDB in development myself. As it seems I not only need the port but the socket as well?

```py
>>> MySQLdb.connect(user='root', passwd='secret', host='localhost', port=33306) # port published by docker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (2002, 'Can\'t connect to local MySQL server through socket \'/var/lib/mysql/mysql.sock\' (2 "No such file or directory")')
```

**Comment by ktsaou** [comment]
No either tcp or unix socket is ok.
Edit `/etc/netdata/python.d/mysql.conf` to see the alternatives. There are many examples there.

**Comment by agross** [comment]
Yes, I saw these and added mine:

```
etherpad:
  name     : etherpad
  user     : root
  pass     : 'secret'
  host     : localhost
  port     : 33306
```

netdata says it cannot connect, hence I dug into the Python source and tried to connect manually with the same parameters that I thought netdata will use.

**Comment by agross** [comment]
OK, think I found it. If you specify `localhost` connections automatically go through the socket. http://serverfault.com/a/337844/247219

**Comment by ktsaou** [comment]
nice finding!

**Comment by agross** [comment]
Perhaps the default targets would have to change as well?

```
tcp:
  name     : 'local'
  # user     : ''
  # pass     : ''
  host     : 'localhost'
  port     : '3306'
```

Would use the socket regardless of port config. What do you think?

**Comment by ktsaou** [comment]
I didn't get it. By default is check all possible combinations: https://github.com/firehol/netdata/blob/master/conf.d/python.d/mysql.conf

Your owncloud db needs indexes:

**read rnd next**, the number of requests to read the next row in the data file. This value is high if you are doing a lot of table scans. Generally this suggests that your tables are not properly indexed or that your queries are not written to take advantage of the indexes you have.

**Comment by ktsaou** [comment]
here: https://router.netdata.home.therightstuff.de/#mysql_owncloud_handlers

**Comment by agross** [comment]
> By default is check all possible combinations

Yes, but the default combination like the one stated above (https://github.com/firehol/netdata/pull/883#issuecomment-244555837) would just ignore the port because the host is `localhost`. Here the same aliasing would take place that hit me:

```
if host == 'localhost'
  use socket regardless of tcp port specified
else
  use tcp connection to configured port
```

**Comment by ktsaou** [comment]
oh, I see. You mean to state this in the config file. Ok. I am making a PR.

**Comment by agross** [comment]
Yes, or

* change the default host to `127.0.0.1`, or
* tell the python client to use TCP protocol as soon as a port is defined in netdata config.

I think the latter would be the best solution w.r.t. to clean netdata config files.

**Comment by agross** [comment]
> Your owncloud db needs indexes

Sheesh... I just want to use ownCloud, not manage their DB indexes! ;-) Need to investigate whether indexes are just missing or oC doesn't install any.

**Comment by ktsaou** [comment]
I see the server is not getting many queries but the read random next metric is high. Probably, it is not a problem (and it is not that high).

> Yes, or
> 
> change the default host to 127.0.0.1, or
> tell the python client to use TCP protocol as soon as a port is defined in netdata config.
> I think the latter would be the best solution w.r.t. to clean netdata config files.

We need @paulfantom for this. Check this comment: https://github.com/firehol/netdata/pull/883#issuecomment-244556239, in short: mysqldb is ignoring port if host is `localhost` and attempts to use the unix socket. Is there an option to force it use tcp when port is given? Alternatively, we will merge PR #885.

**Comment by ktsaou** [comment]
I just checked read random next on a completely idle mysql, and it is around 300. Yours is 500. So this might be something mysql is doing internally.

**Comment by agross** [comment]
I also wondered why it is that high. MySQL for etherpad should also be idle, but is at 500 as well. So I'll think I'll just ignore it for now as the apps also appear to run fine. Thanks for checking!

**Comment by agross** [comment]
>Is there an option to force it use tcp when port is given? 

To quote from the recommended [mysql python client docs](https://mysqlclient.readthedocs.io/en/latest/user_guide.html#functions-and-attributes):

> unix_socket
> location of UNIX socket. Default: use default location **or TCP for remote hosts**.

**Pull request merged**
