### PR TITLE
fail2ban_plugin: parse both conf_path and conf_dir/; regex update

### PR DESCRIPTION
**Pull request by l2isbad**
https://github.com/firehol/netdata/issues/1837

### CODE REVIEW

**Comment by nublaii** [comment]
Humm... nope, still happening, any way I can start this up that could give you more info?

**Comment by ktsaou** [comment]
merge?

**Comment by l2isbad** [comment]
yes

**Comment by l2isbad** [comment]
wait. no 😄

**Comment by l2isbad** [comment]
ready @ktsaou

**Comment by ktsaou** [comment]
merged. thanks!

**Pull request merged**
