### PR TITLE
optimizations

### LINKED ISSUE #393: [plugin:/proc/diskstats] Find sector size for partitions.
Sector size for partitions is not found right at the moment.
There is no folder `queue` in the `sysfs` directories of partitions. We need to use the sector size of the matching disk.

I will tell here when starting working on it. If someone else start's implementing it please post here.

### PR DESCRIPTION
**Pull request by ktsaou**
I did several optimizations to speed up netdata:

- web statistics now use a single lock per web request.
- diskstats cache all the config options for the disks, so that on each data collection iteration there is no configuration options check
- eliminated a malloc()/free() per web request by refactoring the url_decode() function

a few optimizations to lower the memory requirements of netdata:

- registry now uses dictionaries without statistics info (saved 32 bytes per person and machine)

added a new performance chart for netdata:

- Average API response time in ms is now reported in netdata charts

Optimized a bit the code that parses the web request:

- a few array references were converted to pointer operations

Configuration changes

- `on demand` renamed to `auto`. `on demand` still works when parsing the configuration file, but the generated one will have the values as `auto`.

Code cleanup:

- diskstats cleanup a bit the code, renamed the variables, etc.

Bugs fixed:

- netdata was not able to find the hw sector size for partitions. Now it is. This fixes #393

### CODE REVIEW

**Comment by ktsaou** [comment]
@simonnagl I made the cleanup.

The problem is that there are mount points that report different major/minor. Check this for example:

```sh
# cat /proc/self/mountinfo | grep " / / "
20 0 0:17 / / rw,relatime - btrfs /dev/sdd3 rw,compress=lzo,ssd,discard,space_cache,autodefrag
```

Check now what `/proc/diskstats` reports:

```sh
 # cat /proc/diskstats | grep sdd3
   8      51 sdd3 5998226 3434511 1558097540 58687559 14872113 2357297 1075834472 34324007 0 6450778 92990864
```

`0:17` in mountinfo, `8:51` in diskstats !
wtf?

**Comment by ktsaou** [comment]
> 0:17 in mountinfo, 8:51 in diskstats

I guess this happens because of btrfs, which is like lvm. However, this means we need somehow to report disk space usage for disks that are not in `/proc/diskstats`.

Any ideas?

**Comment by ktsaou** [comment]
I read what `df` (coreutils) does:

Check this:

```sh
df -ah
```

Is the same with `/proc/self/mountinfo`.

I guess when you say `df -h` it just eliminates all mount points `statvfs()` returns zero.

Would you like to do it, or you want me to do it?

**Comment by ktsaou** [comment]
I think the only good solution is to split diskstats in 2 modules:

1. `/proc/diskstats`
2. `/proc/self/mountinfo`

The first will only report performance, the second will only report space usage.
For the dashboard there will be no difference, but internally they will have to be separate. This also means that `/proc/self/mountinfo` will be read every second.

I don't know. I'll think about it...

**Comment by ktsaou** [comment]
This passes all tests so far.
What remains is to find a way to show mount points that do not correspond to disks.

I am merging it.

**Comment by simonnagl** [comment]
> 0:17 in mountinfo, 8:51 in diskstats !

This sounds very strange. If you give me some time I will setup a machine with `btrfs` next weekend and try to find out what's going on exactly.

> This also means that /proc/self/mountinfo will be read every second.

I do not think so. We can use the polling of /proc/mounts here too.

If you want I can take a look at this. Is there a entry with 0:17 at diskstats?

Also for space usage of brtfs systems pleas read this:
https://wiki.archlinux.org/index.php/Btrfs#Displaying_used.2Ffree_space

Today I have no time to look at it in more detail.

**Comment by ktsaou** [comment]
ok. I am not doing anything related to it yet.

```sh
 $ cat /proc/self/mountinfo
16 20 0:4 / /proc rw,nosuid,nodev,noexec,relatime - proc proc rw
17 20 0:6 / /dev rw,nosuid,relatime - devtmpfs udev rw,size=10240k,nr_inodes=1000354,mode=755
18 17 0:13 / /dev/pts rw,relatime - devpts devpts rw,gid=5,mode=620,ptmxmode=000
19 20 0:16 / /sys rw,nosuid,nodev,noexec,relatime - sysfs sysfs rw
20 0 0:17 / / rw,relatime - btrfs /dev/sdd3 rw,compress=lzo,ssd,discard,space_cache,autodefrag
21 20 0:19 / /run rw,nodev,relatime - tmpfs tmpfs rw,size=807380k,mode=755
22 19 0:20 / /sys/kernel/security rw,nosuid,nodev,noexec,relatime - securityfs securityfs rw
23 19 0:7 / /sys/kernel/debug rw,nosuid,nodev,noexec,relatime - debugfs debugfs rw
24 19 0:21 / /sys/kernel/config rw,nosuid,nodev,noexec,relatime - configfs configfs rw
25 19 0:22 / /sys/fs/fuse/connections rw,nosuid,nodev,noexec,relatime - fusectl fusectl rw
26 19 0:23 / /sys/fs/cgroup rw,nosuid,nodev,noexec,relatime - tmpfs cgroup_root rw,size=10240k,mode=755
27 26 0:24 / /sys/fs/cgroup/openrc rw,nosuid,nodev,noexec,relatime - cgroup openrc rw,release_agent=/lib64/rc/sh/cgroup-release-agent.sh,name=openrc
28 26 0:25 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime - cgroup cpuset rw,cpuset
29 26 0:26 / /sys/fs/cgroup/cpu rw,nosuid,nodev,noexec,relatime - cgroup cpu rw,cpu
30 26 0:27 / /sys/fs/cgroup/cpuacct rw,nosuid,nodev,noexec,relatime - cgroup cpuacct rw,cpuacct
31 26 0:28 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime - cgroup blkio rw,blkio
32 26 0:29 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime - cgroup memory rw,memory
33 26 0:30 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime - cgroup devices rw,devices
34 26 0:31 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime - cgroup freezer rw,freezer
35 26 0:32 / /sys/fs/cgroup/net_cls rw,nosuid,nodev,noexec,relatime - cgroup net_cls rw,net_cls
36 26 0:33 / /sys/fs/cgroup/net_prio rw,nosuid,nodev,noexec,relatime - cgroup net_prio rw,net_prio
37 17 0:15 / /dev/mqueue rw,nosuid,nodev,noexec,relatime - mqueue mqueue rw
38 17 0:34 / /dev/shm rw,relatime - tmpfs shm rw,size=16777216k,nr_inodes=2097152
40 20 8:49 / /boot rw,noatime - ext2 /dev/sdd1 rw,data=ordered
41 20 9:127 / /data rw,relatime - ext4 /dev/md127 rw,stripe=256
42 20 0:36 / /tmp rw,relatime - tmpfs tmpfs rw,size=25165824k,nr_inodes=2097152
43 20 9:125 / /mnt/mdroot rw,relatime - ext4 /dev/md125 rw
44 20 0:38 / /backup rw,noatime - btrfs /dev/sde1 rw,compress=zlib,space_cache,autodefrag,commit=240
45 16 0:41 / /proc/sys/fs/binfmt_misc rw,nosuid,nodev,noexec,relatime - binfmt_misc binfmt_misc rw
46 20 0:42 / /var/lib/nfs/rpc_pipefs rw,relatime - rpc_pipefs rpc_pipefs rw
47 16 0:43 / /proc/fs/nfsd rw,nosuid,nodev,noexec,relatime - nfsd nfsd rw
48 20 0:34 /var/tmp /var/tmp rw,relatime - tmpfs shm rw,size=16777216k,nr_inodes=2097152
49 41 0:44 / /data/home/costa/.gvfs rw,nosuid,nodev,relatime - fuse.gvfsd-fuse gvfsd-fuse rw,user_id=1000,group_id=1000
```

```sh
 $ cat /proc/diskstats
   8      16 sdb 52279 28906 18314253 1161943 23811 153539 1402307 1060236 0 770401 2222157
   8      17 sdb1 34 0 970 66 3 0 12 47 0 113 113
   8      18 sdb2 133 0 1403 118 5 0 7 232 0 344 350
   8      19 sdb3 52101 28906 18310848 1161736 23801 153539 1402288 1059942 0 770046 2221597
   8      48 sdd 87132 9085 5458698 64461 565622 78288 38906840 1389957 0 238437 1453947
   8      49 sdd1 211 0 3536 60 139 0 1035264 46 0 74 106
   8      50 sdd2 110 0 2438 17 0 0 0 0 0 12 17
   8      51 sdd3 86763 9085 5451452 64367 540030 78288 37871576 1295532 0 146163 1359410
   8      32 sdc 53766 31399 18381759 1671413 24296 152822 1400555 2653302 0 975297 4326655
   8      33 sdc1 418 0 6246 1331 3 0 12 32 0 411 1362
   8      34 sdc2 304 0 5853 466 5 0 7 93 0 444 558
   8      35 sdc3 53033 31399 18368628 1669575 24286 152822 1400536 2653144 0 974709 4324661
   8       0 sda 51723 31109 18365253 924931 25112 157376 1443507 1116669 0 780689 2041634
   8       1 sda1 84 0 1122 232 3 0 12 55 0 286 287
   8       2 sda2 110 0 1023 80 5 0 7 214 0 291 293
   8       3 sda3 51518 31109 18362076 924598 25102 157376 1443488 1116379 0 780346 2041012
   9     127 md127 144910 0 54214786 0 45037 0 2430344 0 0 0 0
   9     126 md126 357 0 6000 0 0 0 0 0 0 0 0
   9     125 md125 398 0 6066 0 1 0 8 0 0 0 0
   8      64 sde 1490 25 49344 12346 2056 114 108456 260511 0 17698 272853
   8      65 sde1 1445 25 48552 12308 2049 114 108456 254837 0 11991 267141
 252       0 zram0 147 0 1176 0 3 0 24 0 0 0 0
 252       1 zram1 147 0 1176 0 3 0 24 0 0 0 0
 252       2 zram2 147 0 1176 1 2 0 16 0 0 1 1
 252       3 zram3 147 0 1176 1 2 0 16 0 0 1 1
```

**Comment by ktsaou** [comment]
diskstats does not have any entry with major 0.
They must be something like `proc`, `dev`, etc.

But there are a few cases we need to report space:

1. tmpfs
2. btrfs

possibly others too.

This is what `df -h` reports on this system:

```sh
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             10M  4,0K   10M   1% /dev
/dev/sdd3       222G  134G   83G  62% /
tmpfs           789M  1,2M  788M   1% /run
cgroup_root      10M     0   10M   0% /sys/fs/cgroup
shm              16G   12K   16G   1% /dev/shm
/dev/sdd1       976M  471M  455M  51% /boot
/dev/md127      3,5T  3,3T   43G  99% /data
tmpfs            24G  260K   24G   1% /tmp
/dev/md125       50G   49G     0 100% /mnt/mdroot
/dev/sde1       1,9T  577G  1,3T  31% /backup
```

and this is everything it sees:

```sh
$ df -ah
Filesystem      Size  Used Avail Use% Mounted on
proc               0     0     0    - /proc
udev             10M  4,0K   10M   1% /dev
devpts             0     0     0    - /dev/pts
sysfs              0     0     0    - /sys
/dev/sdd3       222G  134G   83G  62% /
tmpfs           789M  1,2M  788M   1% /run
securityfs         0     0     0    - /sys/kernel/security
debugfs            0     0     0    - /sys/kernel/debug
configfs           0     0     0    - /sys/kernel/config
fusectl            0     0     0    - /sys/fs/fuse/connections
cgroup_root      10M     0   10M   0% /sys/fs/cgroup
openrc             0     0     0    - /sys/fs/cgroup/openrc
cpuset             0     0     0    - /sys/fs/cgroup/cpuset
cpu                0     0     0    - /sys/fs/cgroup/cpu
cpuacct            0     0     0    - /sys/fs/cgroup/cpuacct
blkio              0     0     0    - /sys/fs/cgroup/blkio
memory             0     0     0    - /sys/fs/cgroup/memory
devices            0     0     0    - /sys/fs/cgroup/devices
freezer            0     0     0    - /sys/fs/cgroup/freezer
net_cls            0     0     0    - /sys/fs/cgroup/net_cls
net_prio           0     0     0    - /sys/fs/cgroup/net_prio
mqueue             0     0     0    - /dev/mqueue
shm              16G   12K   16G   1% /dev/shm
/dev/sdd1       976M  471M  455M  51% /boot
/dev/md127      3,5T  3,3T   43G  99% /data
tmpfs            24G  260K   24G   1% /tmp
/dev/md125       50G   49G     0 100% /mnt/mdroot
/dev/sde1       1,9T  577G  1,3T  31% /backup
binfmt_misc        0     0     0    - /proc/sys/fs/binfmt_misc
rpc_pipefs         0     0     0    - /var/lib/nfs/rpc_pipefs
nfsd               0     0     0    - /proc/fs/nfsd
shm              16G   12K   16G   1% /var/tmp
gvfsd-fuse         0     0     0    - /data/home/costa/.gvfs
```

**Comment by simonnagl** [comment]
I see. No matter how we handle `btrfs` we need to split `proc_diskstats` into two modules because of space metrics for `tmpfs`.
I am willing to do that. Also maybe this will automatically the `btrfs` issue.

Before doing that I would like to do two other things:

- Merge the global polling #430 
- Finish the discussion I startet just now. It is over how we name disks. #435

What do you think?

**Comment by ktsaou** [comment]
ok.

**Comment by ktsaou** [comment]
I am have made my comments for both. You play now...

I have re-arranged the code in proc_diskstats.c. I hope you find the new arrangement a lot more clean...

**Comment by simonnagl** [comment]
Yes. Great work. I will notify you when I have done the changes in feature polling.

**Pull request merged**
