### PR TITLE
Haproxy module optimization

### PR DESCRIPTION
**Pull request by l2isbad**
Some optimization (https://github.com/firehol/netdata/issues/1551)

@hameno can you test it?

[new plugin](https://github.com/l2isbad/netdata/blob/haproxy_module_optimization/python.d/haproxy.chart.py)

[new alarm](github.com/l2isbad/netdata/blob/haproxy_module_optimization/conf.d/health.d/haproxy.conf)

### CODE REVIEW

**Comment by hameno** [comment]
Sure, simply downloading the linked files to my installation should work, right?

**Comment by l2isbad** [comment]
Just replace them and don't forget about permissions. alarm must be `netdata:netdata`

**Comment by hameno** [comment]
Ok, tested it for both cases (MAINT and all servers down), works!

**Comment by l2isbad** [comment]
Actually i can add an option to format dimension names.
You need to provide a `lambda` function as an option in config file

Example

`function : lambda name: name if len(name) <= 9 else name[len(name) - 9:len(name)]`

Logic: `if len(backend name) <= 9 then dim = backend_name else dim = last 9 symbols of backen name`

```
In [16]: func = lambda name: name if len(name) <= 9 else name[len(name) - 9:len(name)]

In [18]: func('hello')
Out[18]: 'hello'

In [19]: func('super-long-name')
Out[19]: 'long-name'
```

You can provide your own logic.

**Comment by ktsaou** [comment]
thanks!

**Pull request merged**
