### PR TITLE
disks with major 253 do not have partitions #258

### PR DESCRIPTION
**Pull request by ktsaou**
#258

### CODE REVIEW

**Comment by glensc** [comment]
hardcoding them is wrong! the major node is allocated dynamically starting from 254 counting downwards. here's example when device mapper is loaded before mdp:

```
# sed -ne '/Block devices/,$p' /proc/devices |grep -E '253|254'
253 mdp
254 device-mapper
```

here's example when virtblk is loaded before device-mapper:

```
# sed -ne '/Block devices/,$p' /proc/devices |grep -E '253|254'
253 device-mapper
254 virtblk
```

**Comment by glensc** [comment]
here's some documentation i was able to quickly find:
- http://www.makelinux.net/ldd3/chp-3-sect-2#chp-3-sect-2.3
- http://www.tldp.org/LDP/tlk/dd/drivers.html
- https://www.kernel.org/doc/Documentation/devices.txt

so from `Documentation/devices.txt`:
> 240-254			Reserved for local use

but probably doesn't matter as all of them are registered in `/proc/devices`

**Comment by ktsaou** [comment]
The whole idea is to exclude partitions from the charts. As I see it, these devices can probably have partitions too. Any idea how to find if a block device is actually a partition?

**Comment by glensc** [comment]
without getting into deeper what you ask, perhaps [lsblk](http://man7.org/linux/man-pages/man8/lsblk.8.html) or [blkid](http://linux.die.net/man/8/blkid) tools help?

**Comment by glensc** [comment]
this perhaps?

```
# lsblk -d
NAME MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda    8:0    0 465.8G  0 disk 
sdb    8:16   0 465.8G  0 disk 
sdc    8:32   0  59.6G  0 disk 
sr0   11:0    1  1024M  0 rom  
```

or even:
```
[root@blodnatt /]# lsblk -d --json
{
   "blockdevices": [
      {"name": "sda", "maj:min": "8:0", "rm": "0", "size": "465.8G", "ro": "0", "type": "disk", "mountpoint": null},
      {"name": "sdb", "maj:min": "8:16", "rm": "0", "size": "465.8G", "ro": "0", "type": "disk", "mountpoint": null},
      {"name": "sdc", "maj:min": "8:32", "rm": "0", "size": "59.6G", "ro": "0", "type": "disk", "mountpoint": null},
      {"name": "sr0", "maj:min": "11:0", "rm": "1", "size": "1024M", "ro": "0", "type": "rom", "mountpoint": null}
   ]
}
```

**Comment by ktsaou** [comment]
```
strace lsblk -d 2>&1 | egrep "/(sys|proc)/"
```

It seems that if a directory with the disk name exists in `/sys/block/`, then it is a disk, otherwise a partition.

So:

- `/sys/block/sda` exists, it is a disk
- `/sys/block/sda1` does not exist, it is a partition

**Comment by glensc** [comment]
inventing logic of scanning `/sys` again and handling differences with kernels (there's no stable "api" for `/sys` structure) has no sustainability

your code would pull in device mapper targets, which you called "partitions" that you want to omit:

```
➔ LC_ALL=C ls -l /sys/block/
total 0
lrwxrwxrwx 1 root root 0 Apr 18 13:01 dm-0 -> ../devices/virtual/block/dm-0/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 dm-1 -> ../devices/virtual/block/dm-1/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 dm-10 -> ../devices/virtual/block/dm-10/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 dm-11 -> ../devices/virtual/block/dm-11/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 dm-2 -> ../devices/virtual/block/dm-2/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 dm-3 -> ../devices/virtual/block/dm-3/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 dm-4 -> ../devices/virtual/block/dm-4/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 dm-5 -> ../devices/virtual/block/dm-5/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 dm-6 -> ../devices/virtual/block/dm-6/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 dm-7 -> ../devices/virtual/block/dm-7/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 dm-8 -> ../devices/virtual/block/dm-8/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 dm-9 -> ../devices/virtual/block/dm-9/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 md0 -> ../devices/virtual/block/md0/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 md2 -> ../devices/virtual/block/md2/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 ram0 -> ../devices/virtual/block/ram0/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 ram1 -> ../devices/virtual/block/ram1/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 ram10 -> ../devices/virtual/block/ram10/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 ram11 -> ../devices/virtual/block/ram11/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 ram12 -> ../devices/virtual/block/ram12/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 ram13 -> ../devices/virtual/block/ram13/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 ram14 -> ../devices/virtual/block/ram14/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 ram15 -> ../devices/virtual/block/ram15/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 ram2 -> ../devices/virtual/block/ram2/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 ram3 -> ../devices/virtual/block/ram3/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 ram4 -> ../devices/virtual/block/ram4/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 ram5 -> ../devices/virtual/block/ram5/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 ram6 -> ../devices/virtual/block/ram6/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 ram7 -> ../devices/virtual/block/ram7/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 ram8 -> ../devices/virtual/block/ram8/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 ram9 -> ../devices/virtual/block/ram9/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 sda -> ../devices/pci0000:00/0000:00:1f.2/ata3/host2/target2:0:0/2:0:0:0/block/sda/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 sdb -> ../devices/pci0000:00/0000:00:1f.2/ata4/host3/target3:0:0/3:0:0:0/block/sdb/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 sdc -> ../devices/pci0000:00/0000:00:1f.2/ata6/host5/target5:0:0/5:0:0:0/block/sdc/
lrwxrwxrwx 1 root root 0 Apr 18 13:01 sr0 -> ../devices/pci0000:00/0000:00:1f.2/ata5/host4/target4:0:0/4:0:0:0/block/sr0/
```

**Comment by ktsaou** [comment]
I think all them should be reported. I don't want to report partitions because the disk charts would report the same values. So reporting partitions too will just waste resources.

Check this:

```sh
$ cat /sys/block/sda/sda1/partition
```

If we can't rely in `/sys` and `/proc` info, I don't really understand what we can rely on.

Do you suggest to run `lsblk` to collect this info?
Generally we should avoid running external commands. Running external commands forks netdata, which is an expensive operation that should be eliminated and also adds a dependency to some other tool that all systems should have installed. I prefer `/proc` and `/sys`.

**Comment by glensc** [comment]
so if all my device mapper targets based on dev sdb, they will report same values similarily sdb would report sdb1 you mentioned.

**Comment by glensc** [comment]
and yes, i suggest using `lsblk` not to invent `/sys` and `/proc` scanning yourself (and getting it wrong). i suggest at least look at `lsblk` sourcecode how they handle it now if you need to avoid forking.

btw, you can call the `lsblk` only once and only scan devices `lsblk` returned. or at least call lsblk not so frequently as stats collecting (maybe once per 5 minutes?)

**Comment by ktsaou** [comment]
Sorry. I have to disagree. Calling external commands is the worst thing a real-time monitoring solution could do. Of course calling it just once or every 5 mins is a solution, but I don't like it. 

Keep in mind I have looked at the code of many system commands to build all system monitoring functions, especially the disk ones - the code I have in netdata - the one you called **hardcoded** is taken for a system tool - I think vmstat.

The latest source of `lsblk` is here:
https://kernel.googlesource.com/pub/scm/utils/util-linux/util-linux/+/master/misc-utils/lsblk.c

I'll have a look at it later (although stracing it is very close to it).

**Pull request merged**
