### PR TITLE
python `sensors` module

### PR DESCRIPTION
**Pull request by paulfantom**
Created possibility to change default `/sys/devices` path for `cpufreq.chart.py`.

Implemented `sensors.chart.py` which is using modified version of not merged PR from [PySensors](https://bitbucket.org/blackjack/pysensors/pull-requests/1/add-python-3-support-and-fix-flake8-lint/diff). Since this library isn't available anywhere I bundled it to `lm_sensors.py`

Also this implementation needs `libsensors.so` and isn't the speed daemon (sometimes it is even slower than `mysql.chart.py`). But it works and for me, personally, this module allowed to disable `chart.d.plugin`.

Sometime later I will try to find better way to scrap sensors data.

### CODE REVIEW

**Comment by paulfantom** [comment]
I couldn't find good sensors library which would be compatible with both python versions and wouldn't need compilation.

**Comment by paulfantom** [comment]
I just checked that it is still faster than bash counterpart.

**Comment by ktsaou** [comment]
nice!

Please also do the following:

1. Add the author of lm_sensors.py to LICENSE.md
2. A few people ask to select only specific chips (e.g. `coretemp-*`) or specific sensor types (e.g. `fans` and `temperature`). Can we have something like that?

**Comment by paulfantom** [comment]
I will investigate it first thing tomorrow.

**Comment by paulfantom** [comment]
Added options to select specific chips and sensor types (look at `sensors.conf`) and entry in `LICENSE.md`.

Should be ready to merge.

**Comment by paulfantom** [comment]
@ktsaou I am rewriting `ap.chart.sh`, but I need to do some research since running `iw` and parsing its output isn't the best thing to do according to `iw` itself:
> Do NOT screenscrape this tool, we don't consider its output stable.

Since I don't have any AP could you check if `/proc/net/wireless` gives the same data as needed for `ap.chart.py`. Or maybe I need to grab data from other files in `/proc/net`.

Since I don't want to cause you more trouble, could you give or point me to data sets needed for `nut.chart` and `opensips.chart`?

I also plan to implement `redis.chart.py` but I need to know which data you would like to present on graphs (data gathered by `INFO` command in redis).

**Comment by ktsaou** [comment]
```sh
# iw wlan0 station dump
Station 8c:7b:9d:f5:f0:ea (on wlan0)
        inactive time:  432380 ms
        rx bytes:       802019
        rx packets:     7993
        tx bytes:       245286
        tx packets:     1195
        tx retries:     54
        tx failed:      0
        signal:         -37 dBm
        signal avg:     -37 dBm
        tx bitrate:     1.0 MBit/s
        rx bitrate:     39.0 MBit/s MCS 4
        expected throughput:    32.42Mbps
        authorized:     yes
        authenticated:  yes
        preamble:       short
        WMM/WME:        yes
        MFP:            no
        TDLS peer:      no
Station 00:90:4c:0d:f4:0b (on wlan0)
        inactive time:  2810 ms
        rx bytes:       18194
        rx packets:     155
        tx bytes:       26738
        tx packets:     90
        tx retries:     10
        tx failed:      0
        signal:         -41 dBm
        signal avg:     -39 dBm
        tx bitrate:     58.5 MBit/s MCS 6
        rx bitrate:     65.0 MBit/s MCS 7
        expected throughput:    30.120Mbps
        authorized:     yes
        authenticated:  yes
        preamble:       short
        WMM/WME:        yes
        MFP:            no
        TDLS peer:      no
```

```sh
# cat /proc/net/wireless
Inter-| sta-|   Quality        |   Discarded packets               | Missed | WE
 face | tus | link level noise |  nwid  crypt   frag  retry   misc | beacon | 22
```

As I see it, `/proc/net/wireless` is like `/proc/net/dev` for wireless connections. In the access point case though, each client does not have a network device on the access point.

**Pull request merged**
