### PR TITLE
add plugin for Stiebel Eltron heat pump system

### PR DESCRIPTION
**Pull request by BrainDoctor**
My next plugin ;)

1. Node.js plugin
2. Readme page section in node.d/readme.md
3. Default configuration in conf.d/node.d/stiebeleltron.conf.md
4. Updated infographic. Had to move the lowest section down a bit, to provide space for this and future plugins
5. I didn't update the "Add charts" wiki yet. Should I split the "UPS and power" section into "UPS" and "Household appliances"? Or just a new section? Which links would get broken? I'm thinking of moving the solar power plugins and this one to "household", which would make more sense to me.

I'm aware that the plugin is collecting values based on a rather large JSON configuration (definition of charts, dimensions etc.). I decided to do it in this way so that other people are able to collect different values in their systems. I cannot provide a plugin that is working for every setup, since I cannot test them (there are air/water systems, geothermal probes, etc). But I can make it adaptive.

Also the metrics are collected using RegEx. Not optimal but there is no direct API (AFAIK) and performance-wise they are just fine (some 0.9% spikes on a Intel Xeon). The slowest component is the device response itself (usually around 1s, sometimes it takes up to 4s).

### CODE REVIEW

**Comment by ktsaou** [comment]
Nice!

> I'm thinking of moving the solar power plugins and this one to "household"

I like that too.

I haven't reviewed it yet. Give me some time.

One note: for the images you add to the infographic, please copy and paste the image to a comment like this one. The problem is that third party sites update their images and as time passes the infographic breaks and needs maintenance. If you just paste the image to github and use the github URL at the infographic, our interactive page (https://my-netdata.io/infographic.html) uses the github CDN for image delivery which is usually very fast and available.

**Comment by BrainDoctor** [comment]
You mean pasting the logo here:
logo-stiebel-eltron
and use this link?

**Comment by BrainDoctor** [comment]
I updated the infographic with the stiebel logo from here and the fronius from PR #2416 in the same commit. I know, I was too lazy to create a new PR ;)

**Comment by ktsaou** [comment]
I am ready to merge this.
Do you agree?

**Comment by ktsaou** [comment]
this one?

**Comment by BrainDoctor** [comment]
Yes, unless you want to wait for the refactor

**Comment by ktsaou** [comment]
Your call... whatever you like...

**Comment by BrainDoctor** [comment]
ok lets merge this, so we have at least a working version. Have you decided what to do about the wiki pages? household category etc.

**Comment by ktsaou** [comment]
household seems good...

**Comment by ktsaou** [comment]
merged it! thank you!

**Pull request merged**
