### PR TITLE
smart module

### PR DESCRIPTION
**Pull request by vorph1**
This requires the smartctl binary to have suid set.

#840

### CODE REVIEW

**Comment by l2isbad** [comment]
Yo @vorph1 

First of all - the plugin is very heavy ( Popen chain). It takes over 1 second for execute `smartctl` for **1** disk (on my system).
Another problem is raw_values from smartctl output (which are used) - some of them are vendor specific and

> often not meaningful as a decimal number

If @ktsaou is ok with **several seconds** of plugin execution time we can continue to discuss `smart module` code

**Comment by l2isbad** [comment]
Anyway my suggestion is to make it easier:
1. `_get_raw_data` should ONLY execute a command and return decode value (all other logic is not needed)

```python
 def _get_raw_data(self, disk):

        try:
            raw_out, raw_err = Popen(['smartctl', '-a', '/dev/' + disk], stdout=PIPE, stderr=PIPE).communicate()
        except Exception:
            return None

        return raw_out.decode(encoding='utf-8') 
```
btw `encoding='utf-8'` is needed

2. _get_data should parse data from _get_raw_data and pass to netdata dict or None

The `smartctl` output is easy to parse with regex (its only one step!)
Example: `(r'(\d+)[\w\s]+0x.*?(Always|Offline)[\s-]+(\d+)')`

```
In [14]: reply = reply.communicate()[0].decode()
In [15]: re.findall(r'(\d+)[\w\s]+0x.*?(Always|Offline)[\s-]+(\d+)', reply)
Out[15]: 
[('1', 'Always', '0'),
 ('3', 'Always', '2208'),
 ('4', 'Always', '123'),
 ('5', 'Always', '0'),
 ('7', 'Always', '0'),
 ('9', 'Always', '12298'),
 ('10', 'Always', '0'),
 ('11', 'Always', '0'),
 ('12', 'Always', '120'),
 ('48', 'Always', '232'),
 ('194', 'Always', '35'),
 ('196', 'Always', '0'),
 ('197', 'Always', '0'),
 ('198', 'Offline', '0'),
 ('199', 'Always', '0'),
 ('200', 'Offline', '0')]
```

Then 

```python
def _get_data(self):
        to_netdata = dict()

        for disk in self.disks:
            data = self._get_raw_data(disk)
            if data: to_netdata.update({'_'.join([ident, disk]): value for ident, upd, value in self.regex.findall(data)})

        return to_netdata or None
```

3. **The most important**. You need to define custom **check** method

Popen(['smartctl' - this is bad. You need absolute path.

Check must (move all logic from init to check):
1. Find if smartctl exist or not. If yes define self.command = absolute path to smartcl. If not return False.
2. Find if suid set for smartctl. If not return False.
3. Only if 1 and 2 is True: execute `--scan-open`
4. Then execute _ged_data. result =  True (if _get_data can collect smth) or False

```python
result =  bool(self._get_data())) or False
```
5. If result is True - create charts, dimensions, return True. If not - return False

After every step  we need to write to error.log (no command or no siud or command cant collect any data etc).

**Comment by vorph1** [comment]
This takes about 400ms with 6 drives on my setup. I'm not aware of any alternative approach w/o smartctl.

**Comment by l2isbad** [comment]
To locate full path you can use netdata env variable
like

``` python
try:
    path = os.getenv('PATH').split(':')
    self.command = next(('/'.join([p, 'smartctl']) for p in path if os.access('/'.join([p, 'smartctl']), os.X_OK)))
except StopIteration:
    self.error('Can't locate smartctl binary')
    return False
```

**Comment by l2isbad** [comment]
And what about charts 'units' (celsius, hours etc) ?

**Comment by l2isbad** [comment]
Ok this graph from my home PC. 2 disks: 1 ssd, 1 hdd
screenshot_20170130_220422

You can see the cpu usage diff w/ and w/o smartcl plugin.

Since

> Netdata is very resource efficient 

We need @ktsaou to decide are there any reason to continue with this or it's to heavy for netdata.

**Comment by simonnagl** [comment]
An alternative approach might be parsing the log files/syslog of smartd.

Pros:
- Less CPU usage.
Cons:
- Needs configuration at smartd.conf.
- Less metrics available.

**Comment by ktsaou** [comment]
I see that smartd [supports the option ` -A `](https://www.smartmontools.org/browser/trunk/smartmontools/smartd.cpp#L1495) which creates a log file per drive, with all smart values.

Also, it [supports the option ` -i `](https://www.smartmontools.org/browser/trunk/smartmontools/smartd.cpp#L1523) to set the interval smartd queries the drives.

If the above are right, then we could create a very light python plugin tailing these files. It will be tricky, since on start the plugin might have to go through the entire file to find the current value for each attribute of each drive. But will still be a lot more efficient than running `smartctl` all the time.

**Comment by l2isbad** [comment]
Agree!

-A option looks promising

```
[/var/log/smartd]cat WDC_WD10EZEX_00BN5A0-WD_WCC3F7FLVZS9.ata.csv 
2017-01-31 05:47:34;    1;200;0;        3;175;2208;     4;100;123;      5;200;0;        7;200;0;        9;84;12323;     10;100;0;       11;100;0;       12;100;120;     192;200;48;     193;200;232; 194;108;35;     196;200;0;      197;200;0;      198;200;0;      199;200;0;      200;200;0;
2017-01-31 05:48:34;    1;200;0;        3;175;2208;     4;100;123;      5;200;0;        7;200;0;        9;84;12323;     10;100;0;       11;100;0;       12;100;120;     192;200;48;     193;200;232; 194;108;35;     196;200;0;      197;200;0;      198;200;0;      199;200;0;      200;200;0;
```

Super easy to parse! :smiley:
Anyway i dont understand one thing - which values do we need? Normalized or raw? Raw makes no sense. I think normalized are good. Am i right?

> "Normalized value", commonly referred to as just "value". This is a most universal measurement, on the scale from 0 (bad) to some maximum (good) value. Maximum values are typically 100, 200 or 253. Rule of thumb is: high values are good, low values are bad.

> "Raw value" - the value of the attribute as it is tracked by the device, before any normalization takes place. Some raw numbers provide valuable insight when properly interpreted. These cases will be discussed later on. Raw values are typically listed in hexadecimal numbers.

**Comment by l2isbad** [comment]
@vorph1 do you want to rewrite it using log file or can i?

**Comment by vorph1** [comment]
Go ahead

wt., 31.01.2017, 07:12 użytkownik Ilya Mashchenko <notifications@github.com>
napisał:

**Comment by l2isbad** [comment]
Done https://github.com/firehol/netdata/pull/1693

**Comment by ktsaou** [comment]
@l2isbad nice! I think we can close this in favour of #1693

**Pull request closed without merging**
