### PR TITLE
MySQLService class added + rewritten mysql_plugin

### PR DESCRIPTION
**Pull request by l2isbad**
Initial version.
Should be tested (works ok for me).

### CODE REVIEW

**Comment by l2isbad** [comment]
@jurgenhaas can you test the PR please?
It works with no problem (restart/stop/start service, not enough perm to execute slave status, python2.7/3.4+) for me but may be i missing something. `mysql_plugin` is the one of the most used i'm sure so to double check it makes sense.

**Comment by jurgenhaas** [comment]
@l2isbad I've cloned branch MySQLService_class from https://github.com/l2isbad/netdata.git and installed on Ubuntu 16.04 - it is working and I've not recognized any difference to the main master branch. The config file looks like the same as before. Is there anything else I should be testing?

**Comment by l2isbad** [comment]
@jurgenhaas the output/charts is the same, yes.

> it is working 

Nice, thanks!  

@ktsaou i think we can merge it

**Comment by ktsaou** [comment]
done! merged!

**Pull request merged**
