### PR TITLE
tomcat.chart.sh plugin

### PR DESCRIPTION
**Pull request by jgeromero**
Hi. This is a pull request to include a tomcat charts.d plugin. Tested on Tomcat version: 7.0.54. Thank you.

### CODE REVIEW

**Comment by ktsaou** [comment]
Nice! Thank you for contributing it.
May I make a few suggestions?

**Comment by jgeromero** [comment]
Yes, of course.

**Comment by ktsaou** [comment]
ok, here they are:

1. **autodetection**

 I suggest to set the global `tomcat_url="http://<user>:<password>@localhost:8080/manager/status?XML=true"` to either something that will work out of the box (auto-detection) or to just empty.

 The way it is now, every time the plugin starts it will actually make this request, as-is.

 so, if the default port of tomcat is 8080, I guess this:

 ```
tomcat_url="http://localhost:8080/manager/status?XML=true"
```

 will do it.

2. **performance**

 in `tomcat_get()` you download and process the same XML 5 times. This is a waste that will be executed every single second your plugin runs. Think of it. Tomcat, curl and xmllint will do this 5 times per second. This consumes CPU resources and increases the load of the machine.

 I read that xmllint might be able to output all 5 xpaths in one run. If this can be done, this is the way to do it. Check this: http://unix.stackexchange.com/a/52749

3. **dependencies**

  In `tomcat_check()` you should add this at its top:

 ```
tomcat_check() {
       require_cmd xmllint || return 1

       ...
```

 This will allow the users know (in error.log) a required command is missing for this plugin.

4. **information**

 I would appreciate some information about this plugin, a screenshot, etc, to add it to the wiki. Anything you would like your users to know, will do.


I hope these are not too much... :)

**Comment by jgeromero** [comment]
Suggestions make sense, thank you. I was not happy with that get function either as I knew it could be optimized but couldn't find the right switch options to get it working. I'll try the solution in the link, fix the rest and commit changes. Cheers.

**Comment by jgeromero** [comment]
Ok changes have been committed. Much happier with it now. Some information about the plugin:

* Tested on Tomcat Version 7.0.54 on Ubuntu Server 14.04.1 LTS
* Requires xmlstarlet

Attaching a screenshot below. Thank you!

tomcat-netdata

**Comment by ktsaou** [comment]
ok. very nice work!
I'll merge it now.

For my reference, could you please post one dump of the XML tomcat provides? I will add it to the wiki page, and will probably help us debug issues reported by users.

**Comment by ktsaou** [comment]
Added to the wiki: https://github.com/firehol/netdata/wiki/tomcat.chart.sh

If you want to add more info, paste it here and I'll copy it.

**Comment by jgeromero** [comment]
Hi, here's what the XML output from tomcat looks like:

```
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="/manager/xform.xsl" ?>
<status>
  <jvm>
    <memory free="114325512" total="308281344" max="477102080"/>
    <memorypool name="PS Eden Space" type="Heap memory" usageInit="16777216" usageCommitted="141033472" usageMax="146800640" usageUsed="58760568"/>
    <memorypool name="PS Old Gen" type="Heap memory" usageInit="42991616" usageCommitted="150994944" usageMax="357564416" usageUsed="124971648"/>
    <memorypool name="PS Survivor Space" type="Heap memory" usageInit="2621440" usageCommitted="16252928" usageMax="16252928" usageUsed="10223616"/>
    <memorypool name="Code Cache" type="Non-heap memory" usageInit="2555904" usageCommitted="12189696" usageMax="50331648" usageUsed="11989760"/>
    <memorypool name="PS Perm Gen" type="Non-heap memory" usageInit="22020096" usageCommitted="179830784" usageMax="268435456" usageUsed="95602520"/>
  </jvm>
  <connector name="&quot;ajp-bio-8009&quot;">
    <threadInfo maxThreads="200" currentThreadCount="0" currentThreadsBusy="0"/>
    <requestInfo maxTime="0" processingTime="0" requestCount="0" errorCount="0" bytesReceived="0" bytesSent="0"/>
    <workers/>
  </connector>
  <connector name="&quot;http-bio-8080&quot;">
    <threadInfo maxThreads="200" currentThreadCount="12" currentThreadsBusy="3"/>
    <requestInfo maxTime="2763" processingTime="55516" requestCount="24406" errorCount="2" bytesReceived="293" bytesSent="172619782"/>
    <workers>
      <worker stage="R" requestProcessingTime="0" requestBytesSent="0" requestBytesReceived="0" remoteAddr="?" virtualHost="?" method="?" currentUri="?" currentQueryString="?" protocol="?"/>
      <worker stage="R" requestProcessingTime="0" requestBytesSent="0" requestBytesReceived="0" remoteAddr="?" virtualHost="?" method="?" currentUri="?" currentQueryString="?" protocol="?"/>
      <worker stage="S" requestProcessingTime="0" requestBytesSent="0" requestBytesReceived="0" remoteAddr="10.10.0.14" virtualHost="ubuntu-server" method="GET" currentUri="/manager/status" currentQueryString="XML=true" protocol="HTTP/1.1"/>
      <worker stage="R" requestProcessingTime="0" requestBytesSent="0" requestBytesReceived="0" remoteAddr="?" virtualHost="?" method="?" currentUri="?" currentQueryString="?" protocol="?"/>
      <worker stage="R" requestProcessingTime="0" requestBytesSent="0" requestBytesReceived="0" remoteAddr="?" virtualHost="?" method="?" currentUri="?" currentQueryString="?" protocol="?"/>
      <worker stage="R" requestProcessingTime="0" requestBytesSent="0" requestBytesReceived="0" remoteAddr="?" virtualHost="?" method="?" currentUri="?" currentQueryString="?" protocol="?"/>
      <worker stage="R" requestProcessingTime="0" requestBytesSent="0" requestBytesReceived="0" remoteAddr="?" virtualHost="?" method="?" currentUri="?" currentQueryString="?" protocol="?"/>
      <worker stage="R" requestProcessingTime="0" requestBytesSent="0" requestBytesReceived="0" remoteAddr="?" virtualHost="?" method="?" currentUri="?" currentQueryString="?" protocol="?"/>
      <worker stage="R" requestProcessingTime="0" requestBytesSent="0" requestBytesReceived="0" remoteAddr="?" virtualHost="?" method="?" currentUri="?" currentQueryString="?" protocol="?"/>
      <worker stage="R" requestProcessingTime="0" requestBytesSent="0" requestBytesReceived="0" remoteAddr="?" virtualHost="?" method="?" currentUri="?" currentQueryString="?" protocol="?"/>
      <worker stage="R" requestProcessingTime="0" requestBytesSent="0" requestBytesReceived="0" remoteAddr="?" virtualHost="?" method="?" currentUri="?" currentQueryString="?" protocol="?"/>
      <worker stage="R" requestProcessingTime="0" requestBytesSent="0" requestBytesReceived="0" remoteAddr="?" virtualHost="?" method="?" currentUri="?" currentQueryString="?" protocol="?"/>
    </workers>
  </connector>
</status>

```

**Pull request merged**
