### PR TITLE
slack.com notifications support

### PR DESCRIPTION
**Pull request by ktsaou**
With this PR, `alarm-notify.sh` supports:

1. email notifications
2. pushover.net notifications
3. slack.com notifications (slack calls them: **incoming webhooks**)

Also, each alarm gives one or **more roles** (yes, with this PR, multiple roles can be given, space separated at the `to` line).

For each role, there may be multiple recipients (email addresses, pushover user tokens, slack channels).

Documentation for configuring it, at `/etc/netdata/health_alarm_notify.conf` (here online: https://github.com/firehol/netdata/blob/master/conf.d/health_alarm_notify.conf)

cc: #285 #663 #846 #826 #88 #879 #318 #775 #809 #813 #848 

This is how it looks:

image

### CODE REVIEW

**Comment by ktsaou** [comment]
Another example:

image

**Comment by ShepherdJerred** [comment]
Not sure if this is frowned upon, but I'd like to leave a note that my Slack notifications weren't working with a particular channel if I only had one channel listed for notifications. I got around it by putting `,netdata, `for the channel name (My Slack channel is named netdata)

**Comment by ktsaou** [comment]
strange. I have just one channel and it works. When it did not work, was it logging any errors in /var/log/netdata/error.log ?

**Comment by ShepherdJerred** [comment]
None that I could see. It was extremely odd, it seemed like it would work with a channel named "general" just fine, but "netdata" would simply not work. Nothing mentioning the word slack in the logs except when it would send alerts to "general"

**Comment by ktsaou** [comment]
ok, but did the script was saying it was sending it or that it was failing to do so?

**Comment by ShepherdJerred** [comment]
The errors log was empty.

**Comment by ktsaou** [comment]
hm... is it still empty? Does it now log when it sends slack notifications?

**Comment by ShepherdJerred** [comment]
It does show up in error.log now that it's fixed.
`2017-01-23 20:40:11: alarm-notify.sh: INFO: sent slack notification for: ts-mc.net disk_backlog.sda.10min_disk_backlog is CLEAR to 'netdata'
`

**Pull request merged**
