### PR TITLE
php_fpm_plugin: avg dimension for cpu,mem,dur charts added + bugfix

### PR DESCRIPTION
**Pull request by l2isbad**
https://github.com/firehol/netdata/issues/1888
I saw on the chart max and avg dimensions..
min was added. Not sure it was right but looks logical to me 😄 

screenshot_20170304_185918

### CODE REVIEW

**Comment by ktsaou** [comment]
merged (I cannot tested though)...

**Comment by ktsaou** [comment]
I have posted at the author's blog to let him know: https://scotthelme.co.uk/launching-my-new-server-monitoring-dashboard-horizon/

**Comment by l2isbad** [comment]
For some reason author uses very old netdata 😄

**Comment by ktsaou** [comment]
Currently, "very old netdata" is probably "a week, or two, old".
You are doing a excellent job to shorten that time further... :+1: 
I really like that...

**Comment by ScottHelme** [comment]
I'm working on updating it now, I should be able to let you know shortly. I've also added an entry to my Ansible scripts because the standard update mechanism doesn't catch netdata, it shouldn't get too out of date now.

**Comment by ScottHelme** [comment]
Ok, they're all updated now! 🤞

**Comment by ktsaou** [comment]
nice! Keep in mind you can easily enable systemd services monitoring too.
Edit `/etc/systemd/system.conf` and set:

```
DefaultCPUAccounting=yes
DefaultBlockIOAccounting=yes
DefaultMemoryAccounting=yes
```

Then execute:

```
systemctl daemon-reexec
systemctl restart netdata
```

You should have another set of charts, monitoring all systemd services.

**Pull request merged**
