### PR TITLE
Add init script from CentOS6

### PR DESCRIPTION
**Pull request by sergiopena**
I made this script for my CentOS 6 installations, maybe you want to add it to the contrib folder.

Cheers

### CODE REVIEW

**Comment by ktsaou** [comment]
thanks!
This has to be integrated to the installer, so that it will be modified to adapt the installation path chosen.
I don't the time to do it now, so I will leave it open to remember it.

Thanks!

**Comment by n0guest** [comment]
I guess this version can be improved with few things:

1) support for non-default installation path (e.g. if installed from the sources to /usr/local/netdata)
2) start the daemon not under root, but under different account (e.g. user netdata)

Both features can be "borrowed" from this version #443.

PS: If you want to, i can try to make those changes and post results here.

**Comment by ktsaou** [comment]
nice! yes, please do.

**Comment by sergiopena** [comment]
Awesome, thank you @n0guest

**Comment by n0guest** [comment]
Here is merged version:

```
#!/bin/bash
#
# NetData 		NetData Realtime performance monitor
#
# chkconfig: 	2345 80 30
# description: 	Real-time charts for system monitoring
# processname:	netdata
# pidfile: 		/var/run/netdata.pid
# lockfile: 	/var/lock/subsys/netdata
#
# Added init info from d

### BEGIN INIT INFO
# Provides: 			netdata
# Required-Start:	 	$local_fs
# Required-Stop: 		$local_fs
# Default-Start: 		2 3 4 5
# Default-Stop:			0 1 6
# Short-Description:	Real-time charts for system monitoring
# Description:      	Netdata is a daemon that collects data in realtime (per second)
#                   	and presents a web site to view and analyze them. The presentation
#                   	is also real-time and full of interactive charts that precisely
#                   	render all collected values.
### END INIT INFO

. /etc/init.d/functions

umask 077

SERVICE_NAME=netdata
PROGNAME=netdata
PIDFILE=/var/run/${PROGNAME}.pid
LOCKFILE=/var/lock/subsys/${PROGNAME}
RETVAL="0"

# Source config
if [ -f /etc/sysconfig/$PROGNAME ] ; then
    . /etc/sysconfig/$PROGNAME
fi

RUN_UID=${RUN_AS:-netdata}
RUN_CMD=${PREFIX}/usr/sbin/netdata

conf_check() {
    [ -x $RUN_CMD ] || exit 5
}

check_retval() {
  if [ $RETVAL -eq "0" ]; then
     success
     echo
     exit 0
  else
     failure
     echo
     exit 1
  fi
}

run_start() {
    RETMSG=$(status -p $PIDFILE $PROGNAME 2>&1)
    RETVAL=$?
    case $RETVAL in
        0|1|2)
            echo -n $RETMSG
        ;;
        3)
            echo -n "Starting $SERVICE_NAME"
            conf_check
            if [[ ( ! -f $PIDFILE )  ]]; then
                daemon --pidfile="$PIDFILE" $RUN_CMD -u $RUN_UID -pidfile ${PIDFILE}
                RETVAL=$?
                echo
                [ $RETVAL -eq 0 ] && touch $LOCKFILE
                return $RETVAL
            else
              echo ", but is already running ..."
            fi
        ;;
    esac
}

run_stop() {
    echo -n "Stopping $SERVICE_NAME"
	status -p $PIDFILE $PROGNAME > /dev/null
    RETVAL=$?
    if [[ ( $RETVAL -eq "0" ) ]]; then
        killproc -p "$PIDFILE" $RUN_CMD
        RETVAL=$?
        [ $RETVAL -eq 0 ] && rm -f $LOCKFILE
    else
        RETVAL=0
        echo -n ", but is not running ..."
        if [ -f $PIDFILE ]; then rm $PIDFILE; fi
        if [ -f $LOCKFILE ]; then rm $LOCKFILE; fi
    fi
}

run_status() {
 	status -p $PIDFILE -l $PROGNAME $RUN_CMD
}

case $1 in
    start)
        run_start
        check_retval
    ;;
    stop)
        run_stop
        check_retval
    ;;
    restart)
        run_stop
        echo
        run_start
        check_retval
    ;;
    status)
        run_status
    ;;
    *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 3
    ;;
esac

exit $?
```

In /etc/sysconfig/netdata can be defined two variables:

* RUN_AS - run under this user (netdata if it isn't defined)
* PREFIX - installation prefix (if option --install was used for netdata-installer.sh)

PS: BTW, i've recently built a packages for main distributions (rpm for CentOS 6/7, deb for Debian 7/8 and Ubuntu 12/14). If you're interested, i can publish changes, that i've made to build it.

**Comment by paulfantom** [comment]
What about this?
@jasonwbarnett since you were doing el6 support (#728), can you verify if this can be used to something?

**Comment by jasonwbarnett** [comment]
@paulfantom let me look this over...

**Comment by jasonwbarnett** [comment]
I don't immediately see the advantage of this over the existing [system/netdata-init-d.in][1] which is currently included in the existing [netdata.spec.in][2].

What am I missing? What am I not thinking about?

[1]: https://github.com/firehol/netdata/blob/master/system/netdata-init-d.in
[2]: https://github.com/firehol/netdata/blob/master/netdata.spec.in

**Comment by paulfantom** [comment]
Yeah, I haven't seen it either.

**Comment by n0guest** [comment]
> What am I missing? What am I not thinking about?

For example RUN_AS and PREFIX variables which can be defined in /etc/sysconfig/netdata.

**Comment by jasonwbarnett** [comment]
> For example RUN_AS and PREFIX variables which can be defined in /etc/sysconfig/netdata.

1. `RUN_AS`

  netdata is similar to the httpd package; you define which user the program is run as in the application's configuration (e.g.  `netdata.conf`, `httpd.conf`), not the init script or sysconfig.

1. `PREFIX`

  This really only makes sense to have in an init script if you're installing netdata using a method other than through the RPM or [netdata-installer.sh][1] script.

---

I definitely saw value in this prior to the RPM spec being finished, but now that it's finished and working for EL6 (RHEL/CentOS) I don't see how it improves or adds to the existing.

Again, if there is something I'm missing or not thinking about, please let me know.

[1]: https://github.com/firehol/netdata/blob/master/netdata-installer.sh

**Comment by benwtr** [comment]
This is confusing. Why are you wanting to add an RH style init script to `contrib/`?

There is already an RH style init script in `system/`: https://github.com/firehol/netdata/commits/master/system/netdata-init-d.in

Oddly, the wiki had some bad/wrong instructions about this on the installation page, saying this script was an init script for Ubuntu which it definitely is not. I corrected it - https://github.com/firehol/netdata/wiki/Installation/_compare/af1a7fdffcaea69fbb909f9ead338854aff3b07c

It also has a bug https://github.com/firehol/netdata/blob/master/system/netdata-lsb.in#L22 , it should be: `PIDFILE=@localstatedir_POST@/run/$DAEMON.pid`. If you install to default paths, currently you will end up with `PIDFILE=/var/netdata.pid` in the init script.

**Comment by ktsaou** [comment]
> It also has a bug https://github.com/firehol/netdata/blob/master/system/netdata-lsb.in#L22 , it should be: PIDFILE=@localstatedir_POST@/run/$DAEMON.pid. If you install to default paths, currently you will end up with PIDFILE=/var/netdata.pid in the init script.

fixed that in PR #1052

**Comment by benwtr** [comment]
@ktsaou Thanks for fixing the pidfile path in the netdata-lsb script! 👍

**Comment by benwtr** [comment]
I added a note to the wiki's [Installation](https://github.com/firehol/netdata/wiki/Installation) page regarding the existing init.d script: 

https://github.com/firehol/netdata/wiki/Installation/_compare/6d16e050e2a5bf0fb41a272cd99f2b6517126c52

I also tested it. The service starts but the init script seems unable to stop the service.

My suggestion would be to close this PR, and open a new one (that references this one!) to merge @n0guest's changes into `system/netdata-init-d.in`

**Comment by ktsaou** [comment]
ok. @n0guest can you make a PR please?

**Comment by paulfantom** [comment]
OMG this is still open? Should we do something about this PR? Like close it?

**Comment by ktsaou** [comment]
ok, I am closing it. It is ancient and I don't know if it still valid.

**Pull request closed without merging**
