### PR TITLE
More IPFS stats in less code

### PR DESCRIPTION
**Pull request by pjz**
First I wanted just one thing (repo_size), and putting that in made me look at the code, which was very repetitious.  So I made it less so.  Which made it so easy to add new things that I added the repo_objects info.

### CODE REVIEW

**Comment by ktsaou** [comment]
thanks!
I can't test this. Is it ready to be merged?

**Comment by ktsaou** [comment]
@l2isbad please review this...

**Comment by l2isbad** [comment]
I have no ipfs..but now code looks definitely much cleaner! It is super easy now to add new api calls.
The only suggestion is do all additional calls as non default.

**Comment by pjz** [comment]
I just wanted to make what's there a little better.  Extending it via config options is, I think, a different PR.

**Comment by ktsaou** [comment]
merged! thanks!

**Pull request merged**
