### PR TITLE
Rabbitmq plugin

### PR DESCRIPTION
**Pull request by l2isbad**
https://github.com/firehol/netdata/issues/1813
Overview section from the management plugin. Better than nothing 😄 

screenshot_20170513_012258

### CODE REVIEW

**Comment by ktsaou** [comment]
Wow! You are the best!

**Comment by l2isbad** [comment]
@ktsaou ready. Let's start from simple one. That's all metrics I was able to get from the instance that I have access to.

**Comment by ktsaou** [comment]
merged!
I haven't tried it yet, but I am really looking forward to...
You rock!

**Comment by ne0c0de** [comment]
Hi,

I'm a newbie for net-stat, i already installed it on one my servers and try to enable this RabbitMQ plugin (this is why i try to use netstat)

Is there any instructions for how to configure and use it?

Thanks

**Comment by l2isbad** [comment]
Hi @ne0c0de 

- [install management plugin](https://www.rabbitmq.com/management.html) 
If your netdata and rabbitmq instances on the same PC plugin should work.

**Comment by ne0c0de** [comment]
Hello @l2isbad 

RabbitMQ is on different server (actually there are different servers that holds different RabbitMQs)

management plugins are already enabled on all of them and i can reach over 15672 port to all of them. 

I already configured the configuration file but i'm still looking for how to enable rabbitmq plugin

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/blob/master/conf.d/python.d/rabbitmq.conf#L57-L75

**Comment by ne0c0de** [comment]
as i already said above i already configured it, but i was looking for enable it then o noticed that restart the netsdata service will enable it.

So it's working very well now.

My new question: Can i define any alert rules for it? if yes, how?

**Comment by l2isbad** [comment]
> Can i define any alert rules for it? if yes, how?

Yes.
https://github.com/firehol/netdata/wiki/health-configuration-reference
https://github.com/firehol/netdata/wiki/health-configuration-examples

You can add any number of alarms to the `health.d` (`/opt/netdata/etc/netdata/health.d/`
 in my case) directory.

Predefined alarms:
```
ls /opt/netdata/etc/netdata/health.d/*.conf
/opt/netdata/etc/netdata/health.d/apache.conf         /opt/netdata/etc/netdata/health.d/named.conf
/opt/netdata/etc/netdata/health.d/backend.conf        /opt/netdata/etc/netdata/health.d/net.conf
/opt/netdata/etc/netdata/health.d/bind_rndc.conf      /opt/netdata/etc/netdata/health.d/netfilter.conf
/opt/netdata/etc/netdata/health.d/cpu.conf            /opt/netdata/etc/netdata/health.d/nginx.conf
/opt/netdata/etc/netdata/health.d/disks.conf          /opt/netdata/etc/netdata/health.d/postgres.conf
/opt/netdata/etc/netdata/health.d/elasticsearch.conf  /opt/netdata/etc/netdata/health.d/qos.conf
/opt/netdata/etc/netdata/health.d/entropy.conf        /opt/netdata/etc/netdata/health.d/ram.conf
/opt/netdata/etc/netdata/health.d/fping.conf          /opt/netdata/etc/netdata/health.d/redis.conf
/opt/netdata/etc/netdata/health.d/haproxy.conf        /opt/netdata/etc/netdata/health.d/retroshare.conf
/opt/netdata/etc/netdata/health.d/ipc.conf            /opt/netdata/etc/netdata/health.d/softnet.conf
/opt/netdata/etc/netdata/health.d/ipfs.conf           /opt/netdata/etc/netdata/health.d/squid.conf
/opt/netdata/etc/netdata/health.d/ipmi.conf           /opt/netdata/etc/netdata/health.d/swap.conf
/opt/netdata/etc/netdata/health.d/isc_dhcpd.conf      /opt/netdata/etc/netdata/health.d/tcp_resets.conf
/opt/netdata/etc/netdata/health.d/mdstat.conf         /opt/netdata/etc/netdata/health.d/udp_errors.conf
/opt/netdata/etc/netdata/health.d/memcached.conf      /opt/netdata/etc/netdata/health.d/varnish.conf
/opt/netdata/etc/netdata/health.d/memory.conf         /opt/netdata/etc/netdata/health.d/web_log.conf
/opt/netdata/etc/netdata/health.d/mysql.conf          /opt/netdata/etc/netdata/health.d/zfs.conf
```

@ne0c0de  If you think we should add some alarms to the predefined list feel free to suggest it here.

The one which we really need to add is `last_collected` (alarms if rabbitmq instance is not responding)

**Comment by ne0c0de** [comment]
I defined a rule something like that:
`
# make sure postgres is running

template: rabbitmq_last_collected_secs
      on: rabbitmq_local.queued_messages
    calc: $now - $last_collected_t
   units: seconds ago
   every: 10s
    warn: $this > (($status >= $WARNING)  ? ($update_every) : ( 5 * $update_every))
    crit: $this > (($status == $CRITICAL) ? ($update_every) : (60 * $update_every))
   delay: down 5m multiplier 1.5 max 1h
    info: number of seconds since the last successful data collection for rabbitmq
      to: dba
`

how can i be sure that this rule will be working or not? is there a panel in netdata dashboard to check this kind of rules?

**Comment by ktsaou** [comment]
On the dashboard, click the alarms icon on the navigation bar, swith to the second tab named `All`. Then look for rabbitmq. You should have a section and a badge for it.

**Comment by ne0c0de** [comment]
Thanks @ktsaou now i can see my alert rules there,

My current alert templates like this:


template: rabbitmq_alive_alert
      on: rabbitmq.queued_messages
    calc: $now - $last_collected_t
   units: seconds ago
   every: 1m
    warn: $this > (($status >= $WARNING)  ? ($update_every) : ( 5 * $update_every))
    crit: $this > (($status == $CRITICAL) ? ($update_every) : (60 * $update_every))
   delay: down 5m multiplier 1.5 max 1h
    info: number of seconds since the last successful data collection
      to: dba

template: rabbitmq_waiting_message_alert
      on: rabbitmq.queued_messages
    calc: $messages_ready_raw
   units: message
   every: 1m
    warn: $this > 1000
    crit: $this > 10000
   delay: down 5m multiplier 1.5 max 1h
    info: waiting messages is increasing
      to: dba

i'm trying to add this rule:

template: rabbitmq_consumer_alert
      on: rabbitmq_azureapp.global_counts
    calc: $consumers_raw
   units: consumer
   every: 1m
    warn: $this < 231
    crit: $this < 200
   delay: down 5m multiplier 1.5 max 1h
    info: consumers missing
      to: dba

however net-data is not recognizing it,the difference of the latest rule is it,s a spesific rule for only 1 rabbitmq instance ( i have 7 different RabbitMQ instance running on different servers.)

I can see the metric on

http://xxx:19999//api/v1/alarm_variables?chart=rabbitmq_azureapp.global_counts

as consumer_raw but when i used it in the alert template it's not recognizing. What i'm doing wrong here?

**Comment by ne0c0de** [comment]
Also i tried to change this:

template: rabbitmq_waiting_message_alert
on: rabbitmq.queued_messages
calc: $messages_ready_raw
units: message
every: 1m
warn: $this > 1000
crit: $this > 10000
delay: down 5m multiplier 1.5 max 1h
info: waiting messages is increasing
to: dba

to that:

template: rabbitmq_waiting_message_alert
on: rabbitmq_azureapp.queued_messages
calc: $messages_ready_raw
units: message
every: 1m
warn: $this > 1000
crit: $this > 10000
delay: down 5m multiplier 1.5 max 1h
info: waiting messages is increasing
to: dba

and it didn't recognized too.

So is there a bug in here or i'm doing something wrong? Any idea @l2isbad ?

**Comment by l2isbad** [comment]
Not sure why you are using `raw` values. Raw is last collected `as collected`. 

Random example

```bash
template: rabbitmq_waiting_message_alert
on: rabbitmq.queued_messages
lookup: max -10s of messages_ready
units: message
every: 10s
warn: $this > 1000
crit: $this > 10000
delay: down 5m multiplier 1.5 max 1h
info: waiting messages is increasing
to: sysadmin
```

**Comment by ktsaou** [comment]
What I normally do in cases like that, is to create 2 alarms:

1. long duration average, this does not have warning of critical conditions, so it does not trigger
2. short duration average

If the second is X times the first, the alarm is triggered. Similarly, for the critical condition.

Example for messages ready:

```
template: 10m_messages_ready_average
on: rabbitmq.queued_messages
lookup: average -10m unaligned of messages_ready
units: messages
every: 1m
info: 10 minute average of messages ready

template: 1m_messages_ready_delta
on: rabbitmq.queued_messages
lookup: average -1m unaligned of messages_ready
calc: $this * 100 / $10m_messages_ready_average
units: %
every: 10s
warn: $messages_ready > 100 && $this > (($status >= $WARNING) ? (150) : (250))
crit: $messages_ready > 100 && $this > (($status >= $CRITICAL) ? (250) : (500))
delay: down 5m multiplier 1.5 max 1h
info: the percentage difference of ready messages waiting in the last 1 minute, compared to the last 10 minutes
to: sysadmin
```

So, the above triggers if the 1m average is 2,5 times (250%) the 10 minute average and there are at least  100 messages ready. Once it is triggered, it needs the threshold to go bellow 150% to be cleared.

Similarly, the critical condition 

(ps: I have not checked the alarms - there may be typos in it - please check it if you use it)

**Comment by ne0c0de** [comment]
My case is different,

I have 7 different RabbitMQ instance defined in config and i want to create a template for instance spesific alerts. This is why i want to use `rabbitmq_azureapp.queued_messages` as a metric (_azureapp is the instance name) but it's not recognizing that rule

**Comment by ktsaou** [comment]
I forgot to mention that these "rolling" alarms have a little limitation:

Let's assume we have 100 messages ready during the last 10 minutes and now the system is constantly having 1000 messages. In a few seconds the alarm will be triggered, but in 5 minutes the alarm will be cleared even if the queue still has 1000 messages waiting. The reason is that the 10 minute average will grow as time passed.

For these cases, I also add:

```
options: no-clear-notification
```

This disables the clear notification.

**Comment by ktsaou** [comment]
> I have 7 different RabbitMQ instance defined in config and i want to create a template for instance spesific alerts. This is why i want to use rabbitmq_azureapp.queued_messages as a metric (_azureapp is the instance name) but it's not recognizing that rule

hm... what does "not recognizing this rule" mean?

**Comment by ktsaou** [comment]
oh, I got it.

You have 7 instances, but you need an alarm just for 1 instance of them.

Then, you need an `alarm` for that specific instance. Not a `template`.

**Comment by ktsaou** [comment]
Pay attention to the `on` line. On alarms that line should be the chart name. On templates it should be the chart context.

So, just change `template` to `alarm` when you use the chart name at the `on` line.

**Comment by ne0c0de** [comment]
> So, just change template to alarm when you use the chart name at the on line.

this is what i'm exactly looking for, i just changed it to alamr and now it works. thank you for your help ;)

**Comment by ne0c0de** [comment]
hello again,

i want to ask another question, i want to configure the template for queued messages like that:

if queued messages count is greater then 1000 for 10 minute send a warning alert.

my current template is:

`
 template: rabbitmq_waiting_message_alert
  on: rabbitmq.queued_messages
    calc: $messages_ready_raw
   units: messages
   every: 1m
    warn: $this > 1000
    crit: $this > 10000
   delay: down 5m multiplier 1.5 max 1h
    info: waiting messages is increasing
      to: dba
`

i think that i should change the `calc` value with the given your example above `lookup: average -10m unaligned of messages_ready`

am i correct?

**Comment by ktsaou** [comment]
yes, it seems correct.

**Comment by ktsaou** [comment]
I think there is a bug in the rabbit plugin:

https://github.com/firehol/netdata/blob/b1d939b956c2c82d3319efa32b1f4b0a02e979b2/python.d/rabbitmq.chart.py#L88

it says messages_ready is an `incremental` value. It should be `absolute`.

@l2isbad ?

**Comment by ne0c0de** [comment]
this is why i used raw value :)

isn't raw values can be usable in lookup?

**Comment by ne0c0de** [comment]
this is a status of my RabbitMQ instance:
screen shot 2017-05-22 at 14 19 11


however this is the result in net data

screen shot 2017-05-22 at 14 20 23

**Comment by l2isbad** [comment]
fixed in https://github.com/firehol/netdata/pull/2221

**Comment by ne0c0de** [comment]
Hello @l2isbad 

I just applied the patch to my netdata environment, service restarted but it's still showing that ready message count as 0 however it's 420 ( i can see it from net data API from messages_ready_raw property)

**Comment by l2isbad** [comment]
Well, it works for me after the patch. Value should be absolute indeed.

```
{
	"chart": "rabbitmq_remote.queued_messages",
	"chart_name": "rabbitmq_remote.queued_messages",
	"chart_context": "rabbitmq.queued_messages",
	"chart_variables": {
		"ready_last_collected_t": 1495454451.00000,
		"messages_ready_raw": 5.00000,
		"messages_unacknowledged_last_collected_t": 1495454451.00000,
		"messages_unacknowledged_raw": 2.00000,
		"unacknowledged_raw": 2.00000,
		"red": null,
		"messages_ready_last_collected_t": 1495454451.00000,
		"update_every": 1.00000,
		"ready_raw": 5.00000,
		"messages_ready": 5.00000,
		"unacknowledged": 2.00000,
		"ready": 5.00000,
		"last_collected_t": 1495454451.00000,
		"rabbitmq_waiting_message_alert": 0.00000,
		"messages_unacknowledged": 2.00000,
		"green": null,
		"collected_total_raw": 7.00000,
		"unacknowledged_last_collected_t": 1495454451.00000
	}
```

**Comment by ne0c0de** [comment]
i changed /home/xxx/netdata/ptyhon.d/rabbitmq.chart.py line 88 and 89 like this:
```
            ['messages_ready', 'ready', 'absolute'],
            ['messages_unacknowledged', 'unacknowledged', 'absolute']
```

this is what i see on https://github.com/firehol/netdata/pull/2221/commits/d8d3e9c16720eec4086dca8c2ef7d6c55cc8c912

and then restarted the netdata service for few times in order to be sure but here's the result:
screen shot 2017-05-22 at 15 10 11

**Comment by l2isbad** [comment]
> i changed /home/xxx/netdata/ptyhon.d/rabbitmq.chart.py

Hm, /home/xxx/netdata/ is the source code, isn't it?

**Comment by ne0c0de** [comment]
yes

**Comment by l2isbad** [comment]
```
[/home/lgz/netdata]./netdata-installer.sh --install /opt

  ^
  |.-.   .-.   .-.   .-.   .  netdata                                        
  |   '-'   '-'   '-'   '-'   real-time performance monitoring, done right!  
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->


  You are about to build and install netdata to your system.

  It will be installed at these locations:

   - the daemon     at /opt/netdata/usr/sbin/netdata
   - config files   in /opt/netdata/etc/netdata
   - web files      in /opt/netdata/usr/share/netdata
   - plugins        in /opt/netdata/usr/libexec/netdata
   - cache files    in /opt/netdata/var/cache/netdata
   - db files       in /opt/netdata/var/lib/netdata
   - log files      in /opt/netdata/var/log/netdata
   - pid file       at /opt/netdata/var/run/netdata.pid
   - logrotate file at /etc/logrotate.d/netdata
```

vim /opt/netdata/usr/libexec/netdata/python.d/rabbitmq.chart.py     <---

**Comment by ne0c0de** [comment]
oh yes i just edit the file on /usr/libexec/netdata/python.d/rabbitmq.chart.py and now it's working

for the alert template i changed messages_ready_raw to messages_ready and alert template is working too. (i guess templates doesn't work with raw value because it didn't trigger any alarm when the lookup metric is a messages_ready_raw however it worked with messages_ready)

**Comment by ktsaou** [comment]
nice.

`lookup` is performing operations on the database, which only stores the interpolated values, after the algorithm, multiplier and divider have been applied.
So, no you cannot use `_raw` in lookup - their history over time is not stored by netdata.

**Comment by ktsaou** [comment]
merged the fix.

**Pull request merged**
