### PR TITLE
update lgtm config

### PR DESCRIPTION
**Pull request by ktsaou**

### CODE REVIEW

**Comment by paulfantom** [comment]
Why LGTM suddenly fails?

**Comment by ktsaou** [comment]
The filtering on the files did not work. So it gives hundreds of errors due to urllib3, etc.
I am trying to figure out how to exclude third party libs from their analysis.

**Comment by ktsaou** [comment]
@paulfantom this does not work.

The python check says the `urllib3` and `pyyaml3` packages are not whitelisted and the javascript  check that `**` is not allowed in the filtering (although the docs say otherwise).

Can you help?

**Comment by paulfantom** [comment]
Maybe use only one `*` instead of `**`?

**Comment by paulfantom** [comment]
Documentation suggests (but not directly) not to use `**` in exclusions.

> Example
This block specifies that files with paths matching test/util are not tagged as test code. Any other files with paths matching test or testsuites are tagged as test code. In addition, all proprietary test files (extension .test) are tagged as test code regardless of which directory they are stored in.

```
path_classifiers:
  test:
    - test
    - testsuites
    - "**/*.test"
    - exclude: test/util 
```

So just delete `/**` from all `exclude` line endings and it should work.

**Comment by ktsaou** [comment]
ok, let's see

**Comment by ktsaou** [comment]
This pull request **introduces 8 alerts** and **fixes 31** when merging 6d22b09b2269f8f8d91351ad4c045667dee9a0b0 into 8e0b0bcb551ac14d2b24bbf2551ef9f6cd96e405 - [view on LGTM.com](https://lgtm.com/projects/g/firehol/netdata/rev/pr-8af79f9bcfd76eef0682948363dd8fa2ad0bfff5)

**new alerts:**

* 4 for Syntax error
* 3 for &#39;import \*&#39; may pollute namespace
* 1 for First argument of a method is not named &#39;self&#39;

**fixed alerts:**

* 14 for &#39;import \*&#39; may pollute namespace
* 3 for Inconsistent equality and inequality
* 3 for Unused local variable
* 2 for Superfluous trailing arguments
* 2 for &#39;super&#39; in old style class
* 2 for Inconsistent equality and hashing
* 2 for Unused variable, import, function or class
* 1 for Duplication in regular expression character class
* 1 for Syntax error
* 1 for Variable defined multiple times

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by paulfantom** [comment]
Maybe it will work when used like this:
```
- exclude: "python.d/python_modules/pyyaml3"
```
instead of:
```
- exclude: "python.d/python_modules/pyyaml3/*"
```

**Comment by ktsaou** [comment]
ok, let's see

**Comment by ktsaou** [comment]
it did not work either...

**Comment by paulfantom** [comment]
Are you sure it should be done in `extraction` and not in `path_classifiers`?

**Comment by ktsaou** [comment]
let's see if excluding all the directories, one by one, helps

**Comment by ktsaou** [comment]
Well, it didn't work again...
I am out of ideas...

**Comment by ktsaou** [comment]
added on top of the others, `path_classifiers`.

**Comment by paulfantom** [comment]
I will try it in separate repo and come back with config.

**Comment by ktsaou** [comment]
didn't work either.

**Comment by ktsaou** [comment]
so, I don't know what to do now.
@paulfantom I am closing this. If you can make it work, please do.

**Comment by paulfantom** [comment]
But don't disable LGTM as their insight is useful for development. Even when we are checking too much.

**Comment by ktsaou** [comment]
> But don't disable LGTM as their insight is useful for development. Even when we are checking too much.

No, I won't delete it of course.
But we need to find a way this to report something that is fair to us.

**Pull request closed without merging**
