### PR TITLE
First commit new Samba python plugin for smb2 uses smbd -P 1 profiling

### PR DESCRIPTION
**Pull request by ntlug**
This change is [Reviewable](https://reviewable.io/reviews/firehol/netdata/2094)

### CODE REVIEW

**Comment by ntlug** [comment]
You can actually turn on profiling via the smb.conf file as well.

**Comment by ktsaou** [comment]
@l2isbad could you please review this?

**Comment by ktsaou** [comment]
@ntlug thanks!

**Comment by l2isbad** [comment]
@ktsaou 
Well, it uses Popen, `sudo` and "dummy" for color selection..

**Comment by ktsaou** [comment]
hm... I didn't notice... thanks!

@ntlug this plugin is going to be heavy / resource hungry. Apart that, I am trying to figure out how to get `smbstatus -P 1` work. On my systems I get:

```sh
# smbstatus -P 1
Profile data unavailable
```

Have you compiled samba yourself?

**Comment by ntlug** [comment]
Yes... Samba has to be compiled for profiling support (sorry).  The one on CentOS 7 is.

**Comment by ntlug** [comment]
With regards to resource hungriness, it's actually pretty lightweight for a process exec.  That is, it's about a lightweight as they come exec wise.  But it is an exec.  I actually started from the varnish plugin as my basis for how to do this.

**Comment by ktsaou** [comment]
ok. Lets decide what we will do.

This plugin has 3 issues:

1. It execs
2. It sudos
3. It uses dummy dimensions.

I think we can accept 1, if it does it properly, which means It detects it is not usefull to run (i.e. `smbstatus` does not provide any usefull info, or is not installed).

Sudo is the next problem. Are you sure this is really needed? In most of the cases, sudo can be avoided by adding user netdata to a group that has access. Can you check it?

Sudo is problematic for 2 reasons:

1. It execs again
2. it needs adding user `netdata` to sudoers, which is equivalent to running netdata as root. So, this is a breaking issue.

The last issue are the dummy dimensions. I haven't understood why you need those.

Could you please also post screenshots of the charts to see the final product of the plugin?

**Comment by ntlug** [comment]
smbstatus only works as root.  You can do sudo by command see comment in plugin (no need to give netdata all access as root, just to do smbstatus -P).  There's no documentation on how a plugin can change the color of a dimension.  You can remove all of that if you like, everything goes to red/green/blah...

Screenshot: [http://endlessnow.com/images/Samba-plugin.png](url)

**Comment by ktsaou** [comment]
> smbstatus only works as root

hm... and it also refuses to run when it is setuid to root.
Then I guess you should use `sudo -n smbstatus -P`. `-n` instructs sudo to never ask for a password.

From the screenshots, I see the plugin produces very useful info.

So, @l2isbad I think that if @ntlug:

1. adds `-n` to sudo and we veriify it fails to pass auto-detection if netdata is not added to sudoers
2. removes dummy dimensions
3. provdes a default config file that sets the plugin update every to 5 seconds
4. adds the plugin to the makefiles

We can merge this. What do you think?

@ntlug ito change colors and/or add information on the dashboard, you will have to edit this file: https://github.com/firehol/netdata/blob/master/web/dashboard_info.js

1. [example that adds gauges on top of the charts](https://github.com/firehol/netdata/blob/5b42a3ae452606bc6d7a168bf00c6e857cbca933/web/dashboard_info.js#L604-L609)

2. A little bit below you will find another one that sets colors. You can add many colors as a space separated string. But you give fixed colors, please make sure they look ok on both dark and white background.

**Comment by ntlug** [comment]
Probably missing something easy, but what I have in dashboard_info.js isn't working color wise.  Can somebody take a look?

**Comment by l2isbad** [comment]
@ntlug 
check `codacy` errors pls

**Comment by l2isbad** [comment]
@ntlug thx. almost ready 😄 
1. [python readme](https://github.com/firehol/netdata/tree/master/python.d)
2. [wiki page](https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata) (open for everyone to edit)

And i'm not sure about all these commits. Maybe close this PR and open a new one @ktsaou ?

**Comment by ntlug** [comment]
Wiki page updated with samba (created new section for File Servers)

**Comment by ktsaou** [comment]
nice work! merging it.

**Pull request merged**
