### PR TITLE
Postgres plugin

### PR DESCRIPTION
**Pull request by facetoe**
Add a possible implementation for a Postgresql plugin with a minimal set of charts. ~~Most of the SQL comes from the Munin plugins as suggested in #82~~. 

This is my first attempt at writing a plugin for netdata so let me know if anything is amiss!

### CODE REVIEW

**Comment by ktsaou** [comment]
Thanks!

@paulfantom could you please review this?

To merge it, we need a configuration file for it (like the rest of the python.d.plugin modules) and the packages required to be installed for this to work.

**Comment by facetoe** [comment]
No problem @ktsaou, I'll try to get the config and dependencies sorted out this weekend.

**Comment by facetoe** [comment]
I'm going to refactor this plugin this weekend as I think I can improve it.

**Comment by facetoe** [comment]
I simplified things and reduced the number of queries needed to one.

**Comment by ktsaou** [comment]
ok thanks!
@facetoe when you are ready to merge, please let us know to review it.

**Comment by facetoe** [comment]
Hi @ktsaou, this should be good for review now. I've added a default config file and made a couple of final tweaks but I'm not sure where to put the dependencies. The plugin currently required `psycopg2` to work.

**Comment by paulfantom** [comment]
It looks ok. 
However @ktsaou what should we do with required `psycopg2` module? We have same problem with python requirements for:
 - `python.d.plugin` - PyYAML
 - `mysql.chart.py` - pymysql or mysql-client
 - more will come (for example GPU monitoring module)

It would be solved (at least for majority of people) when we start releasing netdata as binary package, but right now I don't have any ideas apart from `install-required-packages.sh` script.

**Comment by ktsaou** [comment]
We can add this to `install-required-packages.sh` and the wiki. This is what I found:

```sh
declare -A pkg_python_psycopg2=(
	   ['arch']="python-psycopg2"
	 ['centos']="python-psycopg2"
	 ['debian']="python-psycopg2"
	 ['gentoo']="dev-python/psycopg"
	   ['rhel']="python-psycopg2"
	   ['suse']="python-psycopg2"
	['default']="python-psycopg2"
	)
```

Do you agree?

**Comment by ktsaou** [comment]
Added: https://github.com/firehol/netdata-demo-site/blob/0a947f7b0dd0959858c029531ccb6d869edc1b66/install-required-packages.sh#L652-L660

**Comment by ktsaou** [comment]
Added to the wiki too: https://github.com/firehol/netdata/wiki/Installation

I am ready to merge.

merge?

**Comment by ktsaou** [comment]
I don't see anywhere any information about the configuration required on postgress to allow this module connect.

Also, the auto-detection configuration seems limited. If a postgres database on localhost is configured to allow the module connect, will the module connect to it without further configuration?

**Comment by facetoe** [comment]
Not currently. If the `postgres` user is able to connect without a password it is trivial to discover all the databases on the host, however I'm not sure how to inform netdata of these databases from within the plugin.

**Comment by facetoe** [comment]
> I don't see anywhere any information about the configuration required on postgress to allow this module connect.

I will add this information to the config file.

**Comment by ktsaou** [comment]
> however I'm not sure how to inform netdata of these databases from within the plugin.

Why would you need to do this? Add charts for each database?
If this is the case, the plugin should be able to do this.
@paulfantom any ideas? If I recall correctly, we have encountered this request once again: dynamically adding charts.

**Comment by facetoe** [comment]
Yes it would be to add charts for each database.

**Comment by ktsaou** [comment]
> Yes it would be to add charts for each database.

ok, let's way @paulfantom to suggest a solution.

**Comment by facetoe** [comment]
One solution might be to allow plugins to provide their own configuration if a flag is set in the config file. The [_parse_config()](https://github.com/firehol/netdata/blob/master/plugins.d/python.d.plugin#L203) method could be modified to honor this flag. 

The flow could be something like:
* if flag is set in config file
* call the (overridden?, static?) method `_get_config` (or similar)
* return config provided by module and proceed as normal

The mechanism for flagging modules that want to provide their own configuration could also include a way to reject config options suggested by the module. For example, you might want to specify a list of databases to not display. 

This would make it pretty straightforward for modules that want to automatically discover available services to do so without changing much of the existing code.

Anyway, just an idea. Let me know your thoughts @paulfantom @ktsaou !

**Comment by paulfantom** [comment]
@ktsaou package list included in `install-required-packages.sh` for `psycopg2` looks ok. 

@facetoe we have dynamic lines creation in `hddtemp.chart.py`, `cpufreq.chart.py`, and dynamic chart creation in `sensors.chart.py`. Maybe following path created by those modules, requested feature could be implemented in `postgres.chart.py`?

I don't understand what @facetoe means by saying:
>  modules that want to provide their own configuration

What "own" configuration? `module_name.conf` IS it's own configuration, and if this file is missing there should be default values.

Also I think that `python.d.plugin` shouldn't interfere with module logic, it shouldn't know what module does, how it does it and so on. If some feature is needed for specific module it should be implemented in it's class or it's parent class (in base.py).

**Comment by facetoe** [comment]
Thanks @paulfantom, I'll have a look at the chart creation in `sensors.chart.py`, sounds like it implements what I'm trying to achieve. 

For clarity, I might have misused the term `module`. What I mean is a Python module that wants to dynamically enrich the configuration found in the `*.conf` file. In the case of the Postgresql module it could be a function that returns configuration determined at runtime. For example, I could connect as the `postgres` user and enumerate the databases available on the host, returning configuration for each. Netdata would then create a job for each of these databases. 

I got the idea from looking through the Munin source as it has something similar. 

It is really a convenience thing. It allows me to say "clone my module N times with these configurations" without having to worry about the details of creating multiple charts for each, or knowing the details ahead of time.  

I'm not sure my explanation is very good, I would be happy to provide a PR with a prospective implementation if you guys want, however if it's a terrible idea at face value I will drop it and study `sensors.chart.py`!

**Comment by ktsaou** [comment]
> Netdata would then create a job for each of these databases.

hm... if we do it like that, the prostgres sever will get one connection per database per second. 10 databases and we will have 10 connections per second.

**Comment by facetoe** [comment]
This is a very good point. It would be more efficient for the module to take care of this in a single database call. I'll look into implementing the multiple charts in the same way the `sensors.chart.py` does.

**Comment by dangtranhoang** [comment]
@facetoe 
Base on your work and python code from https://github.com/MeetMe/newrelic-plugin-agent/blob/master/newrelic_plugin_agent/plugins/postgresql.py, I create another plugin for postgres which I use for our servers. Hope it help.

[postgres.chart.py.zip](https://github.com/firehol/netdata/files/540711/postgres.chart.py.zip)

**Comment by facetoe** [comment]
This is awesome @dangtranhoang, loving all those metrics! I'll replace my version with yours as it has much more information.

**Comment by paulfantom** [comment]
@facetoe please include yourself and @dangtranhoang  as authors (line 3 of `postgres.chart.py) :smile:

**Comment by facetoe** [comment]
@paulfantom, @ktsaou this should be good for review/merge now. It is only necessary to have a single connection per cluster and the plugin will provide charts for each database.

**Comment by dangtranhoang** [comment]
@facetoe could you put table and index stats as an option such as enable_table_stat / enable_index_stat? It will help others customize our plugin. What do you think?

**Comment by facetoe** [comment]
No worries @dangtranhoang, I can add an option to include those stats. I'll look at adding that tonight.

**Comment by facetoe** [comment]
Also I might as well try and get the replication and WAL stats working also as they would be pretty handy.

Might have to hold off on the review @paulfantom  until I implement these last few things.

**Comment by ktsaou** [comment]
@facetoe I really like this plugin!
@paulfantom please review it. I can't wait to merge it...

**Comment by facetoe** [comment]
Good to hear @ktsaou! It should be good to review when you get the chance @paulfantom. I'll have to add the replication chart later as it needs a bit of work.

**Comment by paulfantom** [comment]
It looks ok. I am merging it. Thanks @facetoe :+1:

**Comment by facetoe** [comment]
👍

**Pull request merged**
