### PR TITLE
Add ZFS charts to FreeBSD plugin

### PR DESCRIPTION
**Pull request by vlvkobal**
I've commented out sysctl calls for missing or not used mibs in order to lower CPU time consumption by unnecessary calls.

### CODE REVIEW

**Comment by ktsaou** [comment]
very nice!

I suggest to:

1. move the freebsd code to `freebsd_spl_kstat.c`
2. create the files `zfs_common.c` and `zfs_common.h` and move there the 2 common functions and the object definitions
3. include `zfs_common.h` from both the proc and the freebsd versions of the plugin

So, that `proc` and `freebsd` are independent.

What do you think?

**Comment by vlvkobal** [comment]
I like it. Thank you! Here are the changes.

**Comment by vlvkobal** [comment]
Ups. There is something wrong with statistics... I'll tell when it will be ready.

**Comment by vlvkobal** [comment]
Now it works. Please verify if ZFS statistics is working on Linux. I don't have any Linux with ZFS installed.

**Comment by ktsaou** [comment]
nice!

I don't have either, but I have created a little script to help us: https://github.com/firehol/netdata/pull/2020#issue-217007964

If you can't check it, I will do it, most likely tomorrow.

**Comment by vlvkobal** [comment]
I've checked the PR on Linux with the script. It works.

**Comment by ktsaou** [comment]
merged!
nice work!

**Pull request merged**
