### PR TITLE
varnish plugin (varnishstat)

### PR DESCRIPTION
**Pull request by l2isbad**
Not ready.
Must be tested.
@LeeNX @Bilge you are welcome guys.

I am not using varnish so i need your help
What additional charts do we need? (from varnishstat output)

**Literally any suggestion is super welcome!**

### CODE REVIEW

**Comment by Bilge** [comment]
Is it possible to see a net graph for each backend and each HTTP host?

**Comment by l2isbad** [comment]
If something in varnishstat output we can graph it (or do a calculation using any fields from output and graph the result - like cache hit/miss percent).

Do you mean those guys?
```
VBE.default(127.0.0.1,,81).vcls              1          .   VCL references
VBE.default(127.0.0.1,,81).happy             0          .   Happy health probes
VBE.default(127.0.0.1,,81).bereq_hdrbytes         1225         4.27 Request header bytes
VBE.default(127.0.0.1,,81).bereq_bodybytes            0         0.00 Request body bytes
VBE.default(127.0.0.1,,81).beresp_hdrbytes          654         2.28 Response header bytes
VBE.default(127.0.0.1,,81).beresp_bodybytes         3638        12.68 Response body bytes
VBE.default(127.0.0.1,,81).pipe_hdrbytes               0         0.00 Pipe request header bytes
VBE.default(127.0.0.1,,81).pipe_out                    0         0.00 Piped bytes to backend
VBE.default(127.0.0.1,,81).pipe_in                     0         0.00 Piped bytes from backend
VBE.default2(127.0.0.2,,81).vcls                       1          .   VCL references
VBE.default2(127.0.0.2,,81).happy                      0          .   Happy health probes
VBE.default2(127.0.0.2,,81).bereq_hdrbytes           412         1.44 Request header bytes
VBE.default2(127.0.0.2,,81).bereq_bodybytes            0         0.00 Request body bytes
VBE.default2(127.0.0.2,,81).beresp_hdrbytes          283         0.99 Response header bytes
VBE.default2(127.0.0.2,,81).beresp_bodybytes         3041        10.60 Response body bytes
VBE.default2(127.0.0.2,,81).pipe_hdrbytes               0         0.00 Pipe request header bytes
VBE.default2(127.0.0.2,,81).pipe_out                    0         0.00 Piped bytes to backend
VBE.default2(127.0.0.2,,81).pipe_in                     0         0.00 Piped bytes from backend
```

My varnish conf is 

```
backend default {
    .host = "127.0.0.1";
    .port = "81";                                                                                                                                                                            
}                                                                                                                                                                                            
backend default2 {                                                                                                                                                                           
    .host = "127.0.0.2";                                                                                                                                                                     
    .port = "81";                                                                                                                                                                            
}                                                                                                                                                                                            
                                                                                                                                                                                             
sub vcl_recv {                                                                                                                                                                               
if (req.url ~ "^/test/") {
        set req.backend_hint = default2;
    } else {
        set req.backend_hint = default;
    }
}
```

**Comment by Bilge** [comment]
@l2isbad Yes, I think that's probably it 👍

**Comment by l2isbad** [comment]
Can you post here your backend part of varsnishstat -1 ?

I am interesting in `identity` part of it
Mine is `default(127.0.0.1,,81)` (backendname(address port))

But it looks different from @LeeNX output
`xxxx-ab-ms.elections2016api`

**Comment by l2isbad** [comment]
My bad. I can see your hosts.

```
VBE.boot.default.conn
VBE.boot.default.req
VBE.boot.ghost.happy
VBE.boot.ghost.bereq_hdrbytes   
VBE.boot.ghost.bereq_bodybytes
```
Whats your varnish conf/ varnish version?

**Comment by Bilge** [comment]
`$ varnishd -V
varnishd (varnish-4.1.3 revision 5e3b6d2)`

**Comment by l2isbad** [comment]
The only values that changes for me are
```
bereq_hdrbytes
beresp_hdrbytes
beresp_bodybytes 
```
I think we need **response** (beresp_hdrbytes, beresp_bodybytes). Am i right?
Now it is in bits/seconds. Should i change to kilobits/second?

screenshot_20170115_000638

**Comment by l2isbad** [comment]
Now we have 
- all history cache hit rate
- current poll cache hit rate
screenshot_20170115_024631

**Comment by l2isbad** [comment]
Current dashboard menu looks like
screenshot_20170115_150321

**Backend response** 
 * reponse stats chart for every backend (beresp_hdrbytes, beresp_bodybytes)
works for
`VBE.webheadDummy(127.0.0.1,,8080)`
`VBE.boot.ghost.happy`

**Cache performance**
 * All history hit rate ratio (cache_hit, cache_miss, cache_hitpass)
 * Current poll hit rate ratio (cache_hit, cache_miss, cache_hitpass)

**Varnish statistics** (actually 'all other stuff' here; must be renamed)
 * Request rates (Client requests received, Sessions accepted, cache hit/miss/hitpass, backend conn success)
 * Transfer rates (Total response header bytes transmitted, Total response body bytes transmitted)
 * Sessions (all session stuff: accepted,dropped, failures, queued etc )
 * Uptime

**Backend health**
 * Backend health (conn success/not attempted/failures/reuses/recycles/retry)

**Memory usage**
 * Memory usage in megabytes (available, allocated)

**Problems summary**
 * Misbehavior (all session/backend/thread  fail/dropped/errors)

**Extra charts** (if enabled)
 * All other charts
 
I don't think i want to dive into varnish. If there are no more suggestions, I'll leave it as it is. It can be improved in the future

**Comment by l2isbad** [comment]
I think a good idea is to use [datadog](https://www.datadoghq.com/blog/top-varnish-performance-metrics/#toc-key-varnish-metrics) article to decide what metrics we need to monitor.

**Comment by LeeNX** [comment]
Just a few notes, not that I am an expert  
  
```xxxx-ab-ms.elections2016api``` is not a backend, but a VCL load name. If loaded from init scripts, normally called ```boot```. Only one VCL can be active at a time, but many can be loaded This lets you load a VCL and switch to a different VCL without reload your cache, pretty cool feature, but tricky.  
  
A second, thing, but I am thinking this more a packaging issue, if netdata is install from DEB/RPM, let's say and it tries to add it's user id to the varnish/apache group and varnish/apache is not installed yet, something might break. Adding a sub package for all the extra sub features, like nginx, apache or varnish would be better, because, if you add Varnish or Apache after installing netdata, netdata would have problems access restricted resources like logs. Not sure where to put the request or information, or help to test?

**Comment by l2isbad** [comment]
Ok, now plugin collects only [Key Varnish metrics](https://www.datadoghq.com/blog/top-varnish-performance-metrics/#toc-other-metrics-to-monitor)  + Backend reponse bytes + Memory usage
@LeeNX can you test it?

**Comment by wioxjk** [comment]
This is awesome!

**Comment by l2isbad** [comment]
@ktsaou this one is kinda ready. All key metrics from datadog article is present and it works for me (but i am using ~old version of varnish). Unfortunately not so many testers here. So we can merge it and update/optimize after.

**Comment by ktsaou** [comment]
merged.
Please update the wiki....

**Comment by jurgenhaas** [comment]
Very excited to see a Varnish plugin in the make. I've installed it and added the netdata user to the varnish group. On the console I can execute `sudo -u netdata varnishstat` successfully.

However, when I restart netdata service I don't see any Varnish charts and in the error log I see

```
2017-01-18 19:05:10: python.d ERROR: DISABLED: varnish/None
2017-01-18 19:05:10: python.d ERROR: varnish cannot find check() function or it thrown unhandled exception.
```

Is there anything I have to include in the config file?

**Comment by l2isbad** [comment]
@jurgenhaas 
my bad
https://github.com/firehol/netdata/pull/1568/files#diff-155f44a6ea57af82d59ed86f5f65b080R126

must be
`self.rgx_bck = self.rgx_bck[1]
`

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/pull/1589

**Comment by jurgenhaas** [comment]
Great, now it's working.

**Pull request merged**
