### PR TITLE
web_log fixes No 2

### PR DESCRIPTION
**Pull request by ktsaou**
1. make web_log alarms work above 30 reqs/minute
2. fix web_log plugin descriptions

cc: @l2isbad

### CODE REVIEW

**Comment by l2isbad** [comment]
👍

**Comment by l2isbad** [comment]
I use nginx as a caching reverse proxy.
screenshot_20170211_224829

A lot of 304 (NOT MODIFIED). ~ 30%
It's a successful response.

**Comment by ktsaou** [comment]
I fix the alarm though.

**Comment by ktsaou** [comment]
@l2isbad I see that timing is always an integer. It should not. 1ms + 2ms = 3ms / 2 request = 1.5 ms / request. So it should float.

Am I wrong?

**Comment by ktsaou** [comment]
netdata parses only integers at the plugin API, so we should pass 100x the value and add a divider of 100.

**Comment by ktsaou** [comment]
hm... I don't know how to do it... to complex python for me...

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/blob/master/python.d/web_log.chart.py#L306
https://github.com/firehol/netdata/blob/master/python.d/web_log.chart.py#L173

function for nginx_ext lambda x: x * 1000

avg is 
https://github.com/firehol/netdata/blob/master/python.d/web_log.chart.py#L325

**Comment by ktsaou** [comment]
ok. doing it now...

**Comment by ktsaou** [comment]
I guess these too: https://github.com/firehol/netdata/blob/master/python.d/web_log.chart.py#L218-L220
they are the dividers.

right?

**Comment by l2isbad** [comment]
Only for **apache**

10.4.0.181 - - [11/Feb/2017:23:24:14 +0900] "GET /themes/default/images/bg_2.png HTTP/1.0" 304 143 563 **231** "http://log.ttk-chita.lan/themes/default/main.css" "Mozilla/5.0 (Windows NT 6.1; rv:51.0) Gecko/20100101 Firefox/51.0"

Microseconds

**Comment by ktsaou** [comment]
Yes, but I need to make them x100. Yes?

**Comment by ktsaou** [comment]
could you please check it?

**Comment by l2isbad** [comment]
Why?
231 microseconds = 0.231 milliseconds
So divider is 1000

**Comment by ktsaou** [comment]
hm... I think the average calculation does not need it. It is already 100x...

**Comment by ktsaou** [comment]
> Why?
> 231 microseconds = 0.231 milliseconds
> So divider is 1000

ok, let's do this:

1. we will send to netdata microseconds
2. we will give netdata a divider of 1000, so that the user will see fractional milliseconds

To do this, what do we need to change?

**Comment by l2isbad** [comment]
> we will send to netdata microseconds
already done for apache (function for apache lambda x: x - no modification)

**Comment by l2isbad** [comment]
After * 1000 nginx timings in ms too.
The only problem i see is average.
https://github.com/firehol/netdata/blob/master/python.d/web_log.chart.py#L325
I think we need to add `round`

```python
 to_netdata['resp_time_avg'] = round(float(request_counter['sum']) / request_counter['count'])
```

**Comment by ktsaou** [comment]
So, I should add `* 1000` here: https://github.com/firehol/netdata/blob/master/python.d/web_log.chart.py#L306

and `round()` the average.

This is it?

**Comment by l2isbad** [comment]
No.
self.resp_time_func in case of nginx = lambda x: x * 1000

**Comment by ktsaou** [comment]
ok. so:

this https://github.com/firehol/netdata/blob/master/python.d/web_log.chart.py#L173 will become:

```python
 [lambda x: x, lambda x: x * 1000000, lambda x: x],
```

and this https://github.com/firehol/netdata/blob/master/python.d/web_log.chart.py#L306

```python
resp_time = self.resp_time_func(float(match_dict['resp_time']) * 1000)
```

these: https://github.com/firehol/netdata/blob/master/python.d/web_log.chart.py#L42-L44

```python
['resp_time_min', 'min', 'absolute', 1, 1000],
['resp_time_max', 'max', 'absolute', 1, 1000],
['resp_time_avg', 'avg', 'absolute', 1, 1000]
```

and these will be removed: https://github.com/firehol/netdata/blob/master/python.d/web_log.chart.py#L217-L220

right?

**Comment by ktsaou** [comment]
and the `round()` at the average: https://github.com/firehol/netdata/blob/master/python.d/web_log.chart.py#L325

**Comment by ktsaou** [comment]
removed line 306 (by bad).

**Comment by ktsaou** [comment]
did it, have a look.

**Comment by l2isbad** [comment]
haha @ktsaou i'm confused right now.

Lets assume..

nginx: 0.599 0.599 0.699

apache: 234 444 222

What data should should we pass to netdata?

**Comment by ktsaou** [comment]
ok,

## nginx

0.599 sec + 0.599 sec + 0.699 sec = 1.897 sec / 3 requests * 100000 usec per sec = 632333 usec

with a divider of 1000, netdata will show `632.333 ms`

## apache

234 usec + 444 usec + 222 usec = 900 usec / 3 requests = 300 usec

with a divider of 1000, netdata will show `0.3 ms`

Are you sure apache is `usec`?

**Comment by l2isbad** [comment]
> Are you sure apache is usec?

[Yeah](http://httpd.apache.org/docs/current/mod/mod_log_config.html).
`%D	The time taken to serve the request, in microseconds.`

**Comment by ktsaou** [comment]
so, this is it?
merge?

**Comment by l2isbad** [comment]
Ok. I think i got it.

 ['resp_time_max', 'max', 'absolute', 1, 1],

to

 ['resp_time_max', 'max', 'absolute', 1, 1000],

 self.definitions['response_time']['lines'][1][4] = 1000

to

 self.definitions['response_time']['lines'][1][4] = 1000000

 to_netdata['resp_time_avg'] = float(request_counter['sum']) / request_counter['count']

to

 to_netdata['resp_time_avg'] = float(request_counter['sum']) / request_counter['count'] * 1000

**Comment by ktsaou** [comment]
hm... this is not what we agreed :)

We said we will always send to netdata microseconds. So the divider should never change. It will always be 1000.

**Comment by ktsaou** [comment]
(we are very funny right now)

**Comment by ktsaou** [comment]
as it is in this PR now, it looks ok for nginx.
I don't have an apache handy. Can you test it?

**Comment by ktsaou** [comment]
nginx live at http://atlanta.my-netdata.io/#menu_web_log_nginx_netdata_submenu_timings

**Comment by l2isbad** [comment]
Well, all is good for apache too i'm sure. Nothing changes for apache 😄

**Comment by ktsaou** [comment]
ok, so apache values will be just pass through without `* 1000000`, so it is good.

I think the `web_log` plugin has an major issue. You are passing all metrics as `absolute`. This means all the metrics that say `per second` will be totally wrong when `update_every` is not 1.

The right way to do it, is to send incremental values to netdata. This way, netdata will always calculate the per second value to show (taking into account very detailed timings - at the microsecond level), no matter what `update_every` is.

**Comment by ktsaou** [comment]
update: send `incremental` dimensions to netdata.

**Comment by ktsaou** [comment]
So, I am merging this.
If you can turn the dimensions to `incremental` (and the values of course), please do so.

**Comment by ktsaou** [comment]
Live at the registry: http://registry.my-netdata.io/#menu_web_log_nginx_netdata

**Comment by l2isbad** [comment]
> This means all the metrics that say per second will be totally wrong when update_every is not 1.

Wait. why so?
Plugin pass to netdata data every update_every. All values are for update_every and they are right. What am i missing?

**Comment by ktsaou** [comment]
ok,

`absolute` means a gauge, something that does not have duration. netdata takes the number, and shows it. This used for example when we want to show the free space of disk, the used memory, the number of clients connected right now at a web server.

`incremental` means a counter, something that has a duration (the incremental difference to the previous value). netdata interpolates this using microsecond arithmetics to find the exact per second **rate**, independently of `update_every`. So, even if you set `update_every = 3`, all charts remain "per second". This is used for most of the metrics in netdata.

Since you pass all metrics as `absolute`, netdata will just pass them to the dashboard. Then, the following legend will be wrong if `update_every` is not 1:

image

In general, netdata is very precise in calculating rates. It does 2 things:

1. calculate the rate using microsecond durations
2. interpolate everything to second boundary

So, you should not calculate the rate at the plugin (i.e. please do not divide the values collected by `update_every` to fix this).

**Comment by l2isbad** [comment]
thx for the explanations!

**Comment by ktsaou** [comment]
To better understand the difference, let's assume this:

at 00:00:01.500 the `incremental` dimension gets the value 100.
at 00:00:02.500 the `incremental` dimension gets the value 200.

What should be the value shown for 00:00:02.000 ?

netdata does this right for `incremental` dimensions and shows 150. This is interpolation at second boundary.

**Comment by l2isbad** [comment]
Yeah. It's very clear now why we need incremental.

**Pull request merged**
