### PR TITLE
Add HipChat Server support

### PR DESCRIPTION
**Pull request by frei-style**
Add support for HipChat Server (self-hosted version of HipChat Cloud).

### CODE REVIEW

**Comment by ktsaou** [comment]
Hi. Thanks!

I would suggest to make it like this:

At `alarm-notify.sh`:

1. Add variable at the top: `HIPCHAT_SERVER="api.hipchat.com"`
2. Replace the string `api.hipchat.com` at the curl command with `${HIPCHAT_SERVER}`.

At `health_alarm_notify.conf`:

1. Add commented variable `# HIPCHAT_SERVER="api.hipchat.com"`

I don't think anything else is needed.

Since the message is generated statically, by the script, we should know upfront if it is `html` or `text`. I see the message has html elements in it, so I suggest to set it always to `html`.

How does that sound? I hope it is simpler.

**Comment by ktsaou** [comment]
perfect! Have you tested it? If yes, we can merge it.

**Comment by frei-style** [comment]
Thank you for your feedback. It's simpler indeed.
I tested it against a self-hosted server and it worked. I don't have a hipchat cloud account to test it.

**Comment by ktsaou** [comment]
perfect!

**Pull request merged**
