### PR TITLE
build: migrate to autotools

### PR DESCRIPTION
**Pull request by alonbl**
Please review, I have not tested it as I do not know what this application is doing.

It should be a good base, much better than the existing.

After reviewing this, please resolve all issues raise by --enable-pedantic, there are lots.

The startup script was not copied in existing, so I did not touch it, it it is required, there is lots of work there.

### CODE REVIEW

**Comment by ktsaou** [comment]
I get this error:

```txt
$ ./autogen.sh
autoreconf-2.69: Entering directory `.'
autoreconf-2.69: configure.ac: not using Gettext
autoreconf-2.69: running: aclocal --force -I m4
autoreconf-2.69: configure.ac: tracing
autoreconf-2.69: configure.ac: not using Libtool
autoreconf-2.69: running: /usr/bin/autoconf-2.69 --force
configure.ac:60: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf-2.69: /usr/bin/autoconf-2.69 failed with exit status: 1
```

**Comment by alonbl** [comment]
sorry! forgot to add this file.
fixed.

**Comment by ktsaou** [comment]
Help me with this. With:

```sh
./configure --prefix=/usr --sysconfdir=/etc
```

I see it is compiled like this:

```
-DCONFIG_DIR="\"/etc/netdata\"" -DLOG_DIR="\"/usr/var/log/netdata\"" -DPLUGINS_DIR="\"/usr/libexec/netdata/plugins.d\""
```

How do I change the LOG_DIR to `/var/log/netdata`?

**Comment by alonbl** [comment]
What most distros are doing is:
```
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var
```

**Comment by ktsaou** [comment]
Nice work!

Here are a few comments:

1. all the files `plugins.d` have to be installed in `libexec/netdata/plugins.d`

2. there must be another directory with name `libexec/netdata/charts.d` with all the contents of `charts.d`.

3. all the files in `conf.d` should be copied to `etc/netdata`.

4. the files in `web` have to be placed somewhere. I don't know where. These are private files used for netdata to serve its site. They are static html, json, js, css files. I see that I have not used a `WEB_DIR`. We should. In line 139 of web_client.c there is the statement: `if(!web_dir) web_dir = config_get("global", "web files directory", "web");`, it should be `if(!web_dir) web_dir = config_get("global", "web files directory", WEB_DIR);` and of course we should set WEB_DIR using `configure`.

5. the directory `var/log/netdata` has to be created during installation, or netdata will fail to start.

I plan to add a lot of files in the above directories, so it would be great is we don't have to configure each file by hand. So all files in these directories of the source should be copied to the final place.

**Comment by ktsaou** [comment]
Also, we need a `LIB_DIR`. I'll tell you where it needs to be set in the code.

**Comment by ktsaou** [comment]
Regarding `LIB_DIR`:

in line 182 of rrd.c it says:

```
if(!cache_dir) cache_dir = config_get("global", "database directory", "cache");
```

it has to become:

```
if(!cache_dir) cache_dir = config_get("global", "database directory", LIB_DIR);
```

and `LIB_DIR` should be set using `configure`.

**Comment by alonbl** [comment]
I do not understand what LIB_DIR is... do you refer to /var/lib?

**Comment by alonbl** [comment]
or maybe /var/cache?

**Comment by ktsaou** [comment]
> or maybe /var/cache?

ok, they are database files used to resume operations for the point it left. They can be deleted safely. netdata will just start from scratch.

So I don't know. either /var/lib or /var/cache seems appropriate.

**Comment by ktsaou** [comment]
@alonbl make it `CACHE_DIR`. I think at some point I'll have to use `LIB_DIR` for more long-living data.

**Comment by alonbl** [comment]
All done except:

> I plan to add a lot of files in the above directories, so it would be great is we don't have to configure each file by hand. So all files in these directories of the source should be copied to the final place.

in autotools environment it is not well practice to copy all files blindly, may cause left overs to be copied. when you truly have lots of files, ping me and I will find a solution.

**Comment by ktsaou** [comment]
Perfect!

In `charts.d` you install `Makefile.am`, which is not needed.
In `plugins.d` you missed the file `loopsleepms.sh.inc`.

@alonbl how should we handle permissions? netdata when run as root, will start as `nobody`, so all the directories and files should be owned by nobody. Shall we create a user for netdata, or what? How other packages handle this?

Also, for some reason, it now does not become a daemon and it logs on the console. I'll try to find what is happening...

**Comment by ktsaou** [comment]
Regarding daemon, you need to also define `NETDATA_DAEMON=1` by default. There is command line option to disable this, but it should be by default on.

**Comment by ktsaou** [comment]
Also, we need:

```
NETDATA_DAEMON=1
NETDATA_WITH_ZLIB=1
STORAGE_WITH_MATH=1
```

**Comment by alonbl** [comment]
fixed.

for the daemon, I expect this to be a command-line argument not a configuration option.

for the dependencies, default is usually off, package management can enable if required.

**Comment by alonbl** [comment]
permissions: package manager should set permission, see the spec, I've changed to nobody as owner, although this is not best practice, you should create your own user and own these by your own user.

**Comment by alonbl** [comment]
another option is to open the log then drop to nobody.

**Comment by ktsaou** [comment]
Actually, for these we could set `--disable-xxx` options in `configure`:

```
--disable-daemon
--disable-zlib
--disable-math
```

> for the daemon, I expect this to be a command-line argument not a configuration option.

Yes, but if `NETDATA_DAEMON` is not set, the code to become a daemon is not compiled at all.
A command line option to disable daemon is already there.

> another option is to open the log then drop to nobody.

This is what it already does, but it needs read/execute permission in libexec, /var/cache, /etc/netdata, etc.

> you should create your own user and own these by your own user.

I agree, how we do this?

**Comment by alonbl** [comment]
> Actually, for these we could set --disable-xxx options in configure:

ok, although in most cases the default should be to seek minimum deps.

> Yes, but if NETDATA_DAEMON is not set, the code to become a daemon is not compiled at all.
A command line option to disable daemon is already there.

so why is it optional?

> This is what it already does, but it needs read/execute permission in libexec, /etc/netdata, read/write on /var/cache, etc.

why do you need write permission into /etc, this is not best practice.

> I agree, how we do this?

done.

**Comment by ktsaou** [comment]
> so why is it optional?

You are right. I'll remove it from the source.

> why do you need write permission into /etc, this is not best practice.

This is what we need:

read/execute in /etc/netdata
read/execute in /libexec/netdata
read/execute in /share/netdata
read/execute/write in /var/log/netdata
read/execute/write in /var/cache/netdata

**Comment by ktsaou** [comment]
This is for directories.

**Comment by ktsaou** [comment]
Regarding NETDATA_WITH_ZLIB and STORAGE_WITH_MATH, do you want me to swap their meaning? i.e

NETDATA_WITHOUT_ZLIB
STORAGE_WITHOUT_MATH

?

**Comment by alonbl** [comment]
ok, I think all done.

**Comment by ktsaou** [comment]
Can I make a few commits to this pull request before merging it?

**Comment by alonbl** [comment]
> Can I make a few commits to this pull request before merging it?

not sure I understand what you mean.

also, please notice that your daemon implementation can be dropped in favour of daemon(3).

**Comment by ktsaou** [comment]
ok. Many many many thanks @alonbl !
You are perfect!

**Comment by alonbl** [comment]
> Regarding NETDATA_WITH_ZLIB and STORAGE_WITH_MATH, do you want me to swap their meaning?

no... I prefer positive terms.

**Comment by ktsaou** [comment]
But how the distributions will now the default? The default should be with zlib and with math.

**Comment by alonbl** [comment]
> But how the distributions will now the default? The default should be with zlib and with math.

I enabled this in configure as default per your request.

distributions usually explicitly enable features, refer to the spec file.

**Comment by ktsaou** [comment]
> distributions usually explicitly enable features, refer to the spec file.

I see! Thanks!

So, I can disable by default the nfacct plugin by just removing the relative line from the spec?

**Comment by alonbl** [comment]
> So, I can disable by default the nfacct plugin by just removing the relative line from the spec?

yes, and you probably want to remove:
```
BuildRequires:  libmnl-devel
BuildRequires:  libnetfilter_acct-devel
Requires:       libmnl
Requires:       libnetfilter_acct
```

but I won't bother much, as if it goes into fedora it will probably be modified anyway.

I can also create a subpackage for this plugin, so it will be optionally installed.

**Comment by ktsaou** [comment]
No its ok.

I need to write some code so that plugins can either be compiled into netdata, or as standalone plugins. This is due to permissions. The netdata daemon runs without privileges, but some plugins need to be root. So, instead of building them into the daemon they could be build external plugins, much like the `apps.plugin`.

I haven't write this yet though.

So the requirements will always be there. The compilation will change.

**Comment by alonbl** [comment]
if you want it to be optional, you must build it as separate plugin.

**Comment by ktsaou** [comment]
@alonbl if `make install` is run as root, is it ok to give apps.plugin the setuid bit and also chown the /usr/share/netdata and /var/cache/netdata directories?

**Comment by alonbl** [comment]
usually you do not do that automatically, as setuid root is something people need to approve explicitly, downstream distro will do this for you, look at the spec for example.

today there are other methods of establish privilege escalation, you should look into one of these, see capabilities(7), or even executing a root daemon and communicate using usock.

**Comment by alonbl** [comment]
ok, I see sudo is doing this, no reason why we won't.

**Comment by alonbl** [comment]
https://github.com/firehol/netdata/pull/18
https://github.com/firehol/netdata/pull/19

**Pull request merged**
