### PR TITLE
Optimize counting of recusive pins

### PR DESCRIPTION
**Pull request by pjz**
Avoid building (potentially large) unneeded list of strings

### CODE REVIEW

**Comment by ktsaou** [comment]
@pjz I haven't update you on netdata CLA yet. So, since you are here, could you please sign the netdata CLA so that we license netdata according to the requirements of CNCF?

To sign, you just need to add your username and name to CONTRIBUTORS.md

**Comment by paulfantom** [comment]
@pjz please rebase

**Comment by pjz** [comment]
@ktsaou was putting my name on the CONTRIBUTORS.md enough? or does something else need to be done?

**Comment by ktsaou** [comment]
> @ktsaou was putting my name on the CONTRIBUTORS.md enough? or does something else need to be done?

this is fine.

So, merge?

**Comment by ktsaou** [comment]
merged! It was ok.

**Pull request merged**
