### PR TITLE
Fail2ban plugin

### PR DESCRIPTION
**Pull request by l2isbad**
One more to security section.
Simple plugin to monitor fail2ban logs
It parses conf file to find all enabled jails then parses log file to count all bans for all active jails
You can exclude certain jails via plugin conf file

### CODE REVIEW

**Comment by ktsaou** [comment]
nice!

I haven't tested this. Is it ok to be merged?
Please add it to the wiki too...

**Comment by l2isbad** [comment]
it works very well on version under 0.9 (tested 0.8.13-1 on debian8). 
But reading the configuration file, I noticed  fail2ban "was heavily refactored in 0.9" and now there is a 0.10 version on github. 
I quick review changes and the only important for plugin is recommendation to separate .conf files under jail.d directory (in this case jail autodetection will fail).
i think its ok to leave it as it is. I will add fail2ban to Makefile and then its ready

**Comment by l2isbad** [comment]
I still need some testing.

**Comment by ktsaou** [comment]
nice! merge?

**Comment by l2isbad** [comment]
yes

**Comment by ktsaou** [comment]
merged! you are the best!

**Pull request merged**
