### PR TITLE
Isc dhcpd plugin

### PR DESCRIPTION
**Pull request by l2isbad**
Almost all 'soho' servers has dhcp server installed. So the plugin is really needed.

The only you need is to set
- leases_path
- pools (in CIDR format)

**Charts:**
- Utilization in percent (aggregate; all pools in one chart)
- Leases (individual chart for every pool in the list with number of current active leases)
- Parse statistics (parse time, dhcpd.leases file size)

The plugin uses ipaddress module (which is built-in since python 3.3)

Tested on my debian 8. Works well (unfortunately i have no a big nice isc dhcp instance, mine is 100% soho.).

Its strange but its more accurate then `dhcp-lease-list` script from isc-dhcp-server package (if i understand man dhcpd.leases correctly which im not 100% sure).

Also default update_every is set to 60 seconds. Dont see any reason why we need a lower value as default here.

### CODE REVIEW

**Comment by l2isbad** [comment]
The main problem i see is the size of dhcpd.leases file. 
If its poorly configured instance - using with no business reason a very short lease time, large number of clients  or isc dhcpd version that is not doing clean-up dhcpd.leases file for a some reason (should do once an hour) it can be large.

Aslo seems no chance to use .seek method because of internal dhcpd clean-up algorithm.

As a workaround i can check time to parse a file with regex and if its over some value disable plugin 

Anyway i am a very new to programming and any suggestions are welcome.

**Comment by l2isbad** [comment]
Well i made some improvements. Now its 2x faster. will commit later.

**Comment by l2isbad** [comment]
Way better now!

**Comment by l2isbad** [comment]
Plugin is ok now. I like it. And i am 100% sure there is still room for improvement but need active isc dhcp users reviews.

**Comment by l2isbad** [comment]
Hm i just got the idea to monitor dhcpd.leases file size and add this value to Parse statistics chart..

**Comment by l2isbad** [comment]
ok i am done

**Comment by ktsaou** [comment]
@l2isbad could you please add this module to https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata ?

I merged it but we forgot to add it there...

**Comment by ktsaou** [comment]
I am trying to configure this for my setup and I get:

```
# ./plugins.d/python.d.plugin debug 1 isc_dhcpd
2016-12-26 10:49:55:  INFO: Using python v2
2016-12-26 10:49:55: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
2016-12-26 10:49:55: python.d INFO: MODULES_DIR='/data/src/netdata-ktsaou.git/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['isc_dhcpd']
2016-12-26 10:49:55: python.d DEBUG: isc_dhcpd: loading module configuration: '/etc/netdata/python.d/isc_dhcpd.conf'
2016-12-26 10:49:55: python.d DEBUG: isc_dhcpd: reading configuration
2016-12-26 10:49:55: python.d DEBUG: isc_dhcpd/leases: job added
2016-12-26 10:49:55: python.d DEBUG: all job objects [<Service(leases, initial daemon)>]
2016-12-26 10:49:55: python.d ERROR: isc_dhcpd_leases Pools configurations is incorrect
2016-12-26 10:49:55: python.d ERROR: isc_dhcpd_leases check() failed - disabling job
2016-12-26 10:49:55: python.d ERROR: DISABLED: isc_dhcpd/leases
2016-12-26 10:49:55: python.d DEBUG: overridden job names: []
2016-12-26 10:49:55: python.d DEBUG: all remaining job objects: []
2016-12-26 10:49:55: python.d FATAL: no more jobs
DISABLE
```

It would be nice if the error message could state why the pools configurations is incorrect, i.e. what is exactly the problem...

**Comment by ktsaou** [comment]
Well, I can't make work.

I first added `as e` to the exception, and found the error message:

```
./plugins.d/python.d.plugin debug 1 isc_dhcpd
2016-12-26 12:08:10:  INFO: Using python v2
2016-12-26 12:08:10: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
2016-12-26 12:08:10: python.d INFO: MODULES_DIR='/data/src/netdata-ktsaou.git/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['isc_dhcpd']
2016-12-26 12:08:10: python.d DEBUG: isc_dhcpd: loading module configuration: '/etc/netdata/python.d/isc_dhcpd.conf'
2016-12-26 12:08:10: python.d DEBUG: isc_dhcpd: reading configuration
2016-12-26 12:08:10: python.d DEBUG: isc_dhcpd: job added
2016-12-26 12:08:10: python.d DEBUG: all job objects [<Service(None, initial daemon)>]
2016-12-26 12:08:10: python.d ERROR: isc_dhcpd Pools configurations is incorrect'10.11.12.0/24' does not appear to be an IPv4 or IPv6 network
2016-12-26 12:08:10: python.d ERROR: isc_dhcpd check() failed - disabling job
2016-12-26 12:08:10: python.d ERROR: DISABLED: isc_dhcpd/None
2016-12-26 12:08:10: python.d DEBUG: overridden job names: []
2016-12-26 12:08:10: python.d DEBUG: all remaining job objects: []
2016-12-26 12:08:10: python.d FATAL: no more jobs
DISABLE
```

I searched for this error message and found that it is about unicode encoding.

Interesting is that it works on python 3:

```
# python3 ./plugins.d/python.d.plugin debug 1 isc_dhcpd
2016-12-26 12:07:47:  INFO: Using python v3
2016-12-26 12:07:47: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
2016-12-26 12:07:47: python.d INFO: MODULES_DIR='/data/src/netdata-ktsaou.git/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['isc_dhcpd']
2016-12-26 12:07:47: python.d DEBUG: isc_dhcpd: loading module configuration: '/etc/netdata/python.d/isc_dhcpd.conf'
2016-12-26 12:07:48: python.d DEBUG: isc_dhcpd: reading configuration
2016-12-26 12:07:48: python.d DEBUG: isc_dhcpd: job added
2016-12-26 12:07:48: python.d DEBUG: all job objects [<Service(None, initial daemon)>]
2016-12-26 12:07:48: python.d INFO: isc_dhcpd Plugin was started succesfully
2016-12-26 12:07:48: python.d INFO: CHECKED OK: isc_dhcpd
2016-12-26 12:07:48: python.d DEBUG: overridden job names: []
2016-12-26 12:07:48: python.d DEBUG: all remaining job objects: [<Service(None, initial daemon)>]
CHART isc_dhcpd.parse_time '' 'Parse time' ms 'Parse stats' isc_dhcpd.parse line 60000 60
DIMENSION ptime time absolute 1 1
CHART isc_dhcpd.leases_size '' 'dhcpd.leases file size' kilobytes 'Parse stats' isc_dhcpd.lsize line 60001 60
DIMENSION lsize size absolute 1 1
CHART isc_dhcpd.utilization '' 'Pools utilization' 'used %' Utilization isc_dhcpd.util line 60002 60
DIMENSION ut_10.11.12.0/24 10.11.12.0/24 absolute 1 1
DIMENSION ut_10.11.13.0/24 10.11.13.0/24 absolute 1 1
DIMENSION ut_10.11.14.0/24 10.11.14.0/24 absolute 1 1
DIMENSION ut_192.168.2.0/24 192.168.2.0/24 absolute 1 1
CHART isc_dhcpd.total '' 'Total all pools' leases Utilization isc_dhcpd.total line 60003 60
DIMENSION total leases absolute 1 1
CHART isc_dhcpd.leases_10.11.12.0/24 '' 'Active leases' leases Pools isc_dhcpd.lease area 60004 60
DIMENSION le_10.11.12.0/24 10.11.12.0/24 absolute 1 1
CHART isc_dhcpd.leases_10.11.13.0/24 '' 'Active leases' leases Pools isc_dhcpd.lease area 60005 60
DIMENSION le_10.11.13.0/24 10.11.13.0/24 absolute 1 1
CHART isc_dhcpd.leases_10.11.14.0/24 '' 'Active leases' leases Pools isc_dhcpd.lease area 60006 60
DIMENSION le_10.11.14.0/24 10.11.14.0/24 absolute 1 1
CHART isc_dhcpd.leases_192.168.2.0/24 '' 'Active leases' leases Pools isc_dhcpd.lease area 60007 60
DIMENSION le_192.168.2.0/24 192.168.2.0/24 absolute 1 1

CHART netdata.plugin_pythond_isc_dhcpd '' 'Execution time for isc_dhcpd plugin' 'milliseconds / run' python.d netdata.plugin_python area 145000 1
DIMENSION run_time 'run time' absolute 1 1

2016-12-26 12:07:48: python.d DEBUG: created charts for isc_dhcpd
2016-12-26 12:07:48: python.d DEBUG: isc_dhcpd starting data collection - update frequency: 1.0  retries allowed: 60
2016-12-26 12:07:48: python.d DEBUG: isc_dhcpd sleeping for 0.9298379421234131 secs to reach frequency of 1.0 secs, now: 1482746868.070162  next: 1482746869.0  penalty: 0
BEGIN isc_dhcpd.parse_time 0
SET ptime = 3
END 
BEGIN isc_dhcpd.leases_size 0
SET lsize = 36
END 
BEGIN isc_dhcpd.utilization 0
SET ut_10.11.12.0/24 = 1
SET ut_10.11.13.0/24 = 0
SET ut_10.11.14.0/24 = 0
SET ut_192.168.2.0/24 = 0
END 
BEGIN isc_dhcpd.total 0
SET total = 3
END 
BEGIN isc_dhcpd.leases_10.11.12.0/24 0
SET le_10.11.12.0/24 = 2
END 
BEGIN isc_dhcpd.leases_10.11.13.0/24 0
SET le_10.11.13.0/24 = 0
END 
BEGIN isc_dhcpd.leases_10.11.14.0/24 0
SET le_10.11.14.0/24 = 1
END 
BEGIN isc_dhcpd.leases_192.168.2.0/24 0
SET le_192.168.2.0/24 = 0
END 

BEGIN netdata.plugin_pythond_isc_dhcpd 0
SET run_time = 25
END
```

So, the plugin works only in python 3.

**Comment by l2isbad** [comment]
it works with py2-ipaddress installed
py2-ipaddress (3.4.1)          - Python 2.6 backport of 3.4's ipaddress module
  INSTALLED: 3.4.1 (latest)

**Comment by ktsaou** [comment]
Yes, I have this installed, but still it does not work.

I think I fixed it though. I am making a PR now.

**Comment by l2isbad** [comment]
> could you please add this module to 

ofc. will do later
Its strange but there is no problem on my python2 servers (deb 7, 8)

**Pull request merged**
