### PR TITLE
Fixed multiple issues with PID file

### PR DESCRIPTION
**Pull request by pavel**
Pull request fixes several issues with "service" scripts.

Issues fixed:
* `system/netdata-openrc.in` - OpenRC initscript's `start_post` was working, but `stop_post` function was not stopping a service.
*  `system/netdata.service.in` - service's start was not working.

**Issues' cause**:
the program fails to create a PID file if a path to the PID file contains non-existent folders.

### CODE REVIEW

**Comment by ktsaou** [comment]
Probably it would be better to use `/var/run/netdata.pid` to avoid the directory creation.
Previously, the daemon was creating the directory by itself, but the distribution packagers didn't like it and asked for its removal (so these scripts broke).

**Comment by pavel** [comment]
Ok, let me fix the path to `/var/run/netdata.pid` in this pull request.

**Comment by ktsaou** [comment]
nice!
Shall I merge it, or you plan something else?

**Comment by pavel** [comment]
Wait up a sec. I'll run some tests first. I'll let you know, when I'm done. Thanks.

**Comment by pavel** [comment]
Please, merge. It works for systemd. Though I can't make Gentoo to work anymore (even with previous versions of OpenRC initscript). Probably doing something wrong.

**Comment by ktsaou** [comment]
ok, I'll have a look at openrc script.

**Comment by ktsaou** [comment]
I think I solved it with this: https://github.com/firehol/netdata/commit/5860142b1caaf17ec8b5402fb7a53bfd5cfef889

if not started as root, cannot save its pid file in `/run`.
So I let it start as root. Netdata will switch to its own user after started.

**Comment by pavel** [comment]
@ktsaou Yep, works for me now.

**Pull request merged**
