### PR TITLE
container / cgroup improvements

### LINKED ISSUE #1571: How do I exclude certain NICs from interface_last_collected_secs alarm?
I keep getting alarms emailed to me about `net.vethXXXXXXX` interfaces (Docker pseudo-devices) being critical.

> interface last collected secs = 66 seconds ago

I think this is coming from the interface_last_collected_secs template, but it is unclear from the `health.d/net.conf` config or the documentation how to disable this alarm for certain interfaces, since neither seem to mention exclusions.

I would like to be able to specify an exclusion pattern that can match `net.veth*` or similar.

### PR DESCRIPTION
**Pull request by ktsaou**
1. fixed a minor memory leak in cgroups (3 strings were duplicated, without being fred)

2. cgroups internal defaults for matching which directories are evaluated and which cgroups are enabled by default, are now configuration options:

  ```
[plugin:cgroups]
	# disable by default cgroups matching =  lxc docker libvirt qemu systemd  system system.slice  machine machine.slice  user user.slice  init.scope  *.swap  *.slice  *.user  *.mount  *.service  *.partition  */ns 
	# disable by default cgroup paths matching =  system.slice  system  systemd  user.slice  user  init.scope  *-qemu 
```

3. simple patterns now support asterisks in the middle of strings (any number of them)

4. simple patterns now support negative matches

5. cgroups can now have a different `update every`, compared to the rest of netdata

6. several optimizations to allow faster cgroup chart updates

7. alarm templates can now match patterns of chart families; fixes #1571 

8. netdata now monitors **systemd services** through cgroups!

   **Check the 1st comment below for instructions**

### CODE REVIEW

**Comment by ktsaou** [comment]
Well, I was planning to release netdata v1.5 today, but I think I'll have to postpone it for a week.

This PR has a lot of significant changes.

1. The key change is that netdata now monitors **systemd services**. I have added only 2 charts (cpu, ram), but it is now trivial to add the rest (disk, swap, etc). Example:

   image


2. Internal cgroup heuristics are now configuration options. This means cgroups can now be configured from netdata.conf to monitor whatever each user wants.

  ```
[plugin:cgroups]
	# cgroups plugin resource charts = yes
	# update every = 1
	# check for new cgroups every = 10
	# enable cpuacct stat = auto
	# enable cpuacct usage = auto
	# enable memory = auto
	# enable blkio = auto
	# enable systemd services = yes
	# path to /sys/fs/cgroup/cpuacct = /sys/fs/cgroup/cpu,cpuacct
	# path to /sys/fs/cgroup/blkio = /sys/fs/cgroup/blkio
	# path to /sys/fs/cgroup/memory = /sys/fs/cgroup/memory
	# path to /sys/fs/cgroup/devices = /sys/fs/cgroup/devices
	# max cgroups to allow = 500
	# max cgroups depth to monitor = 0
	# enable new cgroups detected at run time = yes
	# disable by default cgroups matching =  *.mount  *.partition  *.service  *.slice  *.swap  *.user  /  /docker  /init.scope  /libvirt  /lxc  /lxc/*/ns  /machine  /machine.slice  /qemu  /system  /system.slice  /systemd  /user  /user.slice 
	# do not search for cgroups in paths matching =  *-qemu  /init.scope  /system  /systemd  /user  /user.slice 
	# script to get cgroup names = /usr/libexec/netdata/plugins.d/cgroup-name.sh
	# do not run script to rename cgroups matching =  /  *.mount  *.partition  *.scope  *.service  *.slice  *.swap  *.user 
	# cgroups to match as systemd services =  !/system.slice/*/*.service /system.slice/*.service 
```

3. netdata has a very fast **simple pattern** mechanism embedded. No regex, something like shell asterisks. I have added this to diskspace matching, cgroups filtering, alarm templates filtering based on chart families (check #1571). You can also experiment from command line: `netdata -W simple-pattern`.


I need testers guys. My main concern is that I translated all internal netdata heuristics for filtering cgroups into configuration options. Have I done it right?

netdata is stable. no crashes. static code analysis passes it without any findings, so it is good to go if the default config is also good.

cc: @l2isbad @vlvkobal @jurgenhaas

**Comment by ktsaou** [comment]
cc: @ovizii have a look at this.

**Comment by ktsaou** [comment]
tested arch, gentoo, ubuntu 16.10, fedora 25, AMI... all good so far...

**Comment by jurgenhaas** [comment]
I've installed it on a number of Ubuntu 12, 14 and 16 hosts and all is looking good. At least it keeps working like before.

What I'm missing though are the new charts for systemd services. Is there anything I need to configure?

What I'm seeing in the log is like this:

```
2017-01-15 18:16:09: cgroup-name.sh: INFO: cgroup '_' is called '_'
2017-01-15 18:16:09: cgroup-name.sh: INFO: cgroup 'init.scope' is called 'init.scope'
2017-01-15 18:16:09: cgroup-name.sh: INFO: cgroup 'system.slice' is called 'system.slice'
2017-01-15 18:16:09: cgroup-name.sh: INFO: cgroup 'system.slice_dbus.service' is called 'system.slice_dbus.service'
2017-01-15 18:16:09: cgroup-name.sh: INFO: cgroup 'system.slice_sys-kernel-config.mount' is called 'system.slice_sys-kernel-config.mount'
2017-01-15 18:16:09: cgroup-name.sh: INFO: cgroup 'system.slice_cron.service' is called 'system.slice_cron.service'
2017-01-15 18:16:09: cgroup-name.sh: INFO: cgroup 'system.slice_rc-local.service' is called 'system.slice_rc-local.service'
2017-01-15 18:16:09: cgroup-name.sh: INFO: cgroup 'system.slice_apport.service' is called 'system.slice_apport.service'
2017-01-15 18:16:09: cgroup-name.sh: INFO: cgroup 'system.slice_systemd-modules-load.service' is called 'system.slice_systemd-modules-load.service'
2017-01-15 18:16:09: cgroup-name.sh: INFO: cgroup 'system.slice_ifup_eth0.service' is called 'system.slice_ifup_eth0.service'
```

but no charts.

**Comment by ktsaou** [comment]
Hm... this log does not match this PR. Are you sure you installed the ktsaou/netdata repo?

---
Sent from my iphone.

15 Ιαν 2017, 20:24, ο/η Jürgen Haas <notifications@github.com> έγραψε:

**Comment by jurgenhaas** [comment]
Oh sorry, I thought it was merged to firehol/netdata already. I went for the wrong one then, thanks for the hint. I'll re-deploy tomorrow.

**Comment by jurgenhaas** [comment]
Just re-deployed everything from https://github.com/ktsaou/netdata.git with no luck, don't see any systemd services charts.

**Comment by ktsaou** [comment]
@jurgenhaas it needs systemd for this feature.

On ubuntu 16.04 LTS, I see it works: http://azure-west-eu.my-netdata.io/

**Comment by ktsaou** [comment]
On Debian 8, systemd does not expose any usable performance metrics for its services.

**Comment by ktsaou** [comment]
I updated the 1st comment above to show the systems the new charts appear.

@jurgenhaas I have added also information on how to configure systemd to enable these charts, on systems they are not enabled by default.

**Comment by ktsaou** [comment]
ok, I've spend the entire day testing this on all kinds of systems.
So, it is time to merge it.

btw, I added disk charts for systemd services too.

**Comment by ktsaou** [comment]
merged!

**Pull request merged**
