### PR TITLE
use pidfile to send HUP to netdata via logrotate;

### LINKED ISSUE #4020: Problem with logrotate config (PID discovery)
Greetings!

I've discovered a problem with current logrotate config behaviour on a server with a bunch of LXD containers. Here's the problematic line: https://github.com/firehol/netdata/blob/6832ce444d2637173a6bac436805ca9e55b84fc1/system/netdata.logrotate.in#L10

When executed on host system, pidof grabs all the PID's of netdata-slaves running in LXC-containers. For example:

```
~# ps aux | grep '[n]etdata -P'
100000     330  0.4  0.0 119112  4552 ?        Sl   Jul26  27:23 /usr/sbin/netdata -P /var/run/netdata.pid
root       832  2.6  0.4 360888 132544 ?       Sl   Jun20 1530:03 /usr/sbin/netdata -P /var/run/netdata.pid
100000   11231  0.7  0.0 124032 17492 ?        Sl   Jul05 279:17 /usr/sbin/netdata -P /var/run/netdata.pid
100000   13089  0.0  0.0  97648  1164 ?        Sl   Mar30 173:25 /usr/sbin/netdata -P /var/run/netdata.pid
100000   14501  0.5  0.0 111836  4036 ?        Sl   Jul15 114:58 /usr/sbin/netdata -P /var/run/netdata.pid
100000   15821  0.5  0.0 124280  5420 ?        Sl   Jul05 221:28 /usr/sbin/netdata -P /var/run/netdata.pid
100000   23054  0.5  0.0 111432  4356 ?        Sl   Jul05 200:56 /usr/sbin/netdata -P /var/run/netdata.pid
100000   29453  0.0  0.0 121936  2356 ?        Sl   Jun20  41:44 /usr/sbin/netdata -P /var/run/netdata.pid
100000   29691  0.6  0.0 123596  4812 ?        Sl   Jul05 224:10 /usr/sbin/netdata -P /var/run/netdata.pid
100000   30283  0.5  0.0 119368  4344 ?        Sl   Jul04 188:30 /usr/sbin/netdata -P /var/run/netdata.pid
100000   32069  0.5  0.0 111732  5424 ?        Sl   Jul05 190:12 /usr/sbin/netdata -P /var/run/netdata.pid

~# pidof netdata
32069 30283 29691 29453 23054 15821 14501 13089 11231 832 330
```

So, a SIGHUP is being sent to a series of wrong PID's, in addition to the needed one. As a solution, one can consider adding a -c option to pidof (from man):

>        -c     Only return process ids that are running with the same root directory.  This option is ignored for non-root users, as they will be unable to check the cur‐
>               rent root directory of processes they do not own.

Here's the result:

```
~# ps aux | grep '[n]etdata -P'
100000     330  0.4  0.0 119112  4552 ?        Sl   Jul26  27:23 /usr/sbin/netdata -P /var/run/netdata.pid
root       832  2.6  0.4 360888 132544 ?       Sl   Jun20 1530:03 /usr/sbin/netdata -P /var/run/netdata.pid
100000   11231  0.7  0.0 124032 17492 ?        Sl   Jul05 279:17 /usr/sbin/netdata -P /var/run/netdata.pid
100000   13089  0.0  0.0  97648  1164 ?        Sl   Mar30 173:25 /usr/sbin/netdata -P /var/run/netdata.pid
100000   14501  0.5  0.0 111836  4036 ?        Sl   Jul15 114:58 /usr/sbin/netdata -P /var/run/netdata.pid
100000   15821  0.5  0.0 124280  5420 ?        Sl   Jul05 221:29 /usr/sbin/netdata -P /var/run/netdata.pid
100000   23054  0.5  0.0 111432  4356 ?        Sl   Jul05 200:56 /usr/sbin/netdata -P /var/run/netdata.pid
100000   29453  0.0  0.0 121936  2356 ?        Sl   Jun20  41:44 /usr/sbin/netdata -P /var/run/netdata.pid
100000   29691  0.6  0.0 123596  4812 ?        Sl   Jul05 224:10 /usr/sbin/netdata -P /var/run/netdata.pid
100000   30283  0.5  0.0 119368  4344 ?        Sl   Jul04 188:30 /usr/sbin/netdata -P /var/run/netdata.pid
100000   32069  0.5  0.0 111732  5424 ?        Sl   Jul05 190:12 /usr/sbin/netdata -P /var/run/netdata.pid

~# pidof -c netdata
832
```

Could you please fix this in future releases?

### PR DESCRIPTION
**Pull request by ktsaou**
fixes #4103
fixes #4020

netdata.service and netdata openrc init where not using `/var/run/netdata.pid`, but `/run/netdata.pid`. This PR fixes them to use the universal ones (`/var/run/netdata.pid`).

logrotate was using `pidof netdata` to send HUP to netdata. Now it uses the pid file.

### CODE REVIEW

**Comment by paulfantom** [comment]
lgtm

**Comment by ktsaou** [comment]
Could you please check again? I had to unify all the start up files, so that they will all use the same path of the pid. A few of them were using `/var/run/netdata.pid`, others `/run/netdata/netdata.pid`, others `/var/run/netdata/netdata.pid`.

Also, since netdata starts with root privileges (on init.d) and then it drops privileges, it may not be able to remove the pidfile. I added code on all startup methods to rm the pidfile if it exists after netdata exits. Generally, this should not happen (netdata chowns the pidfile), but still I have encountered this many times. So, better be safe than sorry.

**Comment by paulfantom** [comment]
still looks good.

**Comment by ktsaou** [comment]
@Ferroin has a look too, please.
Do you see anything wrong in this PR?

**Comment by ktsaou** [comment]
merged. thank you!

**Pull request merged**
