### PR TITLE
Update dovecot.chart.py

### PR DESCRIPTION
**Pull request by justohall**
Add two extra charts with data from sessions chart. 
New charts are activesessions and logins.

### CODE REVIEW

**Comment by ktsaou** [comment]
thanks
@paulfantom could you please check this?

**Comment by paulfantom** [comment]
Looks ok, merging.

**Comment by ktsaou** [comment]
@paulfantom is the `sessions` chart useful any more? I think the same metrics are assigned to multiple charts.

**Comment by ktsaou** [comment]
yes I understood that and it is nice, however you added 2 charts without removing the old chart.

**Comment by justohall** [comment]
Ah, okay sorry about that. Didn't want to remove a chart that people might be using. I will put in a PR to resolve that. Thank you

**Pull request merged**
