### PR TITLE
Added cgroup name processing for Proxmox LXC and VM

### PR DESCRIPTION
**Pull request by efaden**

### CODE REVIEW

**Comment by ktsaou** [comment]
have a look at codacy suggestion. They are optimal...

**Comment by ktsaou** [comment]
Can you handle the case when netdata does not have access to read the files, and instruct the user to add netdata to www-data group? It will save some documentation and github issues...

**Comment by ktsaou** [comment]
seems good!
merge?

**Comment by efaden** [comment]
Seems good to me.

**Comment by ktsaou** [comment]
merged! thanks!

**Pull request merged**
