### PR TITLE
do not make executable netdata.service

### PR DESCRIPTION
**Pull request by ktsaou**

### CODE REVIEW

**Comment by ktsaou** [comment]
@philwhineray check this.
Travis now fails.
Can you check the travis log or you want me to paste it here?

**Comment by philwhineray** [comment]
Strange. The decryption command is failing. I am not sure why that would be.

I am looking into it, perhaps it is because the PR comes from a different repo.

The decryption step is only used for the deployment part, so can probably make this non-fatal anyway.

**Comment by philwhineray** [comment]
OK, [this page](https://docs.travis-ci.com/user/environment-variables/) makes it clear:

"""
Before adding sensitive data such as API credentials to your .travis.yml you need to encrypt it. Encrypted variables are not available to untrusted builds such as pull requests coming from another repository.
"""

I will rework the travis script so it should allow remote PRs - not that these will not deploy anything though, so a release will have to be done by PR from within the main repo or by directly pushing an update.

**Comment by ktsaou** [comment]
Thanks! I would appreciate a quick fix that will allow PRs to be checked by travis in the mean time.

**Comment by philwhineray** [comment]
They are probably one and the same. I have created a PR. Let's see if it builds. If it does, we merge it and provided it deploys to the website everything is good.

**Comment by philwhineray** [comment]
There are still errors. I will sort them now.

**Comment by philwhineray** [comment]
OK it took a few attempts to get everything right but PR #1388 now resolves the remote pull problem. I will merge it now. You will need to get the changes into this PR for it to work.

I will check later if the deployment of master-branch builds to the website is OK. Hopefully it will be, but if not I will create an extra PR, since this is not so urgent.

As far as the Travis logs themselves go, I believe they are public (because the repo is public), so there shouldn't be a need to copy/paste them unless we want a permanent record in an issue.

**Comment by philwhineray** [comment]
OK, I have sorted the problems with master now - everything should build regardless of origin. The master branch is deploying to the website unsigned directory directly from travis after a successful build.

Let me know if you have any other problems - it might be tomorrow before I have some more time though.

**Pull request merged**
