### PR TITLE
unified error logging; disk stats and virtual and remote disks

### LINKED ISSUE #605: Disk space utilization for mount is incorrect
I have mounted hard disk which has one partition over the whole drive (sda).
This partition is ext4 formatted

When I look at netdata it gives this:
image

but `df -h` gives the following: 
/dev/sda1       275G   43G  219G  17% /mnt/fts300gb

edit: inodes from netdata match the output of `df -i`
edit2: available space of /mnt/fts300gb seems to match used space of `/` (maybe coincidence?)

my id if needed: 950c6083-0fc1-4da3-87c4-dde194ee526f
how can I give you proper debug information?

### LINKED ISSUE #747: disk space reporting for mounted disks without a block device
Currently for netdata to report disk space utilization, the disks have to be block devices.

We have to monitor disk space for non-block devices too.

### LINKED ISSUE #1144: nut.chart.sh
Hi,

My NUT installation uses SSL to establish connections. When using the `upsc` command you'll get a warning printed to `stderr`
```
# upsc -l
Init SSL without certificate database
Connecting in SSL to 'localhost' (no certificate name specified)
Do not intend to authenticate server localhost
SSL handshake done successfully with server localhost
Connected to localhost in SSL
Certificate verification is disabled
[... list of declared UPSes ...]
```

This is harmless for the charts collection but these messages to `stderr` flood the `error.log` which is an inconvenience. The fix is pretty simple, just add a `2>/dev/null` to `nut_get_all()` and `nut_get()` and the `error.log` gets clean again.

### LINKED ISSUE #1145: Include runtime dependencies in RPM spec file
According to your Installation documentation, the following two packages are required to be installed in order for netdata to run, however the spec file does not include these packages as Requirements to install netdata from RPM:

package|description
:-----:|-----------
`libuuid`|part of `util-linux` for GUIDs management
`zlib`|gzip compression for the internal netdata web server

### LINKED ISSUE #1148: Disk space health monitoring false criticals
I have a mounted usb disk on my Raspberry Pi, it's a 2TB disk as shown from this 'df -h' line:
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       1.8T  268G  1.5T  16% /mnt/external

I think it's the TB size that is messing with netdata because netdata seems to think that the disk is 85% full which it clearly isn't. When I write large files to the drive I get critical alarms from netdata that the disk will be full within the hour and sometimes that the drive is 95% full.

I got the alarms last night and this is all the data I saved from when it happened. I'm happy to add more data to this issue. Just request what you need and I will try to comply.

On a sidenote. Netdata is a fantastic application, you guys have done great work with it!

### PR DESCRIPTION
**Pull request by ktsaou**
- fixes #1144
- fixes #1145 
- fixes #1148 
- fixes #747
- possibly fixes #605
- several error logs have been minimized or prevented

### CODE REVIEW

**Comment by ktsaou** [comment]
@alonbl I added the Requires lines to .spec.in

I don't see anything else missing related to https://github.com/firehol/netdata/commit/3fea7af57c42b8df85aef0b6a1e2c56b3c39470e.

There are a few changes, but I am not sure that is the difference. If you believe there is something more missing, please let me know.

In /etc/netdata/ subdirectories there are a few `.md` files, which I would like to overwrite the versions already installed. How this can be done?

**Comment by alonbl** [comment]
> In /etc/netdata/ subdirectories there are a few .md files, which I would like to overwrite the versions already installed. How this can be done?

why do you have anything at /etc which is not configuration?

**Comment by ktsaou** [comment]
> why do you have anything at /etc which is not configuration?

well, node.d configuration is JSON and JSON does not support comments. So, the only way is to place there some kind of documentation.

**Comment by alonbl** [comment]
On 21 October 2016 at 11:40, Costa Tsaousis <notifications@github.com>
wrote:

> why do you have anything at /etc which is not configuration?
>
> well, node.d configuration is JSON and JSON does not support comments. So,
> the only way is to place there some kind of documentation.
>

Documentation belongs in /usr/share/doc, you can have a README to in /etc
to refer to this place for people.

**Comment by ktsaou** [comment]
ok, what is the `.spec` way to install a README to /etc?

**Comment by alonbl** [comment]
On 25 October 2016 at 22:00, Costa Tsaousis <notifications@github.com>
wrote:

> ok, what is the .spec way to install a README to /etc?
>

Like any other file without %config, you will get a false positive warning
in rpmlint, ignore.

**Comment by ktsaou** [comment]
ok, thanks!

**Pull request merged**
