### PR TITLE
Route monitoring python plugin

### PR DESCRIPTION
**Pull request by tyrken**
Initial attempt at monitoring route tables via netdata.  Reports number of IPv4 route table entries as num_routes and on presence of specific named routes defined by CIDR.

**Still WIP** - need to skip column-headers & other verbiage from netstat and normalise 'default' to 0.0.0.0/0.  Should test in other distros (only Ubuntu & FreeBSD so far).

---
This change is [Reviewable](https://reviewable.io/reviews/firehol/netdata/2073)

### CODE REVIEW

**Comment by ktsaou** [comment]
Hi,

I does not seem to work for me:

```sh
# ip route show
default via 10.11.12.1 dev wlp2s0 proto static metric 600 
10.11.12.0/24 dev wlp2s0 proto kernel scope link src 10.11.12.104 metric 600 
172.16.254.0/24 dev vpn0 scope link 
172.16.254.0/24 dev vpn0 scope link metric 18 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
192.168.122.0/24 dev virbr0 proto kernel scope link src 192.168.122.1 
```

```sh
# ./plugins.d/python.d.plugin 1 routes 2>/dev/null
CHART routes_default.routes_v4 '' 'IPv4 Routes' 'routes found' ipv4 routes.routes_v4 line 60000 5
DIMENSION num_routes num_routes absolute 1 1
DIMENSION local_10 local_10 absolute 1 1
DIMENSION local_172 local_172 absolute 1 1
DIMENSION local_192 local_192 absolute 1 1

CHART netdata.plugin_pythond_routes_default '' 'Execution time for routes_default plugin' 'milliseconds / run' python.d netdata.plugin_python area 145000 5
DIMENSION run_time 'run time' absolute 1 1

BEGIN routes_default.routes_v4 0
SET num_routes = 6
SET local_10 = 0
SET local_172 = 0
SET local_192 = 0
END 

BEGIN netdata.plugin_pythond_routes_default 0
SET run_time = 6
END



BEGIN routes_default.routes_v4 5003889
SET num_routes = 6
SET local_10 = 0
SET local_172 = 0
SET local_192 = 0
END 

BEGIN netdata.plugin_pythond_routes_default 5003889
SET run_time = 6
END
```

So, it says zero routes, although there are a few.

I am not sure why this information is needed. Why do you need to chart the number of routes? Do you have setup that the routing table is so ephemeral?

**Comment by ktsaou** [comment]
Also, check this:

```sh
# cat /proc/net/route 
Iface	Destination	Gateway 	Flags	RefCnt	Use	Metric	Mask		MTU	Window	IRTT                                                       
wlp2s0	00000000	010C0B0A	0003	0	0	600	00000000	0	0	0                                                                           
wlp2s0	000C0B0A	00000000	0001	0	0	600	00FFFFFF	0	0	0                                                                           
vpn0	00FE10AC	00000000	0001	0	0	0	00FFFFFF	0	0	0                                                                               
vpn0	00FE10AC	00000000	0001	0	0	18	00FFFFFF	0	0	0                                                                              
docker0	000011AC	00000000	0001	0	0	0	0000FFFF	0	0	0                                                                            
virbr0	007AA8C0	00000000	0001	0	0	0	00FFFFFF	0	0	0                                                                             
```

This is the same information in hex. If you use this, you will avoid a fork per iteration.

**Comment by tyrken** [comment]
num_routes = 6 is correct (total number of routes), and as none of your existing routes match the particular CIDRs in the starting conf file they will all be set to zero (boolean false), so working as planned.  (Docs could be improved though.)

Yes, my admittedly unusual monitoring case is for a transit network with dynamic route tables (using BGP and OSPF), and I will be customising the conf file to use the CIDRs for our internal 'core_backbone', 'branch_office', 'london_datacentre' & similar as I need to know when they stop.   I did wonder about dynamically making dimensions for all existing routes via text manipulation, but the mapping from CIDR numbers to logical names is useful for me & I wasn't sure you can introduce new dims after startup.

I did have a look at /proc/net/route & implementing it in C but my main use case is running it on FreeBSD, where there is no /proc to depend on and the syscall API is fairly complex compared to grepping the tool output.  Basically I chickened out of the cross-platform issues compared to the easy route.

Do you think it worth coding the python plugin to take advantage of Linux optimisation by simply not calling _get_raw_data but still deriving from ExecutableService & using that for non-Linux?  Is the cost of fork that high (I don't have numbers before after yet)?

**Comment by tyrken** [comment]
Oh, do you have any views on the naming convention of the dimensions/charts/etc.?  Originally I tried to get this to appear inside the existing IPv4 dashboard section but couldn't.

Noticed most other plugins don't set update_every, is there a reason?  Given routes change on the order of 10's of seconds I don't need anything faster than every 5 seconds really.

**Comment by ktsaou** [comment]
> num_routes = 6 is correct (total number of routes), and as none of your existing routes match the particular CIDRs in the starting conf file they will all be set to zero (boolean false), so working as planned. (Docs could be improved though.)

oh! I see. I thought `10.0.0.0/8` should include `10.11.12.0/24`.
So, you are doing exact matches...

> I did have a look at /proc/net/route & implementing it in C but my main use case is running it on FreeBSD, where there is no /proc to depend on and the syscall API is fairly complex compared to grepping the tool output. Basically I chickened out of the cross-platform issues compared to the easy route.

For /proc it is extremely easy to do it in C, like the rest of netdata does. I guess in freebsd there must be a systctl to get the routing table too. Anyway, since this is mainly for a special need, I guess it is ok the way it is now. What I would like to have before merging it, is for this plugin to be disabled by default. No offense... I just think most people would have a pretty static routing table, so there is no meaning to enable this on the thousands of netdata installations out there.

> Do you think it worth coding the python plugin to take advantage of Linux optimisation by simply not calling _get_raw_data but still deriving from ExecutableService & using that for non-Linux? Is the cost of fork that high (I don't have numbers before after yet)?

If this was to be enabled by default on all installations, a fork is a no-go. We re-wrote all the BASH plugins in python to get rid of the forks. Generally speaking, a fork is the worst operation for a system like netdata. It copies the entire process memory (the whole python process), calls `exec` to execute the external program which involves dynamic linking, etc. So, yes it is the single most expensive operation that exists in the unix world. The next one, is 100 times less expensive...

> Oh, do you have any views on the naming convention of the dimensions/charts/etc.? Originally I tried to get this to appear inside the existing IPv4 dashboard section but couldn't.

Yeah... this is based on heuristics on the chart names currently ([it is my shame](https://github.com/firehol/netdata/blob/99d44b7d0c4e006b11318a28ba4a7e7d3f9b3bae/web/index.html#L1158)). If you name it `ipv4.routes` or `ipv4_routes.X`, it should be moved there.

> Noticed most other plugins don't set update_every, is there a reason? Given routes change on the order of 10's of seconds I don't need anything faster than every 5 seconds really.

There are a few plugins that control their update frequency. Actually they enforce their minimum update frequency. The whole idea is to allow the user set it to whatever suits him best. There are are a lot of netdata installations where per second data collection is not feasible (embedded devices, IoT, etc). In these devices, the user/admin may set `update_every` to 5 or even 10 seconds and we have to respect it.

**Comment by l2isbad** [comment]
Yo @tyrken 

> this plugin to be disabled by default.

I see it's hard coded to  IP**v4**. Are there any reason for this? If so you have to rename the plugin to `routes_v4` 😄 

```python
Python 2.6.6 (r266:84292, Aug 12 2014, 07:57:07) 
[GCC 4.4.5] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> "Hello {}".format("world!")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: zero length field name in format
>>> "Hello {0}".format("world!")
'Hello world!'
```

**Comment by tyrken** [comment]
Half hoped to include v6 also, but no personal need & so will change it to routes_v4 for now.  Still trying to make it appear in the IPv4 section of the GUI but failing.

How to disable by default?  Ship with a `routes_v4: no` in python.d.conf?

**Comment by l2isbad** [comment]
> Ship with a routes_v4: no in python.d.conf?

yep

**Comment by l2isbad** [comment]
@tyrken 
`python.d.conf` is not overwritten on upgrade

**Comment by ktsaou** [comment]
> python.d.conf is not overwritten on upgrade

hm... this means all users that have edited their `python.d.conf` will have `routes_v4` enabled after the next update...

**Comment by tyrken** [comment]
That's not ideal.  Can/should I implement a disabled-by-default setting in conf.d/python.d/routes_v4.conf which returns some known error or a cleaner way of self-disabling?

**Comment by ktsaou** [comment]
> Can/should I implement a disabled-by-default setting in conf.d/python.d/routes_v4.conf which returns some known error or a cleaner way of self-disabling?

hm... @l2isbad what do you think?

**Comment by l2isbad** [comment]
The problem can be resolved by adding custom `check()` method. It will fail if there is no configuration in the module configuration file (job should be commented out!).

i wanted to give an example but ended with  rewritten plugin (optimization + bug fixes).

1. All unnecessary logic was removed from init method (only)
2. ```self.prefixes = self.configuration.get('prefixes')''' have to be defined as a ```dict```
ex.:
```yaml
default:
    prefixes:
        default: '0.0.0.0/0'
        local_192: '192.168.0.0/16'
        local_108: '10.8.0.1/32'
```
3. Custom check method added. It fails if job configuration is missing.
4. Actually there is a method to find the binary (https://github.com/firehol/netdata/blob/master/python.d/python_modules/base.py#L455-L466):
```self.command = 'ip route list' if self.find_binary('ip') else 'netstat -rn4'```
5. No reason to convert data from '/proc/net/route' to IP, better to convert prefixes from the configuration to hex on start 


```python
# -*- coding: utf-8 -*-
# Description: routes netdata python.d module
# Author: Tristan Keen

from base import ExecutableService
from os import access, R_OK
from copy import deepcopy
import re


# default module values (can be overridden per job in `config`)
update_every = 5
priority = 60000
retries = 60

# charts order (can be overridden if you want less charts, or different order)
ORDER = ['ipv4']
CHARTS = {
    'ipv4': {
        'options': [None, 'IPv4 Routes', 'routes found', 'ipv4', 'ipv4.routes', 'line'],
        'lines': []
    }}
# TODO: Host path to proc file under docker?
LINUX_IPV4_ROUTES_PROCFILE = '/proc/net/route'


class Service(ExecutableService):
    def __init__(self, configuration=None, name=None):
        ExecutableService.__init__(self, configuration=configuration, name=name)
        self.order = ORDER
        self.definitions = deepcopy(CHARTS)
        self.prefixes = self.configuration.get('prefixes')

    def check(self):
        if not (self.prefixes and hasattr(self.prefixes, 'keys')):
            self.error('Prefixes not defined')
            return False

        for prefix_name, _ in self.prefixes.items():
            self.definitions['ipv4']['lines'].append([prefix_name, None, 'absolute'])

        if access(LINUX_IPV4_ROUTES_PROCFILE, R_OK):
            if not self.prefixes:
                return None
            self._get_prefixes = self._get_data_procfile
            return True

        self.command = 'ip route list' if self.find_binary('ip') else 'netstat -rn4'
        self._get_prefixes = self._get_data_executable

        if not ExecutableService.check(self):
            return False
        return True

    @staticmethod
    def _get_data_procfile():
        """
        Extract ro
        ute table cidrs from /proc/net/route
        :return: list
        """
        prefixes = list()
        with open(LINUX_IPV4_ROUTES_PROCFILE) as route_procfile:
            raw_data = route_procfile.readlines()

        if not raw_data:
            return None

        title = raw_data[0].split('\t')
        try:
            dst_index = title.index('Destination')
            mask_index = title.index('Mask')
        except ValueError:
            return None

        for route in raw_data:
            route = route.split('\t')
            prefixes.append(route[dst_index] + route[mask_index])

        return prefixes

    def _get_data_executable(self):
        """
        Reformat data received from route or ip command
        :return: list
        """
        raw_data = self._get_raw_data()

        if not raw_data:
            return None

        prefixes = list()
        for route in raw_data:
            prefixes.append(find_prefix_for_exec(route))

        return prefixes

    def _get_data(self):
        """
        Parse routing table to extract metrics
        :return: dict
        """
        raw_prefixes = self._get_prefixes()

        if not raw_prefixes:
            return None

        data = dict()
        for prefix_name, prefix in self.prefixes.items():
            data[prefix_name] = 1 if prefix in raw_prefixes else 0

        return data


def rebuild_prefixes_dict(prefixes_dict):
    def convert_prefix_to_hex(prefix_in_dec):
        try:
            net_address, prefix_length = prefix_in_dec.split('/')

            net_address_in_hex = '{0:02X}{1:02X}{2:02X}{3:02X}'.format(*map(int, net_address.split('.')))
            net_address_reverse = ''.join([net_address_in_hex[i-1] + net_address_in_hex[i] for i in range(7, 0, -2)])

            mask_in_hex = hex(int(''.join(['1' for _ in range(int(prefix_length))]).zfill(32)[::-1], 2))\
                if prefix_length != '0' else '0x00000000'
            net_mask_reverse = ''.join([mask_in_hex[i] + mask_in_hex[i+1] for i in range(8, 0, -2)]).upper()
        except (ValueError, IndexError, TypeError, SyntaxError):
            return None
        else:
            return net_address_reverse + net_mask_reverse

    hex_prefixes = dict()
    for prefix_name, prefix in prefixes_dict.items():
        prefix_in_hex = convert_prefix_to_hex(prefix)
        if prefix_in_hex:
            hex_prefixes[prefix_name] = prefix_in_hex

    return hex_prefixes


def find_prefix_for_exec(route):
    prefix = route.split()[0] if 'default' not in route else '0.0.0.0/0'
    prefix = prefix if '/' in prefix else prefix + '/32'
    return prefix


```

**Comment by l2isbad** [comment]
Update

```yaml
default:
    prefixes:
        default: '0.0.0.0/0'
        local: '192.168.0.0/16 10.0.0.0/8'
        vpn: '10.8.0.1/32 22.0.0.0/8'
        remote_branch: '10.8.8.1/32'
```

screenshot_20170416_194612

**Comment by tyrken** [comment]
Thanks for your input & many minor fixes, and I particularly like the dict form of config over the awkward list.  However I must respectfully push back on point 5 - I don't think the cycles it saves are worth the complexity of convert_prefix_to_hex and the multiple code paths.

If I import most of your other ideas & update my PR is this likely to be acceptable?  I'll also have to change **netstat** parsing as you've coded for the Linux  **netstat** output (which is likely to be covered by /proc or the **ip** command), whereas FreeBSD  **netstat** outputs CIDRs directly like **ip**.  I could perhaps handle all cases by looking at the title row a bit more...

Aside: Having the possibility of more than one job & shipping with a 'default' one was merely what I got working first.  I didn't remove as it's possible to have multiple routing tables - I thought we could use alternative jobs to configure looking at non-default tables in future.  But that's a vanishingly small use-case that's not planned to be implemented, so would it simplify things to go back to global config?

**Comment by l2isbad** [comment]
> - I don't think the cycles it saves are worth

it's always worth. It can be > 1 million routes is case of BGP. Actually the same should be implemented for the `netstat` (or not if `netstat outputs CIDRs directly like ip`).

**Comment by l2isbad** [comment]
I'm not an expert but
https://github.com/tyrken/netdata/blob/routes/python.d/routes_v4.chart.py#L44
is not enough. Some `/proc/` stuff is not world readable on systems with grsec kernels.

Job configuration in the `routes_v4.conf` should be commented out (https://github.com/tyrken/netdata/blob/routes/python.d/routes_v4.chart.py#L40-L42)

I don't understand 'number of routes' thing. It makes no sense. If you want to implement it you can make it optional.

The main goal of the plugin (If I understand it correctly) is to monitor OSPF/BGP routes as group of routes. Group can consist of `n+` routes, not only 1 route!
Look at my example - user can add any number or prefixes to the group.

@ktsaou if the plugin is ok for you i think you can merge it after

> Job configuration in the `routes_v4.conf` should be commented out

**Comment by ktsaou** [comment]
> if the plugin is ok for you i think you can merge it after

@l2isbad  I think this should be entirely your call.

I understand the plugin counts the number of routes found, that match a specific subnet. As such it should be useful in router configurations where OSPF/BGP or some other exotic routing is used (since for most servers the routing table is pretty small and without any overlapping routes).

My main concern with such niche plugins is not to introduce any issues to the majority of our users. Also, once this plugin is merged we will have to support it.

So, If this can be disabled by default, and the plugin follows the general python rules the other plugins follow, I don't see why not to merge it.

But, still this should be your call. You know better in this area...

**Comment by ktsaou** [comment]
To move the charts under IPv4 you have to edit https://github.com/ktsaou/netdata/blob/2965c14d05d9ada0a1adf0aad7a0c6589e27afd3/web/index.html#L1170-L1170 (at the exact point shown), and add:

```js
                case 'routes':
                    chart.menu = 'ipv4';
                    chart.family = chart.type;
                    break;
```

Also, if this is to be merged:

1. it should provide a default config file (which should disable by default the plugin)
2. added to the makefiles

**Comment by tyrken** [comment]
I tried making something more performant, but also with simplicity that I would be equally happy to support, but I didn't like how it was turning out.

Given it has a narrow use case & we've already decided to keep it disabled by default for other users, it's beginning to sound more like a hindrance to the project than an asset.  Hence I'm going to close this PR.

Many thanks for your repeated help & advice - I hope to continue using what I now have locally as I'd originally intended.

**Pull request closed without merging**
