### PR TITLE
Improve phpfpm module.

### PR DESCRIPTION
**Pull request by clinta**
* Get the fpm stats in json format for easy parsing
* Get stats for each process and track maximums and averages for each.

### CODE REVIEW

**Comment by ktsaou** [comment]
Thanks!

Have you tested if this is backward compatible? I mean, will this work (with limited functionality probably) for all those that have this module configured and running on their setup?

@paulfantom please check this too...

**Comment by clinta** [comment]
As is, if they someone has configured phpfpm.conf to point to a different url and do not have ?full&json at the end of the url it will not work. I can put back in the old code to fall back to if parsing json fails.

**Comment by ktsaou** [comment]
Hm...

Are all versions of phpfpm supporting these extra options? If yes, you could append `?full&json` if it is not already there.

If however, there are versions of phpfpm out there that may not support these options, then your proposal is the right one.

**Comment by ktsaou** [comment]
@paulfantom please also review this one too...

**Comment by clinta** [comment]
The json option was supported as far back as I can find. The full option was [added](https://bugs.php.net/bug.php?id=54577) with version 5.3.9 (Jan 2012).

I was originally trying to append the parameters to the URL but this might require changes to the URLService library which resets url to the value specified in the config during the check function: https://github.com/firehol/netdata/blob/master/python.d/python_modules/base.py#L479

**Comment by ktsaou** [comment]
ok. Then falling back is possibly the best choice now. Could you please add it?

**Comment by clinta** [comment]
This is now backwards compatible, and supports urls specified including json only or json and full or urls with no parameters.

**Comment by paulfantom** [comment]
Ok, glancing over the code it looks good. I will test it tomorrow.

**Comment by paulfantom** [comment]
Works flawlessly. thanks @clinta

**Pull request merged**
